apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-policies
  data:
    minio-admins.json: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "admin:*",
              "s3:*"
            ],
        "Resource": [
          "arn:aws:s3:::*"
          ]
        }
      ]
    }
