apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-policies
  namespace: minio
data:
  minio-admins.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": [
            "admin:*"
          ],
          "Effect": "Allow",
          "Sid": ""
        }
      ]
    }
