apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
spec:
  pools:
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: local-path
