apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../platform/services/argocd/overlays/dev
  - ../../../../../platform/services/forge-db/overlays/dev
  - ../../../../../platform/services/forge-keycloak/overlays/dev
  - ../../../../../platform/services/forge-mongo/overlays/dev
  - ../../../../../platform/services/minio/overlays/dev
  - ../../../../../platform/services/redis/overlays/dev
  - ../../../../../platform/services/rabbitmq/overlays/dev
