apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
  annotations:
    metallb.io/address-pool: private-pool
    external-dns.alpha.kubernetes.io/hostname: redis-dev.int.aethericforge.ca
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
