apiVersion: v1
kind: List
items:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: aethericforge-admin-config
        namespace: aetheric-forge
      type: Opaque
      data:
        Bootstrap__Enabled: ENC[AES256_GCM,data:CUL2IiDttvQ=,iv:MhN6A7az3WetIm73Mn+039xq/MGN3dLRqwBWuc1VfWw=,tag:ZEUTAfD2kJqYjKcQx1P1IQ==,type:str]
        ForgeCampus__Redis__Password: ENC[AES256_GCM,data:xpR9D9YyXM0zKdK0DrQYmJ77IebGW7YN7c6nH+VlpCEx8JVMS1drTbLAMvxzByBuawOb41au9AXN4MDgul/KOJfblcGfPrwGKJnsUDYFVI0hQu9PDdr1yQ==,iv:zTZbFtRr5BLkVeaXJX4yCNBazox/vtwPB+QzBbe8I3k=,tag:9PS6qoE2q8EydRv/gbVx2A==,type:str]
        ForgeCampus__Redis__User: ENC[AES256_GCM,data:g1Mfq+7BtmAor3/32UqeGI5H2rc=,iv:wxR1bifHkURJKGAY4v/ysFIvblq3/HZKAV07su5CdoQ=,tag:wiDgkYJEkfQlOvC2sNA7NQ==,type:str]
        Keycloak__Authority: ENC[AES256_GCM,data:9rA1P32Ojha5PTPgUIMFVeKvfX6tsncnT6rYySCQF8759uHA5IR+Gw==,iv:7yf5k0XR6cYahH/3lib15kM7Csw0GO8g+u0wt/h3crg=,tag:gfVIohVmE+KeVpFPp8AK5A==,type:str]
        Keycloak__ClientId: ENC[AES256_GCM,data:uM3W9EDiiDB4dEqgCyHFFzLLRIE=,iv:/0f50uwbblPEUVmyiieC5jItVJ8ryjg2ZyRxCbUkvdM=,tag:tFxKzUB/+gIQ3lUufxcrxA==,type:str]
        Keycloak__ClientSecret: ENC[AES256_GCM,data:Rcgxm0S9epYlxSgX1Koc5W+pompI+ALKBX2iUSdHtMiefEZes3p3U0XD+jQ=,iv:JP/ElV8PlxVAOtSqi0nLad90GsWlKATaHzHOOOCDyVI=,tag:s2G9eGRtFcIb+EoXea1GCQ==,type:str]
        Keycloak__Realm: ENC[AES256_GCM,data:ZC8BcNetiVl7nfUBAFLmBu/PJn6lQgE1VPHnDw==,iv:JmDbApD0l0TdLXysH9D5CakGJ+QR1D7JwA4XKmTHoPQ=,tag:x0gDzfeoPUnb5CfQ1ta57w==,type:str]
        Maintenance__MongoDb__AuthenticationDatabase: ENC[AES256_GCM,data:RofwPhBr+K6kI5YeKVmDbm0oE/Zxp8LFwJB0bQ==,iv:ilnv+0RMLuK3pYD07fVaGwSD64C5J8K7USH33P8MGwA=,tag:ca2JyqkfKSXzDr8ktk+3zw==,type:str]
        Maintenance__MongoDb__DatabaseName: ENC[AES256_GCM,data:yL2Z0aPKLLqZV8mm25yEM7M+v7gxr2mx/qx4Pw==,iv:J6eb0RMcZSxb3Cv+uztuAsN489ROEdXP8ojXUYD6dyU=,tag:leSonTAcIILo+3sebHhN/A==,type:str]
        Maintenance__MongoDb__DirectConnection: ENC[AES256_GCM,data:rzewluNXYoc=,iv:bVVFx54vbxMuCkXHiHCH0AyGyaZ94e03uyVSVX1sda0=,tag:BQ7bOpFzL8J8aE83recxxQ==,type:str]
        Maintenance__MongoDb__Host: ENC[AES256_GCM,data:uPq0fYclcKS3uVp6ZE/iR9dTqrVt1BYgbnCbqIvLJFiSRC00nlfe03XANh8xfuVywHEKjhZCb5vudAt00zxDlLFYYuwlx+Xtqnn3K1lTJE4=,iv:OGmkvHyn/zZqeGT1bhdzjVPxQNDEpXYDKUUyrjeqqUE=,tag:+jKYrBLD/5KOK2U+iW+Wjw==,type:str]
        Maintenance__MongoDb__Password: ENC[AES256_GCM,data:zt9jyh7P3gufnwm6r/HEU9UNG8fd4uIEKluyfzfEDW/Kz5DjH4awnz15gY2NzIZdgoTh2/rSA0iTEtcIjVcZcCGZqYZ/Np7hf9LD69kNUrGZbqlE01kK7Q==,iv:soI5K6wjUKVSKvR3AuxvHNUEhIhGeGUdx+0GheBkebo=,tag:zZY3q6rgDJ8L8nRXg91fqw==,type:str]
        Maintenance__MongoDb__Port: ENC[AES256_GCM,data:3MDDagLWuiM=,iv:phXAWYVEL7C2VUaqM8CpFDZ6i/57xFBLLBUvSSskIoY=,tag:ns+McaLPa186y1W//wkqLA==,type:str]
        Maintenance__MongoDb__Username: ENC[AES256_GCM,data:wFKnh/AZg5PywIcyOaZcE5JEoG1LMGQClv9kJg==,iv:w+2EtMHQMkKHHa7AOfbKphXHM4lcOCznIDmKGvydcbw=,tag:7+gTsGkqg1k0wwgA76nAqw==,type:str]
        Marketing__MongoDb__AuthenticationDatabase: ENC[AES256_GCM,data:vyThxMYmIo58KZXmwlDJPU3Bi80f2wCa,iv:hPMvaqoAEeRSnaPzX3FPuWILuUzPTPwVLDzcBfxFg9w=,tag:UMx/Gh68NEw94g+phBYxmA==,type:str]
        Marketing__MongoDb__DatabaseName: ENC[AES256_GCM,data:m7nF4fJ1wcWbyaRHITvY7JC5UmhGxf8p,iv:xQyD2bnOQhNXSS2OhFEt6vJpAOkTgOvW2SsDOLLcJTQ=,tag:Ga5FN2ht4jhrNDK6lBkcCg==,type:str]
        Marketing__MongoDb__DirectConnection: ENC[AES256_GCM,data:F9fsov+IVOo=,iv:R6jMETRoWdk9ITqIhUQVAy9zq66s8tevu9YkDcy/jic=,tag:iZDbfn6VP7BjBNDLrxfX8w==,type:str]
        Marketing__MongoDb__Host: ENC[AES256_GCM,data:di8oiFUrhP3i4cAYvkW67TdLKPS/Bmj5JjesCw6csK/xlQ6QMIfyAfyBExNURTjZYi+x3c8JjqSvE7k+IM2IUk6g3N7VhJc/A4ygh2MmjFI=,iv:2+WFC8dKBlIxLhdnNI9UI5IHR1K2SCW7Jxe4MCicOxc=,tag:q/nqVGdFQ5y/sAoPcOi+DA==,type:str]
        Marketing__MongoDb__Password: ENC[AES256_GCM,data:6ZgW6WdbR4Q1D7mwi08qDe56zso70POfT2QLwjB0scSXb3ZXBUe9rteb2wKHa/3FEfdUBMNowRpbl6PK4tOyOkW7Jd/Uz5QIvaVN2qkf8QY5C9lYoh4+fg==,iv:fu8F6TpKiacNNEC/9bq/7wAXHqqI6T/k6ivGwfUtZdQ=,tag:MLjHF296IAn+Wo3pAvFLxA==,type:str]
        Marketing__MongoDb__Port: ENC[AES256_GCM,data:7LHVgJDmaFU=,iv:Pyn7Pvi2YA9NjlQfrh2grAAu6EVZu6arrV5esWVaS4k=,tag:bg2OTgeUV9CRlvwge9utIQ==,type:str]
        Marketing__MongoDb__Username: ENC[AES256_GCM,data:4C4s/uoLDdSLQokj/Wm7H6DxURWaaqwu4XcjnZ7IHlo=,iv:zt5FUbA3kkf4eWzGhvBO+zIJNIscWG80emIQQa8W90U=,tag:ZTGHvEnhtEQgPNMxdhgCuQ==,type:str]
        Membership__MongoDb__AuthenticationDatabase: ENC[AES256_GCM,data:clxv4s33eepco3hxIAV90T4jUfRtxMqeVUzPPg==,iv:xjuCRLZ0cXwz5oWnJWCDalesRtF5hOpg8jCDcNYYX+8=,tag:nUnnkrN4BhcmD1kQkQG34Q==,type:str]
        Membership__MongoDb__DatabaseName: ENC[AES256_GCM,data:avxoApHmR5pJiMbpGnQw6LvLzzkmyGnQ8824wQ==,iv:I+8SEkAn8kPAwW98JG634TUpsmaFIJKNIx6YWcVyExk=,tag:0mCJ3tC3d1UfPQ6cAg4pMw==,type:str]
        Membership__MongoDb__DirectConnection: ENC[AES256_GCM,data:WuX0uV/RJU4=,iv:fKNjJZwC9rcQSh0v28FNVzhTRfSYBAL4sF3lJDIDagk=,tag:15tmv5wYCIOQIWicjKL07A==,type:str]
        Membership__MongoDb__Host: ENC[AES256_GCM,data:bfn8FJrV6hVdVSC5BCu57gLgkxKw39v2zBDs85eeIYjcqdNkyXP7U1U4GuwIJwcN9E5pZTtYyLt/Sy1/6TCb9BdX6YrjMBox9Xlmb8YAYf0=,iv:foLyv+LTZVaqh/qgMExjPaIRyrvwZk5BVYVfTcbhyCY=,tag:OPuKszfv4tIBenZZGj5SwA==,type:str]
        Membership__MongoDb__Password: ENC[AES256_GCM,data:w78gIhaBLFcct/KF4u4DC1AGPj0rHhDdVhUagZKOGq1zTxkcUaBLIIZ56ObiGKdmo+xmKZAsLNoqVIFYzqwDY9thef+aMqdxxnazs+H0Pg5YH3RE7D0uIw==,iv:HEov4+9Bv8iePeKol3xreZyTUmn2l/AiyKdJHCq45uk=,tag:iCqDuiMekDNLKf06yN31rw==,type:str]
        Membership__MongoDb__Port: ENC[AES256_GCM,data:FIUftZYbgH4=,iv:uCP31hODXysbAyO4Ltj/Se+fmj2kj8PEegHtd3r8ut0=,tag:pGgxvuiKqWDrjikHdxGH/Q==,type:str]
        Membership__MongoDb__Username: ENC[AES256_GCM,data:+2sc/lep26I9yY0xrYltcROOFIOMVCy79f61Z1ODXgDmX5ul,iv:wxHcaB842Rzl2TdJgsO4JYreUQXbwq9GL9kylNDf64M=,tag:CulI6X0mKTd4sX5JhS2OSQ==,type:str]
        MongoDb__DirectConnection: ENC[AES256_GCM,data:YFVtHQQNUgo=,iv:M6qEoaoo5uDrlJtUTQrltBzDF92eoGkEIEHhmcYraTw=,tag:65b+z4yDF4vrZXlwBvVu5Q==,type:str]
        MongoDb__Host: ENC[AES256_GCM,data:NMYigXvf0IOHkJFDq5TdwNT2MLqBQHxE/QfvJumEqZ0NOL+wlvcLqDwgwhr9UhdKvIZQ4VyRNJm1Fp6XOv357lkQcYN6UPq17YyEwtGBX5M=,iv:Q5BYXUGqpODSabtfZ3NUtoQOOKNSfs0IfqZvuFGg02U=,tag:GSGv9QD2MXaUjG9ItPx6Dw==,type:str]
        MongoDb__Port: ENC[AES256_GCM,data:Fk4Ua4f6N6M=,iv:MXcFT7fx4CgU9BnarwLoOCV/i2cjK91Rk0Q41Q6Erv0=,tag:D4sy52ISxkj0mXIOQoWlBQ==,type:str]
        RabbitMq__Host: ENC[AES256_GCM,data:ZEH7oBHxjfDoZMHkAX+SsRm808aNgfKhKdGPxHoDMnUnng0WCAKwuCIXRuZE1A/5,iv:Mk36zrla177LSLgTdm+IjuLck/YpslbkBUEF7/gfYbE=,tag:sUO9qrkTwhK3UOVYTgK0bg==,type:str]
        RabbitMq__Password: ENC[AES256_GCM,data:6WEgEEnpgICdefzObjadElFrPwGHO34uu9MLooqkVgFSO1a5+NSPbD/j9BgwhC8u29Yhhx+GIjwlYbTbWEQBohWqiqJuS8FpKYwHKMDtO7XmmRVidLPNPg==,iv:SQCbBIqXlKIiB0FbkJfrXWTocoNgedhjNPP8ijNvrd8=,tag:4i8sAlk4+OvzE45GKw8kpQ==,type:str]
        RabbitMq__Port: ENC[AES256_GCM,data:Ulbsocs29ac=,iv:sNge/NZ96wpHIrHoWisInkngRV2Va2SQdoqptUA5x50=,tag:I7ljeo1+4sMdezzq2eBNeA==,type:str]
        RabbitMq__Ssl: ENC[AES256_GCM,data:mvqYTxuMPpg=,iv:cHCNqPYChM8VoaLMMXAS4Jw1VCALNVm1W2Ao3Sf85d8=,tag:YPQvzCv09cBM50baEY7CkA==,type:str]
        RabbitMq__Username: ENC[AES256_GCM,data:QjB/pXl3t3hLCTjHolJZuUtDc3g=,iv:avkNtiwnOvPgyDg9ZBY19YDyzEiYw2Hh3RPLkPtivSg=,tag:YxB92fsFxUQLaInq7tXU9w==,type:str]
        RabbitMq__VirtualHost: ENC[AES256_GCM,data:MH6I+R8ewPPZW/ezNOhBMnwFr5o=,iv:9dXFaXfzUL8qeak8U4RCqqCJEo/Efltls4qWoK8Hk98=,tag:WAxJUluSPtpSviQO/c9XRA==,type:str]
        Redis__Database: ENC[AES256_GCM,data:aRO8Aw==,iv:JiF1XrvjGLvyRfAvvvAVMIbbuL8BM8nTp1/dlzA5ZHc=,tag:hnuowbfEBQigDc5Hq3moog==,type:str]
        Redis__Host: ENC[AES256_GCM,data:d3tWRdq0ZEyFwunX5gZDbo1op39vQ0YTrQUQx0wWPXO8THPjSYuZww==,iv:2ZHbFpO8SVhcxYpX+C7ilBbGgkTGaPdBmY/jqUXU7+g=,tag:Z3vIOnTFHDunBX3BUW/9Vg==,type:str]
        Redis__Port: ENC[AES256_GCM,data:7LT+E1WkCfU=,iv:Bmynp074pFi8kufKm6Fd73BcnkBtqxwFM9q6WeR7HFs=,tag:p8F5ssQ51zMmKsL1a8DdXQ==,type:str]
        Redis__Ssl: ENC[AES256_GCM,data:w70ZdOgNN9E=,iv:h3FBJ4jX7srr1UNkT6ljHZnZVTNSZ4fnDfbMNGBDIK4=,tag:WWwTugz/+dvVQoF9FlbSpA==,type:str]
        Workbench__Redis__Password: ENC[AES256_GCM,data:bXSL97/sDft1ENSFYtdgRMeyYi32hVI7V7HL2EgVtxkBVG9nTGLlLeH9vXm4pdtIJWASLzgIRiFkagGdEgfIZ+o9l5QjaP5NnwyyRmCTpH0BclHam8bJXA==,iv:pv2oYGWCs4ITBW237X15pRoNjn264d/qLYP5XH1+lO0=,tag:rtl35CjSCQrQnCQ4/LNQ+Q==,type:str]
        Workbench__Redis__User: ENC[AES256_GCM,data:bvJp4nQRuXa2Qzx5fOfT8csM19M=,iv:uNdiNpJMEVc+NQHzDdM4bzrIMGzzw1lsKmHmrsdb4S0=,tag:VedUyjDLi83w+/Y+2VKAGg==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: aethericforge-web-config
        namespace: aetheric-forge
      type: Opaque
      data:
        Marketing__MongoDb__AuthenticationDatabase: ENC[AES256_GCM,data:EJsK7bLvm9ZmzIL3nDmok7SmufLyN1bU,iv:gIRaVWDKzJk2Q7l8u8LzBZ5RwPKZI3R7CBilgYrGERk=,tag:5Lz/RCpfJD4k7GBEZlju3A==,type:str]
        Marketing__MongoDb__DatabaseName: ENC[AES256_GCM,data:H/Bgx3Xb+z/1KhUpxcxM61tbAqchkhC5,iv:cgnRWWT5HQdf0pbGvKWe3EzygxeE+OxR6zI3JInaqa0=,tag:qiP2/9+JHM10xyRAhrD1zg==,type:str]
        Marketing__MongoDb__Password: ENC[AES256_GCM,data:dTppy2LcwQtvmoOMFIo4clka/EpT/TcNzNMtmgH3d3V7ZbuxMk3eafWFpR1fzRYr9YkwCZnVw08MEB+e93ptFd9RI0xcot0pxZqwSrH1/KBwhuTZxI1wgg==,iv:DDZrvglF8lJDYrrTDtJuZecmw3Ym7doS8OZ1QnqBA58=,tag:/XEYUDICyS6PEPylZAoaHg==,type:str]
        Marketing__MongoDb__Username: ENC[AES256_GCM,data:sVIMWbXVjwxPdT/nLlU5Lg==,iv:XtBn/pOcIomA3JM9ttNh9DXQb+7ApWsWexsy5d2MWy4=,tag:7fzNaorIEdubykWKiYX29Q==,type:str]
        MongoDb__DirectConnection: ENC[AES256_GCM,data:vqZQhtnU4f4=,iv:lg8bzgdeLVcMumRXpXBpl55OA2XZDfJjlBq8qhyTRgw=,tag:OE804fkjM5FOMrZitS3xkQ==,type:str]
        MongoDb__Host: ENC[AES256_GCM,data:p1cKOEBVINXgEs2/n0MbMG60KbI8iWIhuJtKOW9i91CmKJXR1h/MceoqIUei/EIIg5kYQHFPtWdHrAGEG1qcmuXLTf3nKbwKqXJq25Z9XoI=,iv:TrwN4YD782G+DA87TGSEDdkJEEn7MuRcXhg5LBTgwrA=,tag:m6U7sN+H6agbmCtFQAuD8Q==,type:str]
        MongoDb__Port: ENC[AES256_GCM,data:nNReLBHzH94=,iv:EFqe9oReuqJPzYsWR9ALp16Y6p5EqtkYDrCXsnGDhOU=,tag:rQq8+kTQZpxuK1ZOT2x+5w==,type:str]
        PublicSite__Enabled: ENC[AES256_GCM,data:GYuCLaTNhy0=,iv:DGCGM2PEdZK0Wm66qwJv+SNSZWHlYwEsEesNRNpOnXI=,tag:BtPcXif3P1tRUCjIoINWvg==,type:str]
        S3__AccessKey: ENC[AES256_GCM,data:c79b/Bgcrt2w+0DKEL0lC5cgK9/Nz7JirtWpG35oCMAwa67MUNcV8w==,iv:HUEHyK/8FQjKHJZPdJDD0sGYsxFngZM9f1V8dS9WsgI=,tag:wq/DzKF5ZMtOH97yoUBvzw==,type:str]
        S3__AuthenticationRegion: ENC[AES256_GCM,data:X/ndFTQdA92v9Q/l,iv:t3MBx8ivkfcImvLfoKkbDPtuBAY4Qc09DvdYbSmX/Pk=,tag:d3j/7sZejPtCZHjBimB/5Q==,type:str]
        S3__BucketName: ENC[AES256_GCM,data:O9Joy9EomkY6fg4tTMrBsxE/INc=,iv:D7YyCJ+fMdDl272SHXbmOoTqwjDAtCOlXyzWta72dhA=,tag:ni+mgnjb5g2e2QXtrQlh1w==,type:str]
        S3__ForcePathStyle: ENC[AES256_GCM,data:JDKUe6xHnEs=,iv:wR6kMtskEyAVzrfEbZJAWPwWzsMCz7gopT8oHxZx8jg=,tag:fIxA+OsZqYjbozdrYT9DHg==,type:str]
        S3__SecretKey: ENC[AES256_GCM,data:3IEyezfNgSs7LTsrQOjPVtROc/liJRg1/dFyydBnJSpdmgqe5rZSwMpnLT95sAakcTSFe5krS1d5SOzDHm2Nm2uwn2BH5t10bCWio3vDALSf+IE0ZnGo3Q==,iv:GFIpBUhfCtS3mBivUs0zNjKHODAjfjCBtsj8e9hIRJM=,tag:+V8A5+CnI7GsnCR9djnzYA==,type:str]
        S3__ServiceUrl: ENC[AES256_GCM,data:6ZhqIfzUeRDloJYvAhn+nbBfqFO0b1RaULAmf1MSFGc/yzS8t/Q8hgrytaYUqBbOSB8VDeX6kufhUHBBHgzHQ0FFjE0cLTF3NqSF02pcLYE=,iv:4FpWHWlaDQBhnjlLVWMLSaKtT1xaAqi5+1w9aEwFfAQ=,tag:yZbt6eGFpyxbR1hxUtjwJg==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: aetheric-ghcr-secret
        namespace: aetheric-forge
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: ENC[AES256_GCM,data:XcwqL9swdeH+Tl0papxRyXqpD04EIOSJ2Ok9GcXBuNkb2l/TEMvAl/M03w6AuBklDkThE38s5gdmQx8hB5Xfx/Iw5umgb8ZCtVtPZVxs+ur4uytv1COLTL+9hwhpw64PwvmyJ9ZXEjdsdMnV8iNsV6Z1nfthEq9usok0M4EYUqTMrfzyHTOdfTED4eVVMx+Xj92cmz7scl0=,iv:HGm+1l/G/HgaFd5vwMYoss915B2uXtpL5CLjfhghnD0=,tag:6aLExvCvi2YguC4PYbcinw==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: aetheric-maintenance-mongo-password
        namespace: forge-mongo
      type: Opaque
      data:
        password: ENC[AES256_GCM,data:gh+Ibjl2nQXilGDtoQrA2DrI1WJRJ/0nCaaLRG/DDTnOkYsAzhK8oOFeBl6lq02NA/KxJTx5Bqv8EoXrMyIoRmdah/F2NDrYIVFJNV5PdLsCEGtNthsShA==,iv:/5zQKCscNwpumr895SpSQ8bw0svhsVa9GtXd9O0YkYU=,tag:0EvLIKfLu9mEKgC5EMSeag==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: aetheric-membership-admin-mongo-password
        namespace: forge-mongo
      type: Opaque
      data:
        password: ENC[AES256_GCM,data:SA3vqL6gHw5pwG9fOoD+bZ6rWexZ4RGXjBF2rM+Ugq2SXhm/EdZCSEE26Ste/NJ9r8WdhdBi+ng1SE8qdAZQww7WlCRVOKRSGR6q9Mj/BeKDPapLV/W2Ng==,iv:hFuGTo9gpc6DitYlOiFuM3L228qHQwOhFjRvXVWS8mA=,tag:HnJjw2yE5vX9CEigDbJKcw==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: aetheric-marketing-admin-mongo-password
        namespace: forge-mongo
      type: Opaque
      data:
        password: ENC[AES256_GCM,data:O4IQ3HVDw2oD5HXcCZ9L+jH5An0R8iDRWOW9exmidOm394vKqV3OP8jHBT4Gek6OLb9aWS6DKG/WIydP+pY7u6eGRExQyPZ0QbLgeLi6oknqFmaYoRXnBg==,iv:73svpArxjEtFuWBoZoHL2HwdI4C3Y7T79yNwekzLU5c=,tag:IYIggc/0krfio6jN10KfLQ==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: aetheric-web-mongo-password
        namespace: forge-mongo
      type: Opaque
      data:
        password: ENC[AES256_GCM,data:tYNiq0P+IMfLuBo1COxuyLS5oq86ooqVmo+eeIWFzUu2ifxzWibcEHbG+v0r3+Q8gPwVVDyRgr+wVbsoW/hq22QE17PXfm5sGoEqgWahOy7ZH8ZpENPoOA==,iv:Jo2rXK9HHJFnppIdU327XVmqtZ0GEYcE6UFtReaK7RM=,tag:G94OmCAPGEHcsdLhhk3Ohw==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: aetheric-web-repository
        namespace: argocd
        labels:
            argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        password: ENC[AES256_GCM,data:xS06enV9YPdJpKtAb3WUFfFOGm6/I7TkSs5nLyvJZOdoK8dzh4SKjUHIgW6CXJ3ALvXIzn/2g7w=,iv:one6fdpXfkCCgf1V5DozjISkuYROHFuS82WzD70BuR8=,tag:Rs0E3bu8oBRBdnpw4nswwg==,type:str]
        type: ENC[AES256_GCM,data:EPHQqA==,iv:obt1z+hiLzjj3MvrjZ0HYing9SPQJvXUHRc82ORaeZg=,tag:4fh7uJ09O1DyC48s64VQ+Q==,type:str]
        url: ENC[AES256_GCM,data:lFJD0r6xrYz9d6Pf4etBAGtFblzpjjuR0pzzRiGfQc3OtNi7icBo3E6ss6MWCrBMJIaRXwC08M9R6zkobMqCXqSn5IqQqfHb,iv:meB//RhrlX2NlUKqibtTEnR/l0mCoKhlzv/Fh61h8kQ=,tag:R1lnX3QWjFcnmr81Mo6O6Q==,type:str]
        username: ENC[AES256_GCM,data:8HoAw+/+BNCUz76MWJX+x1mMUew=,iv:I0hYxqc9e11b3mSKAKw40We/xLhyzgSS6M5R/Gd++lk=,tag:43jjPIpUlGjnl94TbfiqvQ==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: seaweedfs-s3-config
        namespace: seaweedfs
      type: Opaque
      data:
        seaweedfs_s3_config: ENC[AES256_GCM,data:73aK2kYz3fVk2S16T0Ysy3j37IgGFRHzlUycSGwqMwzUu7cFRh+8z98Ta7gjcqccOoamuwz8N1L8WopW4vq54ANp+FPoROeEHeI/PYwK0uzXupFGq94GaQ/zX5Z9ruyDMzMd0zXKXVbFbaEjz/xeDz8JgcawvimMsRuT8zOYK8RzQHZnRMw1WBJdXZ5QqQ69ze2oIVYhPb3S8kahDReyz4758KLyQUXsoS3tZUQBNQNo1hZkdyKrjC5NybYq9RuNdLQQurIPdynAj6tf870iq/KqxrMxvMDxwS5st/xIkWm+4dCoc4dXPa666v6PsLMESZp8vun7ttPSG0QDpjcJY+hgCSPfdDK8I9271I306qokqhAYt8HtukWlKpLJ0G10ZMUmv57bnvFL+O2r4IpxQ+w4iq4+WWdrdfMoClFHOLIgwSjzFjISk8gbLGwebLuPTQGpOJer3jm7KC67Ly4AaeXtreKUY5W4URR5r8xa6MPFlIfXELu5VJbM1qjfFd7eienWXO3BhN8oP5BGmXueU0Pm4puCDBRACArJsKG+z0qhC9jTchH6wFy3cZ6BSsren7B6oPvvX04JhUvwpD/jU8ROGeRJKz0EvYomfaB373J3eL2EN1XhkGLBtDXomDH/cQJWfbNtk8F3/O06BkMhGD9uwYCAj/9RMmgZU56n907A2AlgQNnn54wDnD081jnTSXnXRMCitRgdAnI1CkAzpnTV362kQZxkuKKOzxvoDwcd+pufYo/nl1cOh1jEex2hDxaGsAm7vjE4A4S3b49ydZwaR8774j3jBldOEMkdbilly+GzkFu/IR4/zqXJLrhfMvOvQnLtNVBi5i6RC+wcG9O1KbiqUDY66I9zVvliCHrxFC0Udc4E07+cTtOLKXkKyFPeoxWxr0nvgAYWT7cLQW04/NeiWK5dM+zAuBnZMgGOo0zA9GldvFxm8g99pn0E2ymQ96Is5DXjAllCWwZHQD5jJ+9kevIscRUfKDmJOHO+UCVqMxfrAbMuqh9b7M8pCHKoUPeKgVRayohngQvpmsFDNQHuiPwO9lGjAohj8YKp4X25o8VYV1krWnrMgf9646YctqrImCNvQFygWZOCHFppCJ95ZBgpEdRT1OTefApKquMSu7opE9NX+abbRwVdQgFDdmeMdc5x9f4Uyb5UGBaK01SW/AmXhTjZ1p0N99YTgZk8jsFmAIxJqHv9hZSf/g/hIDI/ijhBWbuvxTF3Btmi4gWc38dCKzNYQtEzgPAvtjz6xkdSmjdl5eDfiaZtYEoRY/O/Yc1ZBkDBgCEuq4mohe0jAZWphyP0Bsixx2dGrrp1Jdk+RLBhHnXvd18cf43cDaWIK6kQ7jA9nk54ACFxni1SHb7sjyqK2a92+t+eLC7kg1OzPfLZqYZjkonrbZo1HdxbSLbwdqKw6vy9bTUhixVVKQeyfmplMNYQAG9QcYqd3fBBKzOR+fktBgNylWyjupna7NxSkKuetaPKiFsLXjYnZPN3tRsXrUNLVnb4554buheBSVKg+Gd9aPyEBfV1G/x7mVzpok4keCeB5fn1zlM=,iv:HpXhLkf47ngVREz6RKmT4UOdFNiwpCK8tMdWcw9NIpI=,tag:zsKwu7iis/92P5UVPyQL1Q==,type:str]
    - apiVersion: v1
      kind: Secret
      metadata:
        name: redis-acl-backup
        namespace: redis
      type: Opaque
      stringData:
        users.acl: ENC[AES256_GCM,data:HyJoQyV5fTIN0aR1gdD2v/0iUZoYFkJt91Y++4pewH1GWLXuTDYgf61uf9+onWthuSejeqPrxwoMwzICGkpxAFA9AdVMdIHx4P5DmOwJLISLnp9nXqmAda+htDHGmxq3xGKBBf8gDbqY69Pv164In5exKeHiO4skL59+Pxc+fKgRNkwvA3YamIcVEDH9aaJu4KbRrS2b3BoD4nEausnV7pUKCfJUKtSzlRbAOgZ4EWEAyid0A8Q3fRxuAlHJwlbXT1VHwnmDqKFIDJA+KVUFSWeO3Nqb9M5g+jmD2PVrMfUY/zyIVtw5uXBoB64eWho9KFBphm6dL6YmgD8qwjPpgo/hYWc7PiglrHSDOIOW4lJkzq17uxXJy/BOC/dzi3AKFEGvhYx/Tl+VlfrDn6w6DIp3TKTJ4N4mLKRlrxT7Lz5IfbeTEyThxKxtBlPGKFGPC83a0/96vL1YrwE9Fm/J5vwm,iv:FR/kGa7GEwssB+fHMBpkwtC3TJ/3epu8ommVTwjrANc=,tag:iChOZ+glspvfoEFXaazcQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeTVDcXRZdzM1QVg0eWtY
            ZEFLVEdueUdCak5jTllpTWlaaEZWUUFzeHlZCitoNU9xbFZvVzU4Rmd0ZXNZb1dH
            RU93UWRBVDZabE9Hd3ZNd1NTUGZoRzgKLS0tIGRUdTJGcndLbUpwNXhaTWdEN2E4
            SklFdzlad3h2SlJnL3lYeE5BWFpwdjQKCylrScL1oGHN9GLuqSN6WrkqQRW+QnHE
            FETlZLau5bta4xSlAxX5gApn32Cev4sZYALqTgXU7V3hBoIR6bj5Lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T07:55:06Z"
    mac: ENC[AES256_GCM,data:iq3DCuJD0jK9RyNMm8LzV+0+tIyT4uvU7u+FvA2UV7KLaO86GJyZ/KAiNIDW3QwMHKV0Zk/A4uqvO9xtizATndEidSwGIppovECoNTV1i3OfZJJ1VR6SVPUUFOb9DtChjoGjLYR0Un3q3HFb0WT/dIqQwiK4by0FHtMJvGWccys=,iv:cfMVQt5EPfnq8zezwUQFr6PtBSlUvwNvM32hdqSHXzk=,tag:dbwyg6kBv6TYOu70tfNGVA==,type:str]
    version: 3.13.3
