apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:s2honKPPYXpRzBBDNmbWOxtpo6SHf+I0GpJe6Puwd0YJRHz5yjcRh4eb6yeoPTwZSHgfUh9aI9CZrUXyjSKMpjFAMg7a3a4IzDPOmkHUjBBuWqjQoJTtCOhEFn+eqKGyAsrh,iv:wNLhsMpfnyyXqCi9bOTCCMDd+hIz74SlEja+1w2GE8o=,tag:u5k0z/pdkxmpuuGk9YbINA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c3FjMnJjN0IwS2dOdnM1
            amRFWkw2TDRuamVXT0NoYUpBdFkxTDR6bXlZClBocWozNUUzOHVJaXJFM0lqdmZL
            ditVTDV5U1VzRGlMRzNrWElKVStRU0kKLS0tIEhLQkR1bnlqWTRmZ05JUFI4aHFw
            SUIyeWFRbENRVmlqZVdoQU0zU3ZyUGcKFLLW302eccvDaxD0CYklvYoXJC78oaUN
            qnSVv17VWuxph68WD8KWZkNkOwdvu46pu+uMbkJN3fesY4DDiyThaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZU9sUGxSd0lVbzVnc2c4
            YTBHYXY2b0J0ZGF5cXk2c2JWZUdpSjJIN2w4CmpkTjNjbC9qSjY2b1N6bWhaQVIw
            M2pMWjY4MFpicW9BMVdTMFVGNjFWbEUKLS0tIHI1dXlESXQrWHlzb040RXVlTDlO
            OCs0eFhFd2JwZG1qZ01DVHdONXRhazQKYDX06z93omA0S/HtULswaBcsR1JRG3x2
            2NN/DTIdav5Nzzxpa5A/ZYjguNZgOzLIFJbpDvbMA/wxYDZP169BYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T12:56:54Z"
    mac: ENC[AES256_GCM,data:nKx0M5igRIFFX0oWqqFBgXHYNiwZ4g69owmVG2c2xsWT9Cy43S+DG/wt2Z3sPRBzydTF1IowFulfEQ+l0MJBvYNR9R06NJtpJbEzhs1tRSrpom0Y2TTonYOVc5S/RGvBFVGlceEOIzKOgy8RUKrEB1dN8Wmh+3LHRwK8IGujYxA=,iv:q3MYh9yc1hs6srnbXWsn0BoNxwIwbETvAm2xBiSsIaw=,tag:sJpbJG3AJzM1Q6rQ49zcyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
