apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:l51Pm+DqGmTMA63lmhSzuVe8afKEwLxmUYD6JOKzr+XcOKykiBEwmrCkrrF0LtG0Cvw/d3qpx0odP1yhND2BNf1bH4U78LRk7XCT+y2keVtSsNGbKiBdTW68JnnoMwtCD4HZXA==,iv:bl9aC6YDdcFZ0MOyfKuuLp2i5kU25IFC751iy8osZqU=,tag:T4RdoDzZyCpw2eAFeQ22Yg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NkduMlIvSDh2ZmowWUR1
            T3ptNW9OVVBORlhaVElWbllyWGxZbWM0M1NVCmRzU0QvcGZzdkd1N0N4L2QxRWtv
            S2ZSVEdqUi80MXVLbENHRjB5MVpOMDAKLS0tIDhlWnJvck1HVXo5WDdlcXF1RzNp
            b1NiODhQUHVpZnpBRkVucW1UbXRlWm8K2v3Yg2Me8RPVzVZ65mPbQ57oKdys0URn
            pC15uWn8tZnhwCWOJyhP7wIr7s47tUt5QcOyEjN8/NXn30xNw1cfuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQU5qdkZoWS9LOUJ2KzJl
            RklKUHJ4TG5SeFRnN2ZhYTFBSEJETGxPVDJBCk5xUTBLV0ZTWUtrK3Z4ZEt1S3pn
            bHVHVzNHTHAzdTQ3ckFjN3F4cnlNUDQKLS0tIGNnNzZ5eTBhcVlFcDB5Qis5VXJG
            R2RuN0kxclBxQWhscGg3M2g5dTdZNmsKfKtVKnxo1kvGY8JTvSZaAm7ZYDtVlNpF
            FXCyKophLZF0NTZJ5IqVF50+Drt45sN34/2+EdZwi33Np3NdibzRtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T15:54:48Z"
    mac: ENC[AES256_GCM,data:+fnsUYmSq0pl6vUDD+dBiiY4nWyU279h7PX9ae3ruYWtRfiKI5cBVI7WcYri8xBFJahK8YyEH3BmPX0oZOFJOUuIAjZvCrN6/woTlkQe7wj5u5fT2D3syHLnQMe0pFvcNSvY9133nscvV5XdZ0TvZHiWfgT1yRe0gKYm7xgaIKc=,iv:MiuNFCP3ukGQOG1Oe78+UdTE7sWtiWyghaJErDn0DME=,tag:XevgNFccwdgf6uhwZTQ5Ow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
