apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:mIsOkKSK3PQ0WRDqJmgGnxKFLzQrRZ821GTrLcgdBHU3OMPzMzbtRy125ZKjT6PpAu990UlNx4/WXeFjitlyWQ2f9K8yS2U2I9aXolFYEj2sTopkcnoiqS1ZtuSUbKVxxbyeng==,iv:xyU1wkJZIZp+Mr1GbnJjmv3Uql+JUiCthSqjBXunReE=,tag:fpLXEqwaISufFu5UQfcRoQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d1FpK2U5ZE1KdGV5NTdS
            VVdLMldMNE5mSGpRZ1ovMHJqOTF1YUhZaWcwCmtkdWZHZUFlbzgzUjVpTWNHZENx
            LzF4akpDSlFHRklkQ1VhYmN6azAzUEUKLS0tIGdQQytDZTVGMXdGdENmVC9IZTlE
            bXdaM1FuZ3pLMEVyd1ZOcStNS0RSL1EKXERqIA0cBxjl89lPuskgP3sr2zUy8Wzx
            szlcZLOJRrT2FSpPQP5yq2k1XSx8FhSnPX9GllCvso3MSdes0D9uKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRUFSM1ZlK1dqdStMekNE
            L29rM0ZPYUFMWk1kOERPYWdlTXMwWGwrcWxJCnljMHowQzArM1NEZ1ZpUys2d0VC
            M29qUm5aNHJHSkhSWXlIUnkvSFAvY0UKLS0tIEdpdGYybmdHQmlHcExPaW9JOWVy
            UjFsVVUvZld6RXFTN0tTK1VCa3N1bG8K0vq8+ZscnEXqiyy+iOmK6VjR7Uw60CrV
            ZCwk9PvcsDE/t+y/MT2PfpPAtvzVCq6EOEZh/gPCDtl9OVuoxqT2HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T12:51:54Z"
    mac: ENC[AES256_GCM,data:C4+j0MKRDCgsI41IaLVnh/66lqgftRrBZDsLDVF7kqUIbLTuwSGtGKySKLcop5d5ZBo9eIvOdph6t6tIjR8+FN0F3vIB5vbhUYNvWXhMRX8Vl2PXII27AKPna4pdrPfD22+0ZtvTHisSNMK5jgVIv1vlWEB0BmJS/n0Jn+OQbrU=,iv:7TKJMkWhBs93Je0S7JD1MpjD8NbcNgvmkfJuqoNceSc=,tag:Wf9bK3PffVr7Eeq2MTbGwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
