apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: velero
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:J6TY4PJy+pE323VwW/1g6vR2k/5IOTDXod6W7jHmA8ojlo2YiboCmfjT12bDbx122FqXgv2gynHhzrUgda3USEj5mvD4v3niExWR4lFB2X8joI9aS2dfeLpJnRsJnOzkSr7gbVPwhtYY3A/RtX+P1NhHfrATwcT9H+m3+Fj/VCrsrWHDeXfh4arcug7G2cSP07oGoTaAUz34YZdEgloihXNn3jU57UUNglQGG5112L2GZunhIWysWMYi0Wwx9rrgRWpAX86i8KYhMxQKgQ1vOZjbjhD0bVs4cnLmvUt5AV7g9fxP1ppAwuxFKpkkvd+4k9byJWWUTze3/qf+6sNnJF1CD55AtIRnySwEDmxFqnvyy77uO0IDCMThdXmOaVX7SE9fYK1Zaxkfu6n+ZP+ntXq6keYkGUa22q7BGUxQNayEDbCa5q1VVaJScqbIpEZUltKil09Xe+azSqsa6B2Hdb+UDI1S3+SAJ+iixD2dR2Np2x3k3CwhE4saDN/S6ApejY6Oq6eXPyCTfZJlbRehdrHwiOQEU0EuKk+N0lEmGzrARyNxMU0L2DHpS+ML0c576pGWtgpvntitIL2IPQEankciSbfD3RKXnXqmsehQcQZmIz4DIuL3O8PBGdc/TP3v0r82NON3x+0Vxuh94j0B9k77qs93iTXgdpsc0fCpMlteWRGqIaKLzl6mNM4OTniqhOHjS2sjjQLp42vZRRe/3B7eDZg5sY2HfvxPI7DIPjr9p0OzgqhP+wJAShe4cNE5pyr+VFfYNBAsdcY7xhZOTnqLq3kQFq1hAgayJx+Dkg08Poq4ZgwDf2OZyUFxw3Olll6MiqwBIIwfqBE=,iv:q5arq8daIuiqfXySpw1qdv5ROJD6KMuJCNie+RCVPpg=,tag:hG2vxPVRMubKO/6BrhZ+ag==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdFpSMzZNNTk0QVhiYVFZ
            dWF0MWtXT1Bwa2Q2MlZ4ZGY1bitYWEdNdmg4CkNuNHNHdCtsTzNrVnlkZjRUTFM4
            SWk3M2k1dysrdWwyNWFvN0hrU0ZQQVUKLS0tIEJlS0FXMmxaaWlXVzF3NGZoanFR
            VEFnTTJtTDlRRjFUaUQvZnNnbzhtQTgKzHV20dpWYzO2i1NnOgYg3YnPwJISufQz
            E/1gg4iGEuTD7dEKGB9NBGjZQCFrOTrFl6XbJtuw/ITBDXhahGOAbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHejRxZGVKR0QreFk4c0lm
            bFRia0JsTHRPNnM0a2dSRnFzM25XeXdYWldJCnpOSHdSZXQ3VUJtSi9sMWhrU3Rq
            d0x0U01sZkdsbkhOSEd4eU1BUTlPcGsKLS0tIGlIZ01POGR0MGtWSHNoN2k2dHBG
            dEErenRVMkRSQVRYZysvRzN2Z0NyUzAK370dsnwLM8PS6hDk98Ib2gH2d4Zku+rC
            WsML9x01mxf7ziVOhYDtLKOpEk60zPFd7I/oNIcLO6qiY0p5XgAuHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:55:42Z"
    mac: ENC[AES256_GCM,data:pTlcLrgyyD4dsZl0ncngMamVppUDgoBEGrANQzm70Ued0vMLLfM1CqhYcjmhQJT5LMC9jv+179QwnipB0PlNZQp8brflmjQUETy/YDhEYonjICGSOgDJTRX7FmgRsKWpd78iJr8Vae0PFQ3LtWl0ux1HNJLigrICv9pygjwus3A=,iv:HPqhuryTBwHRel7ECgjmZp4TAMug0KuynFyLJWPJtBA=,tag:PDUwqBvpiK9VgV4sWO+Dyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
