apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: velero
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:mz01RK5mP7ftnCbcBhwfk3eGlvcT0p3Nx7Jtd0YHagV+nTbH1qJSqMk8X+nA8QAOk6wpXXInQU8vdhFYNLPH9SR+ohPnB5iFyRuqlOADM6m1R5EsnJ0PayOeSehoRxSuzd9XbK4kcSNypgnsJGgVTbjdi+jtxhRTcTLbeekNxlpV2wL1x5d4bP8CFljOzX5U09zDZV7wcJ5S9xaE1udKmcE+FQ2hsbwZ9a641lJqaX/Xp6LPrV2b+O4dE1eQtsQ6Ksd29/uIulbSH6IWYMvyp2sGKj0SOdniQvKvvoh7iowHIaATm6tSVgxmdO6DHE8AumYe9CIubM29kMsPQv1yxHTiK+yTCPwtV0fJfxJns9Iy6sgJrKN/ni4kByRV2BOjeT73jhlqca3+/eieyM4XoLfuPEfK85eG3izUnE/U1o6hVhSEY1g6Y3Xus5pIkQBtx0s3fxZDlqm6ciJqBUE4J2hWxwcoy0tGZPMrnUF82Rkci7RzL54LAwMiLium0Y6M+69IuIUsnY2GZ+7ctyRnxYW2iI2ySYsOGWI0d3/uU04hzFbX2n89XIo3VzGsFQT646RjilkXnsng7VCRggP2cDBve6QMbNAwBjD0uonNieqBxTJqTadKnMpL82qvbQzah7HGuzMc5xTwZLsyy8op/9cU61lETudLLB/FApouIf3t6CF3AiF1oSUYd2osEfIUgyjpGusNdUcz8VfIP/CvNAuSOFwNI6evS1OBmqgAFNvqYrdU16oarzfoFFhLZOOCuuAqmA9KNzlclO+8G/HtFe8HDXyChM5u4NYYKyTVkOr5ItSEbldf2b0hky3Tl4RT5arktUjk2Jojcu0=,iv:PkcX6sYSk1Osc7WYbQ2OMq5/NqMVoayJ/TWtizITs4s=,tag:SAKbsH2a8BK3tdsVMiX2RQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUElIbGkycUhld3k5SENm
            bDZzRzRZbG9GSzVTWHR0T0tWNTVmeWtVU25nCjFqa24rNW90b2lBalQrU2tqQ0s4
            MnJRdHArS2p4Ti9pb3FoUy9EYlkxcXcKLS0tIE1QaWJlVytVajdoUlpudUo2dXp0
            ckdYR0c5NzgvMDlndmc4amtpWlZuK28KGebV6xHUwKDeJZLJOodJ+pgyeDJsMh05
            FuSI9QN26pUsYkN7rVByUYGERe62Uiig/zp8d9Q88UKhf/Q1YT+xsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaU94Uk9kUm0zTklWYml6
            UWxSMHJXa2pldlhnYjZWNDUzaFJkMmkweGtnCmJ3S0hoVDkybFNrOHlwRk02alBD
            b0VBcnhRSVkycUs5TFZXSGtBS1dxQTgKLS0tIDBjVjdRQ0RDbndkNzRHcURLR1Vz
            QWJMMXJHNytoRmFyMSs2R3BsSWphZ2MK5+n/Agth8lSD8TTjj/A5MVK/r6c/zJMy
            LF+iGWsfOaXV634Q7G1wSap+dyzhtdANusJ0mwh0bmLk0GEjyVtu9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T01:25:20Z"
    mac: ENC[AES256_GCM,data:w948RoLdd8tUxIidVW+jeGsxgS/L3F1wvQWakb4nzAVGQEQesNclSj0LldaV9OqxwmsFgHDwDkOk/sm1vgvPfPgXetJx4MntPpGYhkVRs9PQyO0GTSnU/vLthbblqQmpX9iT5qZoEItujkacz6/o0hmtARdmZcqmkn6BaHI33Z8=,iv:0ejjABjw+Y8CKA8/WdXdm3zrybq81hDixhXnIu0yKJA=,tag:H4/AQoqmWlL3k/ouJq0yxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
