apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: velero
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:LzZYe6F8UpIGgRJq6BAcEUBhBhUQbaD0dEIKuf64FqXbsUe5m7wVdHwJDDfkuz6SKmSKM5Lf8n94bTyCcRu1gryXmYzH/5nYNgC2PLnWZdlw1fx2bGhzhduh3WURudW1TfT6UAB3wFmu8GvCennzFlQicC5+t0xI7oiKZfHFBmVQqK5eUYW1ZFCiFd9+LWjcBRMa6J3mT2CI0tOlSCHsfEyS+N7SM3UGpqoy2qmvUzsKzc0bl6T4lrtoHRJOLINU3G+V2Rqov1PybPDk9lQpZa9SRcARt9Es2vCdGFt5BbI0jQsyig0TuZdyWeW5RwRK+QMnw+BhUaWAs2k4bfjg8kULnlLtzsYvNu+z8Ijfb4HgeJQCiIKDM2GuxBLV4Wun9Ljhayggt2X953bMnrx5rfqw2oRQieQwEor+Lg0uEMkw5l5p7xG4FeHw0pINIou4ZiHerHbIl0puBBfLjy/99YbXTasa5/zL08B/x01qJSGSZxUoC0+CMIoQU1gGTxPUTxBOEuyn60bFniSxmCg2jw8ctWduYdFD5w6F/QoznkNy1IARVmyD4P2lle3L7grRcthiMN+vFGRQH3dzdxIJBA2s2V7jqdlkjlkynz2weMSOa4l12kE2ia90T8cktjiIZ0wp8a9+LB40zOXu4ACTJzYb5vMe5Ac7hj3Ig3smt/VQaqtWiRDD0M3q/T9J2HBkFFFjTt7W9ZYT2XvDqLMbeyjmCQGxfi3p3gEme99A6Vpsn9GVxkRW9hXGZRCAjgPPzqpk+LwXYqXk91wMQ/zwDAwfwLDzAN0XRBBEKAjs0BXE5Kyto0jq91DSAKoWEgMc/uYAWhJnySj2yFU=,iv:IXBkJmUb+kSEnRIs4hwbThpbqVv9mcZDOEty9CcbCMI=,tag:ijTBTA2abizj1gQdSyYpXw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMGd6NXp5ZzlPTFBMbUto
            OUNVenV2T2pnT0JiRUpmWlVtbkxpWEF3Y0h3Cnh3TjdzeEt6TUFLUEdjQ2lpcWc5
            T3c3Q09xVUF6YWNpdDRuQzB3UEdMMFkKLS0tIDZoa0JLSTF0Q0ZLRE53MmFYckdR
            dHMycDJMQnpDRmNYUFUxZTVoUWJZTkkKdr1OguS5sjIZ7wqU27SBzxS9gmhUUgNw
            3MMb7Tsb58Vrx4ImSugk4Wv6xIiQG6cZTO08HnGJ09t9Xi6LeLrT6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Ukw0K2VRTkwxVXhqT29x
            bWpGN1BrSm9tQkRaRWM2QTFtempmMkFkbURVCjYxWCt3VTl6SlFDeXppdzlpK3ph
            enlFRGN0MXM1VGFOTlJGdnVXR1JhZ00KLS0tIEZ4ZUY5MWZ3UXk4UWpHbW5Pc2pE
            RU9qaGdVbTYzc3RXa0FFQVpDY2dYOTAK7BvRcGtUTPRCdm5Rcedd573GmBBGYxRo
            CWG6ZpVZ5ZCnq5Szw94zbVZ3xFFcCm7MKcQkqdCxo6Bprr0iQhi8rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T20:19:04Z"
    mac: ENC[AES256_GCM,data:3OwSKIIQkN8TRos/WfTHpGAERtoA8/L9EfHc7zOaYwShhYsb6JXnZUEUaSDuO37uT87f11ixg4/rBKEfmZiHilYOjl2LcA+XYX4jeSK8HEu2TeP9+gpF4VlwICTF9d3nytdQrNswOcLZ85Sba5B2rjxigHbHuoUI67q37dY2sCg=,iv:YlZ8TfkRUZn26o78pnuf07xIGN7GBEPuFGxTM1IO6M0=,tag:wI0/tgltVx8VgMZTW28JFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
