apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:hb5ZCFQ7cB/OizvHMa+tW0wOjqj/GlvF4kKlwNDorPeQDnHpeoPrbli1bkA5pKjTAJkxQg7rmV7DWRx7kGXgBfYwv8WfLL3Ri23viW8YvrE8daacOi2u7pU=,iv:GT35Sj6DuSdOz8Obvf8QHbR0R3bFnkHjgCfueZAtLlY=,tag:dH+K5QFb921H1nfdEinIOQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRU1aaTQzM1FVZ2huL1hs
            TXp5NWpIb2RKM3FvYk15cWtNMkVoS0NualRvCjMxVWMyd3NSNTl4S1RLbjhUQnBt
            SDM3dEhzYUcxYVNocW9KYnBLV1hIeGMKLS0tIHRzc0QxdVRObk5NcVRPSnczUkJq
            ei9ZRkJuMG9uUzJldmxtZDBwZHVwc28K546vlfhubhcknEBdyYlOXdedE0jVv3XA
            Qsn6i3Ac74Bs1T3sO+eRahnend8ZBd32VHEhGXudafLgV3HXSD33sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST0pQMjd6aldHNDJ3TEox
            VVRxWHhLOXFYQ05DY1RmS3g5bEdFYXpRZWkwCjhHS3hvcGZoSGdNaitsa1kzZXlN
            N3RFd1RXaUkvRjlra1h1WCswVWtSODAKLS0tIHpxZmdEcWdGeWl3WUNscXQrdGVz
            T0lDUE9CNlBXblFSNk40ZEZ6dFZEUEUKdndRrgTn5HHnQidF2dt2isHs6DRxstxG
            3KjtW6f+6x5ORxr3tr0mmE+J9UOX4sGr8inKFzRvrfsUk5BrKgnRpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T12:27:36Z"
    mac: ENC[AES256_GCM,data:IuFyYjqFqUUwTsDFGJBLmePrexi4yJD1OGR8KXMrJtvOdSZbpGl3SMhWEAWgSiUOyYIGUN0gSbM7WSfPyWtQZAqpl67YPPCRvCqHEUE9N3RlRDwfSDIYbbL3tIe9cPolwv5dLn7Ei7brIoTfTCnI5huMIVH1u7qmXbWjwOoxs6w=,iv:zk/abMpJ0Dp3vCwnMZFElLBfBwsIyvUm1ADJoL4EdCY=,tag:vFRg+lD+0wmJqqSbW5xJhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
