apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-db
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:9Ei9Jgx0M3k=,iv:Nxcg6T0pj4KasinPn4Qsz4kYLbfsnx1Q94zOmo6HDIY=,tag:Kt9/29DlxhSiDCKAqCvKUQ==,type:str]
    password: ENC[AES256_GCM,data:3spWqL+kw0q+grzoqC+gywHGxxKylWliM6bs1Qs++To=,iv:fhvHreQhzMAY64dXnyI7sEgxFShQrsmKfMSYtNYamvc=,tag:1I3m46wfqMJJiNeEX2ZSpQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWWxmS3A3YUI3a2xWb2wy
            ajQyMlZadUoySkExSm5DaWJUejJsenM4K0ZvCktsOGtYZWtpV1BKaCswU21lTFV1
            bTlQb1h3WGlJWUFVVTMrTGRJc29WL28KLS0tIE9VOGJaMDBQVDBjcmN4bWF5SjJY
            SVMyNG1YbTZneXgzUCsxZlYyeFVRWk0KOVBd+FNm65aoPjUBRCVsLJlSytH3Xn1n
            0VRYJBFK+egm5ezx8DbFPP/A7p0c7MnymOYSz44GFJGTEyzTdg4vWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaDJvclRibUoyTlZPaWVt
            M3g0ZmFQSTNMc0h4bDQvTm9zMlJRV2lqcTA0CmYrT2FpNkloSlBpa0JXaG5TRGlh
            czZVZnkyV0ZXeWF4ZlBBNzJxRkYvL2cKLS0tIE5NMUlvTEJFenNIK29aSmI4VFFE
            MGxndE9aL1gxclM5WGl2TG5yN2dRSXcKCZ/HqmhLMoP6yHp6AS9GJwTXEYYW90e2
            c2vShyCEupqJBQPfXUcbJT3CP7dTZFpsUArW4mcuYprjm4kzkG12FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T01:38:36Z"
    mac: ENC[AES256_GCM,data:lZKBXNHvwEMNZ2kj1Q3LAjZzr/+UqhnJsfX67fGqCkMFCczVC1EwVtZ0OCm7eXwGu3JyvnPzASoZoHV6osnnUzm3Ia/lbHrMfO+aQvk7r/FyNBfmK4NxikYoPXr15tsqiqpNyP9i1djFrGqWoHY+CNIp92DetG4AUXtp1aAxI9E=,iv:7ARLThdaKtW3hshP6Q4d8BZNwIhdfvOeXbGg2zTw/8A=,tag:4ZuP+HoRPwnn1IEJXPSKsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
