apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-db
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:aBVmLN/CEsM=,iv:q25wBhpFYor17qkzjXjXQD/TmMErfIDXM900ULf0gGo=,tag:PQFB6FXv7j/5DiLofBzjRA==,type:str]
    password: ENC[AES256_GCM,data:vawT8SrjknsONQTQlpIPVq/IviBaDUM4o4ujer7A2a8=,iv:aUVyQ5q9k6sE17G6fm7qf+cZIhUtSBggrSkpSTbxZMM=,tag:YMoTNCy2UhpzO1W4x2DxSg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SmNPRUZLNVFVMG9pRk11
            NUl5QzZMOWVrSitzZk16YlBFUVo1UjExZ0hRCmVKUUE2Y2dxMnVOY0pnTDIxaWF3
            enBpWCtaWmttZmdHN2Y0NjBzcE1mdHMKLS0tIERLbllYZWFIRm1ndTRQVUFaSWZX
            MS9GNTlGcUt5WERvWXJRTE1tSFFsOGMKBVx5BHa+omD7NrxtQcNa05SR+lQwPy7C
            ni/y2MOPM81SMHhYblXwqIfuVNOZ+E5HFJZje3bZPvXNOmmCzovMAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTWd0ZXdzS05lZzJVZmxN
            WXF6VytmRTlRckdQS1Z6aUxROEtXZW5id0ZNCldsZEE1K2dpZCtmeUlHRmdSZlZt
            SjE4QUk2eSsrUTlENDNLOWlCaHpKMkkKLS0tIDl3UW11YXN3b0lOamRIbGJ2ZTd1
            WnBJZDJXbzJSVFdCS2l2cFNqWUhwU3MKNHaqkcJDJAkPtRL3GwlWEAlXoNV1Ktnh
            26fL0PekhEzZ70tiJbtYhshaLS43ndPFSIaH6Vj3XwK5Rfi7gbhD2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T01:57:01Z"
    mac: ENC[AES256_GCM,data:csMvzb97ng+bnNSDETbcVz6475PLm1pvgvflPxgpJVI8Y841nOwqTtvzItBUDQ1vIj/k+kbU6zWumiC3xfSdKhxRkbU1H958ruPU7zaUo5cVOCRlEfEJaJRqA1ji9w6Rdv78lkvacvUwrS8yRq0l2/fN4c48QFvj58NjeZYdjLE=,iv:F4Ajm1RdviIJVSRdf/X3ObBCL00cW7TubLbvygJ7tac=,tag:ygOgyrNHe/UutmuR2TDKrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
