apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-admin
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:GdDWCII=,iv:IIn1fJNCoTyjx6ujaCm5sUcGn5HUOt6yaBHY61vvbQQ=,tag:hh1Beuz+twLW9plpJ//3Gw==,type:str]
    password: ENC[AES256_GCM,data:MryBYqhWb3/4pED5wMUrqw==,iv:uNpa3KhQiBq7RSA02/EETdezAeoui8cT8ssu5nfoALs=,tag:TvHYP3g+bkGeCj5yth1/Sg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ2tjb3o2L3dwL3R0aGlN
            bmFBeEdVWnBPRnErZlVwQllNV0RmeUZNRGhnCmJIbElTdkZMempQS3ZwVERuRkRh
            a0JZeUtjdXVxcWRnVWNldHQvQzZjZVkKLS0tIDhNNzRwdWp0ak5XeXkxc3oxS1Bw
            NFdpZElnVFFBV2x5YmZGV1NBWUR6MTAKA7icUtl3pdwYLpnqdmli1VTHjtlQaNs1
            pz2Nd8gke1lsqRIJig11PmhFw7Uq4YzJF4kCrXrBxtqkltoUhdGvLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQXJKekVOQTFrRnltaWEv
            VkdqajJTN0U5bWQzSklPZU85VzNyZXk5QXpZCnV4VHpFVGU5Qnh1aWVsQzN4akh3
            OWlBK1h5Um9KSE1UeDRWdGhFdTNqRjAKLS0tIGg1VmVhMkorazZnT0pwMXcwMTJW
            T2RVdHBNZU81V3RBUTd3UkVrV2lzZ2sKQKn4KK6+FayutMuJpKLVzqJFBZik8kfT
            w7C4Psz5vrfG87kxQLC4T68Pmbzq473tPONBIxgg2U90jHMho+wmyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T00:59:28Z"
    mac: ENC[AES256_GCM,data:t5yDynIiqdw+sJVkH8Bd6BlD+u0E2eHQ+skQHcaUsjo36SY63DhVlgFvlWd3WbWCDcn8EJnJvi+LFuu/LD2Rk9BFagxKGoaX8js9erg1uKQQ5NYhgOKs+6vRb7Sbr/4AjibGv02kTGZzMcSE2I9sUBlvwRiBlNHbTSnCqz7qBRY=,iv:aJApezDE6ADsAkJ6AcvzBiaL9tW+JOHJNx9zdcGYjPY=,tag:TzlB9qtvWzb7evR8kw9NAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
