apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-db
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:zuRsy5GaRFA=,iv:xhu9MyvUTXBSEogeqcDXQcpJ8tUqF4trVtsZ2eYB5U8=,tag:pByYLlCQEjstIBXqjhJoCg==,type:str]
    password: ENC[AES256_GCM,data:+l2p7dgonKmrymdBKQ87kRduudCyTy460hps5ziQFe4=,iv:O2W7EzrZSS18wQOT5SvzgSJ9XD4EL6XZf3aERNfWfCg=,tag:5arg9sQSOHoHFLGB40oBPg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaFlCMDg3TURtSmNMWmQ0
            WGcxY1NoalFkWjF3OTEzRGFPMTU2L1Fxd1gwCk40MWNRbmxuSU10M0VGN2dDeXpu
            UTJiSmdaUk5aTGNMUUpOa3pOWGVLZ28KLS0tIDYzZEgwRURBWXBYUWpaQmhWWEc2
            WndnMlVHODY0MHJVaVBHbFczK09YWEEKywnV+8P4/R9/qNTF4Zm10ScfdxYAbU3j
            1Jiw/HlDKGYBxQzPQekHTWIqSEPaG1fPDHsjwMnaERTWIPJLlXOqYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUFJNUU5yU0RNUFY0bktP
            NW45VG9JcjhkVGpxZ0NkVnB4dG8rbURwb1ZnCjdITkNONTJPVUpIMG9nbzNQV2tZ
            cmliYlB3WFRhcW4xUEU5ZzZxTE9QTmMKLS0tIFFyYUNvbEJsYVVsWEMvZHkrMWE0
            TFF6SURBcDhUU3FHNUdnUlJFblRzN28K57nbQYCrgbeqNZ1LNeIfoTTa2nyGZJs/
            9ifW9g4cQhGeZD8OL3SL241eNm2UnEVLoncdO68vlC9EYH+bKAxPrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T20:31:50Z"
    mac: ENC[AES256_GCM,data:YlHTCYwmQSckg4uWJRGNjMX0RA9LEAxuQhhjAU1Y/5w9RM4tJBFTllHDH9csehjTKH3vOq8J85XIECcSTUlG9aWlDinoWHC3GVvI9rK/iLPVVriaVK65BWzGcmKX+1jXL8ZhJ42mj1TqsiLWzxA/1TjE9T5e3dRF3t/ofG8WDMs=,iv:qCBwdOIba8VFeOhT+aeaiaXqEYKrLmwXpvx0nD7wY2I=,tag:3qVLEhIujvIvT7uNz0oELg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
