apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-admin
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:09LmHJQ=,iv:iK342E3xKUihrWUh4pjZsVqDf2J8ABuxKevH3ipaVu4=,tag:GeGUGY/DXxPWUS4jdT2fZg==,type:str]
    password: ENC[AES256_GCM,data:vk0ktkdZYdUpJLHRxrfqkg==,iv:Klvo3gpmLr+rWHr/bH69j6u4y3kgeS1uVIH/CLo5RTc=,tag:CkLequ39kIQ+vkIIKLjGOg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRExKNHFZM3F2WXN0Wk9H
            QVNXSU5oU3pzMzJNWjBSc2hrNVYxazUzWVEwClp5cHlWLzRxVjNsZVp3V0s4blNR
            WC91Q0orN2E5MWcvNU5lRk9xa0pkMTAKLS0tIENhcmdpTXhuU3F0SHkvWGFjUVB6
            MWhHeDlwUE5oNG5mZUdUUHdudGpjQWcKX2a/q/HnOzvvqoAUg67+KKFDMBA1QVZC
            OQPYjoiqeAzBop5c60B25IiBIR7VFZTPVZEf4rNMTLascl0uY+f1Rw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucnkvZlJ2VXV0V29uZ2ZF
            OE1TWmdGMEFuQUNCTUpFUGFvNjQweXd0Z1NBCnNzdUhMK2pEZldjNWdNSTFsNDd4
            UklrZExUd01POW5MYUQ3N2QvaGREdWsKLS0tIE0vSUhRZjM1MC96ck0xSHlSU0h3
            MXpCQkkzSWdKZVg5TnViRGRxN1NxMmcK3OI4m7c4BzhuM8JNIoG5DvW1vmnbP/ez
            4PWZiir2y6JqVrrz5V16LBCMvn+3nxfzqikDHe7Lz5bPP83QCwNYEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T20:31:50Z"
    mac: ENC[AES256_GCM,data:kktLMVOxnapCyleWrA9NA2thwrcFE/IcEwCnYmupMSuk6ofuPTW4u3kxs0Nk//f90n1K0OzXtRQVZ8wylAEgX7uRzq7dQ9qdnfJwypTKP1NvnIB/kKSfq9OSZim5SitAObx0bYnO0Bo3gJ73cHvgvZAD2O3pOiDcV7I8j7A2tno=,iv:pa7CeKBZ5ia3HAtcHEV5uuMaAFt+cXKRwCBZVSOaHDY=,tag:vx7CHfruHv87uj4IZKW99A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
