apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-admin
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:SUjNDrg=,iv:v3Wpe0RttE3UqyOKNsDfsSrXOlMErr1dIx/ZVfHl7/8=,tag:2JiyGlyhhq0niQQquwkTLg==,type:str]
    password: ENC[AES256_GCM,data:kh4tNpeR5fNufohyg4cVGQ==,iv:GHelUuv99t0oszaujz39XntqTbFTy8o9lTWiEhpUanY=,tag:wxjF4Q0CJZI54tKmotT7GQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZnR5bXo3MmRUTUxqOGg2
            NTFJa0ZFeEhPcEZsRTVNY1lHSVdRWXRsTkFzCkRaR1JFYzZjbFJ2cGFqaG5MME9n
            OEt1MWFlSDl1dDhGZ0R4K29Pd1ZzU1EKLS0tIGhrTUM0R1RXcmFzNWpwODhPV2ow
            eEhhZmpwdmhwems3NzU3WmR5YnRKblUKsRFUMl9GQrMeb8MZFcWUJYgFe7XpWIjQ
            le0ic/IJ+E+hNehpgR2pA3gKlfmxNwf2c+nGgOlUWOMuOzbjdyQO5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdGNNL2kwVUNKL3ZJa3cr
            Tk5sWnczN3dxTkdPbEF5dFoxdStkbVArcGxnCm9tRjRvZUs0T3RxSVZaUTRLSEV5
            dmR0SFhTSitwdkN1MndyN2xMUHJhWW8KLS0tIC9zVWpHZkNDbG43Y1phZzJRNTFO
            RklObnNIa3hLVUFFa3lUNlZmd3FGUEUKSKmQktsheszx3WSkq9+FjBfbD3wctaTh
            LIrxeIvSu+jA1jirDO6wK9tqxJ8L6DNysUc/Jkk4NdsZP6LbtOylSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:18:59Z"
    mac: ENC[AES256_GCM,data:1HXoIiRzOekgrrYBBlK7PXkW0UPuGJmn8G7zGNCj7rFqOtBqYM7tdtCE+GbeiqM+AF441lbJqcj1hDbTOGnPyu7PJiJ/k/HfSxksvlVVA5ZFrw6IoOrUyiInWYKimki7toet7HDwe96itErBrFZdI159wo1+hHXyThl62ayAWVc=,iv:rKXhk56GaaStvXgjI8mUdbLjdHtG8vZ9BjWnVp+I4vw=,tag:9UCV/VKEG+hYwm9pt3DD6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
