apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: keycloak-system
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:RYwieQ30j28aKZ12QCfZ6Nl9VZCIep4iZLdygoBrGV5Zient+ZWUu+bbd4AdSPfpVFeLnrDBEkz1r/1IFRXMEBJ9NUwsjjzA0Wd3ah8uWbJaxx2Mdn+nDr7YVWNTq0lC2zr3ptjO1dHCcj/rZ4D7PdeVb/6PHtvK0WzXeR3O9/94L7r0cxil5Vd+ZyE1Wb+vA8LP18n0ZQ8TeR9qEy1J1J855OfpwqroQHmzPr05rCcwD7XCK6wxvbxJMGiftIgoiul2FUowG6IvkK8xubO3lioPYk3cvDqYHYP7BVodYbAoA3Xbnyy/RUS0TnxQHptob5NxnIuajbpJR+RpIEBn+4r4eITIFoCdrSL7CEGaiHNoZXe1P6cVyTnN1vTY3jSKnNUcBxmwAtZf0CUjLsL06o7vvYpd8GSkRxMriz8li6kzqEtofN+VwQ8TJCVTHAnTfIZ9DyqLTYEa2VlfkVjlhyb946vhS6hXzGCtoNRiOJnAzFZRXR9Sk5+pAkLAPoZWvReWTSLbvQ91ItJjqqfYjZhee31XPtVqjsuw4YpIP9ePkPGU0A2A9QNvPZ8PZeE4pa8eBNNC38g3h+YM78HXaooxCirihwRBG5xqnFrd2K/8rzIG2q6OGSx+c79pwEf4VIP4tR/KopHzqIpCLmnbj/czE2qfDdPenRCin/WHfQ9/7fiYwqEQf8DNHkYTCKaEENgMUuMF+NwWfH6S5LqSUPjohEk9Wb0GIAofpcezm9BnhmEOFbqMwOfSiYGqz5R6bKPIn8A/PuG1Yu3NJMPAeND60MPQbmsg+Qkg+xJcMNDOrTtLrYjyE3zbh+vec3c3SBGSSQAAgetY4Cs=,iv:RJ1L7ADK7ymYYoiLET9JjTniqK2ahuQoaO0ua78kUq4=,tag:17xxQfBq2CVA5UVuKzIASw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTG1vVzJnR0FRL2ZlbUtO
            L3FUMFlhdnNlQy91SVUzNk9MWWpadWF0UTFRCnZ5djViUkJZZjBtbnBmQzJzbDZC
            c3FZWDNjbVlEbW42Uzlod2lHNWovY2cKLS0tIExoZGlUS2N5eWNGWFFTV3QyaWgy
            MlZua0FQWmJHc0s4OHV0a3VHK1l4QkUKspQzpEyJ6ZAZ+KdQkw9RwIuJptCtx0yn
            0SdvjO9c06U9fGw+a2/XG836MxefyyEzi7a8wqA3IzoFvKzI2tBiYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQ3BUYjloRm9OMGNmZTRm
            eGR5YVZwbTNuNWd3ZWJIOWQzUWJPTGhQK1Z3Cnd5UXR5QXlUV2tjOVJMZUF5Y25V
            RVBuY2xjMXZCK2tpaWxYRkwvMEVIS2MKLS0tIGZjSnliNWhTcUNEaGppUGc3dFJH
            NFFXb2hxc0h4eDdVZU1seHFYNzV5d2sKzb0CUOdZCIIWV6LZK43kSaT5rcOBRBXU
            +gWPjrbu5YhNVbMhp+Y0swdkS7DXDvR6NVYncmfUHZm//Ne8VxOvSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T01:25:20Z"
    mac: ENC[AES256_GCM,data:dcosPFGGBM62E3tY/xkcdH4cC/cRw5L3EnKAiXk0WbjPC/x2KgYsyrJyMbWvcOtPhl27i5QjZKbdAKJ7wkJP6Qlu+6CQX/jKHbgG7NXtpuAHj2/2hMmahV0/IJZ0swYiTHeJHM9nQkiWvF6eQWy6a1pYeTm9fVc1TjMZh6Q+vzA=,iv:NaOG28gSdYGQ+vXVhk8jR9oVoGoSNsRo4/p0CCFzQRY=,tag:ResJkGDGP+9YmzG2+lqMZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
