apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: keycloak-system
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:EeBFrGuXkJc4jzyl4YBrsXIbkcvvCil7E1vwnJvjdihJE5ooFA+9DWuOKcJCS94+9yJu26PR+x2tiNPqhmWtjPM4GJ1Y1ZnQRKZD5u+QgND6HWJmhaaazAaEJgCkN0zogUvCmsqQVnR1+4azKGZD6iIbYGDgcrA/wj8u+4yMkmfuic2VwBXAQ8hhoaF5izVNe7Kwk0d0GFfCpVNXm8jj5Q7se0/Nd1YBoaBkvZqzpc2e1VfoGfdaQr5tCvmSLU2gjuItiO2/gj2qrnbFZAWlqdGIlHGOvyxb+7H0g19bPPnBblR40fDiQGziO6QILTN5D8Gf/t7dAOo87UcuX64/g6oo1XUnWzMS/WOGg48R6RYT4e7wHCgg/MPti8xN6QBzwKrvWVBEkmF0mtjJjQnjTk9B3K9tdZGBSDbCCxa5hWVGr8pi4NUtsMTXVxP16st3CpNOGfIwkkZbZDvALor6YD6hJxbtqBIerdmaGSCgLnSJn8CfejTQTNuW/aLUeFCf299Lo9vW2CCC0bSspffTtRPMqVn0rAvXfnbYOwbo2LYbKHBhpfPxi+Iy7FnfsD2dDeCe0ZByOE3Bo/iJlNw80FYnNNupjIDU9U98mtYV1Fu0l2oHxnMVLo8VCtHcifP504eKs5tQZNA3BXu9j1xlhrwtqa2i+ESKSNWSMjf3oqIXgz9/dxsCDneFrmKqqzIKh5C4zRxBw+0w5+fJAUg1JXrnhfJQb/8w4Yzv4NcYa4WGHfYy+KTo+iC/wwBZMtZjo3PYIZgwvOamVcxwCtYDR80aUw0i2kMU+tVdBotvOvrx3Az9Q4dbXASAJXuFSG/kf4SmWo998rXdC8s=,iv:rY6rhJ+7izzv48A5Ipe8+gSDJazpJHjQNREh7Sy0MOA=,tag:lMW22OlxJgAbBTti5i2yoA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY1J2a1RrY1pVKzl2N0lj
            amZ4ZzQ3UHpaTTkrNUlPYU0xNnJyZW1PMzBvCm4zRkdwanpDK1lsNHoxYnZ5K1Rk
            b2NUK2NjakJ6UnNNRmVmaFMvR1l6L0kKLS0tIGlycitHMG9qd2hxTnNQVzBRTkNR
            TGRaWGJ2Q2FjK2dqQUMydjNieHN3MGcKOaJNX87gUceIbYNWl+1qMNtdGgaJq5Ms
            s55iYlJ247xDXYu59Z24e+v2v6Of8cEFWOy4bTdPvIeK7gabv0Cnqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUE80K2pSM001eC9VMlBI
            LzJ0YVVRQzBkUktHOEdqR0pGek40RHBTMGlnClhkbDBsVkNOZXYvSGl0ZEJaZXJD
            MDdxeCttbUI3b09Qak8xcWpEUlFOeTgKLS0tIDlBOVBzUGJPNlRPZ3dGb1ZTcktQ
            dGpmWWFmYlA4dHc0S2FSc3VGWm1HeTAK544kUfhtgZuf4J2aYJaUEGgrhcygaPt7
            +lXX7NUiCvFMa8ayjaiAzQWcSnHmeXZblMWpAvT/0huR4E6yquRICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T20:31:48Z"
    mac: ENC[AES256_GCM,data:r0GR4k0S/+0Q/xWN39MVkmksq0yzxerOOZDnzXQIygTtn4ZGDz/e3NOdBdAUxiC1OH9PptroHgQcahTw4ENE/lg/c8Cpkqf4OiTDPWjVOfBaKE7lVt56lP0N9LSPEESET7zrdFQfNWqhmSJKt3/96zUgrZOn7jsGKY9XEjIgHg4=,iv:JWgB+87EGcHwmzTnVEsrFrpSdhgboMVvAStgMFqKFJw=,tag:0ovUobA62iaHE/YE+mPeSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
