apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: keycloak-system
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:UVsaMtklfnW3dBR/OKgXuZyo8wEYbqPA7BF8aiTQV1Ez2FuUEvQqSYf0WHo3dZuFrdDU988ZwKPBhR9ZbxjVQ9/a1z31IdUZd+JcGoO9vjoVhvZE9RokEL+ePwi1rTb57EoWJxHKDdQZvDgx2jJ3WLYP8gQdVsfn0u3ZI/KV44dBO3NeOsQQn5FlY0YK7bL0LBZdXrrgInY1i+Y4pb8gny/qXpLWtTrPnFDxbHitHpc0mvflUXLvv+kB9rYee0m95BlyHDOr25EiXuOdZ/usmIdOzCNeVP7CGl15v7vkzOSgYGDkyW0f3roFi5MegPAuJi8OE+IEUg0qaYFAQ6pZmwBEAThD9u3SVveM630kV+aMiICaprYuAPFZbcbHozNNnS2Y85RUGkdAPIh200j2cfYFajWMkMCodtuLaxP8Ztidg8Tq1ku3RSjHF1k5B2k59xt86xfSvi4D6gLIXseLuUv0A57ScdWI/NBYmYKNxCAHnl+VBjrinKTvs2DVxQIe606qtwl/A/qskxSNNlBVa+CZOz857zGQLfDhd9vu9mj3kK34XqaLONAJu++isZO7qwBhb9agSey8d/HAA6GaPvjodxKYWeYqeTe29TJKDQcmPG2zVgpEnKvhEziKllVshfMK042dzvrpA9hm71Mda45wFmby0wwNMTsWEkYLS62V3Motq2HoeII3goTNiMCsP3MOhAKQXincuRUSphr2tQIbn0YKrSikHjtddWCfYQjAnBhYCcK9V2F8AHISa1w4RGnagBKXBfbFW296zR0DJ9G1kz/3sLgKXLCD+UYzQFiiQT4vdHrZ9TjDjEC+8wYTi6xPrDA8gqUD3TU=,iv:ptThojPDUeUUm14sWsc9654TBFH7jl945irJXIo91os=,tag:5Wzbk4xrgvC438SO9bayOw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMnd0cFVTNG5oVHUrMW1B
            NytDcGUzOE9Wc1o5dWNMNFRqdWIyZks1RXdvCi9STysyYmhJb1F5RVFEcThLaUw2
            V0Y2NUl0L1U2T0xyWWVEa2RmVHZiQjgKLS0tIGxVcVg0TkN2VmhiT2JaV3d5Tmhz
            all0aitsM1daUVJsaDJyZTNTZmJ4SEkK9hSYX2G8IsZis9wLF5yYByb+7tpuThOK
            vA0OOVTBB/TG7lvqr3Odpj6ayBzasxglKxXegiKka45X2V+wpXgO2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVUFhNDY4a0RWaEROYkV4
            alF4Y09JQ3BNN0piWi9nSjB6UkZtU1R3amp3Ckw0U2ZmSHFhYzFMZHBsVzVTcWhq
            dWFjc01CTmt5Z3FuaDVDQ1NJTTc5bjAKLS0tIHZIVjluZGlqOUM3eGxNK0tzWE5t
            cjVyOVg2bHRlUTcyU3B4NFVrOHhFZTQKA2mJKECVqWeyTN+AvO4jTiK/UacNVsPs
            3vP70L+nN8FEqTPpnjGvtBMlCZUtug35+/ThH0anCzFYNxerAQqhLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:18:57Z"
    mac: ENC[AES256_GCM,data:/KAZUfE1HZPM6WNuN7RhaPGTg6HxoQcsUdUVOk27CEk0py6pGrfxUehGb7o05nW8z4WrpYlfwKv2qoE0ULEMpBligunMCLBcVjbiq03QjBIeEEFePMEhEnI6kjzQj7GSdaCFen/NJxgSKMBZIygizzww12WyDTJALFhrMS/Know=,iv:sDoul393b4ugSM/KmfCk+tXH5Jl97Mxxy8Z1+uWgKtI=,tag:ikhzbFUD4vfpO328UpF/RA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
