apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 2

  bootstrapAdmin:
    user:
      secret: keycloak-admin

  db:
    vendor: postgres
    host: forge-db-dev.int.aethericforge.ca
    database: keycloak
    usernameSecret:
      name: keycloak-db
      key: username
    passwordSecret:
      name: keycloak-db
      key: password

  http:
    tlsSecret: keycloak-tls

  hostname:
    hostname: sso-dev.int.aethericforge.ca

  ingress:
    enabled: false
