provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

sources:
  - service
  - ingress

domainFilters:
  - aethericforge.ca

registry: txt
txtOwnerId: external
policy: sync

extraArgs:
  - --cloudflare-proxied
  - --ingress-class=nginx-public

serviceAccount:
  create: true
  name: external-dns-external