provider: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

policy: sync
registry: txt
txtOwnerId: external-dns

domainFilters:
  - aethericforge.ca

interval: 30s
logLevel: debug

sources:
  - ingress
  - service

txtPrefix: cf-
