provider: aws

sources:
  - service
  - ingress

domainFilters:
  - aethericforge.ca

zoneIdFilters:
  - Z042963214MHQUN095Z4Z

registry: txt
txtOwnerId: external
policy: sync

serviceAccount:
  create: true
  name: external-dns-external
