provider: aws

sources:
  - service
  - ingress

domainFilters:
  - int.aethericforge.ca

zoneIdFilters:
  - Z03884493GFEY7I35UA7E

registry: txt
txtOwnerId: internal
policy: sync

serviceAccount:
  create: true
  name: external-dns-internal
