provider: aws

sources:
  - service
  - ingress

domainFilters:
  - int.aethericforge.ca

zoneIdFilters:
  - Z030298939XDSJ8Q3G45W

registry: txt
txtOwnerId: internal
policy: sync

serviceAccount:
  create: true
  name: external-dns-internal
