provider: aws

sources:
  - service
  - ingress

domainFilters:
  - int.aethericforge.ca

zoneIdFilters:
  - Z10476292JQF6ME1QC662

registry: txt
txtOwnerId: internal
policy: sync

serviceAccount:
  create: true
  name: external-dns-internal
