apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: step-ca-int-acme
    external-dns.alpha.kubernetes.io/hostname: sso-dev.int.aethericforge.ca
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: keycloak-private
  namespace: keycloak-system
spec:
  ingressClassName: nginx-private
  rules:
  - host: sso-dev.int.aethericforge.ca
    http:
      paths:
      - backend:
          service:
            name: forge-keycloak-service
            port:
              name: https
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - sso-dev.int.aethericforge.ca
    secretName: forge-keycloak-tls
