apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: forge-keycloak
  namespace: keycloak-system
spec:
  instances: 1

  bootstrapAdmin:
    user:
      secret: forge-keycloak-admin

  db:
    vendor: postgres
    host: forge-db-dev.int.aethericforge.ca
    database: keycloak
    usernameSecret:
      name: forge-keycloak-db
      key: username
    passwordSecret:
      name: forge-keycloak-db
      key: password

  http:
    tlsSecret: forge-keycloak-tls

  hostname:
    hostname: sso-dev.int.aethericforge.ca

  ingress:
    enabled: false
