apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: forge-mongo
  namespace: forge-mongo
spec:
  members: 1
  type: ReplicaSet
  version: "8.0.13"

  security:
    authentication:
      modes:
        - SCRAM

  users:
    - name: forge-mongo-admin
      db: admin
      passwordSecretRef:
        name: forge-mongo-admin
        key: password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: forge-mongo-admin-scram

    - name: blackcircuit-admin
      db: blackcircuit
      passwordSecretRef:
        name: blackcircuit-admin-mongo-password
        key: password
      roles:
        - name: readWrite
          db: blackcircuit
      scramCredentialsSecretName: blackcircuit-admin-scram
    - name: blackcircuit-web
      db: blackcircuit
      passwordSecretRef:
        name: blackcircuit-web-mongo-password
        key: password
      roles:
        - name: read
          db: blackcircuit
      scramCredentialsSecretName: blackcircuit-web-scram

  statefulSet:
    spec:
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
