apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: forge-mongo
  namespace: forge-mongo
spec:
  members: 1
  type: ReplicaSet
  version: 8.0.13
  security:
    authentication:
      modes:
      - SCRAM
  users:
  - db: admin
    name: forge-mongo-admin
    passwordSecretRef:
      key: password
      name: forge-mongo-admin
    roles:
    - db: admin
      name: root
    scramCredentialsSecretName: forge-mongo-admin-scram
  - db: blackcircuit
    name: blackcircuit-admin
    passwordSecretRef:
      key: password
      name: blackcircuit-admin-mongo-password
    roles:
    - db: blackcircuit
      name: readWrite
    scramCredentialsSecretName: blackcircuit-admin-scram
  - db: blackcircuit
    name: blackcircuit-web
    passwordSecretRef:
      key: password
      name: blackcircuit-web-mongo-password
    roles:
    - db: blackcircuit
      name: read
    scramCredentialsSecretName: blackcircuit-web-scram
  statefulSet:
    spec:
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
