apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: forge-keycloak
  namespace: keycloak-system
spec:
  bootstrapAdmin:
    user:
      secret: forge-keycloak-admin
  db:
    database: keycloak
    host: forge-db-rw.forge-db.svc.cluster.local
    passwordSecret:
      key: password
      name: forge-keycloak-db
    usernameSecret:
      key: username
      name: forge-keycloak-db
    vendor: postgres
  hostname:
    hostname: https://sso.blackcircuit.ca
    admin: https://sso-admin.int.blackcircuit.ca
  http:
    tlsSecret: forge-keycloak-tls
  ingress:
    enabled: false
  instances: 1
  resources:
    limits:
      cpu: 750m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
