apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dev-root-application.yaml
  - ../../../../platform/metallb/overlays/dev
  - ../../../../platform/external-dns
  - ../../../../platform/step-ca/overlays/dev