apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../platform/step-ca/overlays/dev
  - ../../../../platform/cert-manager/overlays/dev
  - ../../../../platform/external-dns/overlays/dev
  - ../../../../platform/ingress-nginx/overlays/dev
  - ../../../../platform/argocd/overlays/dev
  - ../../../../apps/dev-root-application.yaml
  - ../../../../apps/hello-world/overlays/dev
