apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example
  namespace: hello-world
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: Example applications

  sourceRepos:
    - 'git@github.com:aetheric-forge/infrastructure.git'

  sourceNamespaces:
    - '*'

  destinations:
    - namespace: hello-world
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
