apiVersion: v1
kind: Secret
metadata:
    name: blackcircuit-admin-mongo-password
    namespace: forge-mongo
type: Opaque
data:
    password: ENC[AES256_GCM,data:1CfFWvp+hIiNTAnl3n2IFqK3GudxgSHF+eOOgDc5428Q6X0S7WHPNFv/CCly3apekgugumD/d8ue+h8Q,iv:/PGZ8NiibtFgF4qjBycOyn0MPrMVAT4ZVMyALopQn5w=,tag:7t+CGaBo622s0e23IPzOGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR25QUWpiUGxZQUZ5VEE2
            VVlTV3dHK1BKdnVIUnZlWVhxeDE1L05zUWpnCmdKaVJOMGpRZzJCSm92QlprNEZ0
            dFlvNGVIUUFKNlhIV20wakdJdk9VbUUKLS0tIFNyUlZvNmRrc1MrVmZqVmdSblI1
            MzZxRzI4WXpyZVRhQUdUbC8xYndFcVEKmZTK+/Oor/oqAsAt/BGY7JNaCJi/lJx/
            q1Lx9Om1VFwQG9M2mw0B+Vz3zl7V9/3WNP4hKnyosQnftIg9RYqz+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSENrelkxWTR6b1kxV2dy
            UGx2bWRmckFoUFMwcGp2MlNaODFjdzUzdVJ3CkRvUDRVTkNwdjZhYUk0MVpkNnNy
            dXJvYkJmM1hXYzR1SjhiaTdnZkRKT28KLS0tIHNvMXNsRW8xcXZhKzJqei9ubHlP
            Sk1lU3Rja25yVTFwbEFZbTEwT2JsczQKlcKfe5HgNvX1SKbB8KJ/GlyZboK5h2wl
            hjCmHg15VhU4xSfH9foqfg840mq0vhlcbawl3eBUmQb6Hd47uHiPMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T23:45:11Z"
    mac: ENC[AES256_GCM,data:ZHdYJUJkqI3drvJ5mQfF8amNQRJR5Zx0Ig8MJOk+R4rqRMo1X072kcsu4f0zDO5iAk6toCmwFARBuEkhFUgISvCxgJZVydhcaCyBbFdP122/MNkOM9kHAfFD4iNDKoTd0clFNNqBXAfdf9sT8Ws2sUl91f8nqkkUIJptdrrvAJk=,iv:rIh0zev4tYh7SM0GGoKEpL1VYwCoWEaiAaAMC21dCLw=,tag:X8TqkCs7Uj4pcyvkgxg9kA==,type:str]
    version: 3.13.3
