apiVersion: v1
kind: Secret
metadata:
    name: blackcircuit-web-mongo-password
    namespace: forge-mongo
type: Opaque
data:
    password: ENC[AES256_GCM,data:5ZuLRofOIEcT7Tjquz0QVUs3arAFcdjjg09LRLpO6JfD88hIgT49ytD/sVZlsxrCvXABA+WwBgmPlbz2,iv:+7rlg9020Mfa49ydL/pvXUPSdOOHnFuhEtk8+fDL/XM=,tag:2r/BIs1Ihozm9wJzkPAJag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ1cyUXN2R3ltL1VwRkFt
            Q0toU0FrSXJjVDlSR0Nnc0tBOSsxOWtSckRzClUrVU5ZUWlDZjUxMnlFVE95L3Iv
            SFJpUi9CTjBHZ3Y2bUR0V3dWRU1xMGsKLS0tIFU3N2lxWG1ZY3BYamJxaDM5YTJj
            UHE2MnI1aURCQXh2QzBuYkhOMVcwRkUKP5/bQ4GqNfm22kEJ/AfPu1pIdJcUi3Ai
            A8mUA2m3qPX8bEgsUNvTmF8vwbeWX8UUKcff+HBf8k1gt0kyTGghYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUjZxaVMzR0o2OHFaN2dI
            NG9INFFBL3pSWEdXZ2FUejg1Tzl4bU5qUGlVCjdYdWVvbHBVNVlKWjAxeC9GM2hB
            ZGZybnZOcGxBTmlDcTErL3NBclY1Z00KLS0tIFMvQUFDRURqN2J4M2l3T2pNQlc3
            dWsrVUY5cFdiblR0aWFXV0lkRTJWOHcK0/hO6ABvvVqDI0qFFgWOeyiUvJyfinvH
            uADYpq27b7RF5ymFMRZ3Efeh4PshRx3r8vKYgF1ZLPZlMrXAAc7lUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T23:45:11Z"
    mac: ENC[AES256_GCM,data:86Q9KlaLszaHC5nLoy/pj9cpg5m2jiK4s3sRW2F6sHW0Mh/kkdnyY0D619gj1AllQ38pYMaRZY0SK9JUUkEzlrwr5Pq/jQGuKRucFsdFB67NMWy+iSTvq6rouUzdL1SL95fiooZeLTSpiOea7t+B8vL9UYb4C8TtmszhX5m5Vmk=,iv:O/i8zMD5d5joylxv1PqahFQcFTlqH8wPcWcB4VrN1Ck=,tag:pOwY4EMYWR3DkK6ftm50Ig==,type:str]
    version: 3.13.3
