apiVersion: v1
kind: Secret
metadata:
    name: forge-mongo-admin
    namespace: forge-mongo
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:D0L5Xp+2H8rqOzX5cw8Uag==,iv:hWBGdtqApHj7vLJ9hozPSZD/4Cnxjt6B2Bn6hXKgud4=,tag:826JYGkljKHzWxgPjUAvsw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoblBXdkw3K0s1ZnZJd0Na
            M0xKNVJ3aS9Eb3QwTksyQ212NUMvSmJoTHk0Ck1zV3l4THNiTmROZ21lU0lUR2px
            NStpbTZDSktoYVhaVEZnek4rdUZzWVEKLS0tIDR0ejBFU29MYWJoTTVvWjFOVk1T
            RzNJRUVJWUdqeE5CVE1RN2RUcm1md0UKx0bmOSyoPaoS9GlmNTjExhH3dcxUGthm
            +olwumaMH7+qRQABZeNAQOdI7inaGFRx57c6D4FSGWSGlfhdaTPBlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SFViQjJVY01JMG1USEh0
            MUllK0Nqc0hJM2JJNGtxOTlUSnZ2T2VXOFFvCnJEc2lyaStkZGhlaGU1SG1SbE11
            ZTl2VXZ4UzNBSVFhWGh2em5jTWp1bFUKLS0tIFVsYXY0aHVSZUVjMUFRcjNSbGRX
            TC9kRnlsbkxnSktCNGprUjMwNXBhYjgKA96a30ZjJYNWQ3cYe7SzMWCDUC8KjxOy
            aLlo+Y7C4Gpl7VK1+6TRu+dRS2G3L4KngPbwgT8fhY+ZSump1iPlNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:22:57Z"
    mac: ENC[AES256_GCM,data:kf4YOvQeue5hSPHHEiLE9IcDu/InykCYmfVowK3E8qj5oqVxhQVzSz1clOCQf1H3yyW8LOyqWZROZ4xWge78EJ+M4nzuMGAA75jiN5LmSQtw8fQQHcMA4Fg7iEmSYTRyI6NKWPWZZqLc22fo7ahk+Kg+RnIjp/SwoOt9VaEDL9Y=,iv:InAffsVzb5JC0FetRJfTSpSsFDivbeE45XsKNToz9iM=,tag:6eh/6bYjmkkP7vDhH2QuEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
