apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: forge-mongo
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:8GZPzeOVyZUYpXmUVuVrL4thBKVkqMK976TVwarP4KsIwQFxkZIiOSrA/CIJ1MUvc0ARUUy3KlqNMORtXC0VQ02XnW+6vpHVB9nTCwNuT0pQ3brhmd/Ef9yG+TpC56jtlGKeT154BbmfYlFutw9M98KWMQ6tVY0n8LCQjtrYshSHwA9F5RV/hZoF5bTHFNMJTp05WCJ4Wakuupuw/K/JEKmnLApbNfoRLD8gzsyySDN98oUlI0qVMp6o74aCeU/+HsQxx/Z6Eu/GW3CbqAjRVcHZ6MCEtit7w5S2fY848CH/u96uUxPBag0gKFZeQWzMetBIe8jR4sKBVHryhMRTEuzKKfDO3ekvcxfLuZORhaav3nPAGJ1Cz91a5KSfGzswWaJcHyLdplT+wWiHBXMeTSpvYqtIKk0W9eEWpVgggczbg8tKo6DEGuJDJxrJAjBUYCWPlRcaoE/T7Lbx0L7ML+INB9PgWY0inlxAOI7njqSoSPrJ4T9gxLrOxq4wdN3mlPDYIrNbk11AKoEEQju2U50PX1OoINXFNPxZ3vO4QWhhXs1ZDG19N326h2FXKXQsYLRvUeuZh3+ApScTBX2NINUh9enF9b0J4Tjaoic9S2XfqJWRweczvsrGBmJRAA5LURwlkgGIJazP+To5mNTOWBfzB67p7lTAiy7TB9/B8j1phtVI+PEwm5F3ea+goyQWMO9uFPDWwTJ+KTL/dFdKqGYtvIskQTrNKHrDyNWhPcQ0QRCUhIzmJLWqrM7Ycxd8gM3gveLgIGV0yraxad5zNG+jB2xMLaAk+i+UiDabocy0ya/HZi5V9Dsc6sqfBO0QcP6Lit6DVMF31eam9RtqmlCK/NXyU+/kIYRGgq1z+PQca4lqJtXUGg==,iv:A6RudDxKdoBDsQv1hkOjG1917tAGUXnfLNuYkERf7Ps=,tag:I1KbD+zXh3Rr+va9+nIEcA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UVBrZmVHdXR4SnNRdjZP
            Q0dtVnJyLy9SeGJDUUUwemJIS0oremU1bFJNCmRkQ0FUZGYyamZjTGFaSVBWYlBC
            MVp5cG5BOS9IOUJkd0VRVkZ0Unh0b0EKLS0tIEF0NmJmTlJCa0lab1d5UjhuYmRZ
            Z3ZJamZnTnJvWnZ1QmErcCtoSW40UlUKnAsHAZkHyzM9gULIXni3EEX7DXdb3577
            QQG8kGB3zHoEcveedw5V4n0Hzi/LytweHLPj3vtUevf1o26vPoQjAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZEhoSXJzUmVZb2xnOU9y
            eEU5ZmQ3VEEwM0VaZEpmNVYyLy9RYkxWblVRCmRWVXRHUldiRnBUSERPckplaGNz
            V0lUVGZLU1ZKTjloTHdlRHhwanpsR00KLS0tIGNUR2xZMmYvOU1pSnpqRFhmVWdo
            SysxU3FCRnU4bDZwSm5HTnoyYjF5bzgKP4lR56/c7IXCHhtPPlt59QbBFmh8vugu
            eFAsZ+L8/ELbGmhknXOazZXuL9W9499OLJD1fDQ7ZkW6UybZ5YJm9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:11Z"
    mac: ENC[AES256_GCM,data:LF1NMKCGHyKbOv2KYRfwA4q8lSllPEeKc6qxEQAqB3Nu8m2ugk3NfjEyMfPw/vJ/KZtpEv2FVm0kYNgdHdOgYUo0z9Wng7IVfLsV5aWgwJxMqRxnhO1AxUrCU9sfvHjQEsOf3jz/RKuRned+4KbI4gbngThnXVWL7SHmHeWnrg8=,iv:++M5EzUEV5O0E/wR1+HhXBFGfQKWECwHrO+NyHUyqyw=,tag:FO9FLTf6XVlOjCwX2WhUUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
