apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:JHCpGsDhbFQej5k6+lHSaWLPryOyIEJPMeZuhPi4a2A=,iv:iCgrfmHPg4U7pbuwo6ByZ8PkpZwqmTR7sq5ruOAvHWI=,tag:OH+JHHx3IfQiYUZvWcEk1Q==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoalV4elZjaUdpYy83dzgx
            RFdOUEM1emk3K3crOFdhUTZ4R0trVTQvQUE4CnJFdkdPWTJuTWc0eWdCcllmbTQ0
            T1RvQmNDSVBVWlRNNXlEb2JMc3dBdFkKLS0tIEM4a3QvR2xJRG5ZeWRKaXRTbjBQ
            dk5kc1FUekxPcU90SnlRK1Z1Wk1jUXcKiiysbQi3yU1TejqN/+Emc02OtuZlm+sV
            1gZYQKpJlFM+DPtzRvY0yKN5i4LmRxLjSs+xFKaBViukLdL2CVb4Yw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVUhjSHhCNTFlOGZ3TFB1
            UFlNK1Z2SHJDQ3k5MDFHOWExQXdKbklIWFZJCkczNDU1OGNLRXhuTmdSUXFIVVM0
            MWhRc1NHbDBvcFA0NXVRTGZmdVFxa28KLS0tIEdZZFQzUGhLNWlIV3g4bHhtaTd4
            WFE5ZmN4MzR5YVNNaXVxSStQQ0JEZk0KhWp4xnmNCrE2I12ylOUX0ZItLIGFfflo
            7iW9hbzx7oOiBdcUoVkj+CE1cOF5qULFutr3KrqFCR0GhPQNIpKsCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:22:59Z"
    mac: ENC[AES256_GCM,data:zfaAB4Ricds37F5rES2sVZyndyOZgj5epXXFbWoVu3DRd19cLHlxOEa42XdNNrIV/90Iz8JiK5WBlG/SMzOQRKpRriy/tmmQShA/UZFZcfZRw0BfTZ/wig5QJ+jP9XsLzdxhmq3FssHNmCQYIQY18kMewCJ0PqAHoMxOwSs8EaA=,iv:QimdbEDAm5SG/CdRta96Uj3rScWeuX64/swEJy55Nh0=,tag:QftwYSF0GMhYChS/EBadgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
