apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: redis
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:RMXQmM+mU9AQaPcpwaSPuPTv59go8bw+v/QPlvGpReR5i+CRtJtFJf3//9JJO8pmu3UwvBAZCX7fulNM+V8gMM/kdAGks4zr4TV6q2etHyegnEwdjj5wOtEVtucOE1iI9PA1aygGtb1ro3YixMMKqR2Zsyk3Klwtzb2o+mW+ncD4J4Joyv6g5buh0X1+GM7MCrwaQfTo95llZWwzTC20kjb6gHdwkPq5IiNmoMMlggBx/fdw9wyMhCCrWieB4BM1YCQb4kPFuCQ+ZrA9fXL3unX8CM0nMLfd0PpJeSmlKZJzvCOskdnfAAciYpBMDl9P3B9WzrLoloq1JuIfWBNqtMCokV9+zqmPIs+xC9ymhxJLmroyNRcsdovy+bVZs3cd3lyLBmeT7NzAhei3ZwWT66RDHbHIq4u4ipGmDtrhfGP5BjXToPkDzsGxhJ0E8UymJxvSaQxhqinumW4bjmQWpZF6TK9JESgH1/YWVDqPcKaXgA9k5dzbAU/pTdx/BztEwi5LI/YgmiAveIH1a6JtMvKl+u8KirVacpvGJ9eJxYaeBlcEuJi6K2L9LJD44E/7r/x3HVGLtSaNlRg47r1Day/fYGAkNDJ0aGuuPW+ufkyedwFiGkEJynXODL7fva3Cvz5xghf+nhRTiLARXQllGlFFGh7HV+Tlbed76PkpSAAvGmEzHq83gLixk7aXZAUlW0d0JMehYixeud5XUMuAPQrPylAz9BiAh3Cja0lDWztwOzWa7FCdtgYSYtZdzCpNdr0PffpQBCPo1hsgyXioUenYD+APITsuE8U0cDklCcIHACt3aySiMaX7qxImO6ZSOsuauAxlou3vdVhwhQkKNUg2OFCsD3SAmw4GccYoMyVkz3FW4tAtPg==,iv:PgelyTvP7bV+RhV+VBmJ2lzAFmfaZfTgY/bwfYHR6xU=,tag:I6e5tbc7KJYijdLkv2UMLg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwazRNV2luVm1zMXoxRjNt
            SXBWSEtRaEt3d0VGcUtHaXFoRU1NVk1LbkcwCktHV0czdEdTOEtOUnd2cnZWS1I2
            Zk5jZG9GREptYUM1cXBydzAxdXE1RVkKLS0tIHJ2Z01oMzJkR2hOV0ZGMEgveHRi
            N1Z3aXdYQUppbElldi92TEQ3TW1KMUEK+gLHXOuZyTBv5xcBN0annd/gLD9TmijB
            yMnL3myzh976MCuJKs7iaY+KaBHvdXrTuUdPnl6GF3vjma1/lRwcsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbDJYRUo1OXprUS9seGYw
            OFJicmxVdGV6UGJtR3ZienczWHdlNEhySnlnCmFWa0ZVVGNZZWpmTUthZFV2RmNS
            dTc5SDVPYmVBMFE1cmd3WmdhUCtXZW8KLS0tIHRqWmExZXdCQVdWejZuWmk3Rml0
            L3M4K2V4bGJ0VXF5Y3FvZzdzMk1vV2sKZVRoUf+94RMsRfKPjtwIRJOMddGg/SYX
            x4Ny8Icf2/7mGBhAZ0NpgR8g+0MnUN0qzPoGT+0YpPVPxH7MfAEOag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:12Z"
    mac: ENC[AES256_GCM,data:LJ08NYoEoCFiPvP9LVr4fSrAHoakWtGbPxDsGX1RlcmMb+2CKyy5kAzjnt0ZF6tqHTYdG8svpjXD0LjvMtW41b16hd3sTqqPigTDhlajJmto4kqn2w//8JI7ANTvuy6OtdEt1mSBGQ8ZzCXXSOPIdt2Ah19cTTE0AGFvfIRTSnE=,iv:7A73Kb4Xdw/ghuUZAdbUoNmlLZXAZj+84FbyOlJjSS0=,tag:OAX14agyacyQEocZj1wSZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
