apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:2g5mTGZQ2CDgLwyMW8IrQr4GJrknLt3S81y3Z36T72qAyMZgsyErgcMPW1yGjr4BWcnKjsu0QsZGFxDer6Zl97kiWUwGd5s9WoKz92kBtvPrDvsPXNJznu1GXMmfKM6whFTaWQ==,iv:MfxZ/BjTpEwn2N5Kud+c6N7DCcgbAcHUDR2FO94ZY3Y=,tag:5Vomg0G5dHQkVviQGSdn/Q==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZWJTdnliLzgxOVhhOWY0
            YkV3WFlPYXZqYVY5NFBZbjlDL0Yvakw5VTM4CnpoM1NqZGRiVnRHZUE0d3J3TVZ1
            OVRpc3hyWHRJOUNOaTZZUVNjdFRXeHcKLS0tIDN3S3M5OVlwUnpqcnByZEtmVVRY
            NUhjVUdiZXl1MnFTUFMrNlp2ckhzVm8KyLCjb/JvF95m0pTdEIuuleK2vy/+Kjk1
            hAU1p2NdX3FJhlWv7BM3u3sip7Pd13JPa9gem0U0grp3mhYNmrWmug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNWJvZ080eGJ3T3pXdjcz
            WjBuZWVKV2htTlJkYXVGNk1ZYUVlSE1tZ2xFCk9OMGswdWVMY1ZRRUtuQ3dMUDla
            TW1ad3hSajNZNjYrTzgyTHhkZ0s3Y2sKLS0tIDFRSkFMaXFYMmg4RTIxRGhCeUtV
            ZFg2K01zcjdEVTRqVUx1QjlubllER1UK6xQAe2ZrDMqY3Zh636SvOYqNEJaellOa
            IKUDi+bsOseQL3ZoBrnVjgTvoZI50f/HMKgplMjzQeAhO0Z8w05rdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:16Z"
    mac: ENC[AES256_GCM,data:RYHlYB4PkN5nV4SL1zUD6SXgagIGiAPSCLOi809EiG9Mfzppcu79cVqK29pzImxmPiBNCjlR7aoY6fpOdGkip+f0tBhwAlAssIQbIzq52MjFRjTh16FQKR4tHgCi7wYlko7RYjmJTBAkhyEE6Oc1KPVeFnsc3frubJek8zJ4aP8=,iv:HcpT/ni61899FI0bwKlBW2CDXeO/W5cyugKot+JsCMo=,tag:+4mgK05USNgzKGyzNl1MRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
