apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: velero-secrets-generator
  annotations:
    config.kubernetes.io/function:
      exec:
        path: ksops
files:
  - step-ca-root-ca.enc.yaml
  - cloud-credentials.enc.yaml
