apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: velero
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:kfhk7D3MUZSwCVUwiCtN1gCOy/qm97CONNOsjzLECtJoEbeLOefBrxVUOmNUKBS8UEagguOorKjbygQcWIW/iL3C5tPtb/rMW2z/loyFwTsdtHohobAh1QSuSU0SjT/ZLKR54PoHUDNKe84ZNnrlwpEnMzEGIC4Vp16sZmkNDpB0oyUgUCgeQDoSdk52PO+8kKArz99WPRzSP6e4802w+lIuWf2BZBx9pwp9rcXJMuPcTYWqgW7EYQLGNKVrpl9r363cTCUJCtUy7IJo+kOCPhpPfv8w0s8ZMpulggaHdv+9YMq/KiFjLD+51VaI4hy3QoK7JeUmrCtDvbhCo23w+g78/yzMQjxJogo3qb4Dbd4aR9zMiSkPeXvhLA+pLo7i+7s5tarD6vrsQHQWztJJvHCd+uOylf20P20X96y4mSCV5t0rQgfbazsu6QKTwAUsMmlw+WOVhllJdTnor7w481OiHvx42cHnKvUUYkkVusz8Kix/3yBPiFhOJyJuGsAJ84G1EwtZBPSAghutJxzwpbSIz1vD0RbtsW1h7IhzAahVH+QBsDRKxP97nnhJaN9jV7KDky8zAkOjLJgKasUb74aMEx+PcENpBH5VAyeizG9pFIXwEEr96kfADZMXp8DF/6rl1TOUMHyOqI81/Hik+E4Pg9LNxl+qjsde7/qqv1/GyKmbgUV/CLaKpQ6cX5/hyjIkmrohDCel+8bthapBK7k1jWijLkiviWMA3gcHz75ia3Tda8TLsdTGvvg1J/mbZ+3xcAXRZSd0S80HZhWjzVb6a0K+FMo670FfFJyhjyimsLOf537vodQPElSBeD6zm6SGwF0poxzHw89AsI1VRRK5ax4lSxLvb9KQR6SzV+GV0h02oYpLTg==,iv:cVvMQxfbpllU6X8ykMV/4oJS0anEc60E8g4wQwlB5ec=,tag:xy6c8X1oli8qqh7iEA/hoA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaW5RK2VRQ0pScE8zdWd5
            eTUxV0UzMEJBVDU5R1RLc2FyZGoxZ1FhaWprCkFDL0k5d3FCTXk1cklybWd5U05S
            SDVnSHdER3NOTlpUUmZ4amtEajc3RmcKLS0tIEUyU20zcit4OWpjMWFaVnNSMXVM
            WC9xWGt0RkZPNUhnckdjVldZMkJscFUKyZIVHhNyqAhlAI5OF12eFMw3H1dvbEvC
            C8mgBc2jP/HU2+WWH0MbrizqAhcfCj0QpZQgaLITHlKuPXmMoxEtdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNVRvVkFOdEZ4dHlFd2JW
            RWRSbUtseGVKdG85VzdjVWlkemx0UTVVeENrClNxSWxodzR2eDJGMEFITHFGMVdh
            b3NsNERtcmxmTlZRaUJDdmJNcGNQUkEKLS0tIGpvbWNzS0dMdkhEYmRZdUhoMXRs
            Q2lBSlAzc2svbzJtcHMvbmo0NkgyU1kKHpJj9+ELSQlEbhq1mxwQcNZsT1SF9Rvx
            uGrt2tCtNxmzT1DQzT1/k36c8fCMtCYprzeOL/8B16ozDIrg/UuOFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:08Z"
    mac: ENC[AES256_GCM,data:JOjVPtceosOCISunjTDTt3x/EyHtzrieFlvCFr6Me0OHQYT1q2SClIfevGYmDrKNr1ZbbVcDYnLUSwTimSSJtEOA2Xj7hsn7xEBECYieXJtCbuYrznv9edjfvQ/9tP0AgUbcKEVBWMuyyeGddvHEcIeg/cAiD97IyLaxBKWw6/s=,iv:iYAlqhWii2N/ezUetn0NbQJjE6/NxJ/YqskIAUGR5OQ=,tag:tdtzmDRxkOZwuZsT1nxo+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
