apiVersion: v1
kind: Secret
metadata:
    name: forge-mongo-admin
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:uXezlFSFa8dswAK6YXQpyg==,iv:coLjdGEx2sJQwEwNBqITx9gHj2vPz9Lq31LFZKH/fqs=,tag:HgQjjon3RC9Qz9bzFbqQ0A==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc0ExZXdEVnVVRzIwUTRx
            bHNDNE5oVDZrblVFQUViTk5pQWIyeFJTTDNvCko5QzkxMm5qaXZ6anhGQlhjcWxx
            QklpdEYzODg5aFlrWlQrUVplamlEeGsKLS0tIDdTQ0txWWh6dEl4eDdkSnBaS2ZP
            aVhVQVVqQTVYbnpwOWpqbEJuN1dQTGcKTkiF6LsmJBUTlVKo5coeM16SG4yz/7Z5
            Wq96UdmagYxYhnmJrHdHaGq6C9oWOZgkqlnQmqJ5UNAAD5o+GFusvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRDVJdWREUStiaGpWTWlo
            OExMbGxieEFyY0lQalhDZWJBK2NZK2xacFNnCnhMV1dXdFM2TEJXLzZlcGF5V0lO
            S2hkV2lVWVAySW9wbWdRYkVLV3J2Y2sKLS0tIFo4MytSNCtQRk9RZHRrUjdmeXhT
            Rks3V2lOS21iWlRJalBoRUkrcjhlRVEKoo5AVHDjBfCHmgyBfPU8pVv9VGzYAvki
            9cvrj7H+ytqdp0t58n6oheo4uWs6LOKPCIie21/Kr6LuiUPDgS8XDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:56:35Z"
    mac: ENC[AES256_GCM,data:3yTNXCaMfao/4lX+31zRE8T/3oik/C+6OLyD99mYzvJiePYvZ8Jwr4LuzfNjn40fiqQr6EzmD7Rob/4ulX5/s+URlzrDw2MAubTTVTCQeqDbtrttsXdu33LyCd/8ARrJRUj1ycPgD6JivC0uiWarH7LjKS9B8r3Nmt2/573DGKU=,iv:VLJgVx0KVeplZn0esh3qMJV4Cilg/loyj8NVxg373bY=,tag:shxrjk+eBrEpGha0bRehhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
