apiVersion: v1
kind: Secret
metadata:
    name: forge-mongo-admin
    namespace: forge-mongo
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:7cwgLp38QLSvZ2wR9mihmQ==,iv:ibR4cRTs42c+JU6nvn09fnnoGRmmJ5+0+Z1AOv0SyPc=,tag:B9DhDeoXZ27gWGcljom7qQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWWVramROU3UvaXR5THFZ
            TjRHT2VYMlgyRDR4K3E4a1ZyUUp5ZTEraEdNCmtHRElWNlZiemRZRWtpTlhxTzJT
            M2xQcTBIQVEzNnpXR29DZlVDUGlXQXcKLS0tIFRTbEJ2YWZXcDNFZnFLZUQySXZG
            WjFKUlEzUWZoRldvdFFld1JnN3JacFEK3+KGO6QxZ/I1dbfKEyY/nNDN6EKzFTLu
            d2+M9RpaAvbvlzAIYvLBZej5KlQDaB085jY5Id9spboBjGHNUAnq1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQXFDbTRZMXBvZ3FnTnkz
            RXRFZlR2NzJiaUlmSURJTElPYmFHRS80TERRClBFS0I2ZE5MMnpaUjE2bkhQZGRu
            TTEvN0F6REkvbEc3SG9FbEthbEdiMTQKLS0tIFp5N0RxbmVFaGd5TkRub2RZRnFY
            RjhLemcwRUw0RXhnUC9ibExBdE9DRmcKxD4g4vDVA2AmqRL+FH+6Yo4LCBSXBM+1
            OC6HEoH3SdKnZmDJ/k8AZfljnbNGl+HZL5SkXMdDPYzqXOqs/2y11g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T01:57:02Z"
    mac: ENC[AES256_GCM,data:UjiwFr+5AHY1snpsJdAW8Bpk+NMPCzJIfiKhU0iW71SVk8w+mx0bdDyOC+5VV5ivbQDaCJ5avq3UMINcY39rS/hxQmx9UJSKuXWqjYJHEpUrohG9ePKz3twL+3gV/Ra66dV+soTCBuOKtLoUIqFlSXzWu3eXh8GeFPooLkXcUhA=,iv:17UJJJ5E7x90pSX4UvT7rr/Zr9EvDoLU1J2QzBLz+7M=,tag:Q64u3qTfv4VXc31ff6rwLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
