apiVersion: v1
kind: Secret
metadata:
    name: forge-mongo-admin
    namespace: forge-mongo
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8NZBcZgD4B8y0geoWf9MIw==,iv:xMbGToJQjViflLkNsEsUL9SnSeCS/Ve9u11GgSzTVac=,tag:KBzSbbPLNKorSZvQVR/phw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYWdFMkM3cVRUV1R1NHls
            eVdvYjZvRGJ2VndIOEE0STlhb1RnMkVzWEZBCndVaXMzQzd4NEhRTzNCaHJBUlBw
            MFhQTVdIbW8rOUkyaWFOUHFXR1VBbHcKLS0tIGdvNTdUNnV3U1RVY3ZtdURlbncr
            N29hSEtCWmE1VTNQT1FKOFNkVThEbGMK0Yd1PJMdhHCAhQd+fLrgYSvqgMVtcvsK
            pH77iGDbbJ9gRNazcbvKFP2VdMHblA6YTKMVkBlI9ra929svOkl7Cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSFJLTUc4WFVVOGhLY1FG
            TVJMWGNheDR6M2lCUzI0M1lGaEhuQ08rZTN3CmFHZ21jNTZad241UFlzRklPWEh3
            NTZxcVRpZGNnUmRlYzduTVJRZmxYekUKLS0tIHYxSUtBSFgyeC8xUHUwZGpmM1NU
            NFI1dmROTjJpaGkvVThDeDVaZVI2Vk0Kohx6nnT9nG0PgGPc+PD4NXQG31eYLAjB
            F6CRZRIPxpr9Ek0+oMXVWCFQpNRLe3YN8J4QjCFaFtAeCGgcKN74lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T20:31:51Z"
    mac: ENC[AES256_GCM,data:lmTj2DMv6RUVG7K26k4t3mJG240klzT92dixa4jCvtMPTNUZdVKJr003hFCxoha6XoOPHLwjv+gwU0z24jZfVXS2yrP7rt8iSYIoKlEk3oIjmjZ70E3Kujr1ljyqQHE0GvFoeyI35uMHPH1M2qwQ1wvRmpNxc8W95WJoYYkuZ3Q=,iv:Q5HnOABOjowN2F94vaWRDpY46ZhHwjdfQ5S9FRnwopI=,tag:IJM2THPb9OztqmvUFsSF3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
