apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: forge-mongo-secrets-generator
  annotations:
    config.kubernetes.io/function:
      exec:
        path: ksops
files:
  - step-ca-root-ca.enc.yaml
  - forge-mongo-admin.enc.yaml
