apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: forge-mongo
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:UZ6r+z4rAXMzFPBSzBGhVl1VY4wju9lWsfsBP2H5k8eSin83m0xWMg3kbMUyLLjQKjSn+qR4nDfmNqbtK0aqxb3C4zZspkpSFvXRY47EEbc07njWBDN89CWFrqEjwdZ99FJ9qwHRoMjMi92gmofFLJYoKd+hOvb2hkt/e0LBVsPLlgNVqd/+N73pOV126pmJG107N+QTfNtpoUf//WLXKnC0i635/4z12Mq7h38+nErpfQ9Srfg0uqCPcodYXLjfxmHe2sq4Nssok+3Fzh0ScWS9mBAyCwzSF5I9I9wHRsRXE1Fg3yY6/Tptvh/QKhjngs5Vh92m1dc9yL6yhQMGkAilUSDz1sKeGrPCRRj7Wp7aiNc9jaEq8dF/PtrzQVBKFHSNIvu04iFySErmFQsb3CXE2NKTB0XkYctpIZzHCbVZwSxLWc5HNR8OGhkEq01Cgpe/G5g4bKKkWyXBpNC/1bg8N0GeGj65N3OloOSLU2FACsr7HuvDbwum77sEfgsSNXr8mQyJuHQ/On/s8Rzm0ErnFPPucxFVVLaXGk0oPTcq13A/7OTfnXd/M/0trOKXaBahUNunf8aG+G3QTidP5NqFjIb2acuPxRlUYjUbCUT43zcR1MVYHcqTXsMuV0rn10t6qU1HHWofNbrSTxIocQnx+NPjj77c0qr1xthmcDCP15AKIyeFvfrotl28qYYH6Kss7zOkDfqJI5Kof9jLo3bJsjZkDEnrJSGKeQt9KP0NgB8Rav1zJcx40uZ082dKdDTybOuBNR/hhHr/t396OR96ySlnG4OeBTCRwgoheGoHuxHrmxR36LkkqGSgbOK8bZXSowhqODTG/cc=,iv:Oq0CpIIHSBbDQmE4qG3VKejKLlmgDblIHU1ReMEsAxg=,tag:/U+7aKcTcx7L0yG2tTshLA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWFR6Y1VaUnJOQ1kxUEtX
            QUNsTmhRMzBkZnhmVFZWS2RpMGh1WEc4aWtjCk9Ka0dkWEdFSXRyUDRYTk5la2tY
            RkgxYnJuRnFXTnpZWE5oelUxQnVqQWcKLS0tIHNLbFR5U29Kd0pqSGE2TWMxVVdT
            bXJWMGN0ZjFpd1ZGYVVEejh4eUJNRjQKTBkd8u3hOoRIEQvH8G7FXqNvJMyxfoXt
            TYpDsMUfcCnDZi0PxFwOvSjFi0uqvr5JUEfA/ovbWs0aFWkWAcJk+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aE5jcHd5UG9pbW4rSGN1
            YUVGL1NMeUNjZUpuVGN4QjB2d0llTUlnbFd3Cjc1NTNpOTFjQTZaby9CZzNZRHJH
            dmQxRE1CT2F3MU5XRDhEQnNIWnQ4RmsKLS0tIE0yVExQWk9kZ2pjYmowby9iY1BB
            Y0ZvRGpQOGd4czNJYmlLQXBGdjhRMDAK+Li2gN4nN2EkzXIVLEQyQvEI5Bs6jfNK
            a2qMG4kjh6j+rtdeJzVqX5rVjUohawqu1Ufae+1jpm6sbTd+kM/GgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:18:58Z"
    mac: ENC[AES256_GCM,data:3do0SF4Doi70J+ZghBBOVs8O/8uOY76JXgHPFuIZxt2JK6Ep6JAtXpU2gcagJ/9Afa6ix9krDuRxEAMzPVVkdhdsOeA/8bkjzlKIfFvT/ZLzaxyKv+iclb7hArz0vgqZa5ZuJG3wX5uxCfM90lyI1t4YK8vW60bIZK83tufOsgo=,iv:EEazUCESLeRxlSGogXd2R/3A0AnvsSdKX5XkmsJ/voU=,tag:vY83YzFa1evW239LGNZ+4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
