apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: forge-mongo
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:cyx+jJD7qYHCuaDdiCREeDN0z/PX9Hzl/DrW0xw0ghROPqnKKqEsOTxb5lPmwyRU+YuRyKdHh6Soka6FC7iFvRYoG/e2FlMZRF3himEskpe9NBPD+GXo8Hl14q/BpqruCQM7SQPyh4f8t3jzroXH0QMWDfILjdOITIoOQTQHGjrMOvhPUPEEA4kQyHImV7ihPh7Svn3xGWOVh+ZAZ5KimisifYx0NDK3xmm1bi6pjLl3ckcagVve0IS4Yh7QY8SmR+YfqZWxW9fTF4+/UnHuZBr93I30l924ZKVWwVpyKmF4SDk2+LXhT/zYmPVx81NT0LONmLbwNsX8fKo8gWJEAsJT0/vaTspZ7NnvBcSusP1235MmcUG+WEf/mWppNL1Tz8OUlbsj72LxDKYvyJFxdgH6V6OsFSuqgAHKCWtCnuvwKhpet5R9t+yuFc57ZpSv6NVdf/XRMKeKLiYS68HbHnVP2u2uKC4kVTXz810UCN/ewJXiILli9Ng+hLI/xfLchi6WOvC2AIL0XBvs+LhB0Qc2pZVacfpMaKweQQsp5jRhRm8U5fzJt7WPRuFc4ij/v6NeyUVr6kJDgOZhnmjWn2ZwSVc4QJYp7caQ/x5lW77Pz69D+JNMT8Xvb4wDnwVy1hWXdbsJEY3GGrczz3emDUqOSRMeW61GhGyZIxn85bR0AvZDFdXCAZS0d2JC9mv3PX9jqARNfbCtFPISwwRF0RSFvXRFudMyH0MaDsrxW6DA7pYArDxPdmDcXyQeNJGmUUA9pVcQIUGiu2aOYJn4+UcBO4B3abNiNmnMcVEG12dfu1kFO/hA2pv692JdlwY3/Qe9uj387v8mI80=,iv:FpGr6UwHwe82RFN/I5kcppL/Bk2FLSenecBmVXimR9E=,tag:P4/f7rHpKKL1+FvUP1J12A==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcFFwa25NNTZwajV0dnhz
            Ryt5S3J0UXFWR0dOc1RDcDh1TDhWaGNLVmhFCkxKNGFoaHd4Y3JCcWNjcmVlL0lT
            S2crVk5kbUpCNUJydmtjV2RSY0R1SzgKLS0tIDZpL1pyaWtpT3JsZGpxTkE1b29L
            T29oUjAwNmM4MEN0ZVJEM1hMQ052bDgKquyqLSmIOgi6hSZWT4Uur9nNm56lkH6r
            Tjw5+2dNCmVDchIskmwQxDr7Ua5D6SwsVO4PlB8ff2wVRf44R1cN1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZG8rNE8zd0hCQ2d2dUpr
            LzhGV1BTUFEveDR4c09BOG1sV0dOM1F6UjA4CnJEenBUa2MwbXNqZS8vN3JTa2F5
            aHNEQ1hINTJmb0tZakRXN3lFRnFxTzQKLS0tIGsySXdNNUIxY1pqMzVRSlllVWoz
            bXlOdDJ4WVV2UmVNTmNoOVdYQjhuZ0kKijRxLg3krkZavnOto32H3Wht1/cb/e1a
            GvdrfVOcVBWvXH2e+qIGo7SlcJY1/w+p0mtBUu/8vcRcM2XahfZEiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:55:43Z"
    mac: ENC[AES256_GCM,data:r5vDep4ZN5CZV1Ci73oCTqHLl3TUqyGTqM/ywELuC0MIQMC0Vl0QmqYvQGeNfW5O61vwpgfGy1VftLEgQVuKfDdmoaFPWHdtMnA0gRZNelZ9j0QSn4veXYD1Zs0b9XK16vTdUSqZGfXTHCCfoRhwPfcOaGnAOTrDjYPIflkk97E=,iv:DFz9DAK9oIGk4XvW79ElknZsd/QxEsMHmttkqTJ+i7k=,tag:1lc78e1TB9ocmtbA6xRM9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
