apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: forge-mongo
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:90T5HcRA72f8L1N197Stk1bYGpUDrFjaLNPxdfReztvKFeczqr6GxAqrU9So4f/QYm0lTfDME2LX4rhJ2KvsVt8tfxsOtkUPRqeIoPqhp60vcGN0/YHmKEOI+NQqcMj4/kX26Dj79ZMz/LuJZj1Nm/KaeZ9JYEEfuDaeHhhchfxdCaGzYGxLAt5jy/eqOkepdo/V5ZR+PSxtgOtvlxyscNOzMfVnvW3vKRBSETtvmK4R/7gCQYZBhK81sgiinGTOyPzItCsV3g/C/Mbqed2WuDZ21pmfmsvjRhJpdZLL9yzhHjGI+7zkbcuH5MyMEhVunKo2TtN/N1JkmZPBW2R1AZ8HqLO0OZfBl81iT+CEOnMA63TKjw/MM9Q1c03g7UZlYEVVnb0DCJrIG50dexcrUiEXP26Upm1banuipr5Lab5KHKkLOp2ZmxkD0B+Xifl+M1RH7T/zL3INl8xo97UX2rD0u/uurxMeYyF1Pa7vkDg1pcFyLRl3lI1btE2nFfEosVBgSNaHF00oN331YU9wWSRqht8dXShHYZRnczmJmYBd9mRVjOyzYG6GlHYLcvHkLAsPmJtNDYaEIxfgvMOFxUA04pPHL7K2B9HZjQrf+uSKgTD/q2x5A5l0ohk1tOUeizBThvnsoLtZ+7sg+DWzDGkoka+txNka1tUZlvDDL686fn0AW4zFXh94quAA3Yiyjw7tdX3E9eTqInJaXFoJZ51TNQhSAaObAs8zgcEVsOJdF2HW78R5rCx5l39Y62seCC5JP+euXanXrafg0HqPNw+YxVeilae6ssoqnkLcyasKZGYoXqzbKhfYB71I3qz5SS+HLXRB5VtsLrc=,iv:Vn/8SyjqTYuMi4phz0Tyeheh3wo+H2lAwMfmQ7jgo5I=,tag:xLOnzWzx96zNMKahd3yO8g==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbCtySHVUcWR3S283bVlR
            QzR1TDQ5VEplY2p6ZmJDczZSOE14NENSc3lzCkVlNWlmaWtEUWdFZDRHVXlVZ2FG
            alB5VUpGMWZQaDhlR2pmbCsxYTkwQmMKLS0tIDdUU1VwWG5PNVpZNzM1d2ZwbjZi
            d1RBYXBMb2xJZ1c4ZkVXdThKOTNkcUUK60Yw3LS6elt66Tv7/eFRpgftmrghTYFI
            JUABwTm4Qx19W6d5OymOYEBvAIbFDTwTN3f/jsfU/TIl0Fhf4KcCXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bEU0NEtuYUg4VjgySG9Q
            bSt3ajN1SVNNSEVXQ2ZPQzBVVEhtcHFyN1FvCjNFK29NZytNSDd5U2FRRXFDeWU5
            ZGNSU25lZmdJdCs2clVoUzl6YVRvcnMKLS0tIEo0Z0NNUStjWFdsdElKZ25ZeFU3
            M3pvZFQ5UXYvblFaTlRqRDRyZUpaM0UK4alMvl2vwDUs75Gk5ac7Ty5smubDYBZd
            aezGpsJDo1x7HgQT2ZdXPO3Ngt5PwktktlL8yzLLQaIiokG5ZS3EOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:00:22Z"
    mac: ENC[AES256_GCM,data:BvkmeQ5DmFaWxJOch3cVradUWarLggmcn3YZiliAyoAhd9v04n44rhxTRV/gfDOmdCwTkI2B09W+3Fi4aVj9oR9HMVAvhpFP37kb8VrsiAOI5K6YC3yd5KGz5QM7HnlMUFUar/mI+IGXQLH8RxidM1FnGPemrQ7G98z+iZPbkhE=,iv:LO9rFim0WmxpAeXsksZEmzD+y44GYg9Fp+tA6V1BQNw=,tag:/RzvaFcrlmr5/41beCoO0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
