apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb-system

resources:
  - namespace.yaml

helmCharts:
  - name: mariadb-operator-crds
    repo: https://helm.mariadb.com/mariadb-operator
    version: 26.3.0
    releaseName: mariadb-operator-crds
    namespace: mariadb-system

  - name: mariadb-operator
    repo: https://helm.mariadb.com/mariadb-operator
    version: 26.3.0
    releaseName: mariadb-operator
    namespace: mariadb-system
    valuesInline:
      certController:
        enabled: false
      webhook:
        cert:
          certManager:
            enabled: true
