apiVersion: v1
kind: Secret
metadata:
    name: minio-env-configuration
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:X2axp7lnbDqvth+Y47Pmy/HyJcG14slfEhAlXt8SfCwyIB6FtIwPvEbDPw8OY4/mZS9E2oroJqrOfiq3qRBfjAQEgd+mZJin7qpUzO5THDZjS4yh2FSqKxkf88LiCCpUr/7TQ2/6ELWLe+/QyJbmvReKF0mmJGeHps7+kDKlesyL/ZerIlzxuNGq9bmnRKTGxFTEctupvH48gS80lJqssOufcE8dep+YqEznW4Ek/1b4H5Q71OluuVuR3I+yHc3DhrWQ3LpZM3ZYkwCq/797TAjfEFclxzzeoyZZwJd4J0sIhMA3UxHb28d4ITRmtdmb6HqtyPD8M1BikIWTmvyx3Zz0ncO0US2LZCzAe6PIfyCIVfnRHL/k1I9TQpu+lYaOKGeXiapWtYREjLKLV5kJUalvfkay4wolVSRk0tVB91asWaTSn51KsTUO+9SBN2LvoSQ6i7zZGWjJlKstcHDCPpu3FLnFSyQbEpSCPt5aBm7XN9zmXO5wmOvyIg07agUHCNy1lDiCnrraAfE31HsdNTrZSkD66nTu7thdli8kVUhJMysCg0R40B4qF7QYD2ez5y9/xJn122VZOWqPyHYFMaEHybkms5QPUoF5QWj1brFKvDrFOoU4LK0oiyvfn9vJ4CCWYOnF+yT5bnVjq1jqXoIpx3t3rDy0VlyKvP7b/COvxmNSdEAzY56yXXVpXc71b/ED0L+Mr7CdxN4wNzmCgauaB9xa10yaBeiHEzKDn7sfSv9MAmn/6Bb26dyBlxWg/VP2Ik5QPvGjuz47V3wQ/tBgo7GVUcSShKy+9+V3htZBjVUZB2+gasqsZt4IIJtuQwN2gh4bxFwNZ7M5cQvADa3TZoZtZqr4PY0kPw7HaXvg6EBFKOWJku97yzpym4qP,iv:rPNd/q5IDKzB+6QqrNcoKxgRb7lT8Cr4FRgNErCTqVE=,tag:tsBJFBrZpeY7SiBP8HxprQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySTQ4azZWMEsvWURuRXkx
            SGJkRzI1dDZmam1hRzdzNG5SV0haSm5WK2tNCkx1OThnaDhrYzJ5ZDhJY0VNMlNp
            U3NtK21XM3RmTVNObUpHQ2llSFp2SE0KLS0tIHo2b2JrYng4Nk1xbmZZVzdRaUJp
            SHl2dzV1aG1rbk9aYlFIZmN1VzBpWXMKqcc3QlPXdEAtF9L8eDJaIPuQ2TJuHorr
            CReOVgsmzvDZxfFRskXrFtNjuaVDqmKTzxZcz9F7BTcpC9MJ8e10Yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y25EZldud05GdUFSdFMr
            bkRCbUl3d25wcnN3emZSaFZUS0dxZVppbkNzCnBWaE5zUnRLZlA0YUxLUjBoZU5L
            eTFIMzRGU0p2KytYUzVLeDEzZ3lGOGcKLS0tIEYvTERFclNrL3NWcnE0aThOdXd2
            cStjdm43ajM3N3ZMSUIzalEzczZQeDAK+k6n2PJmys6vlM3RX8H5G++aVTv2k158
            EIQoS/yJdvULv8Dn947b/RHw7xBzwl6ZPscsTtEzfPpENikCSt5znQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:14Z"
    mac: ENC[AES256_GCM,data:j/2vBJRl8Ja+C6OOfXLGsg+LZMjobeqhhieaXaDM0EHpDuzVx+HDvtIdSnOBAgXnM8FWUXStKZF2srcEA/QRT+Wi2TXmTSJ7H0WG7rNMo7t9FjAyZ57IyBG0izhzCNLYkieGVKt55yvy5oCjTOJ33jaXEOrD0WBPg9aDZB8oppY=,iv:Dudly5yGqPiM2I3IviHKz4Ypj4GT3Cz4T6UQqbQFnjs=,tag:08GkK8x8LA8t24/5G/f6fA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
