apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: minio
type: Opaque
stringData:
    public.crt: ENC[AES256_GCM,data:dpsPhdnbn+xej83fWzAbsVG3nWebLsDps/Wmc6DP0POYXtF1qqUpJ3OJp1nKzoZ2Nz2QKb5Q9/tBonK74zKiR1sR6KG+9Yn5e5xJBpIVGKaQ97mxZvfp23MNoM39na4XVfAZ6qU7OGf658mKnXuO6bBR/Ek+i50aPvoR9K9rn0VbmCUrByElRRiiDw4Cn5tq/BvQjRr7szQIzX+0EmyB+yLWV2/MHFHNSTkPEJB1dm+uPAJRZkKpTKPGF5pdJDyw1wcVoYeEZ2fCKtZxMPdcDsPHPtgS4FEhZcIuvu7E/1AwDKlSQV+dxFQKq629Lok91BZlxtL/TEkKzXSWOcQAVSLTXiLTITeWlBQy5ZOrEbBQGC+HMtzJS8E4LPEi8ZUEabG/56jrqD/mqN7fXuY/6B563o7YjV8SUorDGji2/TUbN/hJCQtMI0kUh9B8SI3afDFmI+MwgLtKoVIbuJCY7dUpflxKboyhcxEFl5//pC9t31ZwnSCHAi04Xkh3fM2xDS1+F6l0iZI+VVSMtJ/wBsv7pW7flSjS9+yFlIbPLbe3+m2BRT07tulYQNSwfs8c4ohcqXtqsfx5vRQTaMN0L42ajmlvYwlU97z5toBoj4q1XBKspj0l30HFlMwXwGbOCV3SVKU78AtATTYNbFrsACQD+u774T0WcUJ9Sja7VqRjaTO8fQkcmCWDJ+sUfLHQ7lzOxNEzlMucb2oB5WM5WHbQluXd0q/vBuknbDgQ9rAR/tk8fBDsQ2PXXsvkg4l3Z0Doyomr7VuXlZmZ7M8mI8yDYx0kjpYUYtXxxVNP+YJo7DVwxZmnGDq1OOucJy69t/3B+qc9aIpYkYGSwto8JpV3D+s34x+ptgVsd5RqSCswwB5kP4Psgg==,iv:0YENr8x8LLkYPfsgITCT6g5YEhaiUDGae4BZWomTh14=,tag:O4EX2sZQ+RCKJ4gbriEpUA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRWdDYytEWExQMURXREth
            ck8xNFZ1VndKNW9PdDVhYUY2c0dXYWZZSnh3CnlKUi9UNllHd29DKzdGcHlMMzdx
            RUlVSHl0UWFBK1QrTkR2blgvZkRLc0EKLS0tIHVRT0xlTS9iNWt6VUl4NWs3YmNx
            Vy9WS0haY3c0V3plWmpjYnFTZWdpd28KxkWSKhJzNw9BCf4GSLKciIiUfsrHaWch
            sdD+xSX3oFP8eum7IXb309UPfcK4e3KXWM+uU4JxjYjn2eP/AVEKmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT3NaSUlpUVVRWEVRWWk5
            azJ6Z0dlZFZuM1FnMlYyRlovTGxHcTMrcGxnCk1NaGs1WE05eVJ4anJ4QTFTdnFN
            WVlWS2RBWm9WN3lscHZzcDNySGNmSm8KLS0tIEdSQy82WThHN25jUHFYRUZRemVw
            Qk92aW9XQW9EeFRXdTN3cm5yU1BRSWMKbBO4B8kWhyfw5mLPbLnXs/tcpu5Wf/h6
            aPrKPFHQLA/JUz430LS40m9wb0WiQ/9OUAqwClrFCDc5dsAF6ZbPOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:06Z"
    mac: ENC[AES256_GCM,data:cqEATEBSitRgWJIJE6exqabwRDNjM3tkUhnjLTUR+/ZGKinwNLc6jza4lEMbi0vTPvWHyGWKwqPTM5jbK96HR5FdjJ3WhxpBo2VkMQMzJwr9W7147CMu7HqLWCxDPRQNgx0CRzJ6qmMQeFwAL4eL5W6DxnkokgTGBFq8CxD/X90=,iv:qNR78bf5VCqm+PsaA6VUw/DHGhY07HaB47qGnpjuFDg=,tag:9En8hbRNO7qW3JqajqfD5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
