provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: apiToken

sources:
  - service
  - ingress

domainFilters:
  - aethericforge.ca

registry: txt
txtOwnerId: external
policy: sync

serviceAccount:
  create: true
  name: external-dns-external
