apiVersion: v1
kind: Secret
metadata:
    name: forge-cnpg-superuser
    namespace: forge-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:52bIHxfwyD0=,iv:kyJUyqz6kX6rWXcAGILp6IUM++y25KhvLEXIcZzMmFk=,tag:nR+jsjPhs78Kbqm/YzaeVw==,type:str]
    password: ENC[AES256_GCM,data:6kdyF/9lw4qnowNg4hFsJo2ncy8w/NI7ILr/hUE2TqQ=,iv:OqdAIL6q0bIM7DnCYiQtgsaFAwIvwaBEpEw9Yz45VA4=,tag:mVJvzrmgBjpPcZ4vmHT8QQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR0lDZHJaT2dOWWlmdng2
            Yi9wQXJUVExaREFNdkxrV0J2aDhnOC91LzFvCjlNV3pmVFlFSVZHZmkyL0QvVWd2
            SlJ3NXArMytNSGNhY0ZmWjVjdGV3ZGcKLS0tIEM3KzB2cW9Gb3pwcitYMW1tQ094
            MFFVVVh6Qnl1WWpXOVNIRTZ0cG1wdkkKETqRS9mZOPdNXHZsB4JjWYHn2nzvHOov
            ymIe/BtxJeHfGVfedP9o4oGM3JyEkw9RffyvZrtLSXzMMWPJT+r0nA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGenZjMXJoTHZFRlRyOWpG
            S2h3cmF1QzdYdW00NXR2VTRnQmxpVVpXVkNZCnpDUGJFZDZlcGNVcUFQbndGNm0z
            TGpZYXJPaG01N29qeVJRRVlZMDJNTGcKLS0tIFBiVm9ONUpHbnIwZXd1ejgrVDhK
            QjRZWnV2cE40eFlCRHEySHhqdjJ3ZEUKNsZKLr892HQGnZ2JcIn0zOqL+XZc47c4
            k3mckkNQx+CoI+YolZb5iqBxxxI5KC/SKePZeK0HcmInEe3hS0QSAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:22:50Z"
    mac: ENC[AES256_GCM,data:9fhFiUZRSsxYZn27e9ANjzU0RRtXR6aGhh5QMoq9g595DVoPUnVEuihB0RjcGhGfR2swxDLr7NmZ/DI1kY6W9lrLhrLs6Gyzq/v6e904dklyMUzqAOL9VNxzLaEVTBgG5MT76UPwPv6OKdZPfANDwcW9Xh1tALsTXOofcANGL10=,iv:brHiAHJGYIqpn5zqz5PRWaHYaOBs6mMTicVfwb1w3Co=,tag:hJsnLEKHlae5ILDk0rP6yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
