apiVersion: v1
kind: Secret
metadata:
    name: forge-db-backup-s3
    namespace: forge-db
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:/SjRZeAy53wMmGzJpVR0ew==,iv:YnSYlNIuH+myz3+eAlimJWGr0aKh4w/LQUKwZIMnjnQ=,tag:Ypr5I06XYz+qArgsqAhypQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:BjS2GnavGqPGeGtmR9Mp/5Wx/FLvlsiv+7Yi2kyJfSE=,iv:kUi8M2yF6Y1ymlu+aGKiZRgcBU1JN/qE/5VOMmeqe+s=,tag:eFalOgv5tZj2M+Q+NeKskQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZWkzTkJCM3N4MDdnS3Na
            WGs4Ry9uUDZLTzBCRkFWNWx5d0JPNFNocERNCmgxeWo1Y2RDY09hT0VoWEpXYUUy
            VzZNOXpZZ0RTbG5tS3c3VmVBMUZUL00KLS0tIDJtcGNzUGx4SVdRQlFzWTcyQ1Yy
            eEFidStWSVNMeVNlUk5NWUxZUTNOd0UKJ51kySP1eDOq1+ilRt79oPKu4nrqvDeZ
            +7lPxRZZgYEXyN1uZCN0/F4cq4VZyFRPMutOyxQeBAlMvvkYSlFCig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONnVSREV6RHptZXUvUFhs
            RlZDWDU2M1BlWnZMQ0w3amNOcG4wSkFhS1hJCjRabm5KejNBcmlDWkk5WFpsMk1t
            bDJRN25FdHdPY2NuWVAwMDRGeFZEUTgKLS0tIEtrMVNDcHFXcXpQc3E3dFN4ZEFU
            WWdNSGFPWE9Gc2xnRlRsdURzQzdTbU0K4ojxVxbY15cYr8OmcRcOvO+2A8rCgYXQ
            2sMpdQb030qmk0JmrAMXVjfi75xK7aYLyc2UmrwU1KCnYafMXMn3wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:22:48Z"
    mac: ENC[AES256_GCM,data:IfM9wrCGn74zAwxCTZIo4wj4OxW/4ub8SqnokoxIErPVCEdon8v9U6fDFQag7BkwPkq+rMkT5xDriWc7rqYUHki9ioU9l9tTtb3zBKxjmGUpS5cDVajDKwT1kcLPz/7SzJPyTkycRURBljD2+PZ2KM8eoNeXBoi37ahq9sdBOv0=,iv:G1I/tJbN1mjqmDFW6PllqKYtrqr9ExEE49RbKS/Mx0k=,tag:W3uS1efdCSq7aLFpJ1ySCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
