apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: forge-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6lVnc3lKuuE=,iv:bkPGyvcy0+uYToI+UTJ44IQVCh6l1RH1LCW8+7Rv8dk=,tag:1/yZyjr8zoswghmGBAwPRg==,type:str]
    password: ENC[AES256_GCM,data:XnkE8hdINjApADGjadtfkbgijHIj/p07VC4uSaFY+0I=,iv:1UVuVDU7ZhckcV9FAOPZOohM8dp3zAg9yTWGgobMksQ=,tag:FXLLJuj6ubu7d3OV1J/QSA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSDU4c2d6bm9lZ25JNTJW
            N3JBSXBxOFArNGFWMERIYjEweEY4dG1pUjBvCk9zVVlWeExiMFFoWU9yakNtZVUy
            Wi8xVGo1SGpGTjB3L2tFaldXbFJITkEKLS0tIGVxU3JlQUJKalp0dS8wV0FyYUsv
            UzRiWTFKZ3YxbnZ1NjQycGVCaXQ2N00KFlYDotmanwRlr1WlhE0ONkwmIo3zvPYt
            v3p6caMzH3BzigXKUamozfuJ5PkjC7VeNCXiQf2SE/nxy2JqRV7YCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZEpmMHcyUGkybm9UWCtP
            b0ZxeWlKbFJaZkV4dDY0UnRkM2FkL0h4M2xnClBhdy9iKzdmQXRrVmVBNjBJYjAr
            czBwK09pK21xcUJ2YXNvNTZ4c2RaMzAKLS0tIDRiZG0zUFF5Qi9WWlZ5Wmh1aU81
            WjUwSHNCNEk3aUF0akRWWlhBYW8yL00KTJChI49F5Tn9fAQ8dmTMI5MvL1gAkHyd
            s+bPl5csI0tNgDdNE74FYSzCMRg0r/MPGvO9estGq9ZzfPEH8+qBUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:22:51Z"
    mac: ENC[AES256_GCM,data:56Px0fb43DGB2BGT4e9y0Y8JKzY9pLhPJAY8E0O3MBAJUeB7a5wHSeERU8X1TYG33TrWqnzdhEch1yMQ+5Pt0ymvG6o1R6GunqVqb5xCB/5B1dbIxnmGuKCWbr0/fSwibJ7Lz07t9w4GG96LVfhweQnWcCvKl4C2kvYqqmDGkIM=,iv:/AOqz60KvN38zjgLlYtr1j8d1g8clBtYpmTOBLbnnUc=,tag:iQEfqaFp5ebhmfl9vVuwTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
