apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: forge-db
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:3JCWvHPs/osFj3I0nDYdDmjQbYSugKuwWubLuwrDZD51v5ERC/0YC00y9iPhgswQvklx71LDqppU0gZOGyeLyalEnqpZ2fNqE60UIqTP/Xux5V7fH61QeiyXYKh3izirQPaodDJw5kyY79+G5xfFkcdW79IPBUqsK/mdPgg9fPu4brEVWZj9+UpGYgWt5ocB3Nhv0NI1HTb2zDqp73/T+dl45YfwDHtlxWxz0a9ffBUde7n3KMhcOwH7DaqyPNKgfZRPyH4zcz/x9fYIm8EJ9UioKzp7TJMBQkagb0xxTa76FjU/s2V/GSHKJk4KdZn9DAmzYjNF3U2xHJr055vrvHxyro7ElmKp4Uz+o9m7X8897R7EPj+9QtqV4IIZssAJx6SYdJTtTXL1n9vbcLxfqWiTIQmcDWVEoHe8EdEdq/q6rgkVVCMXEDoNeRPGMoytLL9p9U6B0U3LS7qhbXa23inttVzwSdws1uqSEqtxDobem3KLl7NIN5KIcqF4B0PXaBH3bB7bCJj0R8PBXVAvPIsOw0OT85M7Xeod03Bh4+pvse8Bp4Gvzb2hp49I3GnnmTatJPFqkCJWd93Ue8tl7F9KRZYuASeN6/Ngu4eNkGkNRrA1rkxVWdKPvXqM5RBai3iOgbjtXKRv52i2tL1FUVO7IhbRLqoIT1ZjMhlyUQGOOPc4NqB36X2YeNCw50OAncXu4WNiRUjsMVaN36PMGhRznEayKpgygFrvxLi3esJnk4U4/LsrJA4swY0tEnNOJFgXJS5wcqIuey/Kr0SZqQ3brgVlIrGaWGjl5kE3MInUaTC+1T8BVhizYp8k0oBEjUDZhw8Ckr8enFZjfHwqNeCIEbuuFUupB2oOi9ikFzqERfPq+EBZpA==,iv:HMu/Rskkywk3lvOkQ6+SeLLf55KdwU63RmZ/OoTLNZ8=,tag:1CciN3YDsBfmQ4/3eTi63Q==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWnFEU2pidkxKbjJGVUl4
            bHJjcWRCbjl3b0ZMWUNXQStwS2FHak9LZTFNClhzZ0s3bWtkOGZDa0NFb29zMFhY
            UUVJbmFLL2thOXlRTXMvTW5yTE0zbGcKLS0tIGNuaUU2UVJ5eVA5MDMwamIxN2xF
            OGV0MzByWVl1Zm1yUmQ4TE1pV2ZWdnMK+ja11RmRQqYk10ftdR1sw3ONpctbG2ID
            ZiV8HjAkd+1+dmXEcuThaFumCWuY2s0Zu2E7yQenwKwb33pEOSXNOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeGtBQ1YyTDNPSmFjSG42
            QmJZNFpYU0cxM0dHaVM4cVRIczRZeEF4RWlJCndJUFhrVGh5UjgxMzEwRW0wNkxW
            R2xjbG9wVG1EUytrSHBXRjlMcjNkZ3cKLS0tIGVoWDJwTVprTURpcVNZdEJlekds
            ajd6eGZ2VHBCclNTRUFyQXIreThQaDQK9d8VIJpp1L0+CIUAFYRqoLibS8zInWyo
            Bn5ef7TW5/it6+yAsY0/mSYzqz+hheh7MBTlLCtxW8yMh/IuSIqUNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:03Z"
    mac: ENC[AES256_GCM,data:Ik1Y26xKPoq1E3u4Q9Pz2RbATdYqM+HG9Y04VDfYQ6BDy/DFlIVdu2mwhEO6m2JJThXrm8wxU5VugC812yJTxYZXFA9Ui1qIAbjkHTP5pUl9chhiXqqDTyYQ3kxVuPDb7OvJSafQnUclBG3SsHSCUhl3PC2E737aVsN5IVMBHdY=,iv:iyc2Q1sbHQRtMHmflJ3/phdGLBFZIT3GbaP4OgXOwJU=,tag:L6g4X6/mkCOQFyB848OxVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
