apiVersion: v1
kind: Secret
metadata:
    name: ps-cluster1-secrets
    namespace: percona-mysql
type: Opaque
stringData:
    root: ENC[AES256_GCM,data:lN3KQOqCWAQ6vDu1/QyeXllb3JwhAOvulmnoZGubR/Q=,iv:k/Pl/H9aNfXcM7J+HDR/Fs+Q4pUEj3ADiypQ2IALgmg=,tag:zK0iPhCTDZPYAow7Mz7TIw==,type:str]
    orchestrator: ENC[AES256_GCM,data:tr+j9jTEZwlu349XejaXgA==,iv:pjEwezJskOskP+r8/FYj7epI/1Va5BxHGeIQo7mcvgI=,tag:s66/KnUzrh9SuGUVGPy2hQ==,type:str]
    xtrabackup: ENC[AES256_GCM,data:IamWzPa3UKThx6gDAVmfbQ==,iv:mDzZ6UL2XCMIdlb8TeC4LTkiVh4Qhay1ej/jogAuGJU=,tag:XOTcT74VWY2dtgW5MsNEXg==,type:str]
    clustercheck: ENC[AES256_GCM,data:2/sfyCi2uTkDz1eHxYl6Ew==,iv:AvByWVikzT4waaUlzJ5GO2o/I0ZWL8jn2FWOUbVraOk=,tag:8D5bXudtjp9T31rsEW2+RA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT3VYMms1Nk9LUTF0cUs3
            V2N1c1RCWms2RVF5SmFsY3RYY21ZNjEwTkJnCjgrSkYrN1NUK0F0cGRocjNhQmhL
            d3lvRnNyS0N5UEpSeEx4Mkg2Q0FlQUkKLS0tIDhoSTY5b3I5VXliRXdmcU5Wa0JQ
            Q2Y5K3lmdk9XdmIwcDVlWFlDbFllcVEKEdjNhdiKdOhrHtFmS6T9vxw/zAFpFnZC
            X++TCmFnP54e3CxCJO3RQ6ufPSm5BY3s+Hea8/hbS5DnorLPhGxpvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdEJRUGxISDk4SEQxVlZQ
            RzdUVGJWK3dJNFlPVFdJQmxxYWFCb1U1dEhZCkpnOFp5YVk0Mms2TzI3S3pkNGNv
            dXc0KzRiTmdvUGdMNjZ5dzdqSmY1TDAKLS0tIHB5YU9GNWJFalE3SjdEVDlwK1VR
            akV0dG84NnVuVXdPK0tQbDN5V24rOFkKQBGnVayYvSUhyyjeS6VRrKsLQg1rNTCh
            pXciKmU0PgO+3tlt7LrzUn7y+hWETtbGS6ZatWYZs5A2fKC2FPn/NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T20:37:50Z"
    mac: ENC[AES256_GCM,data:qdpDDuLfXAvqt4L1eSwH6qVJcM/PxOFqOOHyj8upQnjaHg1XVn3rUJClkbNclKJPxlu270z07Q/OEkRUeKiIFZcylNs6g44D+JSzwAWjQCBNnPoh9Q1D4jvhj9MOK69+0xJTtcnOeLf+0tyzPHluRrakgj4LL0PFNVHX/zqPa9g=,iv:0V46c3inOwAZ7KyMLq1BYNpnIefggdkAon1baxqMrME=,tag:BI9Tfuz9WOE8WKz7mUE8sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
