apiVersion: v1
kind: Secret
metadata:
    name: ps-cluster1-secrets
    namespace: percona-mysql
type: Opaque
stringData:
    root: ENC[AES256_GCM,data:4FZdPX6kOgrNdXe1/xmSfJPoPqRlMwno1Z/j4xpog2g=,iv:DskemcnnHJwZeWIueA2ZSVAfp8PoZZYWfcDu6rRA128=,tag:qtDbp8mYHwZjawd3gtU4JA==,type:str]
    orchestrator: ENC[AES256_GCM,data:+6mEz4XSr2T+MjBdK5IBZQ==,iv:6mPz1Mm/H6hdJ5TaMOg5lO06f3Zx8BV4PQaM4pEdtFo=,tag:zVmhmlssBHhEUAtHu+FTgQ==,type:str]
    xtrabackup: ENC[AES256_GCM,data:SIpu2jYvoUyKEGi9kNJ7lw==,iv:nbgYbVnrtlwArQqpuJxa11+Yb1F9iP5oj0Pbchd5wzE=,tag:ZuhLeNNQNlN/UeOTTPEFPw==,type:str]
    clustercheck: ENC[AES256_GCM,data:NymOLgdguIAYdpwdedThfA==,iv:xT3mG2V+0LX/U8DaDNd++pLGTR91HLzMtOhzW+3xIaM=,tag:OqQYhVqGtTIfS2Pzt0iAYw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM2UwSWJiekRPTUlxcSt1
            VDQ0SjN3bGZJeWNnenUvbnJXTDc0RmRvQ2c0ClV1MUgwR3BXdGtZak5FVCtDUlk3
            OTVxUHdmVjRrMXY1UGRieTRVSk1kOUUKLS0tIGVSYjdxZXdjRzlZOHdyaXV3MDhO
            enQ1U1EyRU0rTXpsRTRsRkcyVlBmZzgKhutddVUNeZ5jHkas5Gl6a6GuT7bV8NTy
            y5mbqnXGN0JHuPhQp4Ak1gcWVPc0IQgRgRnDboMzb5o5QwBn1G7jQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z2p3b3ZvZGlRcW5XWDNN
            Wnk2QmpvUFBaVWhLV2t1S0I5bkxRcUNGMlRNClFoVGVzcDNvaU5MbWpZVDlZRGNa
            ckhCVWUvcytQT2FRcXJpNGVoNnhyQmsKLS0tIFdMR3dhemlKVXhTYWZxbFNyMGE5
            RkJqamRFWllRTzdTUUF2ZzZDR3I2OTQKQOstyC0qhSm7HYrP8fyeeeIahG/unWdn
            1WpGIOKsTscAfEZqSydgQnFilqiihPW6gxcYq3cdTYvaMP8UTZgs0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T20:51:43Z"
    mac: ENC[AES256_GCM,data:wEWNepu6ixYBNw5WH88O9W/DycSmct8w9TYEwF7WG0KvhDXu4da9qvuA+kS53rC8DeREo1/e7sQOdp/GOL+JtM2R6BWQx5YLT7TSLAihqksxiz7bje2yQGghTnxETBZ70yDOt0yX2+w9luiBsfTMxy0SBpLf5FDMy7Ro8u/mOU8=,iv:opJV/GLvtKeokRJJs82QrqvOjSJD3b2Ux6ZdVaGdt84=,tag:t9iyJrsC89sHEfeUlUznrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
