apiVersion: v1
kind: Secret
metadata:
    name: ps-cluster1-secrets
    namespace: percona-mysql
type: Opaque
stringData:
    root: ENC[AES256_GCM,data:ckfeCIDQ/TqGLXARau1GiysYHw1NCU+qOXVafU0cJM4=,iv:diXBDVbEgJfYPJ86jKPjese86R0V8N1RsoS7yiguK2Y=,tag:QY/0uWiMs5SUQnQrPF0oPg==,type:str]
    orchestrator: ENC[AES256_GCM,data:t53yUm7BpVNqtX72QFmwCg==,iv:23uz2urvBx8Wy+fyEZ4CndTjn86wysCNNM/LDeYlBOM=,tag:YtSCzPVo+NI8FsGPqVlRsA==,type:str]
    xtrabackup: ENC[AES256_GCM,data:91TpEKkavco6IvYNHgdr9w==,iv:Irx4/X2z0W8izNi/ROnqO2XQR4iSJVFTVropdTyMa4Q=,tag:KFIc0hTVMqgM8BPwriqXYA==,type:str]
    clustercheck: ENC[AES256_GCM,data:83pJr171EKXyW+ju4hexnQ==,iv:4kIXEOrCEyg200AvXgt2/h268FFNhh5ZeuNmhz6qNyk=,tag:/04sJ9l1kwqSf6ReBz37jA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL21tWmxianVYOUFzR2dZ
            S2FQbm5rK0c5cDZRWWphTnk2VDVJbmVnV3djCmprb2lNTWVWaHRWeFBmc2F0TW1M
            RDZLcmN0V3EyTnN0RlJVc1MwcDliMlEKLS0tIEsrWElBbC9iSUhMNkgwRy9QOXJM
            TmhDMjBIVTJ1dGIxS1Y2R1FNQjA5OG8Kkj3Vwn8ir+l4CYwc+7r1AWbxfmg4jkJI
            BOVumpyLM8a7tVoBdNP1odQW18oMIIdqEDWHVMG4VzF4sVpqbz1Kqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SHcvdldNVDQzNjdIWjFo
            QXM1QjlBTmtvbkQ2ZW5zb1FYTE5DTEk4TXlzClVFcE1JNjkwSmRGeTNXV3RXSWg3
            dW12bGRzVzk4dTVmaVFzYmJZb0FaUW8KLS0tIDZZVjVwMWF4blV2cVU3bDJ1QWJW
            K2FhNDhhT3pqNE9XSStEcUpCZ1JmSHcKHfKAXCC8c7nnXjLyU1xQJ0DS0BGOEWN7
            PXN4pAVCOmCMr7EmEp+kADpLy4CJnnH1gmObxtUYnvdB4OO603CQSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T20:25:51Z"
    mac: ENC[AES256_GCM,data:OtJCJhPI6k0ECzXu66jema3q2TgDL734MSKjJWx8oD1xwIntQw5gHgOL3FU1DOtyZCRUCq1kPI5zvXCdf3s+lAu4/LVAk39aqPWf/F4krTyak/lfb2ASF8E/580cYYZD9TR3la8lD9juxlEu1ZOVwyvbycw0wTuoOTeVphlYrLU=,iv:PFyy480M6axMj84R5Yjwat9+Ai78X8cq710JZaqA7xs=,tag:3fz3WHCa25LmK7i64gBPBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
