apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: step-ca
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:L5sdKC1VsyVn4+qzNFkc10y4DXaPB2kjTw0gwMOFCigYsvFHjRQ0RihvVRW8ibXUNns8RRLRZmL0II+MplJkw98k/D+E58xyOdZmrHQ6GBs9A6ARRvbrzr0ogHrLR5QVe1HfboIpZtj5Kt3hZ9jal4eSRKo7kEqu5Ok7E3Y8IyjqDAgJSfq3Vd1gRCimNmDj5+/7/lx1cN21lelnp8Wx0MDWswZHoXvHePL8lWPeRA46dCauOwz7CqoYucc6cRoAne6IFa6Nkf3CEcqdAR6mJT5OQ7agdcd57hVAPF/1uwy/3THfMDAgvoYbHYmWL8/9EQ0bg3KdfcDgr0C8rJQZ6P/vHIKPon8m/JdbxfrtKcb4v17SZipJ3z2i38XKZzy55eijVMUCKhytuvuzuI6jN2y0WQqCiBtUEDKCYZxH1jSrIsj8Q3RenI0URIPyK3+UuWzdhF72WEFyV8sKKQGqE3OmVHfEtArTl+MdEthOeiZdU4TAoXi2GTtu/UD2e4vQQ4hfprfHz96RCGliCVECE6C6O2OroPqNYtmu8y48rLtMSHHfZi8KuEM4Ab6b5zEoQCrY0bzxqAejVrQCJVKo45yhB49y6P8UwTdDBC09jlgMPuEJ3V71ZqeNsuNSTGHw9czo9YZMn/+HHH03EPNITUCW4l3ann40vgeNQvE3b99Wp5nYDQ21x5clAJ/m2uOHOR03Bmr8YKSMFeiaW1056DJtyLSin6NJFNbMzzlrP9rywVL7aTEyZBikbfbXbZhqg/7suVEgibcO/askLsioqh4TKFRfhGZQSZkOTavXCnYOvcPNluC0b7iVsfMGNz9aoIuMnFBF8G1Akg==,iv:DWFYX4U0L2PVdEgwf1w9RZBk8mvWPjsiAttWyNxgQpE=,tag:bh5SK9QoN9p5SOAT+D5pWw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZWp4U2tqNUJUdXFXRDd1
            WEowK1BOYzc2MEZhQUcwZ0ZvYmplamtZWEF3ClFSTkkvaTJFbk9zdzBiRHhsNW0y
            UU13UkhLU3d6TERFTjJGWE4wYk1KTFkKLS0tIHVRRDMvZ05oYTBKb3JsSmwvYzlk
            RURFUnhkZTFHWVlRSkl4YXdBYysrLzgKltCCS5I64xnmEGa0vfLZ1Ri7RY4FRthO
            LXv53b5GTTbnzJwEqPqS3MFXILM5wlbxjfnNJh0y2aR64obFDbjwNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWFVXZm1Rb2FWckFuc1F2
            R0RibDBIcittMDhEY2pGZnZ0MGcwTFR6cEJNClNpQStTMWFvL2NkRSs0d09CcjdB
            U2dxYitlOUlDR2JxOFpiejA2VkRLS1EKLS0tIERVZGdVMHhhWlZuSXRzTGt6dWE2
            R0lGV05WYUF4S0t1cXBhUGUzeXBzOUEKYTUDl0oSflYJviVTXk/KymouTYqMpDMI
            uNp8BVgl6FtJik7OR47SJllp6zQMOGNZus7O+DCAPH2n6iqe5sa/HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T20:46:18Z"
    mac: ENC[AES256_GCM,data:BZL3lFrz9Q7cePtovAgFkQ/+ErybMmTTe4l8jqMQz+pIIDVD48npSda8935JRw5z9PykNTKuz5L2Lf61rkSKkvAnxIxvLuRb1xcg1JR4gtvnnV8KSHVlkxlp6xDuTxfmwUzegUe6uO2/KonNPmaXFoFcNAgmikCIqabUApzSTYk=,iv:b0YM/OgdTz1V5S4y2j8lEzsBX1yxVa/8YryzxFafYUY=,tag:g3Cu8Yp2PtVXupbZClKZuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
