apiVersion: v1
kind: Secret
metadata:
    name: forge-cnpg-s3-creds
    namespace: aetheric-forge
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:nhy5JLX+JBwHt+k7CwAUUg==,iv:hiHvrXzmqbia1sH9fq2kIf5R9JeIkvrkKKPjzr0lVC8=,tag:txOMUnKph4a3wS8AectWLA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:g5X263QOm7e2CONdZBoE8xgpUR6G1WtCA4bNABfdBPY=,iv:jJUuSvlWBAx+gWPPvmftxVATMlt3fENAvulLLFlLEjk=,tag:kQK5R7ERCmYHx9mMOdpeyQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza0xaL3RBc1kxWEVtbC9h
            cXJENmJBcCtMT3hWaGg4UmZlc2FJSitVcWxNCnkyaDdobVZYR0FoSWZnUUdOMmgy
            SW5CYkV5V0Y5V1hMRWJwcmVHT0RmaFkKLS0tIGRzK2N1YUo1ekhZeWVvMkVHN0VU
            RXFzRklVVittRHVFSmNlWlZhbE5oTncK+bFRsd5/mTlE/RCGT8IiJE7qjcnzHFxq
            dMsATXY7RW2b2fCSN/SQZoN8j1JEpkwxuNtnqmWt0TiknBZr3xlpMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbTlDVEZWaFRwTkQzbGZ4
            N29LckZhQ3pHK1g0UllGNzFTZnI4eWNOTUdJClZJamVlbTBOT0Vna0lZZjVIK01N
            RzBhckt3aEJ4bTNGYjhBRDRKQzYxUTQKLS0tIHk2S01aQWd0ckNIS1ZXN1J0eFZx
            NlJjQ1phb1ArS05IQkk5Q0cvWllQZVkKunUjzbVnAJonE9JI527yYtRuMNgOSaau
            ZUFTeucs2POC5Wi0+eP/oMNbA6pRZHrqhKW8KH0xxEPTYARu2FKj9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T02:57:07Z"
    mac: ENC[AES256_GCM,data:vxf3nANAJmoEKDvI6JWQs341M8gkcwg/WpM0nRv2e9RxvCJQzsSNYLKio6qF3mmvOkJmrozhKztIUKRXv7FVLsyGGBdQgS3fdp1J8si2BQh8W6CsaNU7+gzvrGou/da3Xv3Mpk06b7hokjlR2K9K24XKLktYFB1wFvm2pCc6uVM=,iv:1JFM58kAO4U/czrITdoDhxM1gduLOUQCxRJPu0f4Bxo=,tag:URFTBEvMG3AoT+4jVU3WwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
