apiVersion: v1
kind: Secret
metadata:
    name: forge-cluster-superuser
    namespace: aetheric-forge
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:bCyxsTY=,iv:9RwraJN+zWA5kLdEFxRiMUo0qJJ0rKBybPfoipSeqRw=,tag:uzL7HAmlhLWOwiy2CNhQeA==,type:str]
    password: ENC[AES256_GCM,data:yeG24EecQsZpuXUIu8jY0Ifc49BOGI4ONewk/THjfOs=,iv:0DTFtbVEMOlEfjFxV2CA8+A6+IFq/6r71d/WIeIHN0c=,tag:pl/64mk2ABVB1RSNi5GhIg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSzAxMG1lb3ljZUd4VHEz
            OEt2N2dTVmcvcnRzNWx1UThZWkFPS2xpZm1RCjlWOGdVTU0rSzVkUFpBeXBTbHFC
            R2pocmIrWWtTQ29kNCtZRmpONThGbWsKLS0tIERndEk4ZVFXVnQvV2YwbWN6RDRM
            a3ZYMG54Yi9HdWQwampFSjd0T2NYemcKfBb+Nh/IkngIcOAkcEgQVGAv2ca259+e
            ed/j4LjVqKsEsQVWMGuKk7LT/a19MWsKOMS8bt9UkXUnCl1DlokIPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZzFubjBrcnVOK2lleFdV
            RjdZTjdaNXlkNGVrTzBXMnV4enpUV3VNS0ZBCnh4NnZ5NWJEajNxTHdUVHVRU01K
            QUFPNm1kTDBuSzY1dmFDdUtZOFhLUDgKLS0tIDFOWTBiajJ5azBEVDgyRVBLdHI4
            dFRDZWRLUStQaWtma2dYWUZ5SGZxWWsKCECoo1YRkl0o1bZOAa5lgK+MHO8HSTo4
            mJhxtPR2pj8e6lSkxQgYrMNA5fQIL1J9NHgl0ehe/vtEX5w+Su8ZZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T07:32:47Z"
    mac: ENC[AES256_GCM,data:EApM5MRO2UiLI6nUAyCf2bRikQg89QEcgsQJU+VLJN3VAoGbKjn95vEf2g2Pp/TQYk12dm61TGYYkuPZE+yP/01tXnobxlkLu+uiEq+oCoZcMK0sMWpgfwWMNwSPouO4dgglndNci7udxQgHvLthO7rhytSgXcT3q/SRiuni5hw=,iv:J4zDfOKuSSF2S7wYHaqIAV891kAZ3QXL/6jJNQifcsw=,tag:n5M5Fd29mMnwLzqy9wfmUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
