apiVersion: v1
kind: Secret
metadata:
    name: forge-cluster-superuser
    namespace: aetheric-forge
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+vLW5Zw=,iv:dGr8UxtBlgOGmrpXNpvcWEN4C3OW3ohZ46TFg7vyz/M=,tag:QwoYoTJzgUyCN+1EOEpaVA==,type:str]
    password: ENC[AES256_GCM,data:M8nOmfF9s282vuulH5eNkWpADorhSeRRBpvbI/CZEPs=,iv:jT+b92yoqdKzKyDlvyOqxga1XLIdbbz9L0ctRJFFy6M=,tag:/L/wpj8Hy6CO4XC5t/UQdQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaFJBUXZLVElrallMdGFX
            Q3hza3g4MEFCN0lNeVp1QTFUYlNmWEZhT25FCnRXaStnOS9idGFRODB3bXFHV1RK
            enRmS1g0TExyUVlSVWxRd1F4M1pSQlUKLS0tIGQzQk5hbWdzQmU5VldibDdGZjBq
            SDRNMGVvRVZSbXIyVkVvbC96cTIxa28KS2iyIBhklm45d+wYQVUmapIbyuaggAam
            FOboPQa7IhHhM9qsZzMOcWtKtLVPSJI4CxGZIgEmsKchEOf71I1UBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWemR4eGh4MTRMWFVaTW5F
            SWs3QXhkbTRGSFpvMUN0dkt6WkQ2dTlycHpFClIxUE9lWlFSVEJCV2hUckhiNTJH
            Q1czMWNBSlIvWkRDU2JiUm1qeXE2TWcKLS0tIDBLRE5DazdlRXg4MFhXU1AzRU13
            TEpEVWZ4dGVwMnJ3NnlDYnBoMGV1M3MKeR5hUs/84F57v74+WA6umHh3LspsXRNn
            7sPO1SeJDq55NYHBAux9Cb2HBSiaQ9wEBTgkbH2nj5qiTk7eYrtIkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T07:30:02Z"
    mac: ENC[AES256_GCM,data:CN33QIuzWyo2W3/MSHb0QQ4ABzT9cb2rT6dDlyiJDnh+9eiUwq1OU9DFbW9cWIQe8gnWZVTAa3AL5KJrRBfHy4FmjaYoRnOT10D2kby76PY/GgRfQSqriwQtLRmOYddvLS+lIUqsB2155Xkf5WahCeTfACmjUm4H1dGbPgCUqZY=,iv:B7CZTFHLSXvYnTKEMtsh2OXWf7Egw/qtcP7No5cq5D4=,tag:+qfLJ2QVZGwy8q5EkhSU+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
