apiVersion: v1
kind: Secret
metadata:
    name: forge-cnpg-s3-creds
    namespace: aetheric-forge
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/6us4FJZ1vaOBEOnGKbw1A==,iv:M+2S1MlOGAxFHc3BOpVCHCuL3t4YzEnWJQUEd7v1wlE=,tag:1jj6OVAZ3nx/Reb+rZrxiw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:QlXyJWFTcOgdTQyv70mMctGLHlKbMpjrzTYU7XimjSI=,iv:3WDA7ObxSjjfXbyGxKRkc6Ss0uKLV2US/aeqKLVotLc=,tag:D2sbdDYYh3dGoS24uvS3Cg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRTFVcmRaWjRJZjdUaFlq
            dGFIL3JDSGoyb0F4cDh1NW9Cc1lXWHJ5Q0hnCm1UcWhXZFNScmYyaEJ3QzFmYlJH
            ZFNKSjE1elplTndQbFIrSW5BWWJhYlUKLS0tIGJ6QUV1ZXM2dHFTUWZGMXEwSVhQ
            SXdkT04xcUlFWUV1VXMxcWJqa244T3cKxK13vNq+Egv+PAMKQoEs+yYdOkhgtPon
            34iCtGZETtMB1xn+0SQdujrvV3Q0TcXFvMJ8ViizXQPXgNw0Rs/FOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZWtUNS9XcXRPaktRWkF1
            cWVNdWhORVRiSzE3Ryt6V1pqY3I5emJHTGdNCjdpMGRDV3B3ZXZzTGhxSGxFSitH
            Q0tnelRsTzFUZnROV1F1M1pMVFJYWEUKLS0tIHdqMEl1U0E5aHZEWUNRNXQza0V4
            QWkyQmUwa1B2eUszUDlxNHArWFlMSGMKFUmCji9gJ4azfDFxsiR1NYw3VmSLtnlk
            VYot/nfNGdrOzMwWG2L0UIc6PiFfcBqwcAlu/Gq7PZEWc8oJQ+rKxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T02:52:08Z"
    mac: ENC[AES256_GCM,data:Cn7V+9VYkjCbK8Bo+LUwrufFVI8L4jV8XvERjiQX/uWkNjcQz8OOlfX/b2jtc/v8ScWBxlcOp4n6D4h7VVPAYgKylX0VbrE6Oe7qFFCb5S5kWw9K2fa08tsdK/5OIHnccCnD80Iuhp1kFn7x5kR+F3lrHthO56NonnqbWCT8Hp8=,iv:VQcdVTgmfhAq+K3osqoGJRHMxMUgjgy8+1+Y1ex/T4I=,tag:NuoQSMtso1Ggcq1akvFV7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
