apiVersion: v1
kind: Secret
metadata:
    name: forge-cnpg-s3-creds
    namespace: aetheric-forge
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:vx07FuOmho2dsYycQ8K7RA==,iv:rB63/n0fgClj4hFyo9OBGA2zsZge0ngIW4396A6Wi7Y=,tag:N5EOo9vGkalAO/jmLlcMtg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:FadfS68u8nHVw0KHWVnRNP6ZdkxtKBC/TLSLOR5/HWU=,iv:1tooucoJKG+/aSIuTb462MY8LP9+2pRBJ5cjSdTiUCg=,tag:s/qUsIGoKnKHfVFWgT5dZQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacGhTTEpWSkJJRGNvcDQr
            VGUxUFNPcnN4dkV3WS9LV3MzSXc1M2tMNERvCjFpZDFyb1kwU2YzQm5XQlNqVVIv
            b0l5aDd4eUN2TUU1UXJZaE1mVG42YWsKLS0tIE1ERGZFYllXWUp5b2FMWHFSMFFV
            czJ1VmxGM3lDWWs0c20weWZYblhHQkkKUibTU1kIfzl6TtrTgV6EIEqT6qLQqw0D
            Ub8DCVh7Ge8BrgJFzeSkPu2ITtQ+8/6BWfTTBoyRjhIIOZ/6z7soDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTnplMmRRREI4L0NySWVh
            eXEzK1doSGxnTWF4QlhBSmNpR1ozVEJ4MWx3CkwrMXFIR0dXZ3IybExXZ3ZSMUF5
            SEdyUldTaHlFWk1iSHhxMnJVdVVmaVkKLS0tIE9KMzdXMFhDaGZpM3BUdCtWcXAz
            aXBPZlF2M1lYWmdzbDVUOTQzdXVTQ0kKoLPOOufLKz/erxX/kE044AHNCzQJTfEJ
            JgMsCiScTcQP7lGeSOuEAnUh8sUQ1XpgJ70xG7gdu+77XrneP9Ah9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T02:55:30Z"
    mac: ENC[AES256_GCM,data:S5Qtz3KQNqe2LYay129fc5xkGCPIaotDnCXfGd5djyGwgIzCONX+nTUsP/kdMyqAFhT6bWldfBcsAJmKYeoaq38h1JLCBLbbZStGicZeObjr0EbgQ0oWort1v5tga66tvtyIYTpWsrwRzr+HqM1S8zJWpk4IqvJN1JM134QQPJE=,iv:6BtfhmEe2hqAUvAnPKRbhMO7JoCzS407xwhNlNu74/A=,tag:uluVGd18BSSZPD7IKFeaKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
