apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: step-ca
type: Opaque
stringData:
    root_ca.crt: ENC[AES256_GCM,data:32+wPuendylscbM+2L8KyefcXWMPPz6aMvI35PZNetp3ZiJDOl71slFikYu+09X1d8q61mr1B1FERXQ333Y4eXcZWS292lC9dKAR10kVfnxyn3MhZOOEVSjS/gvw3W/kF6etXRkqeifOUEhwDH/NpDxaZiHrIIatvRMPkJGP8VOAo4YJzYR73Ft1kw6MRO8dtMIHYelI1BJsB7kZ53yms2w71cbogi+Pta2q6RzUfwgOeNrgC9S+8YThUYLfZQq/XBb3bCIqeDAdkbggnM/BYEyiTo7naT+xOnQ3q/7Chn0EyQyx+dfHVz7K9Kfwelvrv2BeA6B6lle5lEfJp3OhgvkL65FydJL1Gp+A+Jtik+mPUziP+w5w74t3c0l0BJY+7hsUp/ha7UkFhFOKFdQn//wwQ9Txy8fg0EYEaVTH2gRcTV9kky6wcG+AvzobAT+9pmlDa/3ZltAq/FXsGouhjSB4ZgiijuoWlHN0GdbnRvv8iAfOqEpZxrCCKXL2y6Kvq0P9nXVipGidsxnn8Q6LnIIeEruDcLO3ohQK6altjzjVAGemsM4oNir8WHcJaHjaPbEW2hjHthzkKvJw+CCRvVG2Ooex7DXa9/neCPjqT9Hf7YnSKskbtcUjcjE6oPE5YmG5s4LH9HIZkRfNM8WjnfA/vgzyTA5qPB5BG5SJcF12RlDdZOwPS6tlbwlYaHgfc858zu391Pya3hIHP8wd/9EJKMZTw6E0pZ5G0CDRIzqi+nQ9gYtI1C/Vr7sBVcM1JaT+n7+Aq+E30mXkg4RCZRWU/myO5W9Vig2/f9NkpsQzP9/XNINOK/zGY8Z9YaRcQLVXNmu2Ts2izD8=,iv:vvtceVDPzDGpWwAY3HjNf1NslCFUu6yODtNxa7rJJkc=,tag:dltEgziKIAsmCvOdCYzkIQ==,type:str]
    root_ca.key: ENC[AES256_GCM,data:Z9EHYeQxzmLVtfx6OCFLxAE1TQzsv3KGU0U/4+2FQm2TKJyZVa9qL6gkJS4D1G5GsTn+UeUeCG/UWTd+KYB8vUzFPObZr9bSglQ+AmgSW8RWAYXWhJ4S5jhH0mvxRQ2md+GEyfbClhOzDXgwbSj+I3IMusUu02XG8FJK1tCTdyx1juHhBab0pVctmtlOvZ/OIb/8Hx3tf3+wyJ7Ez7+HVX28WzMIS1t7tq7zDB2xpIPFbJfhp9Gakryypy/+9IARPzV7yFMzfGmpZHehOo92+Gvqh927uiWjeygRlzie/G1VdM8+/WddBzGDNrz5p0As,iv:+f58VKsnwX8MiJxYvdI/eKOMlhEVMobPbxjqkqgthiQ=,tag:GHGfO728xBUfEGtslcjsnA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WndhcE93V2hBYXo0eUpI
            emZKaVRuZm9WQTlaY0tVRDFqL1dpUXRoRWdnCmdyMnhXUEZMWUw1aklkU1VRc05x
            SHJ2SVcydStsVTFST1ZjdVVhVUdoSEUKLS0tIEFMSTlGYWxEaitUTzhJZFNqQmhL
            OEp1c3lTL0pueHc4S2xkZkZTSkN2QlUKzDmpNfR2PB5eHltm1er5jdvjDnmIQ/Fw
            C3ji4PcySLwsX+e2nbpZYjsnvvdCt0L5hB+KTg7tBDzLSOEZTZLM/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTTJJSnI5OGw4VmwyOENW
            eFNKNlhDdW5tK2ZDU3NJb0tQcDlLOTd0d2g0ClVIUkpmK3p6T1B3VzdGV1BlLytS
            d3RtMlZIdkNWRDFQOUZidkl0ZTgxL2MKLS0tIFdGUEJ1c2hUU0dPNzdXY1JqbjVK
            WlJLOGpqcWsrZHV5L1kwT0JzNFhYTkEK0XUK+onD2BYtNw/rLBHQFBK+RXOznctX
            t+gFJ1KW/XgO99s9B8ZQUUweAG3CqjtuamA/f0jBtenjJkI221J+Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T04:16:01Z"
    mac: ENC[AES256_GCM,data:nCUefN+0RDOgS5O5U9si5GgiLnlQc+MlTZQKOlB3h+PsSGhsglm7blxz08h8QmFu9RMDntH/DD3zZM9RI0b1zws3FsP45ewosYtXE+jZFInAqdX68S1cHvMJgdHxT88mF1W2DKDQ3p7MejJ5IczqJICSBysCayaXgsd0HQd3B4o=,iv:PfyDtsEBbVNZhR1kgwDu31AOpVxNj6elBkPQHe9b7uQ=,tag:HmyewQPu4h7TIYuOUEboPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
