apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: aetheric-forge
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:B+mIpU9aTUIAJdvW/rTykJ+nWe9BpL0NsjmQK+aEXsJYffO7yGcnmHcc0AxzaR24fSw8onZcNLx9LnHs59qbMszAd5YSMHPgzEyxtJkXT8Cyv/BfTpUWrmMz44FR+3upP5exhftnDR/VBBPKaU+fgFdjtjAq3fl3aRrSsECtQeL5mh06Cy/B1r0wH636HnwTfYStcjj//nXiHnX+Kr2oRbR09T3eqiN5cWOUD5QYhxjXswxVRFB6C9AtE7zzBSiYiEy35aZa4ZJeFxVIWN167XEk9Npi3v9jMx08qcarIRjFmhq1ahffxOgqe2Vq/St71rBCNNOI3kgbsCtREZM0Dqft6RYYhDroxweMspqhk8Xj6bFBXWVPH577pavWR4GcR+cb/o3DA+euDodOiJMCEBrV6kO4V7qKvnGBqfTsbEOeWwXSyOq0utQLbQfOz+Enz4xuDaqsLn3au/kMQuTEqOCz+aeCAQ8jVf8adUId+K2XBCoBrOCc3pY0Q3EZDmcrDv1VvSjF80VqCEvgtHTMDj/F8O8c6VjUvdSBVxXnPSvuAwaKXdh3VGyGjtdRGC3n9/5HaS+7VxgdsANLm/pBl6CuvM0LSK+ox8ZhCkXv3SecWN5EF1Ly6F04dhxzsTi9MH3wZuo0JE0lhAENjAgBGYlfeKxqfgInZrO1bfTlY3y0vhEK/brGPR8t2bJw9L9qsY4GeHLrm7yUBxtKQ1Yu760R67AQreWSYRackq2+jF7Db3caJEkV60fwnfcBHBzC0E3LnmXFTIBdz2CjgokgHxD3jhkh8pchzOjB6uG16WUhkXCLC6l70ixGoMCAU9ZHwLt0iyDEVqES4A==,iv:lOdXKodKyON5QvFTaAa6tJrT3oOceMeMZFCSVJdeUbA=,tag:tMzbYg8qpKH0RCOmxBOgeQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZFBmS09aMTFTYXN0OUxi
            aXMzVTFqb0N6N2dsSGR4VkJsbVVEdVRESHpNClpzZUFkRmRnYnlWRTNEOFN4RVRx
            YWdVS2E3eGV1eDM4YmkzY01uL3lOQ00KLS0tIDhsOTJuRmFDUlNtazkzdHNlLzRv
            K0FJVm5NSXlRdUVVWWxpcndrVFR4SXMKzCXeF9E4lZ4PRVImPHXtkvKodFi8zU+V
            C6v7gTp4753lJkpP0oJTQ1x/iDP5EqF3Xl+q8lZVyJzgJ6Gz9F48fA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja2VIZkxvM0xQdWpmSGow
            aFZQSXdXd1M2YnpkSWM5YTcwaU4zbHJzcFU4ClNYYUViVlplWEl0MFNFOWlrM0hx
            eEV3R2FnZkI0c2ZDQ1o5RFVOdU0zNG8KLS0tIHBoSVlBajZ4VHFyWDdiR1hsZml3
            MjI2QUk3UVRrL0xBZ0hxN0pka1hDWm8KueeDE9JzQ0rXBC8QPW34xZFOG9hBlcnH
            FBkEq4ie4OUZSPWJrSsgQXYhdJydU4UXnVx0rUBdXvLxvqESs8xpYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T07:57:22Z"
    mac: ENC[AES256_GCM,data:vvWuPoHqQ10AYHikf+56BA6jh2eDsx2ByA+R8g9tishC+3X68UJX9Ttvf8y8Zql8xtXPLX6IpwrezX6Wr3GQKadkE/ZXhkNcNUaKsLZ7s8jqku1Q3iSvY7j4yyo+ANSgGRvllKCqZ8O/vg7wPCqTB7c/Y2HhK5cZFVvhOMruKjU=,iv:4MKkqEGJqK35tI4LOEwwlJd6tBWw0ZujkQvoCSjhi18=,tag:VEIeZ++wH6kw7v6Q5FwMWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
