apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: step-ca
type: Opaque
stringData:
    root_ca.crt: ENC[AES256_GCM,data:v/LGA2lbsrqTrmY+Qr0reu3P+1AVL6rFpPfbHJ61tw2Ap8MY5Hdw94bAlzNdTwZSmu/aTW8qEOapGwqOVu/QyvLv3kEqscPTEuHH6u113pPC5erPWBiy76AV+sGpp2zKkFwSA91Ex1drLEqyfxgPrBrf5/qyY+ar+aa61kyKT7YMd9kceUIvb/YSHlsefWarGb7yorXtU/ZyH1yRtg2Br0bTdx/MsOSf1fFo+2EEot3Ht+7FUC+NE71y4gqH0elY7qHrqviZO9RV0jz+UZTzlsIua3SBcpLWzuhXA2+fHH75NeXzErkxmKhWbWNyGHixikQeM+E3tbPXddfEutwtfxCLm8HPqQmOKU3i75or9uvWZgHCQWEGOk+LO4RuYMMSQzjLcgjBgfqMeqHpEJagpaDpqszLveuObdhNBIczI0rLB7/4dT+Es6sguWjnHl9BjEQyQy23STJbV67yiq3gMI6m+eKPaknWffOzQMhIRhGZrRha/K5Q3Zh5ew3WHuc9e43QENUb66NcyPpqarNuVLWqLboLkiPZkj4IQJxoKBFRGuVLbRdWcZXKdUWKYBdT3noKE5WhIXi5xl1uMpyx5sWMZmPC5CxIaUpiBPKSCKMa/MK5iL5CI5LxL83w1F6qH9clCZ22FtQIHStZEhfGsLzJyrcHPkMBtX3fLBjkp3shCtPmuLX/p41Dwil2my90U7Gg37qfAyL/gEs7CuNKwXzI6ZQwocB/eCYk/7/Ed0NhGgJrZL5X6rt1IZNs4Q9RVhhoyKEHw4Jaa7AUFcfF2Xw6HBq0LF46mGYMVb90skZMFF8980MtdF1J8J1PHzeal76RvRJ81prExeQ=,iv:Tp/JzQjoxCRp7Mvq1bOqpFL5fDN9mkGWMPV/N2sVKFk=,tag:EXrWPu1RMEfnrxh57tGZFA==,type:str]
    root_ca.key: ENC[AES256_GCM,data:TpR85sbTSkG7de9Ai/iJbs1CISMTT5rm7OakdeBMBaEinLQ5DqH+Jv/NRl6v4ds/RGBqAjJ1Fkbmtm87Qnk8emoyOOwL7kZ2Xq51VX23ebhAgDvavFNMIF/B09ACUbQQRWt+Sse4/b9oARMtKtg0LlQ2QLvuyn6ReN65OYN/5wSWKulXlFy1S7wntDtT8gCzb6f0jujUXzEW4CUUzo7IVqtJSaRmKrU8aC5g2IEhGFEr+KFxJuGncGAPKK4NC5Rr488vJoLix3/qAWOu+0YUgY9thrSLMBjyuw7mfxNBorpgzij334md4Pb/HB1dF4z5,iv:nG5s2j4p9TCaERGwnNec055jh4NJdngaHFKV6uJlyd8=,tag:yz96r68KYh2cHHtd1rVzqA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwelY0VWR0SkJsL05ZUFd0
            bTBDRlZscCs3REkvcWlicExXREo2blFtb1RBCllzRGdwanNDUHNnVU5DUnhXRWJ3
            czFqU0lMTVVuKy9QT2dRZXZaQUtTUUEKLS0tIHNDV25GYk80MjNLQXFUWEJQZnVC
            aXIzT2c5UHlrWFluQWJoK2FSTWY2YjQKlqa+fmSaAXHvAYVvFlzr7yzGNxtV35mj
            dYmOfULKSQ8SXfWnPfZW4FEbIDySBREXgByMDieU4IXc+H8yYrBV5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa3JtSGlPbTVObmJLNjE5
            WWNrdXZUclBwS2FOalY1bVVZSEp3dEl4RFM4CnlaQlVlazVIczlmZ3J1c3VIQ0dO
            TTBZbStRWkRSK1NyK04wTEpLMW5lenMKLS0tIDR2K3hyTUNyQWM4ZzJQZWY4RjFT
            blNUNkZtTERLYjllUlN3RGlQV0FqMUEK/23xxd470UwOnL8heLvLkS/Z/JZMw6fm
            BZ8GLRoyBQl9G/IK3JbOUKXZA9UMa/L6g7qosCPvp+r6Hq+AaaEJOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T04:11:11Z"
    mac: ENC[AES256_GCM,data:L+Qgr50D3sBZmkbnTrvvdPp0ZhQExcp5lWF+oefKCqkz5jAoZIxnd0upS6fvNahwmx+uHBvb4F5A9GUVq9GywhT/onAe/FokLxg3nk4NUZcOakr5MQsFpGTc94i2TsQiSk+AkRwjS/xFVl8VfhUNDeeYQvNJPDebfXvHlpRK1o4=,iv:hKG4j+ocahWNrFxulkCsj804CBOvvG0YUZNApe67M2I=,tag:VVKNrU/V50gu5tdtUbHTKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
