apiVersion: v1
kind: Secret
metadata:
    name: argocd-keycloak-oidc
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:BXDRoyJjguxupZM7IcnWUYouieoOAJ5W+Uo4Dme9d64=,iv:uljMjuQfe/6SAdCmeBCG7mNsHcYPfN8j3WWQNRKKqso=,tag:VW/Dwd3ZfqFoCyQ+v5dBfA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSzc1eGhjcURESDlkRkNj
            YmRxdVRPbHA5c2FYalJTZjVWOXBDNDRSOEZBClk2Z2VGcU01RkFpMG9RSzNRMHlX
            dzdmdlQ4cXFoRU14VEtVbFJlV3hNMmsKLS0tIGU4N285QXkwZ04vWWEyb21nT2ZK
            SjBScGFnTmNWTEZIY1NVRHljaG1BNHMKyq2zItc4byoWWoW+E/VqF/grmkYXfwlo
            p+0UY5QLUZ5qs5yKHDrRcn5I5KIL8of6oQflNS4ANDJDKKOrf7dvLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SDAwWkRBNys1RUplcy9w
            dUFUcEs3N1h0Vm5vcE5ZWk9LeEtHMHpiS0JJCmM0ZG9jdThxVlZpNnQ4K3lOZVdI
            TStyOXdQTzNnVXgxOXNReDNwN2lHRE0KLS0tIEtzZjBBMUlXR1Rqd2MvemdTc0tM
            eTYyZzlSMk9vaTNDc3dKMDVNSVQ4bm8KgHREfCqdfpUy4/Iho11FyyUgxVKBg3bh
            LZGTWtk64SjELQejoqezm5QcA6loIvqQIyLq83D15RbrqnjFvdCIPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:22:56Z"
    mac: ENC[AES256_GCM,data:uIxvcZqcZAOP6C1yi168kDW7SrQmqNDs57SG6fMS6U27O2vvUhhMCOtB2l75ImJ4KNo/+h0ClHEqgCkcw4EptomttHi6iyxAEM0wUOpoz9dXaZ9+GVluMFwq8waDruMx6R/OZc43Bxj8BrFH7UmOIIA1p7db0lymPkdTApOLH3o=,iv:uNJY4glzU5rT9tWdXAfUMsVAi4a7jA9a+3DQ3OstKe0=,tag:HL/LVoQerZlGTBjUMIjSrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
