apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: argocd-secrets-generator
  annotations:
    config.kubernetes.io/function:
      exec:
        path: ksops
files:
  - step-ca-root-ca.enc.yaml
  - argocd-keycloak-oidc.enc.yaml
