apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: argocd
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:6WorR2EFjpgSlLkkbjDyKNCiymIMhS2olWehKcjCHMAZqnbOyms3W33zsNynFnDcbFTO2TWmTmhuvMibvqO+9t+tpcfkY9BC0YFfXlNIFo1fSUJ9o/SvjkXB9qL8OJ0TIx09+LvEunFG07Yy4k7DOom8EgpmLQp+jcfrixbytntIHdRBnaG1TXPFcYr/YzttB1Wyb6lKxo4BG/D7Q39QLcfW/GBh0j57iKTtNO2yoUSNTh3X6Xi/9GxT8zLIgYA5AIx6t1YJs3jFteGZ9fhyQ54Toot2q1f0PRCxBtXHaTPepdPeflQZPrdqY2i1O+KZZTlqph5eYFnlNMVXqndR69PTyD7q5eXN4mSXxns6Fmog0ftSwjRSH0efRQz01ZF58ox1SyHFdEsbOYqScB/hjvEHpQkWnHDWkB5YK3XE12Qfym70fS1TXo6p94EOoNIwR8xp9Ig0WognGVL27EAp/609LS62Zebpx56CxyAtdMZSj9qM90vXHl8fzJ3GJmDWMz2Z25XkiNn9rJyVGF6qzKMOyGftYLDJAvTV8XnMDD8qflHmkjx4KK/zZoErhoJlkTS+L/50Dk3KpIJKHpYh8V1rQmjKUr1bBO4jyk/S0hDFgUVHq5hvfB9ygCVGG4hIWzfDuNh3oNuEPQP/EEQBhcY6O120WNKYCkz5CJhbhXyO3529DkI490T7G7Er0DOmnKDoA4Qc1SQwigVPWS33nPyWK/5jlBitpmqC5V4a2dMDMQpBsCJperhpNChwGQp9wvMi+OX50bCOcllO9axUKl3dYwEKaD1WulAwDnCg+jF5rf+RwdGYVIsCnwl6Q+4k7n+Zpo0lSzFThnm/ntvnbcm4ORv8u5LXgja4cX9SVE0ko5tMyoKQBA==,iv:7l/eUmJkEhpNr+SyyXstAXxObjyYjfSRnaNmzmnHoJA=,tag:gI8ity2IJTrUWEYQ07zAFA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRVNtY3Y5WWlVR3lUWVZB
            dS9aaXFOcGlGckZleDQ0S1FucDU5d0d0S1VFClZMZHhVTTdOZUpVSmt1cEdKUnRF
            a2taa0ZmUDV5Q0RIL21YR2t4Z3pmSDAKLS0tIEFsNFdFUXlDOHB0OWRqbWVmRSs3
            MmdIdEl1d2U0WmFKNWprTzJjeVlySm8KkvvvOXx36Sye2UBt0lTtxSMzVI/JABVm
            Uk9c96c0kJGA0Em+A4LXN+D4gpzcthjZkZyDsvHVZREMK7A8CvU5cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRUV5Vys1THZrYWdGNlZ2
            ZjROUHdKS1d6NGM0UmV5RStDM2pNOFc5dUFBClRvZk9nSnNsMzNBVk8vdVEvZnpo
            S1dmdUw3dUNPaUVpbSsvL3N3QmRrbnMKLS0tICtWNnI2bXFTNlhiVXZ5WE5IRWd6
            YkpseHFLQlpFaVRYbXYwMnYwVFBtZGsKYD6v7B3u2nY69BhQ320Q+D+/qpgUusWF
            TbjJuO5kNrKTOj/UMp1vEXVAmBeC3bFCst/1mBWAczGFsw6/WS2OlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:02Z"
    mac: ENC[AES256_GCM,data:586CPbnb8HNEKSAQNIY9xiQufz2ZY1BugB1xmJLX+RPQMrLsGnJn49FfZc2TD8qwFxPYAJHgCsYO36artQxAf69vOHmjZ/Vi13RQYXy07m0Z4QlRqkKURz2bJWdXLn2eUBNTqv7polgU7p5O4OZZSGCx5r2DWIk6CfzvZq1uJK4=,iv:EMENcRymQQSgr2kQVIaES2V23iFc/05HpizzGfzDq64=,tag:GSrDSZTPlSYIYa3rTiRVOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
