apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod
  annotations:
    cert-manager.io/acme-ca-uri: https://acme-v02.api.letsencrypt.org/directory
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    email: brian@aethericforge.ca
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            email: brian@aethericforge.ca
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: apiToken
