apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: rabbitmq
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:0sAjjU/4n7WhoOQQKeu321xyeULJhFrJwtIdVRMsXbz/HGakVxxZjGIhF1H3xBAiPkfLLvC6Mi0JpBQGTf2gu3uONXKvmfFdiUTJ7zzFbgKIoW8BLq/HQ1YeD9GXZX/2OcM0v26IFHhFULFOi7sGxaiTsjiSTw+ju0D6369Dzkc6Ul6o4SzWsToxrxtjSGNO7y3Vk+Ys/IW6vlqvKSswVljVveNOpxZbXjLll3CvK8TLygn4/eTYBnsd9+zQJXHYmU+9vX8q9wTJFqpNJ4f6BbhWCJs2JNyoKauE80v/lIJ+BxC8wxCdbZrpBFJA8McpJxrF03tOko1E05fBMrPlVRaM5cejaeGWE0HapZu3BCoPW8Qtk0Ia0fZ1DAZZK0Ek5XML4iSqcbe2hJeX9FurbNLUwlTv24Q26mIccy3+1zRpCeaC7Xqd1DlGzVSIV7ZnyJPN4pTFyyczU50wDoF6+UV9jcLFwOHBPs1T/Egl0pcmJgVgB6VoiXMa16O1jL+GBs5JluYTjs4hjLqqDYfk0098cPacMnRMv8kZBYSJMjIdjdAkPzApQRues6qD1Xeh0nW9VbfjnpqfvqGdgvx0kqI6ZhnMvJjS/IK/joTs6F6/B9b0Kx8+a8x2fRPqQaxEUvekuLRHP6vUTfcw5UxLbEnZ7vgJ8/iqb3itV5au5SAMqLKYAExN5jL5mgsQ+lh4fnU1LOs6x/Aisk2Va2vaHkVzrq7Mva8ImBp7oJ5+DK9VGxA6rO0SMaB7HmF52vlcxnHLUKKyCw/I8irMsfWRMiiOkBcFdsJ+w6OD34G1F7PsBbd8BWahxfGBw6cjHOWcvPCFJeSq6nn/apB3q9+tUkVPUSrml/KcVdjAR4giF5y0B6hq+y7Ziw==,iv:L3/Najsem+Srlf4LvPDnyyNfFk5EQcGNWACfubUxAeg=,tag:e9ex/AK1n2hGsJpTYzBrvw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZjRyeXZpaER3UGh5TGdp
            RHQ2cUpZZnZFSFJOYldkRC9KYzY4dnJ3NDAwCng1YndhSkhvN0NMZFhuR2lENGxz
            ellqYkRML3l0VlhPVmNTcG5zOHpYcGcKLS0tIEhMKzY2aTBjYXRvRFZUaTAvM1ZE
            WUFibzd0N2xBVjFQdTMzNGVneFhCdmMKbJLLO1ZGOAmLRTm/mj/eM7zZ+vWvV0QO
            XrKdQP4HyZGZBN4pA00mvXTkM+vtdDYGv6f2QenXhPpeNj/dBOkmow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSldOL0ZqbXQyTStYcU9u
            QkZvbXgwV2xXN1NPaUd4citHbDZZOHRUd3drCnR2eCtocEdINmw4b2kxT3VNWS9K
            cWxhUG1zRGhZUEMrMWVRWkZHVThHZ0EKLS0tIFF1Zk1HM1J3Qm50TW5FSlBGOGNH
            c2FkOVFQOExuREFHSm5nelV5VkFZa0EKjrVEH2qJYfgusa0ne4jhJ1PYCOdgEpUh
            mxMoF0HNHYwYYSbnogwIC0EmDkQyrkQoe/veGZmokiAN8okeEJ03oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:09Z"
    mac: ENC[AES256_GCM,data:4pB0Q5VH+3V6SZDdL+rELmdqK4rt3GP+NuqR5tUA+BFGXrV4d/AuPnd53oPMnn6AYu3umZ/SgcTphhQh3vFZQ2Rgxtz9NKT+r81ucZLnjXxmL86Vp5Oyzo5c4hGA/8j9MApeWESbRY+/Ozh7J3zu8hr/Ljw2+dfHQkT7jWv/KO8=,iv:Er5aTU2zVHViXtK+rvZPUM2jXzGPFrTwN/khj60cLJg=,tag:Dpo6nXVrWq8fN5KbAYAh/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
