apiVersion: v1
kind: Secret
metadata:
    name: step-ca-secrets
    namespace: step-ca
type: Opaque
stringData:
    provisioner_password: ENC[AES256_GCM,data:ZSf1Fv+y6fGR4OB49QFyAUZB82EXuG1Etl9ryxeaq8wLCWXjHGx26uHWTXqWBjXH,iv:nEePlkj21H9wNWrUsi4FU6UgnsSUpV+uKPAy7annMBQ=,tag:H7KpVpIJJWJugLIE5GP1qA==,type:str]
    password: ENC[AES256_GCM,data:ODaoA0iNeu0xWXOpPKteZfJaVV4Xr5Nu0NAc+VcALYY=,iv:5l9/0//MywzDk5L7a/9WQ8S0sxwFwdW87kuCiEXMfPs=,tag:zqiWV5kCBTEQc/l2WhGIYQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWVBUZTFTZW1QaCtxenVh
            dTYyKzZBSitkaHdjMkEzZ0RJemJXcW8yMlZrClc4RENWWlpNcDRpZjh5Rmh4ZEtj
            YkJyditFY2tud2dRS0FGUTUzakh6QWcKLS0tIGFCUkRkV29KNkQzbWNjT0tkZWNa
            M1dSSFBTaUdxU216NGxlZHpqM1BMZGcKqBahf4x28ydTZTOqczXgiNG/nj+QYieb
            e9U69kRiYmC5Isk17lK6ua1SEGOChB/AS4LiafBzpeIhFS4qaPJMzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZXdrcGo5eTVqUG81UG1l
            cHZuTEpsK3R4a0t4a1E5elU0UktlNnlOU3pjClRpbklvNW15NzAySER5YVNSeHZU
            Um1ydSszcS9OUUFkT3B1NklHdlI2NncKLS0tIGQrTG5kZDhPZ0xYS2Y0Ykx2S3h0
            czZRMmhvN2U3RjJxTHhiZ0xia2crSkkKZBeiM+keu42Oroa9R0I1U5bMeghOsNGJ
            h8UCbHgYDHrlDjOOIK3ishGZ8j/WjERfFOzDCGZ08ys2pLx4ysay9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T13:28:40Z"
    mac: ENC[AES256_GCM,data:a8KXVkqXHhSlVJkZxcEN7pHwiV0pLK7Idx1tQR08jJD0To5br5Rpe72hoG2K7CpGSiiI0tTnnjT1oNA+p19R/k2y9zcpByC+1TukibHdMBgdSEwZlcvXfveKQZQZKp2ye7umtPFS+mM5Fn/DrCBJzbUHN/zphUmTuvNSUjvuU6Y=,iv:Pa4DcxOqHtIk+F4sfU1nCJ2iDn91147ci0qb1zix4MA=,tag:T8KGnFfnApM5tlb7ixJbLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
