apiVersion: v1
kind: Secret
metadata:
    name: step-ca-secrets
    namespace: step-ca
type: Opaque
stringData:
    provisioner_password: ENC[AES256_GCM,data:stQru5OJM2enmC8AnEIA9dX5+N1DQMZzVRX4fJu3K/v0MMzsRT5M+Qnwf8b5pBb8,iv:QK+8DVm6+v7QVg0KSbcE3QiDI9+wCwjbiyRKkGnTxac=,tag:oGkpFeL9RMJCourv+Tuqdg==,type:str]
    password: ENC[AES256_GCM,data:cSG3tfitW3E1DE86M/kFsyh56AFClI3H8TBoFAMRg88=,iv:KqzLrEnAB4CGvWp7goJvMO/N89Qvomv5G+wSbIk2Fks=,tag:+ZnyJrpZu+av6pnyJ7SRZw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQURiSEZtd1pLSitkNFBY
            MnB4UWdaZk83aThpNG9WdHFxOTRlK1labDNFCjRBK2VjWktlZE12TlViWTVBWmRp
            c2w1em9VOHpZL2hGam9tUkZzV09ad0UKLS0tIHpYbXJzamlROTlQdVZUd3NkNUFs
            eWI2OTRGbHB5R0p1cUEzWVJwQll3NkUKGdmvbA25hgo79ZX8cYuyAu31CfilrvF2
            Sx97iEob3ZNJ88GsdaVuXZgNEgo2zWGvcTmSI70uT+ceo2rCqSKfYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVTRHK3JYcjluMnNhOUJQ
            ai9INGNCUitoUG9qT3BJVlZyTE5XTFVXQ21NCjFCZ081aE11b0pudnp2VlpHWlFo
            NUhxSGVpV3RyTVN4Tm9qSU80a0p4WGMKLS0tIHlCNVFISXZId3BlMGt1ald0TWFZ
            cW5ZNW5tRWhvMDgzV0pTekgyK0ZIdEkKW3OKf6qM+RhH5nrx5fShmIWAKqyg2lN0
            LL6GrdhfTTuXXUPc5kPB4UunnSk4EQEVSuKOSNFsIntf+d89yRYK6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T12:51:53Z"
    mac: ENC[AES256_GCM,data:L2uxI6X1pcKB9HFdzEABdBWkNk6yPqPPShTr239AwqvEMe8YV5UxMKMAureuBvGSznibmiG0IOPGJE0n6mPuk+Tje5GV9q1cUJsKO+4S3Iv7tdv+3ArrqURnDNmFnR24kRy/Q4Tmcm0hdg6PAiIPIgpc6Dah9kLFrl44u+xqu/8=,iv:KrRByqxwZeoxSJxRbGQ5oLkAXQpFKj6uXFvCtVHCgWE=,tag:m7izLhk+N2IuYXgt3kZ6rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
