apiVersion: v1
kind: Secret
metadata:
    name: step-ca-secrets
    namespace: step-ca
type: Opaque
stringData:
    provisioner_password: ENC[AES256_GCM,data:SKELplJUdRRxMhEQF3NFJ8ui3YdnuVHx8xHhZ6uIig5gaRhov1Q1C36n5JXg3o0P,iv:LA4Oge9izCzd2wQu8kyoLn64h3uj4ThKEo5C6rrjoyM=,tag:UOzFoZboW4OOH64QT5ZIkw==,type:str]
    password: ENC[AES256_GCM,data:ZF8l2P2kuvV1g0jBxb2mv4lgXJ1PV+CYgU/k+GnaLY8=,iv:ePHtKg8LPz3MO3C6NaLXvMvUfIJhcbxtrIj7bAGPtWQ=,tag:KROXV7I9jAyu+9mqkuJVTw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra09UbnlOSlltNUVwYjJi
            UWxyUXZ6cHlTSGdJc3JoYTVHOEt1eWxjOEZFCnNLdldmR2pJSi9zZjF2eHlHZlZl
            cjQxY1dDWGx2VE1FNDZRbmtlRkhUREEKLS0tIGFkOEdvMmtPQTlENmNpd05wcFRy
            amdZN2FtWmJvVmwrVnRWdSttcklmOWcKG77lKS1C7Q2qAMTWaVyX2DBr7o4wTcjE
            uRADhYp+m6bcuxx1TYCFmz0OKpMVMEXy6PIKQoUy8ySBWGlVlrEaTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT3dXZ3dhb1dySmpJYWMw
            Vyt4b0NHNXI3dlBnU1ZFL1N3RUYvcWFFSW5zCmVEQzJjM2FMSjhxcFBOTHdkc3V4
            YkQyZ01kaFBhWTdUN3RZK2FsUFU1R0UKLS0tIGNmd0hra1NLbXFrNTlkcUFGTDhn
            cUtSL1BTYS9DNFhKODRXak9jTHQzczgKRb3VKhEsndGF6LqlrTXvVM5xidot6E1G
            AAOnXuNnn3XUo0waV4fLsKl3xh1jUF3k/mCBsJaREyvfcWCGMakLvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:18:56Z"
    mac: ENC[AES256_GCM,data:qnOhAGUSoZWMkb4ID7UMPUa9zcU25XBb0aGKU7pDgFd3zmNNAVrWYUmvqAp5kHxol6BEsodtecODeqovHR5b2UKa+siXqYcOOwFU2co9NaxR8tvujKs4kZngmXeAYySg/UE1f1rRQuqDHsib+vEbhrCRnmIVHmvQwegFzR9sE6c=,iv:xn+MmHsnd1iz7DNW/qu3lkQePTAr5dLBFRp/ElsHRdw=,tag:k0o4gWa11Qknj4x0+hwakg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
