apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: step-ca
type: Opaque
stringData:
    root_ca.crt: ENC[AES256_GCM,data:rcD3SIX065gB4CFT8dP0smLigzbo9znEz67L01fznppO+fKzd9SRRGgmcxnoLnHNAENz9OePXy/HKe/dXy3b8mvW2f0g/uEC1E18YJEqOyd6Fd5HK7XtXUx9Q83uiKcMZjf4PwlG51K3Ul4yTBLl+m+nRNNVOyrd9VkMVLt0GIzpjqnV59/6TSXODh+x/lN+Yl+qz8fpVylKdxo5BiAngAQN30vuwLB19Ajf1d1xBSFeXOkJUrIPcflqdgsKQH3GVbh4lGxNXr4uAR11aR2CQ34iJmZiDFQH7n+Tz+LboVRrLSyfzLHhMRNlFcu8PxjUjq/O/4Oa7+EtxLRQc6pRhv/Tb50caTSJJnEc2f7Jry6XQwct5RwXV3reWaPtT3rssDzESSJv+nVqsr/eZ4AE+qo6MVKLAAaZKiePLAbdtKcGDcszaZUUjFTpJ3By4lTMtKKbi9qYwD4Mk/rp76MwTtNX7Jyp75Gn0HO/eab3YYz/R9L500SruWyuppu7hjt0GCJrTOGdlwgQJYULvh95vN85jvPKtSq6HpZ25+Y04X4VywYdKAMpNxkM/pF0h5+ts2lbTS/OtrJmQZRMltUQjWmU+4lA1i9dpZSz/FHlt1dTL8YpbROI5saPSc7QMfKOfw51zC68/PGJGsKvbRHzAIAuab0fHDTX4wrsFzqG5paOmTslDu+6nttI3PDGNj0So772G4IeYF78IFG572qZbHiOT86+KbHjztHpY0IrXmAJYADgDXGZD4Ccs0wvxEGc1xMqhZKofysTBl8L5ZaR7inPAwZnGHLEsJoJmsA2nfOc5xS4WQdz78U6v4pNbVzSKT5CJGeryOfojlo=,iv:XH/+wtzGxxS9J3KYP8lguSWuv762mCHrOVDesN5Kd2g=,tag:ryIoqPqJGmsHwibUnbE3Fg==,type:str]
    root_ca.key: ENC[AES256_GCM,data:sYb6G74R+I3PODjCmTVhJTRICXLqAv3eOKfLGnSBv1bdW5F2XJqnH2XTfWewqRy6yq6K47YATVZGyydR+vxwOBFQVh8PcI27CaudiSWtuIRdvCOq25hZ5BXoiREcJ2Q85rjtM30kh1S25YKPio5w1BQuffVZO/IkIJpJfSySjwfQ01ljXuGaJTSi/18tzTzuB/FZw7phss1tW8ejJG/PSOZBfRdHp7McLHLZKlo6BHqW5XRj6uCuAxH5acEyLTRSts1phE9jauYtmhIXM2ZnDZzQH3CADlTM6MT4qwYVws7MrgHM6LG8gm7AGshQwXy2,iv:LpdMHBlTMB5rVmSJzDmTAPS9pWI4L6AH1koKYXc6CIs=,tag:xMFNJNwa5J40lr6N6lHmUw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cXIyR0VVeTZIRUo4cUYr
            cGtyYzBEOGtVUEcvUHphMEVDYXU4eTE3UlhJCmRaYkRHaFp0SDdSU2VUby9MK1Fo
            RmRqUFo1SFNKWnZieC9RcWcrUVEveE0KLS0tIDI1aGVEN2Z4cU95VlVYZlVEcXJF
            VmlDRWhZZlA0aEFEYktxNVk2OGE3cFkKnoHTTExiieP9x8bwDKDhFgjMvRlGyO4o
            RXCOBvdNwrGd1YWUu5MOTU/JRSkvnOE3JuzaEueNLVwir0EJ6Yeh2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdkpkak1XNXhCUnRBZ0ow
            NlFtSmM5TlN3czFjdEU2WFAveHNEY2pKL1V3ClMyT0lWOXd6c0FGVytzZGZFMWZT
            VjlIZHBRUHNOalgzc2sxTVVaUW1FaXcKLS0tIHowUGlWVjQzeUUwSE1ZNklTQmli
            d1AxMDhqL0cvYkNCSENub3NxZy9NQnMKc1U8UkWSPb9ozbA4HHtJba0PHzn29iwz
            2R8riFWOHeO1mBoboeoAtmHMEorOAeAjUwb9TvmtnDAtK+/fWDWsdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T14:15:52Z"
    mac: ENC[AES256_GCM,data:IYjf1mG/eyF439/hEZJW9JYCeazdlZBFWpMoSSBQg1LsUgPF8TNdW4SOyHYaTZXnBzpBejjRgtCGLIcqDQwmHZOx11zjUwsAoCMLACmjwbgbJxuJoA5CU7fQYyIyqJiV4FJj2JzJHNiqqJMcuxoqzXN+RONgFZ56xoW6ros51aM=,iv:c7G4VPL29JNphAEyzuzGD+3GG+tSe2h2rWitQqgEAnc=,tag:i0vrQvhkJ0KeLNbcniHNeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
