apiVersion: v1
kind: Secret
metadata:
    name: argocd-keycloak-oidc
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:2sx4fCGD/8Ijg1CvSW2PYRFPnFMzZj1+zPEhAV+6nlY=,iv:Oq51FsLih95OfY8YuI4sYEYG/D+20LofhvXfc8xYS18=,tag:/EilpngIPmNpvlJDloLODw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbU92dDBhN01PSEtlZGtJ
            anVHR0hqQzNIczNuY1VodXAzL1hndTJrd3gwClNBb0RFNmpEZG1kSVdUZytZbVJL
            WUN2eTVmUzJFMFova05kNzNmNExuYjAKLS0tICt1NTBwcWlYZy9KbTAzTjJGaXFM
            TS9lQTJGR1FTWXUxb1d3QlhYUXFjRmcKu5tycKX/ySd1IR1eZGo8RPa7Nq8bF5un
            YTog+Zv33pr3zx0YQVPqcR6NVB3fBFIbqGRk0Sqe8nCquxbHN+ZlRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVTIyV0lldU44VlBicDdk
            Y3lEUlhzZlgrZjFjbXlBTHcyL3ZIT3NxbVJ3CldFNnkrd09uMGZNUmZYVXR1eWNq
            TVFsWTM4SEs4aVRIQ0NKZ1ZMMHEzVzAKLS0tIGp6aDhyRmprVE5SM1pIUTVRajBh
            MFNMT2J5OWFPUU9lbERFUVVNV0pyYTQK0gceowbBf3ErwDX85/0S5y4OmE3poGPM
            hR2HadDFmP1UbO/QlLrxnY8cJXy7VF104qQjAT0Q5fVvZy+LSAvxGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:18:59Z"
    mac: ENC[AES256_GCM,data:bmHaT4fIzURMLFUEUbobbZS6TDwlacZA3YufVRaZcaOM+OW5373HN4O0XnmNw1UjqA2DaRovOpU3Mx8pytlTV8OW5l/hvIWfWGjunIRgIg0obYMbtS7KFKPeA97GAku3vT4VHJVUP1OOlOj17sDUsnUZNDs74s4iy37h4MKo+zU=,iv:I0zKF+NC1yj9odgOggwNW2uKaXrGe0x/CnO3edeBCQU=,tag:L/TVaemuD58rt/i71o9Mww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
