apiVersion: v1
kind: Secret
metadata:
    name: argocd-keycloak-oidc
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:WBODkkfixnHRffPxCFkzHHXSYZcOWTu1PpgjAEtmo4w=,iv:lajryhgcYUytIQ5PyHhAmy1R8WNvzz+xjq6RmL0LuK4=,tag:kYEHZFb51rHX9XR34GhPMA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNWtCejNmQXZXald6a2cy
            cUs3eHpDalRsMnRkR21Nd1F2RjNPMWZiV21VCkhvbUNSMjFzM1dMUE54YUQzYkk0
            K0dIcDMzcVVuSzNCcDdQeXh5MjNDdGcKLS0tIElDMng0NS9RWHBQc1BEb1lDWE1J
            YW9aUmRPVnVyU3BwaGdHNGRCUXV2T1kKk59KljhVTk5/lJz5Q+mSoJ2NnZaLhEqD
            cWR4/mNGBxknapEjAWvvS4ovEbDDYuCdCBW9tZvI3i1Xhgm5AZHVTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZFk0VktvY1MzMDUxS0Mv
            cWFCQWptS0dZejJISFhIV3hzeVRUNDVJckM4Cjl3WElrV3k0NWlqeEVlNGNZclZP
            dDFDMXpuVTN2QUlvMDhUdDIwZVFOY0UKLS0tIDEzbXFJUUtiYk5Tcnh5bStGZ3pZ
            dTl6am9oNjUrSjVuZFI4ejZUSWFsbjQKJVmVqoqV7iw9BOufSSZCjVfTqv9rkGWn
            gDsY9nlslwT89znXMNXUjHnntqeb5rxNTDrUISQo68j5a+ssyzS7bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T00:22:04Z"
    mac: ENC[AES256_GCM,data:Y4vQxsedvK5OknbVbJDI86d3Nd/wx6tx/f/X12VYHu8p4BpcbknMQ7pLQuaCUd8qCisyIuvmnJXWQSNbr6v60HjwHQJnwFfXBLG57i1jh7gx2P+7k1EtdqJ66sCistKJDRoiU4lGYzWOBDB3Qr4U+PbpHQjZa+T0le2SzPF+dFQ=,iv:gMES2T/URAiGUhS8xWkvpu6JIe5+TOHMbrTpYZZlEVQ=,tag:Mdg49nIEfGRQJETR0qf66w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
