apiVersion: v1
kind: Secret
metadata:
    name: clientSecret
    namespace: argocd
type: Opaque
stringData: null
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcEdETlh2cmZjZjBMeGY1
            TmJ3V3cxd2kwOWY5WVRrZU9hMUhiekpKNlhZCjIyL08rbnhiRWd4WnF6RGVHMlZi
            S1pwcWprQXdiaW8zUExjaC81OFNlbzQKLS0tIGp5aHpuRW9ERERCemZ1QWFGRlRy
            QVhlMTYxSGltM2ZqdEg4a3Z5dDZ2ODQKAfmVfF+zu/q2rdY5bdECxC/BvtDbkuMk
            LytiehNzXoNgyOzUF8siISdmax/yF2xqr9F1gfjds/i2S/UgqO1KWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY1BhZTZ4V0kzaHZHb0hu
            RXFhL0dMREwrTlNWc3p2ZkZPSjNjRFV0bUVFCmROUjhkdldVMmI4eGFHUE5MN3pB
            VHc5VGtBblN4d1ptV0Z1a0huUy9ucWMKLS0tIGNicE5BQWEyQWxOd0IvYzJQcGgy
            dmZxQU5nTTBCb0tVR1dkNGVqY0RpUmcKifo9xeDmt8/6Cq70lCI++rIluwDowm2P
            6A2qIlhkiYcr6IZv3oQ5QAYvFgaEYTMnyaqxNt7d8hMjzH/Dmk7Dsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T17:34:56Z"
    mac: ENC[AES256_GCM,data:3o9ie6uj4SnOgv7/cy7CDElOTJx4lKctb0RHW4F6YVQe7999JX0WaOpXaNizmarh+zJmPzpeBDMYSOvMXJA6yy8cgXXTCbWsj1RdB2oat+VROUGKmhkpuY9MopF1rRIV6ua23ZFyYlsN7sJWDE6Vv/LKhyoF3UWZ9vG60san9mo=,iv:SYZNl9TNBl4GjC929J8NLRp5Ijv6EY7hhwLOofS68HM=,tag:ftyvTDtOxpIGESlYoZiBnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
