apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:qXEY/Anyi6PCkUEd/Rt6DaacomeyaWkzXHar0SnY7N0=,iv:+wqHIRCNsOjv7tF6oVyzNa6PzG4qGDsbF7i4fycMyrg=,tag:Rx/Q6FLov0s49ff+ydu9GQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcG9IaHJsYkdGWjl5NkZB
            VDNYK1NvQnlsS1FvRHBWQ3J4Q3YrRjE4b3k0CnIvV3RBbnlkYzZKaVd0U1haUW1V
            SVFNb0NQT3FTTHlkalBiM2I3YXZycncKLS0tIE53L1BhYlREbDBmdjlsSVRtbEN3
            UjlPVzRVdERkc2xVYStIczlmTFh0S0UKdIgkcVWoJdQzQpOtq9el8wfjc8u5Icfb
            8U9E+rA6pxPflN/+CaGqvrv8lsnD6oga9hs+XpGaVrGAhyWXnKYkFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y0xnWm1CNmdZZDkvUVhP
            VTRoeU82dDZMYitvQzZxQWM5WDk1OExPUng0Cnkvd1JBYm1lUkVsQjE4QW5GTWV3
            TUwraXB4bmpqN2xWdjdSY2EyQWM2K0kKLS0tIFk4R0plRXpuZjJyb0hQNnh5VGJn
            MVY4d0JUdTY3c1NCQ0hXTHZqeWJwN3cKnGZLJmdtfIJRfp5veDsNb6+MyuauGPLW
            Jap4t1wMwRhUAYAzImTELAbIO7ZJ2GP68OJ3FLYZ1pV6BnN18x3u5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T20:28:59Z"
    mac: ENC[AES256_GCM,data:z1FQ/PzszM2+tVL7thmVKoHUcNc0DTRWw/COyiCveAoWHYz/bX1MpTT9HqDvTa4CAfUtOuTQopSzCbtGoKi6MRoQFEAs7QLK8GtDCxz/MqYTgSgtE8Qg1XbcQNmBUII+YEt5HJ7WaZEmpB3o+dxn8hUQewG7Ta7zquB2KEJAcDs=,iv:RBMxIqI8GVA8MWoUDabIZUL0dLXnBYHl/v0wT4KlM0Y=,tag:xUn9jp3svV/tNYO64gVXTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
