apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: argocd
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:quMvccr2E16ytp917SXjxbS53x0+YaxL4lr7wElbU5q8qfBt2v1oJAXQh8h4kVs2sv5q5sZetehpzsEcONhUVLZyjKJR33NnH0Z+7tKL0WSGj63mY53Njs6iW3eEfxaLyizE74Kyvbef3KuvFWgSAj1ANLqfEZh613aIEKRUrP8iOsfJgrEwTRJ7SUMt/TqB2I4FHKF4GpYxW9d5sRH5vQ0MAsyTTpIP6nHngjDh80omO2ZV+LHqr9TdzHeO0pxgAGlhD2ykmZicARdfntZIksIchDo8bczJKnhatRRYxmA3WAszsFHDsl536NVJN4jGRxrPntVLV+G2VuuO4uHir1quUov8FZU2b6oh9HFWonz8ZVQUGFyPrSvOFmcofWvyTkWhysNyU6bUGVOcPEX+gX6YPytW50oMU+ugQG5wEwGmW0O9E3jxRzi7KvLWOIVpWnlHy6zPHxzQUT+DJz+pzjcgLaxx2El9iuLt/XKqcWzr9tXlHzH7aPieBgZljNqirS8BWQivVk6o3jr8HF/4aTxtzM6fcA4pypFn9RNarTvhbcI9EljZCbitglqrTfsPD3B0khWC7WYQMgpAcTtodLznGn/40+siGFhMQL2MD/YyT5ebz3IrYreOO11nWaMX/VcC3GXKyKidtyvDXsk6iBNRddT4F3iKI3azLvnprFtSaXB4iRgpk9/1LvA7RYu+0S8EAfK1vigUUzuNsu9XysM3s8WJoXYhJ91/BXRwydkhVZFlgnAQdxTodGHS+03iTCzGL4IY8Kr7YOM/wDjHRfQPLNvfSTHCFrLtSzBuCeB6pByPT1zXI91YfZ6mwLITamvwzP7JZqpeKp8=,iv:mEweBuKOKbJeZRvElSOMNRJMAseL/ijb7stzgWO+HCA=,tag:jxQxMgqmWLvORH46XUus7A==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOWhkeTJyTmhyWEdQRjBm
            QVJsMXJld0F6QThWZm12U2tiRXNvYUxUVVZRClpUdlNxUjNZZXViRStKZEVwS2po
            REloTGxOdUNHYnNqR2ZnRXJhb21aeVkKLS0tIHpNQ2Jsb2F1eHZlZlFnY0hJYUJU
            Z1M2c2R2bTh5ZUY5b2ZvenMzeXp0Ym8KyOKsydkHGutp4voO8eYybIx6MzpbDvmI
            zwy+N/xYcLT0ndLPdtu5yrcLRMrIJPp+oAkFrcNoOgPIj2MQ6Afe+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eEJwTDRvN3RlV0o5YXZL
            ZGh3NkUxVWcxQ042WTlwdzE3RXR5dEpJSndVCmszY1VWRnU4Q0ROcHR0UENlcGda
            a25Cd01YK0xDL29ORlJJejVqYmp6SmcKLS0tIEFhanB2Q3BuVUFRTlp0Rk5LK0xj
            VTV0UXZDSVNVM0ZCNm1oSnNlMWFqalUK6xTI2cIAyK4RRAm5tblX3W8QCaHlPFrT
            NuRBAKqiplAznLXbKnnAMTVifwRKz76ZlRPg1kbIAMQIBlyYfiDDJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:55:42Z"
    mac: ENC[AES256_GCM,data:bOhGaFvidiYWy3G+Yu7lrwBbUO3jXHgg1n/b3cOCiNq7eJUoFoutv4l2ovHsnGcdCvHSrx56VUA6h9+OGCvmncgj37qQB+HCLLnDy+rJGBWbTzzGkRVeOnfmhVvvoETZ+15cvd1+Bpg43bM1VP/Cmu5r2xiW6A0b0jWQgZOhq4k=,iv:seQFSSLF8KZW6SJxiT4UKY8NAYivbFlTe8BbH8CK4B0=,tag:13gUxUHxhRHdWmR1rCeJeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
