apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: argocd
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:+4ZbGv3GiTgQrWvAJ7OxDMdReHYn+oF9xk8KpSk1PW3qb3B2zBF2epW3e1ZYbeEmWXyuyN19Pco+Ca5LAcAhfU153Sh2h8OkdU2WpaPu4JIEfS2/OZ1EB/AQmIJEnwGGdhcLuDF/UQUZ/upDQ5m9PotklSBoneN9jGkEPnPN7h0QcEBVCFnApe6FWMRhR2fMulkPAkm49IpXEkoMVNu0N1ql8ShLuMcj54wCStzwcmtbv6M7NK1DueL9NyJgApRsPugBE1fzwRQMuen1gawvHu/ku0wvVBijFzHnC0DqvtAp817yDQht95ry4z9J2HCEnzODYuU1MDONrbNwLqw9+c6WK85ILD0cBdudnwRdZRH8YAuPlKOStpj5Wiva69dzlN7wsE3S4XbHQ9rRitnW1d8ef4gBAUUqqSX+8JOZkGxzG9VfWnJVs3NTiSAIuJS3ubf9GT1TxsWBPU9UqTAM5llYvkpNXBz7o5vJ8DDyB33p7LKiaN35ks6LusuCEeY20Liqq3Kg55B/DWQIUGCwX10ZOHLXbrjYZ8m1pg/DbLBSn/bdWIJrUoDVsRsz6NlXywQPyo5p8UCREdR2qgILM3yCP3L8vOXs6YpCmGjNWuAuxkvdSJr1PGSSQ86ckWrvdC6pHSfQTAerHrFwTGEguT9WjnuiSwYwz4C0TdvibvDVVL15W6K4SpEyt6KTgLdNKvCP0R4pkMS3qNKYRCYeqFq/N+s2rd6fwkkCMqrzpRleHisd6rsZeUEVHtePs0I98COg8M4L4bEmGNRtUjV0XxERCzNkJoO/KaWgPLVjhKKaU/3fSgLHZm8NtlrR3jw4QZiJ+rdd0bMItvM=,iv:2IE2GAgNA/blMGCT4prXoyOp8eiDhnz5AD3tRTNgfso=,tag:jUihDTZAFZaJe8TuixUbug==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VlZzVzM0K2F6UkpubHhL
            S3NVY3lVcEhnc3loUzQxbWZsYkhsQkI1OEZZCmpucGhmUFpzQllTUUNGL010RHNN
            Wlg0U3JocEM5aDI4amI3WE5YSjk1TU0KLS0tIG9lZXJyNGJONGxxRGc5a0R3T1ZK
            ZFR5RGxyVnpiWnBNRjNXZzFRcXRBSm8KfHOyeBwy8V7uMXZBeVzIzjZMxM6WUHbX
            UHI5cjURXZWi0/X8bO/0Nznj55kMyOaORVsiHI/tHNeamKoXqFssyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYjkwTXEwbUNqNWxadG9P
            ZmdBbTFlYUhzUUpUcWtEanJqZTh3UXZLSVVJCnNXdVNXdlNqOFNLTDYxa3dlRTNj
            Zll3QUJuS1R2QmJ3ZXJtMGFQWTRwWEkKLS0tIGpKbDlHQnJ4S0NDTngxWXlwM1Rl
            V0V5VzhYUXJGQTlONVNBL2xYcVlnYzAK5/7pZ0ImbtQj839TxLFqmgIX4CFgLSHF
            uCrT41femMCzw+/w9+iJhVOuW2VEW3xc3nYj96Be8KZW3cNfJdHQxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T18:35:41Z"
    mac: ENC[AES256_GCM,data:uqhoAOYHH4iXvJUcsJfYU0B+Rdy4tOzVJUGOHVXMD8Sijwy2pGF9wP2LGR/KKF2l0yHWDU8S/HWG8exLNo45aEyKuonSueTQjhvjEZsPa9oNI2uGSNTBg/X1DruvU7vflC1LBjwXFlpij/KzEoeKwPiDHdFUrP694IvwOK1dc2A=,iv:xOS1yc81oZ+cPYSlnT+zG9/+sCJjD30HdMFB+noVBB8=,tag:xxyqE2b+zEOr+KVJu6P9pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
