apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: argocd
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:0F3mZwtVyUw3S3ehj/v8jA5wsOAjqD06e4+hdJSZ+aPl/kkyZerYiXsotDHrT0DOU4GP6FeAi9ksptiFHzgE9Axea1lhrpyJ1anSwZ2G8FlbqLYIEWXjzD4bxmdw3LXy5HU8m3boEIDqNwtGzr3q4/j3IsA0hSuUV2rly+QooqOvkF5W/TUQ+soaZl+N0dbQQyQg8Nr/5611xzyaqLQ3A5SaG6bZGoZfTecgysYMp0WXZYhX4750bcHB6DCMpJmwqF1ur1DDTjMg8t6hWS/FoPWuvpzFBewAQ0kMgZumr1ouysTocaTZ8H/0QviXt+YLEyeR2pBlRxnAJXLgrFgqGrEpu4hqIooWeLCTx5eKspOad9M2NnMENs8pva0/sadDeKjzZIoWZXkI5kUtt9CWLUGVFoLh5PpJ+CXBvNlUXwBOJ+wAfCgbV1C7KHOQtzGrWBh+NWloL3V8R8dBMGEiD9Vj8f6iDpZnJarnv3pm/jj63s5aFxuTEf/2K+s0VU9YyL5DJfT+nZW6PqoJirePoVqFd3RruSEH7d116ga4CSJ6gxZ+lZmIGejOWu7LNS+CKNYZmFxt0H4rJUzmp2A9DIZK4oOf4a731W3i9t3BjgQF21CrYNgFMFm8NdUjTHSAwWvj/xs3JVF+AoUthAAUaJySLmNEQGkgMVoHWIz4cAiu2L9i0jvPi0SMMyUsINdxQpyHFtkfgs327vjmqULmHL50P7FZtjETHVkg/cpLN7aynt+mzvrg6T1q6IEwHfHwO/sQ6PEHVdYWPaTTsuUgRUKgmY9XlpzxhJb4Daj8tHBCg0zsq/LJ4WdfqJXcLYkIBsQm9Oux6aMWnc0=,iv:ss3uwAv9A84nW3+4Io+6zsUJl7lrUqex/Phdjl9SNWo=,tag:VhGIheFPbDL0oIaeHrlesg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSjdpZHFaTW1EWWR0ekw5
            Q1RGWWJjK2pMejdCZFQ1Y2ZxbDh4d0U0VERFCkZZdzU4Q0h5UzlFdjNKV2YvYm9z
            aGhNc3g2TEpMNzhQRHlGcGFYZXNDZmcKLS0tIGM1VVpkK2Y1YVcySFNsTzBKRlUz
            WEdyNUIrdXZWVmIyV2V6aGRFNG9vWEEK6lYZaxbcyBUNZDzePvIwQXNS308gq++Z
            lLdhmQEMVu7Tvc5YyQ6d+DNioyPNCEn84bGGedWZLj9f+bWlFpMqJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bzB0MEhrWGI4MjArV3Ro
            NURFaThrT2J1SWUvd0dvRTVLU3RFNzgvZTM4CmdOL0ovRGpKK3JCSmx3UHlETDRO
            V0hIa0gxWXRoMitpenZYaHVxNTFUNnMKLS0tIENaRklnb3RmVjViNFRCSjZVUGZP
            Z0dnQmdGSmhqWFZSRHB2ejFkM2grSWMKDFTg8WU1eYh4rstCj6l7miWNFaNinLCM
            JMCPpKtrISWKL7k+AbjRzddxwCDuW3mhPiBGG1PUxPUlSvakJo1FHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:18:57Z"
    mac: ENC[AES256_GCM,data:P2MclQ27ObgSJh6vCXAjy6zP9gF2hwjW1pjwGE7bdGVEryTm4q25ZnD1PXwJfcB72KEqVd5DCzqWy3YYdspYO+xXb5VanZ2RgUQPN65hdgnHx9d+jwNY3tfoZQwRjuTBZXeR/+QlhUWVhUgZW6XSL74hOjSdorDft8dCbfSl250=,iv:gMBCHxQ5nJxfky5y+Eui/LfyhRGGT4OQpJDnlEWRaCM=,tag:vJbhFaadyp4QYY/Cv55+pQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
