apiVersion: v1
kind: Secret
metadata:
    name: forge-db-backup-s3-creds
    namespace: aetheric-forge
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:5mIb9qcZpS3uRo2hh5XNRQ==,iv:jHbdvF9QZL4JcGs2HQQv6eRePnSltsxfwPqs5to5/+0=,tag:bbfWfEugdtZYTdGCIXxUUQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:tht56kseTxXRy0otd2/Oq+GU+1SLbOVRIrEKkR4TPWA=,iv:VUzo4ThRFE1yaFEzeJeLU8waBM7zYuUyVIi4v1FCrb8=,tag:hK4OJPCj6VDlQB/mz5s/9g==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVG11QXJGOGQxUXFEcmY1
            QldJWjJsc2JaM1FueW9MU1JWSGVnVDM1QUNBCkxJeG8vbHJvTDd3bGJ3dkNWMlZ2
            Y0x1dVhmUEJQekw1bkd4bFJPejJnWkkKLS0tIFB0U2NmNGFScWs4TXlXY1lnU0p4
            ajB4eUx3T0RGOXBtNFI3MHZkc29USG8KBm+YFHqB5K7euY2mSCZkwJt03HTn/g2s
            u06uaoWrKKyuZMJwrXfSHCC4O9CIbECY/Usc/qIMXawEJeeFNIZssw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc1dNWGVhUHh1WlRPbXpJ
            bG5XbmJBZ2ZpQXh4SzJFeEMwc2FPN2krZnlFClI2MXlUclNaSlJFUlNOcGxKNkNa
            NlFoYVE5WWxnNFVqZkVIRlJhZnM5QzgKLS0tIDR0NjQrWC9rM25NM3R2REpqM1Zh
            R21HdTNqNEtKZ2JSeFBQNkNRSDQyS2MKItoQihvIcnIjRkyGNh8CRNMFk0ArP2cn
            8mDxW8n/oxO7kjxMEESpLFgxmFYFL8bx3qvYOTUbVd8hBNtBmjqy/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T15:15:34Z"
    mac: ENC[AES256_GCM,data:azNDE0p7Amy3INc7lW1ZpNcX2jQMnIYU/k7OdAGZF/9m+aWXG9fgyTfz83c00P4u/4brj8ZmZNR0w+/FG/cmSpeypuQzhXpaG8/Yz1u3rFCt2uiYeMHatoxJ8T3H3YTFlR+dRqvL2xZVSjT+weKXFuiS+KW6by2XP8rd0ljFNXY=,iv:Q9aZnNi0MyJp8C1GA+2pRpjgMKGnFwxHOVVXbJ4U2Sk=,tag:vAFRp4OrB/sdWOIUzUSoWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
