apiVersion: v1
kind: Secret
metadata:
    name: forge-db-root
    namespace: aetheric-forge
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:6nCXHrhFh/P7cqiw2DBP3ZNMbudjED7APk4IDTFfckU=,iv:n6XHokZ6JjhPnr4yW3gMx8OAEWtZL9Bgvs0a/RCM/UE=,tag:ezq8PmTl3J/xF+DqNmXwuw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa2VPTzhDMzBZZnVnZ0hL
            UzJJTEp1K3pKMHhkZFE4aGc4UEg1ZlMvMUJrCnJ3TVY3VjVvcWIvbVpidUpNSWxR
            azlkSlBkcDRZSGpFK1k1V3R3R1ppV28KLS0tIFZzUFdzaFlmMTEwMGYxNGFZVDVr
            M0I4V2xBZXNMTldqcmc2QnRCODJNaEUKSiVAlYDoL2XZGZg3+ES3EjqlU88kJxB0
            s/ZiwDBfwc/XsEhCjnrdsyOgx/L9NeVkB0u6NX0cZnDLa66lilfdiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbCtLZWtwT01HUFExUTV6
            YmZJTWZTR0xkS0VPMVdQNHpCVk10TVZ4WndzCmpFaTRnTkJSQnZMVldsRys3emtO
            aXNoUEROU0xwUVBHYU9QZk9TZXM0ZlUKLS0tICsrYVMwelhjQXd4eUFPbDlKSjI4
            Z1BGRW5ubm9TQm1WTUpweitOZERBSzAK0Z0rrlqX+nSrrY/LA6dM/NyJliuYKgJa
            jR87Dg2OoKnrVQFOEVBnWLt9NTBkON6nWS5PXMWXuVGSJecy3l+xFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T21:05:37Z"
    mac: ENC[AES256_GCM,data:6YV9H85nh1WTVhbsX+VTvgS0FqKWURlD6LZdhOKyTm9CchubP2oIz8MAWzl93S/+umqWKnxPir99N+nUVBY2kUHhbBY6rYcqbGNo2Fx15KOwCP1Z4kYi4OPvHjed+Cecz2obMT/ll/ZRFd7tdZbUgOIIBSdEuDVzP7QqwabEzNA=,iv:e6uDWU1Aq3iFWdspKPx+wZA587FMWF2cRu8LQYKjUG4=,tag:sDODNRutD4QEKMxJmawTzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
