apiVersion: v1
kind: Secret
metadata:
    name: forge-cnpg-superuser
    namespace: forge-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:A30mzcqSaOM=,iv:W/NzmuHDqWjMoECCDQ4TgWYdMZZSDT7mbinXH2f5Yc4=,tag:LsHURahIHZV9XQ/C3rD8mA==,type:str]
    password: ENC[AES256_GCM,data:HO9QcWN9FqVbD1TGZAaK/syHtiGIRvfifkmj1UYgt3U=,iv:rsZL1JU3Qvwn06wSBoQnFcE/KrLchNi6vj1lBzR0wYY=,tag:DSwYK9x+Hmzydqv/TuNLhg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcjVkMWhSc3FITUI2TFdp
            dWxJZ2JWNE43ZDdDbHdBTlB2S3ZET1l0VHk0CklwTm52VENiaU9FRU5nMkg0QWhr
            Ry9XY1pPSTdXbFBkeStiNSszcUJmZTgKLS0tIHVpd0N2S3FYS1h1TmNqMG9jV0Zz
            TEFnYlZDeUNlbnJyR081dEdDN0d2S3cK/e/1b8AdSkjXcI8IbpQq2z/Spp9OWXN4
            CH9CUzMUmvkQAE+UyCUTCD2zFeGSd5s2R5dNi7SHuSSeOWV8MZpX7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZS81MDl1bEFZdDVZQ2pY
            dkVTcitkNWwrVTZrWlFNU2lSTHVGb0pEbjJjCmxLZkRBWGR2cWxYVnhPby8rWmh3
            Sk1OT084YTZZOFdaTjV0ODM1TEtVYm8KLS0tIFY2RGdydDRSMmlITUJaOFBYTnM0
            NlAxa0ZCREFIY05PMUNoQmc1U01nS0UKHYv2+gsd7WBBXdC1XSVyrwLRZOUN64YU
            dTwYt+gaFQSGsXlBg81zc0cvDY3fPp5MWI4ZD1P8/S58SG3riPhdBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:55:44Z"
    mac: ENC[AES256_GCM,data:CeqEktgdhVCeEuzLEtoeIsUIgoMMdo/gsK/ANPuD/+AzHPlBFPPND+5uH8kL7AMwMGN+1Ot83g02C+j1yU3kUt3cTxJmxTWk/WF6Y/BX+iCoWd1+kbr0yiS7lyQpbDcW6tTLafFAlElZuRtgchJEz1BDIvgTt/01wcKTnJ0KDD0=,iv:V5pWe3Mno9qRwzvHSlibvAWRM5XRqfT7UDNa7w7bhw0=,tag:wKxfEu+ZUwsHDlah+0ZLVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
