apiVersion: v1
kind: Secret
metadata:
    name: forge-db-backup-s3-creds
    namespace: aetheric-forge
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:ZYA+IKfmF1KmY+Rdqz4OqQ==,iv:hS32Db8IaO2OciWGQ3BPvugCglIC8y6rWEns8ZdwRq0=,tag:E3VcgV5H6P7i/0DHJv4NQg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:n5h869YM32XPuloChmco9FnwGxniB80XJ45iz4f/wKw=,iv:BkF8QG3UVma2kYq9HEwIRC85K5NTzSu3XhQn51qMUws=,tag:ohUPBI79KMb3VSI0Q0o44w==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVmdYZzQ3a3gwZ1V1QjBu
            emtHcmtWdU9iVVY0bGw0ZVdZNjB5T3VSWGd3ClBoYWpZdVpsR1VEOWQ3TE40ckFN
            aG5TL1RXbWNGaTZkVnBTZUlCZ1RVNzAKLS0tIHdkUVJ0NTdJWEFyN1RWT2dSbTRC
            aXhzNFNvSnl1c3JBeHBzTmlzejhCL2cKozM58YiSOG7I3VLjGR1tH696UEUnZ2yg
            PjU0gzV8Q2C3RXRW2A0nc6URx4aslUsBOJDqVZ7VvI4GYB3oLU8YQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMHFwSEZPVWlDRVFDWTlL
            Um1NbTRBU2QydWhjLzdVd2VxSkpVckxwWFVNCm81S1NKUXFNYWd2NDVvWFAxQTQy
            MnJLbXM5QndwY0NGOHhRZmJVMEhCaE0KLS0tIDJjaFkyNmtiUi8wbDJTZkpMcnBJ
            SVNOLzl3aGR6dEFmUVpvMkY0UWFMWE0KH8pt/RsPJKCWK1eehqdpQJAw1oK/8U1A
            WQ8xmDB/CgPF2/CGNHzFOjeT5X2gZcyRdnYmco7xk1WRM0ef1WtAkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T15:17:18Z"
    mac: ENC[AES256_GCM,data:XUzUzNxf/rJqTe0qiYZc+DPe1LG8D3/SudTqqkh9pDaBhj6H2BRzVubTm1gCIJsS+gGEEqbQR1GdBOslo6qu6lF7cJWy4OmIfL+9M5+OWNpDS3H2YnibRuJ8jOZ7cc4pITZHwh1lyDs4Khe7o4BuQFdHnk2Z8pcyfTjHbelw52Y=,iv:fSl6wf1oGDXNTION9HcwZFlLA+QFFytp8pchJ3Gjfdk=,tag:wD8YD4ikbidqWSOZZe6tmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
