apiVersion: v1
kind: Secret
metadata:
    name: forge-db-backup-s3
    namespace: forge-db
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:lIS+8I8I+SHnYrNjJgLJDw==,iv:MW56TfC6rkBrpsYaYLDJCu3WkgdbKS89CDl25fjSdNk=,tag:z1NW/UE/mCyV3hftroxC4w==,type:str]
    secret-access-key: ENC[AES256_GCM,data:XcAqqzR3sH2iXL91pW5K5mZzhz8AFGOCQ2cRcN0ZuQs=,iv:u2z+15Pp3AC0JRq/Ow9Pu9flwLq/kcyQ0pC5ZOmUnUQ=,tag:ogNqmzbh9wOeS30iHQwLmw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Unhmb0IvcFJIY09xNElC
            aWlKc1duUW10SkkrT0tOZDFNLzJ0SWQ3SDNFClJyRUFSamJlNmJkTVZrd1J0TDRj
            ZXFJTElZdmpkZjJ4bU16N1ppVE9xSlEKLS0tIFZBK05wQ3FGY3U2QVE1K1Zwd2Ux
            QS93NjB4ZVh5bVlNOWFxVVo2U2dIQkUKkq+ZCVWmdGE8wSljRX+RIVC7t+lTJe29
            hB2UFRn11fPbx7LnMt5pWp6IHESP5VjITey/xNN65F0UwxHG9KsXlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWG1oZzJvemRPVGJLRVpM
            bkczZ08wRFk4RXRnSDZiM29UOHlpYmhjc1VFClp3V2RuZWFGa01oMEZESkZZYTJh
            WHR4cldZaWdWK2poTnQ1cUFzTFgwamcKLS0tIDZxZDVNZm1iUFZReVFiSzhFUzRT
            ak5pcVJ1Z1UwRnFFblk2K2lEMGp2UTgKxN4vz4mmNEc6d240qIr8zBYliBdfkrZm
            6cE7GMb3LxC/kRB38m4aOAilo6Ph+4EP0wpgeirXDbpCaf6dkSql3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T18:53:42Z"
    mac: ENC[AES256_GCM,data:TFIt6QbPyn50ux+M0IrONz82eCzdQUmMvEWIsfaw0QFFPmK1UPfgdMMCYGHn+VEqm0c8YV/VrT25KsQXZ1BkAxJdpeica9ZmCpUyW9RO6GnPq2DsRVqZXV3Q0xRJggy3bnaOa0b0PQ57OrDV4dqVF6IsHrfkMEQQRQlHUP3U/6c=,iv:WqarqvoP73sftlMIPPExhIlmw9BMTk/TlOVb7F1xwwE=,tag:yubmdhpZvTVzO2cJQWt1bA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
