apiVersion: v1
kind: Secret
metadata:
    name: forge-db-backup-s3-creds
    namespace: aetheric-forge
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:Rt+6xKH/gJJjIXBKyvQxiA==,iv:dcRC2PRX/bpcOar+areDzrm/Haf6pw7RTErE4b8Wsvg=,tag:oCUl0Q8JSO5Mn2g7VaVmCA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:BtRYGmk0/9LiH/SzO99lHaTmFqL6MSwJQFlDAoSdRaM=,iv:ZSfRKxN9MdnhcRLZLztyPzCNBgoY/uKlBLsZwNMv20o=,tag:DXhu/PV34Q4AY3Fsf5kGRg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcjVhV2k4YmdKWEh5VWxq
            R2ZLc2d5SW1uajcvSy9kak8rTklsaXZCVkQ0CnZpTGFBMzdmZFk4RTMzMTB2dkQy
            YUROWjJCc0ZjMmpTZWt2NkdFaEFSclEKLS0tIGx5NkEwTEJockpZVVdaZGlHdW1C
            RlFNaTlsR2YxVG5IaHJJMGJDZzd3YjAKQD8BIR16jT8JaUTg1W6TrqGA0Pkc/j8w
            lrlpfihlv0VBLcY/KHQzrPJeUBV2AHU+wu/PGx645ysp6c3lelB7ZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV1l6T0JyeHQzdVErQXc5
            VzZpek5uMVIzak9iNWxtK01SSGFQVzAyVEQ0Ck1kbk5neXhCTGxKNnliN0R0MUxo
            bUtNd3JMazF4eC9Hbk1PN2FvQWhiY1kKLS0tIEdnRjlrcFg2Nmk4ZERYRlFYN2VH
            dGVweTlCVDdJcXV6TXJ4T1BOcjFjZ0UKY6ntU1BMP5OLH2Z7kUDFUOdkea1w6rzo
            Iv6U2MPsyHd8SimLBxNki/+sElP/v1nOvs5slN0COYOyN0PnMSE5Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T15:12:56Z"
    mac: ENC[AES256_GCM,data:8UbE5Ri3MeQ2N5m8iiySeFrwr4gKTEF5GDkreJyfa9fmCV2XW+TbI3MJE+WKLeBbd2Y9ptzp5UJ725CMtoDGXcMNRxpCHiJp17EB56Hs1MNJ4Eofm3itpSXu4F6FXLZHaMUtM4q7lQw/lRk85Qt4HGKqR8mdLB5h+vPBMbY+0yc=,iv:DiWY7kLjXuuyOO9WEzfyYP/sSRDb2e9BXw1nL6a51VU=,tag:Qg07F2kNUYe9nRlGNzzQpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
