apiVersion: v1
kind: Secret
metadata:
    name: forge-db-backup-s3
    namespace: forge-db
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:xW97NgoHxLofa7EQ3gDpAQ==,iv:GXJ90+0GQ8QCD33UGKtbnAyYC6fYGmdW5/LvLJ0k7jU=,tag:BQJ/sCZxbrEppT2M4TbErQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:3uIYzfBbmPk5kEa16F/4vQ5zfrBT3XnKh8kJ9VwqCP8=,iv:LDqJCeg++737mt3HVwdcwVcsanY7ic4BwSuDBEuTJs8=,tag:yhFUU+U/g4tNDtio1Lk0bA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YTA2eEdUM3E4eWFYV3Nj
            ZkVCNEhzN1N1RlVOeDh6UEhnZUpFandsSndrClA2RUZZQVp4UFg4YjZLOGpJcG9x
            VjBML2YvbWFLNXRub01PTnErVHBlOGcKLS0tIEFyb3B3L3p2bUZJVG5KUzBEOGgr
            YWdiN01oMFliVCtLSzJIeTFCSEszaXcKreIaywHUuBCeuEj8LK72N5vC+9+F6iEE
            vPqDsodg662568YRv6iS19i0tV0H5OXNSdTzcdsq8rTVsf1sq149/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU0c4ZUZmT3NsZWVhK0g3
            YklodzFqMVNoU0hZTVI0SFNtZUtYdStQZGt3CnBEWU5LbHRsd042c3ZqY1NsNSt5
            c0NmNWVSd1lvNjZONzdVcGl6WlI0WncKLS0tIHcyMEVYQ0F2dXpGbmFIcTQ5dXJF
            OWlZZjJIK2ZjK3JFeUNmTVZZdVdubW8KQTAOPv1pUXmF5it8c3T6Wco+UKF3gzYa
            1chSZUeY4w3LTv5sEQctyK0hqj5miSFsnIRyhnoxVl5EQoW4HdTTMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T20:19:05Z"
    mac: ENC[AES256_GCM,data:YCQskAadGPnOBkBLx+dKXp2ZkuOtQxBZaisDiW5qhD3b873/GXVh4CC3Y+6h33sIkaebPLn/URlvl+690wUw26xujnAyrDiFiyarHd6OsN7AyvBw4DaWCYN2ViJRpMdfDh7tTjNeVWk2uxlLHZz5l2a7RdVMQhltqDoFSKlKJLk=,iv:j9Z2XiMLpPEHDUHg1g3eFj9zj0aJHAcerofl56VE55g=,tag:IaFA5x0srZhArw7TP2tBBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
