apiVersion: v1
kind: Secret
metadata:
    name: forge-db-backup-s3
    namespace: forge-db
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:RmHOJ05I4pYMnq68xlrGqQ==,iv:VX11teiTGMaZ+d4dHSI3QMiTtcxZ7V+TfKFSIGYfWgA=,tag:vu9YktnIDJ7E7UodsWYXuA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:0E76wwuD6it2VxKLL5uZnWSOTzELC5cOsHWgG+Vp/PM=,iv:qhziU5B11HPBULYbSSn6lwB5jAN9qAF6/f/pf9LgDIM=,tag:IFlzPCxNgJ6XOUYEQBSjIg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZVhvUzZlUHg4TmxPZnVh
            WUNIUTlNUzh4ZTNGSTdmaHRTQkRiMDhIOFRRCjRaZFhFSGVuTys3TEJkU1JObGQ1
            S2gxTjNXK2ozWGNTZHNFWTJNZEV3TjgKLS0tIExjWU10MTVSVXhRdWtLOUdCN1Bu
            ZW9nSytvVXpTWFRpK1gvR1ZFenhmaFkKTnPP559C+BhYLo5yhJLfXYN2XQVCliqa
            sxJIYDER3ert2MIeSAaq6cP14bJWnin0P0k1qyYbihXPqOfeTJgU1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMHYzWTZ5TWduQ3hWUm5H
            YWwzTkNEeC9XRjhQK1ptSmZETGdodHg4YWtvCnNyNjNvcnVKZGU1KzdnWXZiWUZL
            U1N0R2t1Z2w5YnJSbHRuWVdoaStDYUEKLS0tIEVUQVRPN0t5cmtYb2l0YzZELzhC
            WS83RHVndm1tR0l1bm5TcUQ3RGpzM3cK2+B3R+XPx9cf2WtTN1YTsc7Hr7trq4F4
            dgtapNRUKxB8Lo9BiI2yV7NPtf2Xm9sAIYRRUJIS+svbzr85lHEEQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T15:54:48Z"
    mac: ENC[AES256_GCM,data:NDwDqWmy3UktzxoVDc1oacfgqMK+S6DtMUvD6W2nuc4fkRJUedGBvY9I8uI2l2vbt3XZH+b1k9AQXQz+WyWy/r3aM6/8RwGwrn/OAkuvmMi/lv7691/IKCF20ZHnCP8CeKC9VwIWDhF4pdmgOhvYj4+ZKpnZw2EBAYUz1i+/thA=,iv:JUPJahrWS2ML3hBb/01FGWOr9VdFvBCfpg3mWxhkyjU=,tag:mkpilr5etYTj9naUITaf7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
