apiVersion: v1
kind: Secret
metadata:
    name: forge-db-root
    namespace: aetheric-forge
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:fL+/lgpaFze0ZpgZM9IEo0bBWIqBJ54VN0WZiKr/ZIM=,iv:gSKQMg4ZlSXsIcCSzF9UpndSMzaZ1AbHo/p4jVsZ/LA=,tag:FRp32DhBQqjOrdkEWrdWlQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOUcvK1NrckttSFZmcjgr
            M3BTOFJ2R2piNDczUERnYnpScEsxa2VJcmxNCkUvMmxNRnlUaCtYenFEdThEbkhP
            VHpzVDIzRy96SXVlUkhYN2hBVVk3QkUKLS0tIHBpQTM3c25qdmFHWU1XWGt4aUJx
            a0s0MkxVeGwxVE9GYTJCTGx3TDZVWHcKU+DuXEsfNUhPjLs9xUgyvo8dDcsO9NK0
            jIPyP3P/MjcL5QsOLSYzk6s6xtGnR9CDcl6bNSi72RlpSgYlnss84A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aks3Vzg2aDA3cksxbzVS
            WTRyMWVlM3hoS2JMUTI0REszQ3lZa2VTNnhRCnlQTkVkbXI1aXkzc2RtVzFhWk5N
            dDJvNndJejBvNmt5dFc5Y2Z6bnY4QWMKLS0tIC9sWGRBbE9ZRTlSQWVuL3lpTVd2
            d21kQlNVNWRYMUhEV0RjNWdSVytWdTgKlXdEbtg/tccFxQgAno+Pl5QpmT8sQ5CS
            w5aa7FBwuVAtildVZCxbuu/NZoyZ3NotPNxVlA2p08P1zqawN0HmuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T13:46:33Z"
    mac: ENC[AES256_GCM,data:pbqioFAJrTR/se3YLn/FT03WiLf742xPc9uD/eF3PzZDY6uCY8ZfcwwHXcpXG8xko7R3kCGo33pT0jp8SZtcKXqERwg1w1Cskim5RpcK2UlvwetgsQoAH9wM6Az18Bsnr2/Ui/Y2l98HNj7C4Y/wvEcXRIeDoXOvSIEFuxgTLcQ=,iv:vI7xt74j9ykXV1GlfqbtZ7qf62q7AGQ4XW47x6DR+Xg=,tag:9uHrxAgmt1F5h5h2lA9QzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
