apiVersion: v1
kind: Secret
metadata:
    name: forge-cnpg-superuser
    namespace: forge-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Y8AFsuDOWtE=,iv:D17KZabbzE4tMaX6AAaa04NgcbEfHrqaMRtqthXwnhg=,tag:u/siqk1aBWKIKn3oiv0zPA==,type:str]
    password: ENC[AES256_GCM,data:tuQcCdHGLrshJzY6Xq6DE3GuaF6rbAlV9YlPMfbATM8=,iv:ERhLEjqKV7T7LFrsORbUY1yb2fqaRZxLnNyrieiDjsc=,tag:iBjtWcY/EBSfpO1gcuHyUg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MnBBbStxakJRMmpKMkdp
            K3l5dTJ2NUVEbEE0cm9ReklSY20wVi9QakF3ClpuMDNqOHB0aXRScHNuWEY4by84
            NjRaUHpycS9GaTBnV1ZoemloMXNVaU0KLS0tIEpmZ1JBUW1KbUs3ck1kZUFkWDMr
            YVBITnVKWkdMUllxYWFndlFzMHBkQ3cKtzlGL5wH5rLir/0ZSiyRN3xTBbSAgRt4
            rJvzy/XXMjeeyk8tAUiCuceJBHThfPD3ieskM1sXAseY9NNhx+rReQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTUczTzZJUWxvU3RKcUd1
            elN6dGdGc0ZhbnYwOTZ2RStHQzVtcytpM0h3CmZXOVBBNzdpWnJLRlpZQXpKZjlU
            Q2dxYWVNZEdldHpnakRCNVJEVmRlbW8KLS0tIDhtRm11V2I1S3lzRmU0ZGk5YzhU
            QmF5WHRLUlBhTzl3SU9jVTYxRGc2MmsK9m2pwBcUcwfUzuvddWs/38sKIrPQmj0D
            qZABAaZQuH7WkCdiZQN6I/UJcTjxn0wUXcmONtDxdJYjDp8Z/7iIcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T16:20:58Z"
    mac: ENC[AES256_GCM,data:H44B+WriGSIRe3RoWbzoBh+oXNlfOLvwovm2wTSpwzcFkH4/hi5bAFRaBnMjIpvhdftFrCfuhwcBgjM6uGxYgpbeNiPt7pTtX+SA0vVdmT8fbtKgFs9AbJgu49MaH1rFESUqTPWhYa3tKspFygIfp38Hox8SfV6yk5rw1gQoRMU=,iv:wkrw683J8QpDeBM6mlvyaYMQPA/jh1VbVl7SQcyIxzI=,tag:ohfaQs3Xqr6ECxExvt2xxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
