apiVersion: v1
kind: Secret
metadata:
    name: forge-db-root
    namespace: aetheric-forge
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:/exagR04Tqj9Cm9AC3523xLsG7ADz7g3Ee6LqPXZJlE=,iv:NPwT8XYltFVl8jr3HzlYzwmlLmMV+i3iiptQRZSIL5c=,tag:5VXhCunff+nWKMCuOH4jfw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByalg5dWZHREk0eUU0NW11
            S0tuakh5d0hZUGZ1dDFGUnk1Wi9IdTA0aDNjCm9kMXVwanFxVW56V01aYjhuNnBa
            VUx4WFcvT1hKcWZkeWwrSFZFbjZpSncKLS0tIEsrVmkyUzdUZlMwaXllUUpHdytD
            a3loeGJVMGkvRktXeW1TeERaR1Jsck0Kbmi1S/a8xEd7bJqnPf2LXHa7AzmbkxDC
            YIg1S4bhjSqcN2ARZuJRkF08RD6dYDU2d3R8VNUmF1lTHQoum0+Bjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWWZRK0dPMlUxWXpoTWdG
            ZjNKbHRsY3lZTitzbXhTY1dPMitEVXVRcno0CnhNcFkyNThGVzZsKzUvNXUrNXJP
            UkNhaDBMZmhjMVZORzB4TlduREduaVEKLS0tIEwrbVdMLytycU1QRTdhb2lYWHhS
            Wi92VUxwZFNGdU5xUC9YbUxSb3lEU3MK6nwtMN4KrSE67iKX+FE18Jp0Xr8G/ySU
            8Fd/rn3Lz+c+obEBC9lNjpfRYIhTJ4wdSkZKSWnMdZ7SNHqDdzVa1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T21:26:36Z"
    mac: ENC[AES256_GCM,data:6E+GumCcGgIUEH8UgEnC+ShnU5VWybBECoKFnIIjEKuBhdXb3bD9XQEKBPtj8yxXSQ0F5alRKZDQ8Q18HPaZutrDLO8PbRIdUZfvC+0rbivofJ13AWRurnsB1TeprjhHQ4yQ8Y2v3DHraBy+oLolr9YxYSGmqQyaKmaRSmIa47I=,iv:YNcwCnskNoX99lSiCnu7WvkMf4NT45HrdOpAJb2fWTY=,tag:5BEytHbm0Xa18trxwuYi7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
