apiVersion: v1
kind: Secret
metadata:
    name: forge-cnpg-superuser
    namespace: forge-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:D4+R5C8Fk8g=,iv:TxhpVgoRCoDnWrEnCA+puIIgAy5EudNno5CzVl7ouOg=,tag:qInNWGbUC+7EX508Q6wkxw==,type:str]
    password: ENC[AES256_GCM,data:Z5zb+ROta55hn6QZiqpsK41qVi/PS/1wIa/KKklVczw=,iv:reMz9Tvxykes2cKxaf+CFnzj+tB/G25F3AZ9L1Ap2c4=,tag:SuBiELTV9tGlkC8CQgMEAQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK1paNWdaaWhIcUlzVUpP
            VHlOZVkwTWo2VFJDeXp1M3NRNTB3eXRKQVRRCnpkL2dxREVncUp5YW9qR21CcWJY
            aWk0Z2Z1cTVOVit1ZElRRXI4K08vK0kKLS0tIGlxVDBDcUYwRWtQbHdzaWsxcU5R
            YTNiZzhqNUFZOXArODFCb1lmaFZsNDQKL/D0HA6TMBbQfplzh4JUx4fagrv6XwjY
            cavMWY9NN+2tpnMzLa4iEr9y4w2RXmwNU85nm0K60xHuCSSVkArKtA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR3VZR1B5VE9UQms1anhE
            N2NwTGdGM0NWZVZwV2t6ZnNaM1BCbk5jNnlzCkRTVGhZVVROcEZnaE1HUmZLYUFL
            dzNZY09MbElqclQwOUYraXluOHpHb2MKLS0tIDY2dVZnQk5TeGpHR1FjVEFKdEw5
            dlArQTZCK2JyVXlUUEk5V2IzSWQvM0UKk6Rx65mCYUnhbYMbwen58Yzdu2/590tK
            EX7qQpOsM4VzMjrdj44cxxAbvoXvgSprmoxKy4gjL03CNDF0wJAmmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T00:43:46Z"
    mac: ENC[AES256_GCM,data:9lNNy4na1Jnh3zxFdwtb1sqY0xUikPB/au3qbEuWr9u2ZYqThnhMHwmwepyfkCdsLim9EiCcxjF4sv1zC71cmTRO1Yhufd/5Ji8IlTow8BiQLHpzVFd7eh9QL935oObh/JufJzC69bYsDF2gBQ0GBveFc0zQuE5RhLqtgqy6d00=,iv:4yjsqsAPnTUvNV0uisT/h/Xf6bgNiJqm6os0Ekz9VRo=,tag:v89fQqTPNzcz+T+qqKkDVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
