apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: forge-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6XinyImzYN0=,iv:h7gDPFLl6r7ooMzP6z/albU1tXI4vZPPHvVIZj1uXCY=,tag:z1UiKG11jd5s4Jk7PjyP1Q==,type:str]
    password: ENC[AES256_GCM,data:yy+qqS3cujFVtAk96XPa9B9Wwe+uxT/+e/XAAf4+5NQ=,iv:9wD2ZuUFwtFop17u937yPqjk+8zRzzTLIFwefL0TG40=,tag:JiQpIOhNUZpUVY3s6+3XWA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVEZGeHZOYWxTT1BjZFYw
            M1pKM2Z1ekxpKzVXemF4ZE1sOTFjV2kzZ3lNCm42TnhZZHl3TUN4TjhtYlhBakVX
            RmxDSnVtNG1FUzBuOGpXQXdJMUNqRE0KLS0tIHFadExLdkVnemJQMndRczl4MmZs
            ZG1icnE5MzdCNDZpMHVuVjl3RkZwbWMK5sPqjVmHn4oKzirMO6Z1+6qxJR17bDxS
            CtRaMuqat5qSRalEQLAvWLzfvw7ocqObynKYEwLLqsQZG1N4qX8LrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaUpOeCtOY1Rrb2xSbWtB
            enF2cVlOa3VTLzRkUDhmWEJucE00M1F6UUY0ClRzZnpiNmJEaVFrYlRFSlhtbXpa
            TkRhTW5YRjdtWXpCSzBuY1RYZDRYWEUKLS0tIFVycXVsZE9rM1V3ekZFSUpYQTE1
            cHQyL2Y2VG5MYUNpM2JGRHJpVlh4U3cKCkTr9Sx5Ue3neMsevomeqbivNF3ZqRY+
            3lFT9d2CjVazFZpbyuQ9lCmc6tF7PExE7fQX1H93LCrSMK539Ule/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T12:41:59Z"
    mac: ENC[AES256_GCM,data:q1EBJWjMRHN35itkKjmpV29QcZ5GuSAAAoZFsHFUHSitQ55px1UOcgvYPpSZo79V/iaAKJ08dfUQtFYFb7FJRla5ZMdFhUJbrdPcBrng/TRK8Og1tVOCjHVf0coNp7grnDm+lsrz8A5HzSbqlZ29o/86XPuPsA0wGTYVNRnnJUs=,iv:EPii7Lr5Qyu8XcwkOJ7zmVkPapGmtndTYA4vW279o2A=,tag:uCAC39m/JWSumOEsp0Abyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
