apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: forge-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mrxJpntCTKE=,iv:d0wHZWnSAs5RyoZ414tiG+5gFRaHQ9WSG/BEdFhGRmE=,tag:4VpmbgOa+beEhj6uGZ7MkA==,type:str]
    password: ENC[AES256_GCM,data:3MvEGs9AdxQAgd1al8+7wUo60bU5dDBhZI4Q6j7AaLk=,iv:AMFAKnAvFidWyYhSROgO053eLxSv00SkCSHfGdF4WSg=,tag:1fkKOrgKIDPFn9XM4pEXLQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeFhGQUc5bEc2aDBPOHFT
            WnFsdmJxaGx5UFE2cXhJc3pwdCtHZVoxYlh3CktVNDZYV1VjM0gzbmZoN3AydmRS
            SUg2aGFhdzJRZm82eWdUK3JSYUw5VmsKLS0tIFMvZ2NIRGtGRXpZTFlITFlSU3BO
            eVo4TStSa0RoaWEwMUZSSTQ0MFZFa2cKsAl3wvSQvHBJNaM1NCWvrVt9LiHuVS/F
            bjmztQcZhW4MvZnOqIRHBHmPyfV9Ni2Slz/guz5sHtyK6cqpFb+2nQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL0syelZLVXNmcnFpZ3dj
            M21hR0t6ZlRvSmJadjE3aGh4alJyelhPYWswClpNRGxVazI5TEZTVHBrcXFJOFor
            L0ZZTGlBcHd5SURaTDJac25tMlJBa3cKLS0tIEYyRGVZK2J6UTJ4cmN1VE1LY21W
            Wi8zeXFaMkh6Zm4raUVJYnVWM2hOcHMK+VRj7/O+9Yfd/5ura4/UNQEd/6MKSQ0Y
            qPet0aXvWLW2WLYMFsPF9iFEkuAQ4qie+J2J8bVVsPiF3MOoRMPnmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:55:44Z"
    mac: ENC[AES256_GCM,data:IhxnLHngBW+NCBaDubSRYd3LcHaTdZX1SyEzX/3JIGVZQqH/9zZSxZbtJLB5nr+EZrGjI4nslo1l59VgrQa3Ck/A+xuKUUkkuf+q1KoDPxMbbitC3RImzYqR7A4RN+GtVAEh/NrWOPJXhBRSA7GJBRsyAO7coJqgs1xrNeean8I=,iv:QsiIWeTai+7lkYi9sR3o1U1okSlneeeWqy0f2oQeGEs=,tag:9LvdAigkCCpH0BRRt+Bllg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
