apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: forge-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qjKn59r1m/U=,iv:xv4oxByl3+owUqYAbbwZcZNVcMJxLSY+Zd9Bh3TqAW4=,tag:6VgKx+0rftk3FbVfzr6OLQ==,type:str]
    password: ENC[AES256_GCM,data:C1E07vsa1E4NfF7EUhETqOuDzvfVRTTF3rVXIKrFkUA=,iv:Yl0VH0l3cN85xB3+Q42Qtb/emUweGHFsgOl2cT3YS0Y=,tag:LLPaZ9yapX0oIKKS6vwNbg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHFZZjkvU3F3WU90WHpK
            NnNxbGpxb2RDQklVV01uNEJ6M20vSitYUEFFCmVQZ05UdEhaNmE5Skt5KzVtZElu
            M3hrRDVIRTZZQXZqSDFTdk10SmtnQjAKLS0tIEgxdWtTRUV1bkNXL2dGamU0ZzVa
            U1k4Y1FlZi9MYnp1MXlPUEpYTVJLaUUKo0H47JLZknLRqH0mCQdTpznf6wl+b8X+
            BgAeggT/HWxsc8s/pUuACukYGL60wcQ9FrENoqpmRuyyLM6WPzZsGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WDRxYk5KTWxTWVA4LzA3
            cEV3YlhRUnRyVTdTaHR2c0twck9nZ2pNVTNVCk4zSkJCUXhHKzIwMi9BdE10clpP
            aVk3SGxwbEpzcldScU1WdW1YUC9PNFUKLS0tIGRsWmNDbzlsM0xNYWN3V0wxSGJE
            bnppeXFsT0lncWsrcDRHc2hEYlBVUDQKsAKr5gilcoIKrhtbwRAVCmU/NyabsNdF
            QT4ZYueqkKOMK7nrHS58+MK1Sx0DqbgvLz2vknWiPQ5AB0oP2OUPqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T13:10:33Z"
    mac: ENC[AES256_GCM,data:wZeGs51gExYwmPMH/Hw/xPGjs5xkg7Bk+E8P8iW5btxlkbLeXku4j4hpEMlicEfi0OFBJkSM8+c9+p6JZvioKd5kEj2n51iOhBWjvbzBcpL7yXfC9C8xL2mYu4MFd1ze1mSZuZF7uJd8QC9CrrPYHC1lkhsnfWr74b9AYCmNEJQ=,iv:tZ2ig3AvEY/mi9meGGgjw2AsrDl81disxkIavpA4HcI=,tag:YY/JlW15VJUCEZZTFmxywQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
