apiVersion: v1
kind: Secret
metadata:
    name: ps-cluster1-secrets
    namespace: aetheric-forge
type: Opaque
stringData:
    root: ENC[AES256_GCM,data:qPTy9i1jJhPjj1GjLyqvp2qw3Ou64MkD9sM1uZhW+RA=,iv:hmVZ3fa65vhrKhpnZhWRBV9q1d7luZV+g50O0JioZ18=,tag:Pnrypwa69fMbUWDU8I0ZPQ==,type:str]
    orchestrator: ENC[AES256_GCM,data:iDjqELQ6ZPMsIv506kAHwQ==,iv:vYZJ7rBfL9pklbyKv2tiWKX/hns8HR8j4DS71rj9lpk=,tag:6cKHnbuYkjGILZqhltdiGQ==,type:str]
    xtrabackup: ENC[AES256_GCM,data:o+KY+JNhW9WqHMqyI4a8NA==,iv:MdcuKtcVHi3jwW3G+V3F6r8EH/tAzadmcBDIny24Mi4=,tag:wb8K8REFnkWH/Rl/4j5p3w==,type:str]
    clustercheck: ENC[AES256_GCM,data:fWEg0lP1vWFuMaFtKTCEjA==,iv:5STMqgOaZOaywnRdUMvAeYKOr6X3gdbfZJk22ZpOV9g=,tag:x7i2SSB1mczN2qHPLBWf/w==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTUZndmkvMlRuSzY3UFRT
            a1dsb1dEZEY4Mlc1b0dFN3BZMWxuOEN2K2gwCjRrcFhuVU9PQW9Wd2pqdmIvYWpn
            UkkvK2J6Q1pXQjMwMGtGYll6RVlhSFEKLS0tIFFON29wR3FpeUpUS3I5ZS9TakVJ
            TloxN3E5SnRUMVI3VmRCSDRkdHpvblUKcZ/ZMBDeCKK2NJc3BKRVbrRVB45lZomH
            692UKTXhcg59SfNYNKiALlSlWsIx0BvjAMSQXrpT8ax0Pc0vRiF18g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ1hocU0rQVZCRXdUQ1kr
            S3dFK0ZMZk5XUFZHcUZuQU1CNUc3Z01FWTJVCnZ5dmVqblNpc1dPblcyRk4yaHc5
            ZzllUlpRSSsrMW9XdEVFcStPdDFXWDAKLS0tIFlQOEZpcWwxUXI2aGdOZEhaTWJn
            UjN6SHN3OWlMdmV0dUl2NjJ3UXZ6cnMKy5q3uVXhx0Jf3VUP688rcd5p9UXZxJSn
            16hH606L90YJbm8lG893rpNVFQc/Im7/kErm5s67g5H3ETsEiF4X4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T21:26:36Z"
    mac: ENC[AES256_GCM,data:d4lk5zh0tuFb7qzC41ot5qGhdvPL8qWeAR4/jyPTWrpA6NBAESLjxpYDfr5RbnCaiB/vDR0sTWHfW2MbGB7AJDgtlvgJiXPTaFgJ5cbTMNdSxYBU2766DTq8SzGiD7Wp+fPNvBHF+mN9CUeA1uwB/inZzyJCabwN6pyUuB8SEzA=,iv:+/iGqgi0lGd49YOjlnNdp/PvzDsx0RYewkcitOXLmJE=,tag:DKLIldbPzAGgZp+XTAYckQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
