apiVersion: v1
kind: Secret
metadata:
    name: ps-cluster1-secrets
    namespace: aetheric-forge
type: Opaque
stringData:
    root: ENC[AES256_GCM,data:atiqCwukAPdnIrkaS3Bk8eanKDuG4KipgxA+S8ZzuL8=,iv:DktmBqGaBi4hs0FhuHPoECR5ov5lvNxa/QFMhBkarFo=,tag:eDTV/6Novq55P9ebiTjxIA==,type:str]
    orchestrator: ENC[AES256_GCM,data:qA3jkieefi4uELCL+3FmGA==,iv:oW36eq5Nyn9QAKTwHSW6y+wfznJoBwSl323JeONuo3s=,tag:+a7jylrVia+s2AYolUaJYQ==,type:str]
    xtrabackup: ENC[AES256_GCM,data:VkVCPnDHtQLCbd/T8wKNiA==,iv:LFMNloaN52Q+Ik4vZXAHNYpOuCUFoPF0jYfghI/dS2A=,tag:jW7Bcw3Y4Kpsd+5qUkQhpQ==,type:str]
    clustercheck: ENC[AES256_GCM,data:edVJIgUiwa8T6+CeJQcuuQ==,iv:e3e9ysQ3Pu+M7S3D79HBgvsKrLfC2oXoq2xX4uWJ7zg=,tag:vpDCn8R/tZJuewHg11fepw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdWhKcWFyRUlicWM3QVBj
            eTA4S3BYcENkczh2THZDcW5GOGlsTlJ3dlNvCjFLeE1TeGl6UlVrekFqYUE1cUJv
            aUFRbTRLMXFDS2VTQ25URzBRY09ZVWsKLS0tIElLL0xHMlp6dzEyR1JHdlN4dzFr
            N20xNm9ZUDYxdmRUZUtNaTM4N0dOeDgKbpiX2OqngalDxhImNAe4B99Y4Ne/8Ejd
            Av1BgyxPFf/bLl7/8qA7z9pzRwjiZcypLnJbkhXwlZpWM1G0DwNuMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cE1yTGxuMUVGOWdtTERM
            Y0RmWDhFeDZpdWhHcDNHSVMra0l2TmZ4KzIwCkNiajBobVlNcnFSckp0WUQ3L29J
            c0l5UTBVUEhFQldKSVNsWk9EWmdyNDgKLS0tIHppb3VzMTBFd0xCVXpsMGJ4UE5t
            MzBBb1phMCt5TEVZa2N0bzR3NGhhSWMKCSQFEnvsbqmRuxoQUTTeCL3ElcyUldcQ
            t75uHWwH4WXUBiEch8GXN85SOFxjhU50nToe6+vSVE5c5nXphG9Q9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T21:24:10Z"
    mac: ENC[AES256_GCM,data:bjb3c9F7zTXdQwTAuU6AzzjoiOOTHkpUoc9rYIS/aGBrIuicYzBW5pK64OH8Jq3OK5EcrLzLodkywo8d1zUYmKkzTSPkAqiSNcFMbt4T5DdRpuCSQe7R+4ZdRz7uc1Pl9KBL9TpEBcTdH5XMiVsXEP11Iktcd9Df4lyaDLdn6eM=,iv:bohGpVZnPG5WCT6Mar2S6GfJ1nX8wj0Ppi5tT7gnOT4=,tag:aliq4f9KT1v3enAuKPpHZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
