apiVersion: v1
kind: Secret
metadata:
    name: ps-cluster1-secrets
    namespace: aetheric-forge
type: Opaque
stringData:
    root: ENC[AES256_GCM,data:y81vjy4bXZx/Og8FwqvLcsU99w+sQgGaKHSR22WaL3w=,iv:30z22B5DmiEU6yBTpXX0fjrQc8R0oC/Gx1MQGcvPo1o=,tag:6ucJgDC3q0kU2RpoR2BLbQ==,type:str]
    orchestrator: ENC[AES256_GCM,data:Y6k/c0rqXUTKp8yXI53YuA==,iv:N84qnUB41gLRqn/1phxxDuQxlwA0OtIKG6SqLRwTExk=,tag:tPl4m+DzLn2jyPCsOw1tGw==,type:str]
    xtrabackup: ENC[AES256_GCM,data:sW+B/aQYfPSTF7QVE4zlhA==,iv:1UTDNTOcNQ9k2hZMV2sNjUGcpEJ76ASXcZ2c4iO14Go=,tag:Df6WRMOPU+4HDwmfng7O0A==,type:str]
    clustercheck: ENC[AES256_GCM,data:egMyKbuLNLfx/xpg6gfDtw==,iv:BqlJ+zCcPb49VFSCgoDCxKIrcU5TbF/nirzpyGpTx4Y=,tag:ChDg5e8M48NMtKyEoWC6lA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMjkrTEpLbVZydkorTjha
            NW9SRUdvb2QwbjFQOFVpOHJGYjlKbFozTFZzCnRwYW5CYWlLUFkzeVM2K0NvWkxE
            OUx1d2F4eEVsZkE2YlViaHlFVUtsQmcKLS0tIGRoTXEwcTZxNlBSMjIyOG1yNmxL
            WUgxb0ZMYk52Q3lHZkNmbUl1aWtoeFUKdgF+YRwZ7rTI3QfDtVvq7lqmpeLHJv/C
            Ej5WnfO6Ohc96ipDMTjFg3YemUeXcT92Dos5c22CY/JVzv1mknNQAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybFFBSlR0eFlsbEtmdmh2
            aWl3ZTlWZWpGVmFxUHI5N3JLd0F6S2pBU1F3Cmt1Wms5K00xRXBUMFBIQzhnTUlu
            TkZWOTNXWG4vMWErVEpaa1hUOVdUTkUKLS0tIDg1N2xlbGE0UTRGK25pVStqUmRR
            Y3dheWlJek4vRG5NSWF1aW1ucGhndDQKMMPDLPFMz6P2FVv3KOr11/DzHi++UvYF
            rvW+Hghng0OB+q5eKQmgk12LSenbTEquC274hBLTLmTIzktZAcB6hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T20:59:56Z"
    mac: ENC[AES256_GCM,data:fGA2pGu2/ITazM//rxp0P14wAteSRIQ7nuR0zpnO2LLIQSqZDZaHwQ3RCG9j2ALHVd0q3CotdVk0WTEM5EamofseiVwNPMBVmMcXoWoLSD3+KiYlKR9wuQDopWE3JaD7zIOGKAFxmcqx8SQjpIDYTySil1C3Gaw19E5deRTfv0M=,iv:9Ueh7bqLSV/516/nMKljCj+lcPqkatcOzKo476/bK0E=,tag:+3PePCzGPSv/tl8ZOSzVig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
