apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: aetheric-forge
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:8pCO3Mfve0LZK5FaZEK4RyxOI7OGHMIgLkiDd6opuxo3nNnk5G24EMmGfRfr6CCte3NI7eQMM7jBR9KXOkyABCsEoXNfiddGZTWrauZ89x97p5DUUquAAlHpw57n/qlu19TqcURvhMm0OFvm9fu3vtbqOnt1mFUBCmN9ACMwjj36dpISAh5RYqfpvyBPQ1bw3sJ4h/OY3Qz6DAmDHv1JYUmoZ0Du5PezBud6/skNJwj4oLDxmUjIah3uJxq2D3+J4z0Xgcl2YIdDgRgc1pm6n6+jyq9uU7YsNIrd3CECRuC+qkNgIHOXlsTnuCbcIFbaOwkOpcX2h8DiuEvyK6dVVNqpKEpcpSLrfPQc3GUe44jt4iEWtz0u35YjRqTzGt2+H0N9efq6X8CzQIaAD2G3saEXkxesX2F2Bscub15vp6D78SFx6knNEDujukTwu9xbOloC9/MNU41E33Flk4AHjQxXPTAfv8QEShgQzibLaNI57RR3fti+mvA/erjuNpXtLZKSyBH2E7QWZGaYyQgm118eKOdOBerA7f6t/ckDQdzQbZfZRgyEK9F52eQRNKLppgxwcWnkRl6qGQpGgdIl8dQMtjThmuAw/+OhpNTe4460QYPQWDttLdS7RDBrYbuQUBhuEhJKVkCwjaEHaVOdSskPq8a+++Al6tva6zE0QrSDaCqbxZE+tlPgxDJvXLv3/c3/7zr1uyCMLp4QtpDbaA/sWYxyuw2tTCmOsMumdT9gmd6Ev1Nt8KRTmlCyxc2C2Etz8YzzutzGZ5zInIuo+ohAkKHumNRn/6vZn1TvaU2tdJ/W/NfCWoA8jPW9NDkHzg0A2Rj6jfJRgA==,iv:vrasGasshqPdUlKFlKeAkgaFwTnt+MyTDhRtZnizC3c=,tag:P9X+4wI947a4vr0yeTehKw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwejFUbTQ1NkREQmE3andn
            VkVuMWhqWGxocE8wSXh1RWtEanV0cVRkNkZvCjBkdEp5Wi8vR2tudDlMd1pvMUh5
            bUJ5Nmh4UkFUb1UzV1JnOVVvaWErZTgKLS0tIHQwMWlJWEZwcFBYV2RGclFwZzNm
            WFlBcGk4eXowaUpMdDdTVWtlTkNOREEK+3aPMxhQ8mHED+CwsFlEVzZBcNL0tvi8
            zZV/4sPp2BgsC4y0UHh9Wq+N/7EUBuBG5Rl13P/ltnIZOq7cPdhCfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTkd0R1dJRnhISGpoVTZl
            UG1xbWRkY1N0Y01XNTFqdzFyL0ZWR3BGVlZzCmora0JjaGZvWDR6MHBGTHZJM2pC
            SG5NWWptQXdaSHBuOXI5enkwcHZSKzgKLS0tIDBoWnMxYXA3OTF0QTFJOU5QeTAr
            RDVVSzlQZjV1QTVrcXc0MlRpV0FtQWMKYLqoC1Q7JyqZJ+PkN/++kTk1EOPobkho
            wxBHa+SFeUKeJzEferZQx76MofpjEhSO+KMfOL+OJrBnd4DiY2iyBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T21:24:10Z"
    mac: ENC[AES256_GCM,data:VIs7z3jmh0PCSL5ZTp9wTZQV/9VLz62hCh2hOcBCHJU5WLIR20RPcietGnpft6ZiK34grXho3EVWIdz7bjkJQFwfoJYzJIby9xNTerbtCzUFBxIHtinhLo70gjsdocL2kG6/jEMtGakh6Ofz+XHdVlm5/jqgY2ISYxKCf6mzRGc=,iv:fhqeB/fLBknAVnBm+PCKtNaXQOpMw0DlTw2TzF+uWqk=,tag:ZyqZ/WrawrNIs+jON5jJSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
