apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: aetheric-forge
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:fBTYKEq5Ea9KRFef4sKmE00/V//X3G+Jt4cz6Ug/9jIvNIznxGVAcrKekwDMuaSt9KW+ZZ0zTWZt4LH8BJQqiTcpCxYhI9I9nwh4WAbcOm3GdPPCr33UemolxDkccvuy7DS54Xl04Nz+INJuImXZLex6uLmdvu8dtod23W9ce76kN2hG/hPf/PrF7Vwz1G13YemYprfa8JiawS3PPBiwA83OOy8wE+orv2EZ06Za8fU+8CzPpdTctsG5+00yzLM6ViXozGMvAmA3kRhTSAOLBgNGIwd4/ugy/dvRFY7yZ+DtJpkQN+cAXOImEHlIITwYDVNVwjjA7qB68ZC5e5Qpl2k0X+Iu3rxSictHX9UsdvFQW3xt5pnPsXrfm/FKO4Gw8ClxjKlbzHf968l2Uc+mcVf9pZnqqN1+mZO6WzM3zogTIfcweIdvZ/ABBL19V2BZuU7HK3y4xeTkQSXu/AQWftj/7EXd3R5pF/QrZkAPRT4I4go3ESyH1py71du1zlG+RgiWftLEWIrFlD3TAd1Zlc1zg3YkcH0M7GJxN3EkWUHyChgxCpVX+INjBx4bIwav5W3ANvCX179pYcTC/+G13RPb7YaHBDM2Y3sGhhELowkaRG9mKFBXohdZ601R3vY8y8KPBpBuwEkjdv0etmEzX8CikuFmVqAP0EOBjI1K4F/sK3Ba64MBxah+wP54gXTLwhMJzkYkGCmqrBDLcKTWgrVjcusFaLqmT5pjhnFwJAPNihsdzMeTOvlFcKBZZ5Za6W48iZTPe2u1hznfTDntF9HueaEnVk2uFJXPbmws7IQS093iz4U4H41WGbZYMIOyuFSCU+hdEFgw9w==,iv:kEtvS5Pi8nY3Y7g8fXyIBu8ygHkl42ZFa9p8MEWhDnc=,tag:GVro1KZ0kIFDmxJOj3mhvQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZThrcS9HNU0zUUE0MXVh
            bEhFMERDUU9IU09aL2R2NXBOS2JENngwYlNNCk5mK3hRc0JmdWdBQXBkZ3RodEJx
            bFlia2tWZGRIWTlIYXVlRFBhQUNta2cKLS0tIDZENkVmSWlzTXBWL2VTSldXd3k0
            QTEra0hxclZVN0taRHJwQ09UNVhhYUUK5QudHNOs6yhm3warSWZOqehQfb+zYrT4
            P3snNUAcoZ0csB9JRD/FxPCwj7n2Pp/BG/BrLqpUqOaM1ggyKCEPlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcEk1SkNsOFJiK2JvbXJ2
            TXlEbFA2RnRwTURJeEt2d3BsSW5SbDF4SVJzCkdDdHFJeStzRjRnZjlERzFTVjJp
            L1VnMEdLRCtiM1FwU0xUMHZmbkd3ZlkKLS0tIHpkamE2TkN5bkpWMHhLUWRReExB
            YlNyeTdOQmdmZ0VvSkJwVCs2cnl4SjAKcGvMiE/iunfzGPJhfHwEuint1kjv2PKm
            SOdh3ELoTo3tOppBk8xob5mjb9laGsMTFOpWth3Q6RVJu1+A/zVHkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T15:30:46Z"
    mac: ENC[AES256_GCM,data:g0SQJdn61OWxIpi8zLU+TasnAHdgEo6YS50c8UYN6OQXLzadRh2Y6gHCBCkJHDH89yT202w5aRHmqLPv9AKLdKNGooJ3otHmTJsPPUmW4u6hUdkefHl2uKVTvFAu+NKpFHWiOtG5qntqbhHrjL0xUxBsCU6OijBZNXWaSNJMAe0=,iv:e6V4zESnjaGbNQp2uwslhqxxMSqAOngs5QfhylbVjIc=,tag:e0cCPtbj642aRwJLEVGoXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
