apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: forge-db
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:V/9A+P8YdtwZggC4Wv2zhWLMvacigebnD7E9G4KktNsLwvdcIYwWMfZDJ1WyrCTyOyMlnRsm2fwtU1ctN5/dJraLiOX/flrLyzJd3YisXYrTQJU4tQ6HEInq43GkupYChK3CAsMzlpjFTp3bn1Lt1gui9T3Z0n9/W7Q1B+YQ1itkzBS6w+VeqCkLDCUPhNOtL86fHd1mC6bTEmwxij24vRPzXKubimGKhg1rSoBI/1S+YEA4nhBjNYUGHACN9Hd9Uqv/kYG+/u6z0glhAeu7bpsQNnd2GgGZNNBRNpQUDCHnh2PNWjbxuOp5dFJwCRdfIGGSyx18tSuJdOW5QncxWhyP2R/8SjHtjcTnoSniXOCugjypdwt4vetpCiNNgH/gATMye1ZloWBuBsfyE1oy5ppoC5GzHWz7EjRrJg1EqCN4sgi2yp57YPy536asTcMCjjJf5jlkQLplUVbsOOa9sSXkO2dLTwwBbUwPWeA1iA53wxHI7jVQy3vUpC3rkcr6kJ8vkKcWHDYc0J4bLCSRyysKPKGuqyvhRKz1afTyP1Dqj6a1BPDdMB3GPvrda8ECUHGXdEWiX+hpOvPoTRFKbTr9bOmM3t6JuZlcZC7UMLcOLrOltY5MPc0NWstujqPr68W5eSzxRDRmz/wFvgE2AAJ7BQgs4oWk+1RYyhxyFJiySETcdK7jGvFyVtQapr7TZGr2x5Fhcx66Zb6QiJAtC/+RBiZUYWZU1AcrIBgYfG0tI215SZrTNdE1NQGxnT9QOOpJaO8rUaqNku9qZTtxLbx8faq54P+XgHVaZDoJgFANKdnsX3WnCymIsnI/j2A2mRGQvxWZae3oLNI=,iv:J80uywoJgQaTySzUocoWSwm13si6jvZ5RViNS9+GWAs=,tag:6eW8IfROP8rroDDs3pGwfA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOHRRaWZ5dmVCQ3V0STFl
            NCtnOWNKWXFjWUlVUHVsUWtKRDhJUWRGaERnCjhHR1FDaVVjMWJNampMY3ZGUWZN
            TSsvMGFwckNORWw1VW1nYXAybW5sY2cKLS0tIHY4TmpDL2xCdWp0ak1vU01mSTQr
            RlNSY3JJS3VlWkREQ0hyUUNzbUdwZkUKdWEysh0cw9LcyLjjLo0EeU1bZE6ScyQi
            f1V+IDRVIhykJueM2xDBX4ebg/qkhhydrEnDMhGtfT+AMdWED2PL9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RW1ZOHMwd3RIU0R2dk5t
            Rmh3YkJqQ0VlMm1TVkUwWkpCN2pCMWZ1RFJRCjRCQXNwdlpaSFhmQmVndzRjM2pQ
            MlROVkxuZjlyL0owcnBLNFB1ZEpXWFkKLS0tIFVTVTZaVkdRSlF5azJVM25XWDY4
            KzJCZzN3NHM5NVM4WjUyMDBCYjFadE0KEHH/BcMG2xEOh4uPG2JHm+B5dQPfxaR2
            AEckwrVVppYF9FiHkqnWwQKUbMKvT0iddas2KtbCzrcR3SDgLPHgGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T18:53:42Z"
    mac: ENC[AES256_GCM,data:QIlw5Y5JDo8aAqTHwW4nyqQmJIjNNDnmYL9egS8Ua5NzTbh7URonwcTzLljJ5SBBNDkMhIAfLd7V+wnRgGhCbfwFDYfB/fJOcdMvJV6VRncAqcEXNu6+ZBRzVd8OWhXhubWL2pk5ZP1NSwVYLV8BbOp6bBwbDZ9S+QJ/mSsT/po=,iv:RI/K4KfowZskKIOK2dvtpcTr89v6n/wAms5t4NrUDEg=,tag:aLUS68SGKfPFPTgglP/cSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
