apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.21.1/cluster-operator.yml

patches:
  - target:
      kind: Deployment
      name: rabbitmq-cluster-operator
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SYNC_PERIOD
          value: "1m"
