apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
- name: external-dns
  namespace: external-dns
  releaseName: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns/
  valuesFile: generated/internal.values.yaml
kind: Kustomization
namespace: external-dns
