helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    releaseName: external-dns-internal
    namespace: external-dns
    valuesFile: generated/internal.values.yaml

  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    releaseName: external-dns-external
    namespace: external-dns
    valuesFile: generated/external.values.yaml
