apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-external
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns-external
  template:
    metadata:
      labels:
        app: external-dns-external
    spec:
      serviceAccountName: external-dns-external
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.14.2
          args:
            - --source=service
            - --source=ingress
            - --provider=aws
            - --registry=txt
            - --policy=sync
            - --txt-owner-id=external
            - --domain-filter=$(EXTERNAL_DOMAIN)
            - --zone-id-filter=$(EXTERNAL_ZONE_ID)
            - --aws-zone-type=public
