apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero

spec:
  provider: aws

  objectStorage:
    bucket: velero

  credential:
    name: cloud-credentials
    key: cloud

  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: https://minio.minio.svc.cluster.local

  caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwekNDQVUyZ0F3SUJBZ0lVWWVTNnNLWW8xODJWdVF4eUhMVEVrNkU5MSs0d0NnWUlLb1pJemowRUF3SXcKSVRFZk1CMEdBMVVFQXd3V1FXVjBhR1Z5YVdNZ1JtOXlaMlVnVW05dmRDQkRRVEFlRncweU5qQTJNVEl4TVRVMgpOREJhRncwME5qQTJNRGN4TVRVMk5EQmFNQ0V4SHpBZEJnTlZCQU1NRmtGbGRHaGxjbWxqSUVadmNtZGxJRkp2CmIzUWdRMEV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRuLys1bnc4MWpqckV4VVZnNHhlKzAKeHNNVk1OZUt6ZGZYMDlCRWhUbm1vMjFyUm9ZdzR6WG9MZUVuQW9GWGQ5WGphd0JBUzFmWGZZTlQ1em4rUFN0YgpvMk13WVRBZEJnTlZIUTRFRmdRVUNOQkRYZlNQMnlRSURRQ2dpZWpZRVpQYVNVZ3dId1lEVlIwakJCZ3dGb0FVCkNOQkRYZlNQMnlRSURRQ2dpZWpZRVpQYVNVZ3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEUKQkFNQ0FRWXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBS05RUUtnaVA1c0xpNjNVYzFJV0syeThEWkQrRkNKbgpidjdBb1J4K1IrTGhBaUJXVXdqWFlvYUVnUFZDZmZqellubitzcXF0cjgwRUl3S3MvWG5GM0lHU09nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
