apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forge-mongo

resources:
  - ../../secrets/dev
  - ../../base
  - mongodb.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: forge-mongo
  app.kubernetes.io/part-of: aetheric-forge
  app.kubernetes.io/environment: dev
