apiVersion: v1
kind: Service
metadata:
  name: forge-mongo-lb
  namespace: forge-mongo
  labels:
    app.kubernetes.io/name: forge-mongo
    app.kubernetes.io/part-of: aetheric-forge
  annotations:
    metallb.io/address-pool: private-pool
    external-dns.alpha.kubernetes.io/hostname: forge-mongo-dev.int.aethericforge.ca
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: forge-mongo
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
