apiVersion: v1
kind: Service
metadata:
  name: forge-mongo-lb
  namespace: forge-mongo
  annotations:
    metallb.io/address-pool: private-pool
    external-dns.alpha.kubernetes.io/hostname: forge-mongo-dev.int.aethericforge.ca
spec:
  type: LoadBalancer
  selector:
    app: forge-mongo-svc
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
