apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.crds.yaml

patches:
  - target:
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
    patch: |-
      - op: replace
        path: /webhooks/0/failurePolicy
        value: Ignore

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      crds:
        enabled: false

      prometheus:
        enabled: false

      serviceAccount:
        create: true
        name: cert-manager

      extraArgs:
        - --dns01-recursive-nameservers=192.168.1.240:53
        - --dns01-recursive-nameservers-only=true
