apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
  annotations:
    metallb.universe.tf/address-pool: private-pool
    external-dns.alpha.kubernetes.io/hostname: rabbitmq-dev.int.aethericforge.ca
  type: LoadBalancer
spec:
  selector:
    app: rabbitmq-dev
  ports:
    - port: 5432
      targetPort: 5432
