apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: forge-db-backup
  namespace: aetheric-forge
spec:
  mariaDbRef:
    name: forge-db

  schedule:
    cron: "0 */6 * * *"

  storage:
    s3:
      bucket: forge-db-dev

      endpoint: s3-dev.int.aethericforge.ca

      accessKeyIdSecretKeyRef:
        name: forge-db-backup-s3-creds
        key: access-key-id

      secretAccessKeySecretKeyRef:
        name: forge-db-backup-s3-creds
        key: secret-access-key

      tls:
        enabled: true
        caSecretKeyRef:
          name: step-ca-root-ca
          key: ca.crt
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: forge-db-physical-backup
  namespace: aetheric-forge
spec:
  mariaDbRef:
    name: forge-db

  schedule:
    cron: "0 0 * * *"
    suspend: false

  maxRetention: 720h

  storage:
    s3:
      bucket: forge-db-dev
      endpoint: s3-dev.int.aethericforge.ca

      accessKeyIdSecretKeyRef:
        name: forge-db-backup-s3-creds
        key: access-key-id

      secretAccessKeySecretKeyRef:
        name: forge-db-backup-s3-creds
        key: secret-access-key

      tls:
        enabled: true
        caSecretKeyRef:
          name: step-ca-root-ca
          key: ca.crt
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: PointInTimeRecovery
metadata:
  name: forge-db-pitr
  namespace: aetheric-forge
spec:
  physicalBackupRef:
    name: forge-db-physical-backup

  storage:
    s3:
      bucket: forge-db-dev-binlogs
      endpoint: s3-dev.int.aethericforge.ca

      accessKeyIdSecretKeyRef:
        name: forge-db-backup-s3-creds
        key: access-key-id

      secretAccessKeySecretKeyRef:
        name: forge-db-backup-s3-creds
        key: secret-access-key

      tls:
        enabled: true
        caSecretKeyRef:
          name: step-ca-root-ca
          key: ca.crt

      compression: gzip
      archiveInterval: 10m
      archiveTimeout: 1h
      maxRetention: 720h
      strictMode: false
