apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forge-db
  namespace: aetheric-forge
spec:
  instances: 1

  storage:
    size: 10Gi

  enableSuperuserAccess: true

  superuserSecret:
    name: forge-cnpg-superuser

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: forge-db-dev-lb
              annotations:
                metallb.universe.tf/address-pool: private-pool
                external-dns.alpha.kubernetes.io/hostname: forge-db-dev.int.aethericforge.ca
            spec:
              type: LoadBalancer
