apiVersion: ps.percona.com/v1
kind: PerconaServerMySQL
metadata:
  name: ps-cluster1
  namespace: aetheric-forge
spec:
  crVersion: "1.1.0"
  secretsName: ps-cluster1-secrets

  initContainer:
    image: perconalab/percona-server-mysql-operator:1.1.0

  mysql:
    clusterType: async
    size: 1
    image: percona/percona-server:8.0.45-36.1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 10Gi

  orchestrator:
    enabled: true
    size: 1
    image: perconalab/percona-server-mysql-operator:1.1.0-orchestrator

  proxy:
    haproxy:
      enabled: true
      size: 1
      image: perconalab/percona-server-mysql-operator:1.1.0-haproxy
    router:
      enabled: false

  backup:
    enabled: false
    image: percona/percona-xtrabackup:8.4.0-5.1

  unsafeFlags:
    mysqlSize: true
    orchestratorSize: true
    proxySize: true
