apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: forge-db
  namespace: aetheric-forge
spec:
  rootPasswordSecretKeyRef:
    name: forge-db-root
    key: password

  storage:
    size: 10Gi
