apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: forge-db
  namespace: aetheric-forge
spec:
  service:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.io/address-pool: private-pool
        external-dns.alpha.kubernetes.io/hostname: forge-db-dev.int.aethericforge.ca
  rootPasswordSecretKeyRef:
    name: forge-db-root
    key: password

  storage:
    size: 10Gi
