apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
  namespace: platform
data:
  named.conf: |
    options {
        directory "/var/cache/bind";
        recursion no;
        allow-query { any; };
        listen-on { any; };
    };

    include "/etc/bind/tsig.key";

    zone "int.aethericforge.ca" {
        type master;
        file "/zones/db.int.aethericforge.ca";
        allow-update { key "externaldns-key"; };
    };
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-zone-bootstrap
  namespace: platform
data:
  db.int.aethericforge.ca: |
    $TTL 300
    @   IN  SOA ns1.int.aethericforge.ca. admin.int.aethericforge.ca. (
            2026042901 ; serial
            60
            60
            60
            60 )

        IN  NS  ns1.int.aethericforge.ca.

    ns1 IN  A   127.0.0.1
