apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind-zones
  namespace: bind-dns
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
