apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind-zones
  namespace: platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storageClassName: gp3
      storage: 1Gi
