apiVersion: v1
kind: Service
metadata:
  name: bind-dns-udp
  namespace: bind-dns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    external-dns.alpha.kubernetes.io/hostname: "bind-udp-dev.int.aethericforge.ca"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: bind-dns
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: bind-dns-tcp
  namespace: bind-dns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    external-dns.alpha.kubernetes.io/hostname: "bind-tcp-dev.int.aethericforge.ca"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: bind-dns
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP

