apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-db
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:dxRrqu+tLaQ=,iv:roO6ru0dfeX6c7718T6n4V3M6PJdTit5G/6cDz+kKLk=,tag:Q1/bfGBXijOH1R6eoMWzdA==,type:str]
    password: ENC[AES256_GCM,data:1FamKYwER6R3Gr6QG0Siunvq/bCRC8Cxae/LxTLDHZY=,iv:zovQVABKh4iSZ0TURkFERoaV4VNKgvrpgf+c+Adis6c=,tag:yh0XC5QkMHgZov7kH+h3yA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3My95cGczMnRnNkhJc01D
            WVRyeHY4L096ckRCcmk3M0FDZTdzTEw4YldNClJvbFFIdVdIcEtFVUErT3NUQytm
            bWJVMG01WjRhamczSlZ3MFZ1a3hEcVkKLS0tIGZKa055bVhJeGZkdGE5L0g5cWFm
            NXYrWUkxOThRRTlHTmxxTXFTSjVzZU0KIuwxFOXGw1gutEQI9g6IiQkZ4qqey8AC
            m74u2P8iG/AQtOCxO3nr9d+Db8IgjkE14vReAqeaY8799GP/m2eYqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZXNRdVUyTDZGbTZYLzRm
            NTYwK0dDYzM5dWNNOG5iaGh5YXZ0ZUVLbmtZCnJ3SlpLMklCdGUrNGh5RXY4SWdK
            UEtuWk42TnFaWlRxemFueDh5NlY4TU0KLS0tIEVMeVN4VEtvM3FZVUFQL1NWd2lK
            NHhyWkp1b0JmdTNzaVVldlB6VW05eEkKF3rPBADKpVES+XUDoaTIK84Ph02jLH1c
            Tx6KBMwb+8maPU1E7bJ7khUfMR24fzQGuvrZeuhyTD3IOEhc1vK1ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T00:43:46Z"
    mac: ENC[AES256_GCM,data:r3XGJXNDJQqezHb6AvMXCwLdd/otf9xt+53Uw2r+EAHdBdfpkoBAefzfcPVDM3STm9KbBePx2531Ulzvk+fCrfECxOSmrWghR5NvEdUBa+ZuENphf6qoJydW7TOzXQl8mJ01qqIo9IpmXefVfLYk0tbdMZp25zlQVEylvEgfYq0=,iv:E7JmZ+xCKEI3QbJdqfR6pFLQSrX+UxKJzlmZqVehU8o=,tag:EkRYzZRDq8T/rxA2fUBsBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
