apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-admin
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6JDFLv8=,iv:bY8Gk2O1fctkLVXJTg4i3Gy1PqJzB2FQglyeZ/6aXRo=,tag:SvS//4lB4KreVDlKHv4P5A==,type:str]
    password: ENC[AES256_GCM,data:CZMG7Kq0GLUvnVNQofpExQ==,iv:4vJ4/V1KrmV8f5ZbMcos8g1sJKsWoDeO/39/ABW1CPU=,tag:WpGaKuA5MKvDTYoJo3D/vA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQ0dZenY3V2QyRXN6NzNN
            RVY2VitFRkJXVFNadkFyWU52ZkIwY1F1QlE0CitHaUo3M2wzMlRzenhnbEp2aUU4
            Z0p0ZmhEQkdkUlllZ3lVZG9ENVhaeE0KLS0tICtLQzg4VXlDVGdIRktnaGVtaFFP
            eWtHSWcwWVdLN3d3ZEZyYXFqbG1rVlEK8OV+0xztSNswftyQ4z7w4q4T/Jm5R7ZF
            Q1y9nF7nm0gpgYLsErm++v3XJEm2+NnSbU7B5Az6ZVC2pwcF9K0zhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdnNHaHhMTFN1WXNjZnlw
            Q2JsRUdSV2lxRUliK0craUd2dXJSNzBMUlI4ClgzMFJ2UkFRWGwyOGJaMFZra3VZ
            MXQ4ZG9VOW1WRHpEeEpvMlRObm5tRkkKLS0tIEVpK3dJYlRMRlJUYUdIMjZGbm8y
            aU01NTBBc2xSVjR5czFLQ0dSNkpiR3cKUewlFYyGS5H8QtgUz9ZlBvr+9gRf83TI
            RWSUXYspRIrWJ2LdiDLWpM/sIZgA1V83qHhamwI77iE6j85oEvIcbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T00:43:46Z"
    mac: ENC[AES256_GCM,data:tGaP0OSppVQlE0cJyAhEe/ZTPgDTlcrEFji7I+txc952wv+KRNuGDVKrT2pCQjEc84JgNN8xnPjR3awE9gQuALbjaQnWXaw8tATcWPngsPKe9EFBUr/heZ450P/TPrjF8UDGTtw0W53iuwxCO71LWG6FMCIKCNY0qs+F8mpJqec=,iv:Kvp5s01ILlbF3C6GNe/3TY2Kwoqxw0+El5L9rA4wZso=,tag:l/dsopwMeVieJQQt+srhDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
