apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-admin
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:widJmhw=,iv:ortETUmQE2Br4XetBv8FjVcUKwMvGNtJh9QWVv6zgIc=,tag:85gykrYBWf3cxeqF1DZhMw==,type:str]
    password: ENC[AES256_GCM,data:QTZTx08chmE0RMbNJxMIVg==,iv:nGOxYl77p5UPox3zwpLBZT41kByGD3lmB/itUBf7XD8=,tag:Wey5Dx9+Mwq9TH/cTjyM6g==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudjJuWUhnZStKc25FUTdU
            RS92TzY4V212a0FTMEZyUEdxdCtVUVJxWVZrCmtRd3NxMDg1dWRjakFnSmpaaGdo
            djdaZVBPeVNYVXY3SDJidkdZVVRxc00KLS0tIHZaZGJlMDF3NTA0dWhSQnRBVUs5
            eStFUFJjY01HNjZldXR6RndDdFM3U00KSEKWVONYAUS32gUboJFXqaSsZBu+Oxf1
            BT5OGXaJkY9wT3zBjfqM+t83rokl9RZLMPS7KwI8xWtxpTWWxS0ygA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSDF6ek1ha2pzNGt3c0M5
            bEZwam5NZXQyWk1NOHdRVDZjZkZ5NnBmNGprCk5LVFNRL1ZYMEJabTQyanYzZUtR
            MVVwQk9KemJQVXNNaW8wM3RtVng4dncKLS0tIGFRU2VtbjBLSWQ0MHRkaFJ4bjhJ
            WW5XRzN4L0txdXUwTTBRaVdCOXUxenMKPLEZL1wiyW4bmkbjhStk5R3tSOZBpkH4
            somzgC2KFQb9J9x4th5K2XagLcM77QSlBkIMKJumxaBtr+P0b4VIvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T00:22:04Z"
    mac: ENC[AES256_GCM,data:auUBnF2Z9L4ULojdZ6BsJSzmhu10gjG546oRp8MXXzYsft8DHMThqBrwdolaAbLUf87YuKz48MKTqcVrb1+PPfg1B5vsW1cE84PdGlbyDHzMJ8jug01UeuGhlbs+v7PwOI7P0ljcGA2xqBjuU5fjaN2rviSRX6osh2gt7MYQUj8=,iv:X/SMwAIjGlraQuc4cNG1CPdzToDKrNtoDqSVyHIahSE=,tag:14ILZ28tqzujSG04k8F5og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
