apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LS2QEcs=,iv:iD6m+ZLgONi36KoxcQkWT70NLpg5DXskDlJXN92zVo0=,tag:hm7w0dceMx2SCPbxbwnylg==,type:str]
    password: ENC[AES256_GCM,data:aQJMaLWyR4P6x2PS22eJrQ==,iv:nYAIc5Xz1Y+YDBYDrIFczDDcLtVDxlLA/2JT1sIgymc=,tag:ogGYhvJd6tB0Nf2NfFMjzA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS0dUWksrdFY2K0xkaEZr
            bXIydDh4R2lzK3Vnc29EL0h6RXcyWEQzWndNCmNQZEN2MXBEZ2lIS0RZeENTNDVI
            SGlzcjRXTFhXWWV0NXBLbkUxcXEzMDgKLS0tIDNFbmliMkdzWGJOWXU4N1VZbi9i
            SFFoWDdMejRITUhTN2dsZlNJWG1acXMKvSBrJacmbUXIZZ6gX/xJ25gIPxysRqkf
            AM2u5oXA3R//6/ZfnqMIMm8jkh6v9kppnRFt1hSZMFIWym5hVSa8NA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzhaRzdXenhHakR2SHQr
            WGVRUHg5b3BBbU9wSXVCN1NMdUdzYUpJcGdFClJ1TngvTVpXVFVvU0o0R2xKblZY
            a1EvbVp3dEtNZzdsQ1ZDazRoTTFxRVEKLS0tIHEySkYxcWwxd1RkeGNWT0sybGo3
            czh6WTR6S3RBMXlYVDlxVjBYMHVmcFEKyTNrHMdA6y+K+HrupadW4A9AtEguwo27
            767ee2hubZZz92Bo6EKIypCoMHWd8yYIc7DK6CoW8BmDXckby3W62w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T04:08:27Z"
    mac: ENC[AES256_GCM,data:3F6m5pZok7CDYL4/TQmKC+WEPCQkxLqkc3/rkCDSYT2cHkdghYrQiobM4Mirsm/8akyDRbBpeTdGTgk+xNA4K0Q9vPcJzCKhyVJfqBcvBYlXikyAwGAmThpnXN4vLvAXTj85zzaHjK/czMYhiVQ8CH84k19InRPio45SiQ6Bo8w=,iv:hJ8iGQOcCeQbstMuv0SsNC3gTvMnQHnPOnfiZdYqjmI=,tag:9FYSzqXZJQBHh6P+fYPSGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
