apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:934x2fo=,iv:hqWdq/KaYA6UCH3dWN5CCD7S84ZZZb23t09Nry2CAns=,tag:tdCLP6iuiEO/6PpMMMjTfQ==,type:str]
    password: ENC[AES256_GCM,data:ctbGSIGP2kWgjdDQKLQqNQ==,iv:xAgWE9sXqng1vfKtMpTk4Zd3aapkDrm0UbbZ26wDUcs=,tag:UIHYiiKlMNEosLDj3gB2UA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZXFaemIvRmdrRWExWksy
            b2dqdldNL2d0d0xIeTluby9Ib2Q0WlFqSURNCmVmM0dhVk5tUjVTVnIvcDdzQmRT
            Q0NpZXoyQ0IyUGozditpaGN6UmpHVkUKLS0tIE8xNmZpQzFuZllIV2l6aVVxSVA0
            MnhMT29RMVRlZi92eVA0ZHFES0NxZWcKPczt/aNUEqoWaMXCJBQT70lbJCCdm2gu
            iGgkWU+VWVs045VlcxuHJyYmy0z+q2z/ePsq2nalHDPNBu8hWNAaJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV2xSYWN6RGszWDFFTGxj
            M2ZITXZrMFVZREdqNWZVRFRkSXVuQUZWMWtZCnJSK284UHlodU1rOThRdnNPOXU0
            ajQ2d0MwVTlHck1qcG54dm41U0RLQjgKLS0tIFRjY0NDbXJBTXpDNDVjMWx1Tkhj
            VDhsbHNDSnh1cUlVN1BobHFkME9mY1UKoADAZvYN/H/51Z070ubrDvF3RZDwJXck
            tu6OKo7X0vRD/adHhLEusAdqneDLr2hcBpVpJxQCpqNfOXURm23AiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T04:42:35Z"
    mac: ENC[AES256_GCM,data:AGGhYNE3gntKQwnOotCj1QXuohDDNDX28rWouefowwCr+FPMiRVqfr2XIxZkGaGSTDcvdH/BrAkUB7ptBp0uVpYksjMn+7quqVE13orpaWIYrt3MWnq0DxSbZQ30Yr7pXYxC6nBwS+BLEP9x0fPNHgd/LE+XyPWw7jJRPiPQvHc=,iv:lx1o1A+z647MKWezqbuNPDnnsDLaH1ya3utOpgWHH4c=,tag:jbsRsj6DOYRR0o6MJq8yRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
