apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mmtScdU=,iv:9d4UkqGM5OYQjFX7s6bzIawOvKQQT5jJifzM3a+Kkpw=,tag:R3efSD2DRdhWbIs5fp6ZYQ==,type:str]
    password: ENC[AES256_GCM,data:Sre7cD/PpjFPMi0qwGOyDQ==,iv:mBz0delpw5HNwt/ioZnjfquHRrb2yU4fOuriNNd+T9k=,tag:DI7dALuujaT8OhV/Bb78Gw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dTZLbkNZL2JWaVJEWENl
            VHE5TWEvTzBDSytyK0cxK0RKK2J3OHhvSkhnCmdVUG9ueWdYL1gzZ3lXa21rNXpD
            ZHNjRFFQeDVPR2prUkp6QkFVcGtwVTAKLS0tIGpXWVhzeVViYSszT09samFTOEkw
            VTVXZ2ptTE00czc2QzJHU3NPVEwyUG8KnHF5ws4lxGeN4v7j5U53jaqNtLOslXBP
            06XK1IDXpUoPFYpa3b+fznO+AS8Jquvm8IOYPcSFIiEVOcXwVSP43w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa09McUVlMGZYUExYZlVk
            cTVvRUw0RGtBSDdXbDk5TzQwRGtjU0tnVGdJCm1FWXlsQ0tOVVZqdEJoVmRwblVH
            ekRBakhmd2lvWFBJK0haazFCeVY3cWcKLS0tIEZucmNwaWlrVHdLbVR0QktCNHF2
            dm9qUlJjUTc5S3djdllrWm1MUzdUeVEKXm6iCFu9+YmJSnjsfgYPp2pNKaxyurgx
            PlUeJsxzIRPxAhpRkqJnW/dZXCUYc8a2ppL9B6kA6cgEuPOp6mcW7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T15:48:13Z"
    mac: ENC[AES256_GCM,data:PcJhYLSc/crbcZVabce7LAOGRWdNN48K/EysKtyuUYOnkvtXz1UFW6vssY/4y42L42UNKKRUKAQJzHRPFMb8HWXIVmJEpbtQ/l02Bm6aVYh40GNujEDMVPRgExw2Bk9v4aLoJGhjXMQFwiQMT9OsC4LSpty5rESv3GMCygPow7I=,iv:8BlbVyIvmbd8xZSGQwZX51EVPJnWvP/y4VIRSn1NwSc=,tag:pWcmoUJye/ovpVDk0jMI2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
