apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:88osfQzr/xs=,iv:93boE33wSg0Txp/DLPhbrN+AdGMai3iJACfePg+1weU=,tag:oxy9YQ1oBCpwFOGPpAd+zQ==,type:str]
    password: ENC[AES256_GCM,data:3Qt23LMItYYTPviWuwPuLahZpU3/HKsIWORQQkET4VQ=,iv:3hPtfaXi2rLzCnAQ+nIfoyaeQQCYYPSnqsS6Sq8rukk=,tag:9UfGE8qwpQx/GsyYUgvkCw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRlh6dlhrNGN3cGlhanMy
            ZVRSbXh3YWVyaTVhTWtmZHdXRFphZ0FaU0RvCktBSTVPcmFNd2RHZ3VSaXdPc0wx
            VEI1ald2WGhnYjFWamhlRzQ1V0JiTkkKLS0tIGRQc3Y1cExPU2hZRHNKK3pCZjk4
            TU56ZGUzMitUOHlFdTE2WG5DY1F1Q2cKIA+wbmG3GrCl25GwasTrccqzCoClQvjw
            BwEHqcCtXxAVBr5DJrwwAczFVbkwAH79Z3vpkfRvQUweJu+sDsIv+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRm5wK1c4Uk1JaDN4Zkxw
            bFViOFFCR0NrR0VVTGNydHRlKytTNjE5Y0dnCnNpUUJ5c0d0cHlaYWx4Mk5nbmx0
            RGE5WG1xOWl2dnhRaTdnSUlobyttY1UKLS0tIHEwenk2SFQxR1FBamF6TEdQMXh5
            Z0tMTDIySldEYUt2OGtqbGVJWWxwYVkKFnRnQaqNGoZz22sXi+52jw+8datSNNeC
            8AStuU3Gl2X3wpwwPagkx57P4qW45q18w6okvpL5X4sGCJLVH2cZmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T19:46:05Z"
    mac: ENC[AES256_GCM,data:8sM6UQwUBtFStZYS8MQqYM0blCohtgM9b98w4zwWIRpcv3vRd4ssKGawGnUtc01X9BWhemVsNQrYMl248g00Jo0P1vNmT+jQs8eGqqd3gb4mc2MmcWoMpDkTPy9VzQnFKNIvFLXLFq4abRsoCWrrgKS8G6MwyksvVLowD5WW4Po=,iv:6BLiRGmbKJUrTIAaX0ALQ/c5CFU1ckhvIJScWaNA4Yg=,tag:isrAN2yea1lRmxYTbjeeBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
