apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:UuvHqHybfK0=,iv:YobvzulzOMRRB+KIGeI+1ktp/oVBiK+wituOn1RsC7o=,tag:KCk0NcLHmFo6B3FCvSnBKA==,type:str]
    password: ENC[AES256_GCM,data:7FUiY/WUkch7qfPFJSWbjgW3sQV4jnzpAKo1i8v9y6o=,iv:Iv6DWeT0r7Ynxrun4h43vwhxYPYbbY1zq5PU5zJVXIA=,tag:Uy08/09xGAvu83IpkfY3zg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRXBQNGFieElOU0hEbk9R
            d25EWmpaVDVJNHNHT2NUV1kwVkZhTm9xcjNBCmZ3NFRDSFhpQkwyWFd1ZWFrc2VL
            RnZWaTJwbXdDVTV2dVBnWnBrN2hzTlUKLS0tIGUvZDBOYWdoeUN3ekh4RTVRTjRJ
            QmFicXlneUhOWEJLaHlwQ3hMK0tGUDgKxJ27pAALx8c7XOFN6Doy15nrgSKmyoMI
            hMjaFNj/F8aH5coqt0/5CbE0GiAhdH4Tc/J0ymmYgS1u8ZRM0uqv0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSXBaR2ZTbEN5OTFnalZk
            Nkx0aFRlMWdlalVvSC9yNUlaKzZEcWlFeXl3Cm1CWWN5WERxRC9pdDR2c0NuMWpJ
            YVJNejg1VXZRMWpSTjE0MWNyYlFpNEkKLS0tIHozaUxDVTA2UzVCcFE0dDdFWTZu
            RC9Xa0Vid1U4UVBENC9MRkxJcm9CREkKvDvnjvm/J3MRhsH3lThma9a7aqU+ulNZ
            ZkVYv0iRJDXMxeI/dgKHI+HzX0UOs3rVrfjhrtFxBMHwAKBWZL5d9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T06:44:17Z"
    mac: ENC[AES256_GCM,data:ciah9hpOyg9Hm22hsa4g2UrkRXkop8ulsmt1e2LFRodh34sX6BDqdUHPRO3Q03IHEOcJ1kssPvS2pousgyBtGA2puMegqWrmIJ55V2Svl0euKx++5q+5S2KWjXo58vLBqVB/h7m3XSI9mnKQl6MViueNA8zr69EZjwyRWNhT8oQ=,iv:EJCCeqTfeLhISDMZiy7G4fWMDMupbWwB9vZ4xt9Q5nk=,tag:oZbSO0dnR5E5xGiieWjuiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
