apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:rw5JSYuV4eQ=,iv:1QRUveqPgnDyZ8M1yjI/2y7tWTcliQUQkhv1KdvnS6w=,tag:RFyqXX8bPMV2OVbnMklheA==,type:str]
    password: ENC[AES256_GCM,data:obhnmj+3lbVLYkA/mWn2Mxickktf5JsFVRuHPKuCjOY=,iv:iuH+bGSoGw8I4BS1g0jCCn3vkFziXOttVGlTqZyE5t0=,tag:oLFsTdEVpsqqyDJs+UNf0A==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOGtSVVFRL0hDS1FCQ3Bx
            SklLQ09YR2lKRDNJM3QzTW9uZEdCTXZ1cTNjClRSNjR3VTFxTlZmN0FNQ2tnOUpO
            NlhHWXBtMERpcFNTanlydEdNWEc0MWsKLS0tIHIveUZza0pOcUdUNHlHdFBUa2NG
            RHYxbEZXR1ZOZ3l3Q0hKdkFpckdNVHMKcNTb3DsvGfktPi6gd3Ik9H9ID3RPq+l0
            wkIkoJGNzubR0EOr60DlhNJUbZjcJgX63Of619eSxrYvc3+QN5TK4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eXA3bjFsZzhHazJoT0hS
            SG5PRHNYRkRDME5JNUZXYnVuZDZGTWJaT3g0Cm80VUtndklGQ24rMGFaS2ZqL2d6
            NitjRWVMVjY4Um5UZmV5ZzkvUXBXdEUKLS0tIHpwVlFnQ3YrV2hIYUpkdEZ1bnN0
            c3MvR1hLUkozOCtJdkNaQmszdmVYdjAKNgBgP2EFG6Zia0f2pdkF6SsD64i81QSm
            BOMxBlfMnx7fNW9l7915oF3FnX40kYpXhWHduzj2bjInjWAKCjLBAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T20:19:05Z"
    mac: ENC[AES256_GCM,data:/DL1mML1AnbMxY7t5EQg+PGOZ7U+krlTy93387NIUvXTxnWFB51yV6MUK0699Q6aXyV8vS6aJW1i88K4xMFFIoZ7HKYglEkarRa7oZcDok187na624FnPAeT/ytcOCWWOvolSEQj7LhJzhXG6YJ8ceeHEaBxQ/6r2QD7vtFuALA=,iv:2mg2Y0+qHYfqouQSWATC8RNQZCGHrqE2I92NrC17bTM=,tag:gx8L/zpvXHwjiGOSYyuAdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
