apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: keycloak
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:ernbZy8yoEjVO6H58sbVAiWCLQMd5daTKGP4MHM6n/3XRX7l1El8QoPXWdXZBmZqa5SOgp1V1IS40baBpaEdVtij+I+LM0oLwOTrARdCTcAx+tjU72CgvppANc/0JuF0OO6NCSyQBfu3Wmmb0gMOeeyo8oczImFzlJEXgiWBusFFav2vMpWWdJPuVifXuYKRJUglKna5C98Zy+Z188wdDcdxJafTeCwfMMRsE8lo2vQI1hW+plZ/gFZxjNlR2QZIxI/gzBxHrsJhaGfn0EMbGcmHdOOTnJRtw+jS/04KbK6y5qRzvlsCGCStL6+5OzDIiGu2RxNdtoczPm9aVTsGiNgtsK87UwnG4Z87CvpxchnjQA0+FTlXW3eC5zxw5BYvor99PKfeKzEt3WDeGaf6jp2aQ0ZXvfq1vkYLiADrn7ssRXkBFzR/pbrnUsl0Su9cryCKxjjZ1VQE4ye73fQJpbEM9lTZcGGTGLGKnJkZNp+NT6EQmiHnGkFv+1rUyqOXwVYiaBCU++VL9yPtz/a67KqAfvkzmz+KzPW4yds3qX3cTxwpkTIdSuqW2teOKF+lHXH4AvZPWq2yJ06dxRxOvUNR7EHsdSBSxv9JJgczrV+KlfzDzbujJHL45gVlXuwxT+qcmjWoEMVn4+hkZaBekyWLNIvhbXvBoC/pBnlKJSxwrrvcmxPVP9CDQazu3DtdaYhpO1H1FwJP713ojFY9pTVIDxvX7I+bWPpS5ZI0GMKH9gzpUuV/jOoae3kgwjv4C6AhrkT/4Wl6ywwqOrunmfsrExoZPHvmvdNK1uxidkIS9o5lUhB8E9sEuy//j6E30wIbx43FIQ5jEC8=,iv:Bx9y1nUwt9NuHTQGH5od9iOhkvNISQkBQe3sVSdSKGQ=,tag:7MwiMppAYSPzOrbmdqYmDw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b1hJd0RDTnF0Q3J3SmNK
            akNpVndOZzd0N3N1clEzMFBRbTFxaUZjeEFrClg0eWFyYmxuMlppNS90ME53SGlR
            anFyVzNRcW92ek9pdnIremN6NnE5RFUKLS0tIFZrd3IxR3RDWHBoZ2pQWEdkZHFD
            dGZVWE44NC9sczVlR0lsTGUrS3ZSMGMKP4R5fBOtixzVyL+tOpcAyKrhK/781xGF
            +f1KzcGwGe5G1AB8aB8HXe6b6t58t+WLlxLwaTjoNrhAZy528kgLUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaXhSYkNnekRGV25kb0Fi
            NkszYmIwN1pnYlBScGN6MnRNR1czSGNMTnhZCjdmNS9UZi9jUzhtSmsreC9DNXpL
            MFhRN05YR0FIeFRmSC9Yb2Z0TVJHTlUKLS0tIDJIZ3IzZ3kvMG9yU2JhQ3hSSjJZ
            K0xwV0JieHplTEZ0QWY1azdYeEVUbUkK/t97afkBMt5OO/BqbxF9j/ef1/0nYlkB
            AxDgvngy8OWA+JlnD1vGToKS+NH3nz9WcrTsqFX7T40IqaXSU7gg3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T18:33:20Z"
    mac: ENC[AES256_GCM,data:396OQYeV1MSv+4o7cPoiiN4tukVwb7tltvCzP9/aG1oErXNPmll7PzIJG4UfbNOq41q1jyAHma1RAFcWWjULSlr+GOPtNGIwnVxO6mWhfnEnWFiiLZCcgaxinduk0tBxOfdYHTRU00M7sO3aRMEjv2RWPMePcaxOCfspf4yvXvs=,iv:ob4o1wpc9GP70SrCMsn/X0fBbzZ/l9nrMb3ZZzLidQU=,tag:W+4ykcu3A2bn+6Dkt/pzlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
