apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: keycloak
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:Vp6FEFxpSJZGxvLmjgtNMUcKwyuKyFmuW7WQ+lR09s4CAcxCyUIFZimRoofQvUqAzlQMwFaIBHzkWSYiLyFeC3/wzBhEGP+E3Yl8j0A9CFiTocam9olspnkN8qgiRGxzXV4Jv5LTWmQlZwxvM/jKDhOko3SsM0PERGHGy0HKUbxBIdlLcXomNkLqEYVj7AYO/jFy7EzKw+zhYU8AW4esBmT526fAOgGI/oVl0oSKD1U+Yxq4JARHUa2iVU6C/JhQVicvc/sNW4pGbVgbJAojeHf1Ulc4G4+sp48gHm0510vLt/uyCVaJc3Zgs7s7KNtB3Fn2ZQGMYYqh9cp91X0WlxCAyL2g6qQqCrzumKac9rv+oOPaO9DaayDuajwwgAojOhjWD2NtfqdgNx/VYWHdAtRw9TAjMU5XfcZkSYExODqq3ajA4TJUh46gaPKrl+4xmoe2GqmhWJragiFuhZkoFEHY+oBMkoD9mq7cBOXw+Np/qwL2mpVQC7jZY0ctf4ghlLuboqQ9PKBnAhwSOBnhJG6eK0zPlj2qlRHvWtfDs8HoFLZnGmojeqbJu9HRDM+2mmxM0pkVLUHiOTodvoYmZJbrUJM9uODQ6IRDuXyem4tLnPrrcw5LAPl6jfsxDdTWPUzXul4s3NQ5Occvvv1W0vvQM+2qyhvT7c9tTIcvaJbADSYNMc9tRtakrdQKDc3L9LV1LleEsNjfLi369q7FkVa7f//TjGQ4ncDDG/0chqsMCCtuV5f79eCbo0pGFgwAJommGfMvGPczIRFVIQFcM4EI+T4OPBD6dOeSFcbacUwRqTvQzkAE0/KLgxE4XlFnWcVM49FM3FnuaHE=,iv:1iDj47QYERlMRlKjC7GfiYtppcHIWsh3dCInqk1ZgrE=,tag:iGhSARG3TUB4FKrfErMczw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNDduZCtvQTd1b1NFc1U1
            K3BFS3dURTh3RWNiUjVMTzdjRlRqVURrVjNRCmp4ZGhMMzNJTzZKWG14Szd3L2xV
            bmUwNklxZ3p0bjJCVy9rWVpQcFROYTAKLS0tIFJac21rTms4K3VueDE3UU56RVh6
            MFJKRWVDUjk0Y1NVRzB4TG13N1JJRDAKRJgAOouzUH/w+URV3znmkaaDrffi7RNb
            nwQHjKOj4Ny4PzZ1UtJza4//KilB8oEMpTU2GRR2L6bM3rZUNWKEBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdmhYRFdsZ3d0cFgzMEJR
            SkhkcVorT29zNTk5VVRaajd0QVo0Uk8zT2pZCmxmQW9sNVR0bDNZVUl2ZVdjeEU2
            eUdXNDZCdWxwSXhMME01UGd5NUZ2aEEKLS0tIDBvK1c4QktZUVNGSytBSFg4N05P
            Z29KNndjeTNSR0NCRWpqQWt0QUFzNTgKkkN0tAW0We8AeRW8FZkiOJrKTm/n6XDW
            nYuprokBT7kJ6zabsy/lYY8x4/MUgd6pqCAdi4oe2mmlSglDuN9p8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T15:16:15Z"
    mac: ENC[AES256_GCM,data:BdR5doFGfY2+O66b0vYsrjN0TGj3S+1AjySqcZj9bLI0Wos0sUEJ2hOc+0UVMR18D9Umi+2H++VxlzBYAUMu18rya+nYuxb6XwBqO6jTizU1BhUY19lXT9+wlx3b9TE95MSVs/W0lC2yUqZp+pf1j7SsJYDYLuh2i54D2Q3Ypzw=,iv:7ZIJ+rZ65RuRv9yJin2QeWNuXQ3myRYaluSQKy/iXhc=,tag:z/qA14IjRM9OvbMBzNPKrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
