apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: keycloak-system
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:drrhRK2RHCKuc03qjgq0mplpdVRSpHIniy7AyGbo4S3h6/HezGv3RknxyJPYSHnTYthpIFGmmZMDw06L0MyUxHxOnLPVNDFX/68Tc3Zvanln0hNejbbSJrF0Enl1LOOCP8WvH0aEmkzLy1PxuTheiNbxFJNn0e9Xe+d7jlPQSVzAhHC0sT6dySLCGiWmVz5i2/MuUUGQKE62qPR+cSBIgcoaITebsqDXLG2sWen/VggKupmf/BXN5C8DrITLkPNi+nHanDPiw3ot+pa/AkPmm2fzHmwhiCRC5QMxnaNtK42uRR6pXVXOutesy5vjPzVpj5y7Wqs3mR3FggIdEIjLX1v4gqV6cyXgct3l9F06JDi9zzlglc/FMxYz1w1DslWJlv0/nuJDmYyyV1V9UUo62EYCgILc6cf4aj8K3HWJ38NThjlaOfJgNPm6DkR7vpFRN2M43VObgBu/ie5ytoOubEHjzsnodw68gzEGlfbtH7HsxEzwZqS1Ic4RKhDDSSI44UQZU2gmqw7RDqSVZ/ujrFXWMzGkbKKuhV0hqqRE+6IargRfJkb4LZls8A+oO1Me4znbxYftvjQK2eobcQeVpRH3+AhFrMVbKXJflnpNydoRSVdqLycH7UsxpJXjHf4sMTAGzQ99aHrlgiE0nCrVJjUVcmEqCFhAwCMEWae8a1ozkDgvWzAOcBQGr8L1X74llWvRe8gSif7kaMugpzp0yGrtj4aV2g3/g8BpWYNV91/tNb3D0o632Ktgx3TYZBcgkL0fnOOXiUzudGutnXt8+YUisfRjJ5jUircfihipnKxCFpJ+Uw9pUKvTfJ3aoqPsc6IF3xJz2POO7AI=,iv:mFuET+1BDbnTeM9MnoYiMzzne+yO8kQgDIZKybkxd2E=,tag:6cR2etI9iE7tdgkUcw8+Eg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCemh2Z0tRZjZ0NjdaZ3pF
            UkhqS1dhT2RNSFR5L29ibGgvK2N1MmlBcFN3CnphNEFwVXZWcXhPTHJBQTArcS9o
            OTl2S2pJK25IdGgvVUJZYmhnRUxlOFEKLS0tIDVrWlhpVWZoeldSMXRVZlh6bnpm
            WmJoRy9lTjRydXBlN3VJSUpaUytFMGcKHbbwZcq2YQyHLslB/oTb1Xt5yLt9hhtI
            RorMG6Fr3/RDMCUDMVZdnzCJCNI1GhI3mEOOETPv4oRkk94Cjv1gwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReE50VHA2bUZQbERQV0NY
            WTl2ZExEdGNTYVJRaE9yRHZzditsR0t2UVg4ClJPVFlXVHdPR0dGQ2lnWlVHQVB4
            ZThjbkp3UnlucWx2dldoaFBMdDc1dlkKLS0tIFBoV0tKaDZMWGhuR3B1UWltcnlo
            aVlvNW5vUjVrMXFFMDJLeWEyd3FMdTAKq0YgkCmNiPbon0MNelSdmws2xD7SiGXt
            jty67CE68L2/ofNRhOJlvKT0Knsv7U1tkmyFh1VTJ8HVAS2YwWIiuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T15:25:40Z"
    mac: ENC[AES256_GCM,data:UEf6CqCyCzezVUOlW4Ys+vuhxwZAecak+rIKfLr0tY56PppT3jiQkyOgaQN4j8qKmFI2oF5iTTp5wPs0umCHCJQgsB0p/jGp38gzVBrGmGLSymAD1hZyDZ0q/VUVGrDqlxHihViXI18iRc1svQAPdWYq+2cYg5pYCmaQPGki0Gc=,iv:EmYAWQnGu1Nyx0QmjcMLyu3WDL5QeFq1BLHuNTWKfpU=,tag:P+V8uCX0DBvkp565jgHKQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
