apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-db
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:joOMsgINWgY=,iv:RPnzUYHy+KEIEntCr5AygyDEb0QO8CRpePFHnTAMyCA=,tag:uHU4vCcp/V/XdJZRWoJbiQ==,type:str]
    password: ENC[AES256_GCM,data:2lfsCgYo0Ro2PRGWXfnnV3TgpOrPQYo/VPEt8Tts5js=,iv:nBwCYY9kYNAa+UstJL3aFo0KnHfo5siaRSXxukpdFSY=,tag:Lx5IIgwN3cJ6hy+/w3b9aA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNjJnL3pMVFRqWE5wVGFa
            VGFkR0xrQ1ZnVmlsbEt1K1NKNWRKbDc1a1JBCmd3OW1ha3hZZndUZG1zVWpERjFT
            Y0M2Q0dBTFFOMEFUOTZwMFh6S0lxeTAKLS0tIGFPTUNMMnNMNWVMOXRzaUMxeklD
            c3hhTVkxNHV5ZE5KN3hoaEdaWHFVWlkKixpZlNwlxEL6g5CcEcAOLCrK4tToJVCi
            Diu12r8q6SUmsc+WlHmH52S/xkDhnWk23+5hiim1QuIC1CGZ9QKcPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR0pQaDhSczBsV0Y1UlNs
            SldjUmJVZXZ3TzFwNGJVWEVFbVUwVFdMTmlVCjNwcUdpNGtBdXNZdkNSMkkxUFc4
            c0E3V2g2VWQ3SFcyN0JYTjB6bVc5K0UKLS0tIGY0ZWNOQ2ltNGtLaXlzZjBxWUJu
            SnRyQVZ4OHZob3NzZ2JUVzlpNFI4aFkKYQ4ks6lJFvqKMwKXh/5cdwJS5O9Fndd9
            Z44aYARlfuP3Bst8B3nIruwtFpbK0sncLf2y9rzEkbFYF9CysQPFMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:22:53Z"
    mac: ENC[AES256_GCM,data:UGGS2qK53xMbEArRUfYTnzW32e9EErtOEk45bXfkigkmVRxK1vdRdK/pVqvROn/jTUBUdgGsH0yBLT217fA2I/FlAiBefkrN5PsAWXVowziT4it4wXj0vPV5Sky5ho+Ibip+hxdEfjNJGw9Fk/RS6oPOIwDJGsAkNR2/XoIT5N0=,iv:COmJOR4TDx/SpzSnM0Ax0wtFGcOhT2LxGoMYwEe5IrM=,tag:2IuzqRcrKHSJfao2ntZGnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
