apiVersion: v1
kind: Secret
metadata:
    name: forge-keycloak-admin
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vAx3DE8=,iv:AP792/xdGlSUxLpd6rostdwvLULfqNoZPl5Yxe+Ln2o=,tag:IFKHjIwvfqxoKdUYRvmIyg==,type:str]
    password: ENC[AES256_GCM,data:SatyqKx/wcSrleJtIf75xw==,iv:R4lpbW48pMgsAeRXCtwl4+LWye7+ntzr5XXXDj4bQwE=,tag:n1Kidwt4jZxDoOdaUKv30w==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVW5qZm1aY3pyTHdPODZm
            NVh3azViMUg3WmxRTCt5dktRZEVRUXlvelhnCkt5ZHVIV0tvTzFEdXh2akM2ankw
            U0VnK2NIa2pycWNnNEtvTXNzb2YxZDgKLS0tIFVNNCtoT2RFZ3NFaUlnRGZ2SmJ2
            TzYzUmtHamQ2VXdGWXpiNzFmVk0vZ1kK6p11Z0+z5kRd3K3Pcr2ATM4+PlLze5IK
            QfRBhodcDVKlmTyQAOyxHjt+XrgPVXyy0w//tmD93Il6aL9TP8TW2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d0pvNG5qYW4xM3NrWm83
            cTR1amhGTDZ2dkFxZkprZVlvNEhKOVNRd0U0CnU5OUwrMTUwTWRmNnlwN21kMkZy
            TWVpRFk4Z2JDV3ZNcXVVRSszTVd1RTgKLS0tIEF4WlZyMU52MVJKZGVUVFAwUDVN
            NGdKVjlwd3lHWklvUUhnWll0UW5FWjgKYeoEechKW3ATxrjOVlaqYkNJmkIuA3Lw
            KRzxfqxp+IQYNoy115FnQusUY5ZPnmbkCEywPPJ4pezRNGsO+jyOtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:22:54Z"
    mac: ENC[AES256_GCM,data:GceHpKIuP6CLotLUZ8OgRj8VzWvgxhAzlD9XiQLxv8THae75SyTIZ8V/TLCwhgBR0xqatxJ4vMM1C3QmwWQn0tyCihc13yVoFuJlSMm29BrOd30oim8pRK87QrjuX/bFBQ1ScZ/7rLGrE7cEG4FbRdqqkpDQMQj6R6dqSKlgl8Y=,iv:hiKtP72MHudR+zPK4T8Z9CKL5sTM0W9vJxbRPsYC0CU=,tag:omIE4SHolK3lTRzJOdt/ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
