apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: keycloak-system
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:Fq8u0j4tPDffte/UmEg3ZykCbaaIH/S4FvWZqXr/TyUt6KK2WHBXv2rPzi3NTDZzO6OOx8wQOjcLVnWXCqT4R2WOxn1tXLYENPq1/vMBZO1mC5bF+ezyhlX2g/oa6kB5sQnM/fy5JThUNFMd38oz6YMVP+eH0h+eIjwGEQKQW56C9rk8LrRA9g5A3o1U633eKwKyn8CB/3gHN5zl9eqGAfiFVkupXFW0BtISVMOpibbl3CHzb5Gw2IQ1AQcvXFD+7uDpmpORiY1GkG8weL25eD2N9uO/MygXlAy4X95zzumWi/0oGsVmt91IpraYyTZlZjoeycmFSNK9DUFeiP5dVfXvhcAZ7HH9T+3Ss+EXmKIaa3sGY2lFxvj8HK6ziaE/fgq2k5WcTTNaC+dev6W6xWYyAkD5J6SBHf0nd/RHGxZbrLgKJlREl54HUVvM41etGbiKhk37szrn7J9T2Ap9A4D8QgE7F1Du8+d8Svd25cnJKLlFZw5d6HPBoGSvh2ZDWG+i+qJ5xmJVHF/DchrhnhmGjzvp9Vievoo7Hwt4keipe+A62gu8jlC6gHPucngTLxCmcndHRa6GLJngi6gcr5A/jyBTdAZ+LT/WAXo55MvS9vW8AK/fAL9MoKSkqfYTru3uqt+FsJvbaS20HpFhPnB4OQU7iFks3aYCagBKIUKD9Oi5uN4ygohrMxve+vOMxjRmiBSBWxbNKuD5z01svvxrStDW86/Ua5S0bX0LY99LQngBeW5U7oag2zhZba3DFsg4OqcnUrQLWVn/9ihvnsJ21mc/ptUAxKHXU+/espiETobGy1G9HKrJr2NHLhTs1VKESmCLi5+oyfSeDbFydrzK7V5ZZnw0BAX+KhHJBTAr5jmEYMUJAA==,iv:2KPZzj3roUHoCci4hxsDc3qVC6wAhiRYa4IHjFSwo4k=,tag:cV230sj6Mwho44i4ZIf0Jg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN0EwZFB1Mm9GR0JzR29u
            bHdkbjZuU2t1dldPV04zN1VHRVVQelFHVGk0ClZOWC9WTVlnUjh1Zm10T1Y1VHBH
            ODVRMmo3SUdXd0NxdjhSSTVBRFNtbmsKLS0tIEdEVFVBREZYU0lyc0xIUTh2L0dm
            bmdQczAzU2hLbmhyUlY1VW5rclFrNlEKxjlrZEwvVCCYP/MoyEk+hqNlYQvTS9D6
            jFDTr9dxXcqN87pfZzmZ+PmQklk+TW23sWVyVjeMIFRuoov9Tw4Izw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSjdsMUlYL3pocVhLUG00
            ditiZG5pc1YrVitEMkpsTG5qZFg0K1NiSmtRCjFzcnNuM0Z6dEVBNC9mT3VQRWtp
            SXNWcUNzT0ZLV3kzcGpCUk4wcVdydDAKLS0tIDkxMVE2V2RhV05kdDVuc2V3Tmlq
            NEFJbWNFczRxSFFadEZqVTg0bEtpcVUK+VaMi7EQ4NToamfq3J9IMuszR2DotXuR
            fE3Vcje5+Jmafc3puR1rdIz8IPIlG02q5TSjOXl71yasvzYqZqDrug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:05Z"
    mac: ENC[AES256_GCM,data:RTSH6VSI2PlpOrUhbzEx73xw6mHvuzP7YaZI9s/U+e2XTm0dQSvQOxH/1q/HogELYqI9ol7/I0L+YQFPJNJsJJ/7EfOwsCTpG65hS4itZx0+TBjBnQ/zCQODcVXO7Sz2JX9A8D7SlHjjlRcqWjYNRj71AiMv9fTb3IrfLjEQVvs=,iv:/PttqU9Qjxn8R/+cGhJ8yApaBmEhK/i4pfI8nAXYe5I=,tag:WCHihtzbElS0mrIslAvZsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
