apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: step-ca
type: Opaque
stringData:
    root_ca.crt: ENC[AES256_GCM,data:p2/LaTLhKqM/ckplISjAU7KV0Gmchbqa998fZg/YEzKXB6pOyHQ3WZ722v4WpZnknTGsEouMr0du8EXhi17FX3E2CS+w/eNoUi+JOsDdDYkm97LQ0s2yiQ/5ng4our4k6c9hs6QEbuaFTaKnoBlD3089eFapDuTPUAWIr8r+8qnV6tyTucyHQwKfPSt58L+BQlgFFeawVDTFZx572NP/wPv9dqyRxXaW+qtGZo58YmlmuXdATJaNnAq/uRcc0URai7StL4w7kgTMkHrzSn88wfja8FRLfGB+VBS/295jEG/lm4G3iZQTgMwHY7H1uPzqFyyzRm1oGi6trWTX2DJf1lz0nBnD58q85W6zYy3TZyYMSwW1tpD236srmqFWu40hGwRnVR1WzPXkTnDcFG4RZV6Cqnk9JxX1mLhrkTag6oElZaO2XUSAsxS/dl023gAS7UAYPUGdfZKUHFNAgjMfMoCDSNRqrLtw4VZx82S/X/y70LFNmN1w+cUDRNXKdjLuLB2Mwx4/2e2JM6gj0JnldbCwydn3vBy4nlJ+Nfu7bMDyk9PJZcFDrSYLAc74vMJXBAWPvVaJeqdkbty1UG8wcPtD4BDJEu9p7YxFFHFQvZmsa/ORKnc5DHF0ljxZt2CMiNDtCFz+QzRPBR3bAzoc8EB4K3PL5rir8bBxjaT5Uiz7NEG0glx2i868vJSubOkNcDUeD5r4sD9YXE/ci8YOcG6M16XIIHlW4QbjBkoyhpw43DzQuQMfEVeqQT//DchIn971O5nst9u3Wj3zr6XEDlgsaHWwC91/YBmQSppbEoO5JQQuq9+KNz6svRG4E8jsoAC2x3Gdzi5Grj4=,iv:GHI+lETzn2tK3W8IR+ybLmhe1X1bMyKI32W5twnI7Rs=,tag:vaC+YS4UALEfP4v1E/1CHA==,type:str]
    root_ca.key: ENC[AES256_GCM,data:kXYkMAnKFfQ2TNdLtIDDUaSSGILORRIu1j4cVKx0NiOj6goF+BIF3R8prOCRXhywAFeXCaOvQwMRMpRTzBfJaAKmL3ZgT1lI2azfgnNMLSaFm8hWQL0lHald7wWuxBhVJy0ABNSzROBvQ3Libr2WYl362ySdvg14JWopFw8Zp+oigyTUEINbU44xq+AHZ1cl5lggWcAcKQyvXaMucyCnakb05HnenmCk0GmXdqqyPAlAGClJ9SYRtlGq5/NP0YvWix2qu7be5nZCuyx7yIR4g56Jz6l8RmX9TXpJ6Rq4HAUUUPx9x3LN13Cd8ySBw7qBhQ==,iv:Ij3Anlk5foVwGagnl4rMDSFsZDvYwIgxjZnr0T4Xh3I=,tag:xTWPrTxlVbo514HCnobbzA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVk1BMk1ZRWtzWk1sMnJk
            TnQ2dFNOaHhidGdDRmpvRTBmdTlzbFBqdDB3CkMvb0VzUmNYR1ZFYzZmZlJUVk5j
            T3VuZEhocGU3YmlnSTlTMTlabGFFWWMKLS0tIFM2eDlJTEUvU3hyaXZFSXg4RGkr
            aGs2NW5rdmNpOTQ4ejdDL0RFN25hRE0KvZQ32Omh4YN+siYqFfsTEh1TB+jP4KU7
            c46nwMfewBN0j4kYYfFcMm1xsG5cLQkqgv6B3OysxrXrMx44IQksHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T11:56:40Z"
    mac: ENC[AES256_GCM,data:SHRWMbUKuAuFUdWgiCO54j5Inz1O/FCi/ZROf9PTBUCsM2xQBsnYe/vSe2DtMkF1SQm1diKedoUnbIvl48oc+ykwX6VgjOFAgpWf17kZNFOAEumq2l0jTsF6J8bOBFnU3UpfxA2JB5tercvAKNNPp2iMz1NiNzrltW/WHovudwA=,iv:RnItLHhMPPhVLiDC2BdfNqIwrXQl/J4rb5OV8UCxvqQ=,tag:deZwrJD1owgo6LR9duSOYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
