apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: step-ca
type: Opaque
stringData:
    root_ca.crt: ENC[AES256_GCM,data:AIpIoBEfFtkyBUAucbpUV1Q1g5rYvap1cTqc9CnPJYJkrWnvbenfDZxaxrKaD8Z7xmBGuvsw0ym9lLTofMHjyEjYh6r+7lkhHqSK2HCKpuTwfUC2OnC8PDHJVEY7nn7SscDYxPaI/B6SnhSuTWS/bhHUZs9lDFnPv8b3ZDR7KMSiU+t+S4VEoF2UnZ6T7oDzG7mRQQSH21/3M2WPl21XOk4KPMbDobTE5YCCnYDo1VvAVdTzf+S3htgJpo82NML4e2tPiA6Cxed5IMirYn++Suxe2bvn1fmlkoM2twCbnrZa/HYbkWe587PGiscXujBd/cFUZSmiZOn678IOeS6ZY5/Qlmf3CNdc/fyPgE1RuFFJnAiy1TI6ZkrJ9gqOfUnSDpWpmuADvgHdkNoHf87zyjh/OKQEltU9fZCKUeZqItRFJ5Q77rWFbs3YUwi3mZEXxD07Kweu2NeWRZg55WN/iMw/eb/2X89+dzxG6chtEk30oA30JutjNDu10BnYUofNjN+6gjZst067Vv+bhnTP9HOfEurDGJFZyemXjAqoAdIbyt/5bWaD8x5EA+kEUciG1WnXxK4Vm603y1+vUPGuQHapqV+hFVSlKNEKEBD2vaK6hZ49eCHYAaE+49UgDVzjWgpMBWxD2QvxIl495ohBVX4Pp3nW92fB+1GU7Y8+BpcgcWJczPQoe4XPlEr9ydt1zWUiQNoZPTBVU7KfSZ0iU8Zebpk/omE3e6OdaIpm7NqQPycFI9lO5OnxD8RIPbKND79vay7mp+teAc7+61F7lxOkEM1kTpwmaF3LimnYBQ5pXwLwWIRbbLch9gB8Desqd9rpasmJVT7YQ4A=,iv:+dL9kl+8u3zcpd8MkLdD1JPT1TuFZxtUKG/ERrBFMrE=,tag:SE7APyEhM1GX/iHc4P87Aw==,type:str]
    root_ca.key: ENC[AES256_GCM,data:o1WiI/JLMhv9k64HpK1dTdQB2DgmDAUKUKs+29e3a1rK0bCulwSn9pziyVb9EBzXV4wjz7Q105i0yTOcm5I4Nkse1rSrxgjeBsh6/sqAyc2i8eT8mk+AGHcLI1kWApTUUhSkSoFioTHuiLfIhPHT05U344RZw1P1UDc/DxK09/Sc5KarGt8jq0y+Lqf3JGgS+cAxzlxae613bFGzkkK1VhSTKfd3eqTWGtFKaCUFnhdsYEdQ03rUjHOVmAwD0dJSukD98CsNb8I3WcSlb9aqDyiFH7EmuXXrStRrRu40saKl7qeoRlstYPIpn6CHa1vAxw==,iv:3Zmxm+0yHJ9Grqr1Pw0Erv4idWsrMXwknV91Na7wfkc=,tag:M4MTISGKfo0tYMMNFkwtJw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN1lWdEtDN29jMlJRa3Vs
            eWFYM1JMOVpQR2RWeFF4Q2NtakJjZVQ0OVhRCnVQamhYQ1RlUjZuSjAydmM5TGV6
            YUt5MFlzY2F4WEo2WU5DZWNvN1l0cncKLS0tIC9WYnliSnVsSVY1bWRNTlZ4SEFF
            NUdhWWFLbDBkNjVtbCtrOWRHcDJwcjgKYfARLk7scvsGI25q8FUggJo4TzE2uAnt
            m/FKkwCcWUKxx/p9ymY0fqK0joksx7baw7rLkY8ixvnuE13YU35lGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T14:18:58Z"
    mac: ENC[AES256_GCM,data:jb/BaHk99eeXGSue6WpObls8RNb/zanLNHkdtXOS7lcz1opEQBGemdpsZGBmzMSfoz2a7JZpP1zEKfKhyWhRagr/6Oz48rMaoxzrGTWycUI/Oh4UzAWXz38oHhmQJrFYRMTTdIQNzRM/pBt72WkRNC5tOBR3NisItggIDXG9cXs=,iv:5SGc6/VoDk2TONfLqeH8c6uBR5QghLOuBv+q+zGge2Y=,tag:H3y1wjWhl9D+7xU0Kw032w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
