apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: rabbitmq-secret-generator
  annotations:
    config.kubernetes.io/function:
      exec:
        path: ksops
files:
  - step-ca-root-ca.enc.yaml
