apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: rabbitmq
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:AELS/R32F/53hilpSf2XhbUbELvndG31v3n0FrgWPAsLBg3jnvmnJh0Iyk2QhJl6r6riUisrj7j24/KvHmN7/2kAwvdf5+LC0L2ssBB4Q3SAvMD8B8JHJDbXp7xvk7WrM7x1YyMEOuFT1ME547ndUd7ijv9iKuAyDzFIw5StO05RW4fgmzSidEAhYErcMVr6RoyVHnVXjjDhUHPk0MakwdA0+ERiK+vS3/sx6dNw0Gk0Ib+8t6CuKlPeUiBWiq8ZOl5EIeGsykGCsdMMHUw2JlUPEaUjTu48H9VyXrLOz53hIKM5JIyeweqTgcZ/sqOzn0nFaa/7+4CC1K/G85prH9pRYRyxc9vsN3V8Ct7whpLGxNiqvoo/5ycnMF27jtL9fTyxLvPkZGhD+Km8pY7YGVtAUBF+KtiYrGlXhn98NOjM9ftASxSvv3h4bF7HSQ3EGLefEP8e1AQH6IWXF41tDbn9AaQv9FOW5cECU3RXdKKRc0j7Zya78JHjcDWbIdDEUKKRl3AHqp8Y6gXXRVTg+JzfOMP+2JlMhr6Q+vGlDSPlK5o6bn1BD/9qY66ohAyHtIsYp7x0ya5rpi5xyRKdHGVpkMHXbJs1Xx2Zp9Uw/ZLVYWBsqx0lF6UcvPihd8KGLFxXXzOS1tREtG8i079xylIWamgBjX0HlDNOnFpv19hQ33+0IRnmwlFOkQndmv42MTXeC4aVn6orfa7ZI7axU4MEONlv+fSQ9X17V2CtP2DyspZ/Lsq004aMo+b6SOal/F8N2SxTZz/3vIhg60571ynC5rtiv1YI+gwmiTnK2qBjHa8iuUrOqkuY/J99pmM3rjOcHFOyEkJCZl0=,iv:oyx/zNbzoAoQb8NYql50Uslm7CXW4f+7k3cFX2be1NM=,tag:2zjjl9yoBkr1gxCJ2JkXTg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdlF3dVZNaDFHbzJvckpr
            R1hXcnVHQVVvR20vdHArQlV6NnJ6endKNUgwCkI4N0dORDdvcFQ1b0RSdHhwcTlE
            MlEwcjVCQWFUR1VLeEMyMjJwSmFwNFEKLS0tIGtPMnZIbktUbHhZeDF4amJVQ3h0
            ZkZJaVh5d2hMc2JxRVVINFhtazZkaTAK8HF3Pkb3RWGy9dYaKlY0xsYoBWI9/DhO
            9YcHyn10MjGlweNrZnYS0TZvbtAJOrNMJaD7po72kiAjxu5tFrcSQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZldmYWhzS3FKM0V6ZEJ5
            SEYxRkZpRVhZc3czL2lWclBuekJYNXVObkFVCksxVmR3NDNXS21iWUlhanpVWk1Z
            bTVTRWptZFp4SzdKYUVrZmVOUEoyOHcKLS0tIHdOZjR4aTFxbENHVGlCQjg5RExJ
            QjZDOE9pcTNHWXNtdVl3NHNiR1ZxaUUK74SJnTjs22+Tn+DKKE3haXR9xHxkTqkE
            pNz6mG3Fugea4ZtWdD6GgNDKWWf/4UL7AwqBZJuVJHboJzLZVsX2Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T01:57:00Z"
    mac: ENC[AES256_GCM,data:09dwz/zltAa1MpSEfb2oM26q/CGl0vKWXOGStAFhn8k/e4ZV7jf4xMrrRl+N5//Md7SOQQJfiX0dq8yUZgtMFII18X5lN7bWNX/YHGd/HGp8+L/4AIeK6eFyohOAqVx9+qbsOAlsbxYl6mWchRgxWro4oTmO9J4J5ClUP9KV0mI=,iv:c8rAoVwXCXvsTFEB8E9XaonxS/KWO74Ke9iyLyiv9VE=,tag:bixSmxDpLmPct8rmQzJrzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
