apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: rabbitmq
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:K/Rn1RzoLupyodqVtDAoNn2ZHXSEVfWtgW7RoctHIHgm63U4Ve+iI2sdiVYjsIdAt8ngYS648fQ90yejzFEAMMfDhblm0y0RML8ganWDxrQo+6ypJtRlwmOyYY+RXD9KOGQmJtUr84oWplpH0+Zn2Yblm1jHV27dOTuoaWGkcwuqVSfRB3eLLE6JFTbjj34jD9FmRKwvCG8IqXsZ37+f7JSPho5cc4ypk8g7qSoZJHY8mNfms7ApeLkAECM7YJKyuPOy44HMg9rGXfpkUK2gBgIoa0IcJcLs7LuRRzy396sWwro8zq5BRTU7b8/06I7XJzHi1LrBc6qM4iD9VN9oiv5ubJE0VgwPZuieAKviDww/gmrZJhAcfedlYntATVP4kAaqqXy37ReRUN+SRiaxueMFWCFeJXPszKvpACQcfX2sRpy4rcwq7Ar7BlvBlxNuK1nEe9RW2sPYMTNNp21r4jFIxthuOJ2fyTp7wTCFp5fq38sciQrlxDM0OKsw1DJ14WFLumo+QTD4CH+My99OeHWWHZbjkcBMd6hTPwpwdrctMVOrgKFj5FRWy8Cji68NV6RzodsEe96HjTQpT7VhwaRPZaSKxAn2zMqp9R15By7zjAkRotuhxC3g5wZBJGb39ASs7Y2aCmecc7cKvpHfBda3O5RU03BPwFwp19l0pT1JbalK3X0DoukguKjg0lXE8nySt0dnDZoadb2b4CXC8XbfYJGweE3KC6pc+AZy8XrcaFddbbtddZ5u+PJgg+z5jKJwWYTYlrHTNRdJxCCo3kKPRn66TBgzPm5gUqJcrgwiY9K3LtJvxRyThthfTFfyAA5VAP/K0taVSlg=,iv:QeLw3QQj2aQrt63e7FQ97DnDSueXI6JvRNoQC5H+17E=,tag:h9c/uXybXEi1QefG7iAj3A==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMzBIcWxiUjlKcHYwUm5r
            d2RBV1NTOHlyZ0V2UWJEazh4ekxiR3dKd2xjCmVYZmhHNjIvdUsvdE1MaE5RamZs
            dERoUlB2RDQ4K002ajFFQmZNbFdEU1UKLS0tIEpzMzFDQWh6OWxxa0pzcllKa1Nn
            UTRtVVdiMVJ5U1hBbElRM0Z2WHdpS3MK0Tz/bmMPWpxwAQhc+DMrk2pmVwrZkgN1
            sBxVCbL9D50dZwtsMnWxy/YMPlnnV9dFw8DvPhMqCd3pgfscj8zI+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOWRwS0VYTVpwNnc1b1pr
            bXlMTnBkR3JEdURaZ1dxTjJ4VTRHUGk3aXpJCkVWUHBrMjdVSmJ3TkF2bXJXdWtE
            KytOeHFGa2V4a2RrUmRtd3FCbmFCRVkKLS0tIDY2dkpUSXM0Y2dlVnMzM0pKMXJB
            OWtTUkFsWGhpRE56WkpMZ1l3RWJXemcKtjdMYbuzLY2wCKYaDcUQtO59TgIQ2eRC
            BqH3xT6pZgDY96GUr4XNmfgqtqQqbaRT0we324NpCtNsYhPxTnfFjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:55:43Z"
    mac: ENC[AES256_GCM,data:/11fsJfY935tf7exKKam/qpeP1bB45UVwkjaRCLRPSCdDyMTzE6cfjprA48UWLJLtQRZmYd/PK+xjlPanp1t3fOgM/3QZNiokfJvG2WOtZQFwndC8oWMszcd2+Qp/xemoS6CHfumzlRnNuorPZ7TzmdYXas8IJzPQXiduAI+ipg=,iv:+HI67AYtz1+sWJPaCK8zX1hZ2ihy0DwTheYHJi4ciEs=,tag:zt1bnrpfwfn92dO2u9jq1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
