apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: rabbitmq
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:TO4JCao5zhb9kS7TLXl4TZ56ecKxDL69fXYFtWUTbxP+WnrUfkGvjwJ88LVWa3dIUbHFC9QVl4RlWkeOmiT3fAGIsnThNQRZFmn2k4dWae6qYERqbG5vDv8+PPJdTtk06onDHlAF+n+ytsTOQAE/2DgUE/cV8uUGbJY0aKOjTbtzhzrP8BV+J5MUZ3YQhFkvYud7VOFeawhyPgXvTCpRSw+O+ajpVeps5agOOAkdxeopBuGVANWyVR8qvxTHu2PDjBI8YK35fxerN8LSg8nn2Ox3fHoeKOmbxi+lynN+/ihmdZNeVmze2zXyOgfc8L8CA9ZsWvBQRrYrGavzxzHZ6Lx46BfGpWi6/Rvuvl4Vk8yaB3gNtRtf6Gt8lL6W0QPPtldjjhbqQJ8vU4rCtiu4ynaF9QgU126zgFlsrBKe1COz600ZFHnzKxP4jvIiAi/OK3NmC/ibanzsBlsh7gOD3bsdIGgNoJcMyGKwXQQT1ZN14M3D0q+IF2SsXmIwB/AFjsqk1bBJS/FP/1vGeINv/OHnwk618PR8M9dw5KIVhE22c6GqPsUDml2gRU8vcBDEno/gR2lazhQCKKJNcR5SxaxAs12kL+evwUt8+B/DzVKwZaJrwOJM60Oy64fXNJ2yHDqBqRvDBYBHj3ubaY+H8fBTEz1cQr+kdiAHiDbCeQlKguuHYAeacufZ7FC30KkZpXc8vJ9RxE8qejM/JHM7PnLxy6zFoskHA9ii+WPAu9A6uhaWysbO05NBj27Jx7ne9xqzRgymbxWKBKbwkCkJVW7qkF9w2IHfWvF7bMoeVgJXv4YcLruXx/Bc4nNn+gZHqiVc2PWMTY1/n5Q=,iv:1r/El0UJ1xB+9SLvzFJeQmcO65qeBPPbZxAKUSs7zhM=,tag:YuUN9ryFF8y6+nd9Chqr2g==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdWFHNnBjZW5nQmIzeG1B
            Yjh3UTNTY1gyQmZPZXNnSlQ0a05NUzdIYkhRCkZkS1hNdGNEanJZUHdXckRsNThG
            QS9FUDFDa2RZcllKZ2h5SnM3LzBhTkUKLS0tIGhTem9HNmh1ckhkZVE3UTEvT1Bl
            OFNlcGlBM2ZSQlJvNU9yQXlEQ1FqZFUKo24Bnrvj2XK+OSfrD2/WCAgvX/h4KBz9
            2oyJVJuTkvooB2SQd0yfStCkwMHQeoAI8VDcXboAs5hmlckT+mPL5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUC9LNEVmendQSHRieXp4
            Y1NIeDgySzN5a0V0SjRpSXNtd0hFTHBYM1NNCkNUdlpKV25jeGhKS2V3Tm15clZW
            anNVSzNIOEVkK0pocThJa2FSQ2VQL1UKLS0tIGtUYTVxdk9YTXVUejNYQko3RjFU
            Nm5EZ3dDL0pGSXNwRnhJbHdwRUExYjQKqmGp2vkBw10+jLhs5lX/3jh4D88v+Tfk
            nwLvNS7eJya91yUzLmMdqHFhxDRFcOyJ5+1XIfcLkyVk0rIGkZYTtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:18:57Z"
    mac: ENC[AES256_GCM,data:KKk1gI/MqA91rt2zKaR+97KS9q7M26pyu4Y5EYSCX0JB5dQnDB/6reUoJHm4GUv9lzdd5OeJF8U3hghfpCMh6WKVZp/NZx3WzsONDLvcyAZhVYmtL3MWVb8nEhcXDg8LL+YW01Yghrhb1Y/bQrnh6VmDN8CuU+h56ekw6ON4Kbs=,iv:YF8WjKmV/c8Tq9e7s77FdKyx95+NcuqU+FwYVB5UzAI=,tag:Zme9SheQphEL1borkSOmZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
