apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:LzvRuy5Pi/obJkL8Zc2JsgqQIUdKp/VIpaB3+xbLac8=,iv:NW0CFRNq0NcmcXzhLNLDOrMnQmUDQ6JeLA1h7IvoywY=,tag:WOaCUVoddMPowNOpea4fcw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UmN0bkhQanJmTVZtRzNC
            VzhBcHAyVC9IOWFzVEtWZVQ2cmkvN2xvWWtJCm9RZ2ljQTFVVGVuTUpmS081S2Ji
            RjNKVmVIdWFXSFYvMjBnSm11VnBpUmcKLS0tIEttTEw2ZndNWmV6eXpJdFhpbXJI
            b2JKbzFxUDNWL3R6YkdnQlpWL0hOdDQK4G0obmzUYoDGpTFtPgxIEGFDaqeA+cdg
            XdrrVAjSGOi2s5XGzevQfiKbb73uC0z8PeRjxWpyS/Ny0SRUuKmLpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSXdIU25nK3Rwa214dU1E
            ZWNCUG5YODlIcnIzVWpnZHZzRm92QzV4N2xZCmdJNnJpRzQyWVlDSUN3SmJZM0dY
            UWFtN0pJOGtSNnVFT3dzcXRWMTFYUU0KLS0tIHVET2JEZHJidCt1ekZXVEhLUjdL
            Y1lWNk9GK2M2TkhodTFXNTR1RTdtY0EK6nPnO/wq4SeFZhyB5o7NAJrwEmT1Au++
            O86MOX6PdZNHQ/Og+bE6gBP/YdYdqKJSvfUUuClqsxUJBEHzkLBdTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T21:31:47Z"
    mac: ENC[AES256_GCM,data:+UgbP/tbtcEF+CBqmHQZ0X4JgMnRMuCVn8IFc5lA8eWawx1KSBcOl7sHs/k5asKiLDMLUlgh9Dj3+sh2MzsuWRfZ8VzpgUdbfIUcPIdvSAQamsdZLF0ZHFuB97BP/3zJ9p6CGvaW5swJuJC3gGQD7scA6MT0GGuIaL46cMNsl2k=,iv:DSNQx0pqvHo+rR8+woZbOaOvEWTgI5Fv555t0z+th7E=,tag:iTBtss0jIh3ji0gkY0tu1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
