apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:S28R+G+3bkOOU0IMUP9fEt6edbC1oX6gdtaYQdK9GrM=,iv:4OqZbWMsEBJUcWsa61ynO4T7IXaR8Uy/ThpKNM3iwkI=,tag:prZ82hnAbFfAVPHgtoXqJQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eDlFVFdTeVZ3YWZ4bHAx
            WjJkSzFFazZNdjVjZEVveU1HR1BnaUFVaW1JCk13TTlrV3ZNVVBDWG8xOFJBc3BI
            c2hvL3gzWUNBNXB5Wm00cUI2WXB4eDQKLS0tIFFJSXVlWDg4NUtXWDBWajdIYlh5
            ZTlnS3ZORGZCelJJcXhtcVNtZFNJNlkK5H2kpfEqrI4UPgtV8g04oPFPJyorVgg6
            JSNAOYh/moObSWJvtnpDdOmoBt/DG/kyeWRUR4vMgL1B7Xhhotlaog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSjYwd1hwMEl3NGMvbC9a
            RDE4bjZ3eHF0RU9SQlJENTB2YlExVTFSL21RCm5zNWpwMDBrQjRzaWtJSjdNNTBo
            YTBlc2ozTmdORStCQWtFRTB4Mld0aVEKLS0tIDN3ZTNFeG85aHNkNXZ4YXhQQ3dr
            Wk1lUkh5NVhyK0xFbkUxWUcvSGZyQ2MKHLqxJRj9zqNtBY53HDgThh4zHm2PxFca
            MQ6H2vLPYRHHJ6UhIjvVrgxkTZoKSpdWCsFELWpORyNAJBu6MXLzew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T01:57:02Z"
    mac: ENC[AES256_GCM,data:eZ53TFWkYA+J1c8gu766zpSP05Iyfz+IylMldnMi2MpWJXMxB5JpPuBBSA1lHzfqxgD9dRWoQiRJseUTJCv3UGemRPhi83GjFup5voNGalRzhYOPgdrJMKL07bg5rAURVQKl2xq9cnRSLdc6hCArHwdrW+3hdrr63fAtoWQ4M38=,iv:cm3dmsPz8vLBC5rnyFNLWye42Q9z5to/JQAAX50EVr4=,tag:Cki2w9cQvrbghcsJptiW5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
