apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:XEXjrodtKGWH/TeA2svfLw7FFYpGTmjoeSHBV5KfqCU=,iv:mCVc3pvJbNsHKniizWe37hwO0HA019N5P9zLcXczfV0=,tag:oxVUulmSHbXZlHAR2VbIqw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS0Jwc0R5Mk10aWl6YWp2
            dytDYmpUcGRwNmt0c05nWFJJb3RCSXVpTkZFCnBZbGtnaXZ6ZkhFazNIU05qT3Qr
            dVNiUk0vbTRpYm4vOG5nSk01dElCWTgKLS0tIDBDVEpselNEZDN5d2h1MUZ5bHc3
            dmVkWmNYd2FnbDdHNkV4dHNoMEl6dkUKE6234JgZwzLa1fui2sK9fmJFEj4hXQTL
            36BVczXM5Sgryv0t6FsCua0AnUpdtJI6dMlMdx90/fGQ+I1Op0zEUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsT3F6YlkvOFFTSlZtdTFV
            R2JGOWxGSTRWNEpsWUN5YmtJSVJKRXJURjJFCjZmbzNOQ1hCeEZOeE5zME4wWGMr
            Z2dydENycVZCMUlDc3pPRHlOVy9uM00KLS0tIGozendMREliZmlKbXF3T1dOdXNi
            bmlqdzdiN09nVFZlem1zL2x6NkZsUTQKn4EDnyMkYjK6bWfGyYgr8uElYIzy6Cuc
            Xj2BMKMHcgHGgi9iJk9kGPRpcbOcqpb8lBXPJHgTmT5OpBb6RZDfng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T20:31:51Z"
    mac: ENC[AES256_GCM,data:cGzgh2AhltEyS7V7sDm12LPmupHO94K8ed9pFnDBw7V1pUVzl576qZDjwI1GrU4Tv+4dRG3IAseps53oMmSq/bUovKRViW7Wtre3n/OKzTLrIW+aa9GN/xynMFzOSdnIdonE6rovp4EGZeRdbhsrIkM4V1GyzvP/1kj+87DAth0=,iv:xjVrJAVbRq37hHIgEmqfG6CTtDdV9pyF3yzVAOQ8AlA=,tag:odQSUZpVQ44tAovbor8VHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
