apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: redis
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:XoCST8D02E99pzTa98nttLnngOfWpkzdbwUiHSn+9rxRaF/dxuwAHTTmsNDUjmLrYHWZUbnlNao3bx+kOomb7AM3QsH5PXfdOUxcebKFp5Ikcch3h5neCs+BG67tK7yoSWUV1Tmdm3MeJ9qSc5hE5iXE5W22ZErjR5gBwA1diZ0zKFjRL2dqzrZ7fYV0vv/S71sfEWILdkT0rfA2xUaEY3Pe3ZBKnXJNbkKQEDE9XJ9b8aDcs93NI9YVTgcUa0cjj6CJ078XG67NbFFQSWrqeRCK+G1f0SwjIS0KJs+BGAbKbqZ2Fx6NLKfMmeNjLeHObEdWgc+xwW90r5n50al5nOGnfb1WcT6b/8edx2KV3CfFtrrknCRnQcNyw7DX+TgdCd5GK4UBiqBHbRQyvDPUWw36iGKLzpIAXXtgvUke78I/jk+k+B2Nf2tYtik7ZPWQldGomKqKa5V+6nBSJ0mC4Yqh4x7MKJbZj40o79MHRdQNgVu7dzHUJZw0BwbbZMs/e21SpyIIIPhSTanoisBGMowpYemo7Hl3br/vdSLEFCotgf/Hqs6WKOndYiAVlWiTuGpL2tDojHgArw38srkL463tgee7ElOeztmF5GXHBSK458hxEjmd3foZfzDx5ocsWWeuMmWJSIeWpl9ZQkN+926tY3lr/xXz6cPyKRFQbTre3/vvOtxd7D/p0S/gZ/KFf8R+KwUI6iTt02byZPnpgW/9QCR8JHYmUlJPa+53Q/EkTSiJ1eCD4rKumeMbSI9uKEmKJK0L4mh/Q7+jQpSNPCXCsfnssP4f+yRZabP8zkJhmZ647In149O/AdnCPOlyMt9tjr+V00vWfXE=,iv:OWeQphYfH+Ul9VZUR24gUpixfWZ+hgMbL2Fv+tozaTY=,tag:HwpO+FivM/txTO0MjVY8QA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VWVSc2VmNHFFVWJsMUc2
            ZGdkVEJiT2lMTm1iRUtjRHZ0NFlKdGJpeVd3CmNqUzQ4SXdRRUd1QTJpdXpMaXFy
            cjM1bUhPZENvNFFPVzBPdmQwSlRpaXcKLS0tIFhybTBkazUzeDBkdUw3UWtRMk1N
            VjRNOEE4YVd1UDV5QUl5TnU2eEdKU2MKtndT9RNdydAB3wDdgPlwU2+TcHoVQrv6
            2j7I6M5+MKHQj9Xkiu0XEh1SS1MfD6eptZedOOnGxaDYXrbfDxT+Ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwek54cllTMERsWVBqcDdT
            czhyZWZ1TjVnd053SGNvenQwYW9QcFlRbnh3Cnovem04UUhwdk5jU0JQU3pQYWdw
            WWNmNnRsRkY1OUhpWnBQbWtTajdTYm8KLS0tIDRxOUlwZ1BtTWMzSEVCczh5REts
            UldzL3EwZVcwNkhFeHVmcmY1eUl6T0UKnwG8woL0rsxNdXzt2hyiewjlSxvZBjDK
            JeR8aDFviqjGcFwu5RHlDIiep9CHOkM6iTHOZZ+Qkn5bo+MO43CnBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T20:31:49Z"
    mac: ENC[AES256_GCM,data:ddR+vfwHCAFF7wxu6Gn38hTdMmk3sbxgFYZb8iyycEuUA2Rl3z5vxAO+qMuN4modyKoqams39nZ/cgNG8B4CkMR6CVUsaLe2SWOVM71doOYBzSbkTNQqsBr43ycUq4diFtK1MSi4EcCFVDFowRXo0MHk9JkDbas7pyvld7q6I7E=,iv:TXd0ohHXvp0PtnwyMbwtW8FVq3TWGZMiDDnFVZFQdIw=,tag:J0bpv87hUPDxHTbUR6gptg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
