apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: redis
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:zgYJg+NWr2X55Vh51pkEuiKEPynA9bJj8YRGrfH4FZO4tQJanR2lSqAEQsoM9I6RZ+iz04dSUZMuWAgVgoVn307FmA6jDH01guo3PjqLf9S2llkBKSy9C5uVYBqTCvPhefv+2cBM2xtt1v6rZpJ3Gxs7TQ+u0y1xw2wk/vJ7oSbv8JdAWOHieg+bQkGDkpmKtO3/5boCaXrDGJ6a+7qHXPqaulk0kwThgTL1tlqC0Zh7YzKSiRHW6aZdeS+vFa5dinN2TKHDjeua6bhU7N7c0SAJVMBGwQE86GnQgIF1g3GrIb66dsII+1RDCIqeTuq3RQZjD2E2ta4h61YT94a1fQZK/oAgcZcMFTHhvsf9S/2AT3D2kJuvQt+BKgWXEWpQvRywmUW9HQ6WYbKk0Sj9DYocNbuGqYMGfwNDZ/IcrOtGTMTQgLtOzwVukSGL5e9C4WFr1AhTwj298wyREBFnTxRidxk1qeYc0gHi60BPP6EsjeSXcE6vnHLsTecCZ9tvZFDnQqnzCSABZe2XpAaydgBDQh9w+qOkOAFevL7zm12dRRIFu5BGtcjbVoPg4yklxM5tRuZqaTTOyjzKoBdldRBKIabwPhsLFdKVKAwOSW+KzQecet2KFV+4CgquM5lYR28jgmsjoJDwkzl1T8msq2lolRyaQ79A/N4b0hvPo/F7UXA7T6Ks4jV0D4KZ7i599NwxjK5yw6nZMkfnNKGtSf1rxiGQSbj8o2befmf49d1OjlsDUcuRNH+n9bdDuwwbLvcohqhj2wzLWMFwJS2NX8+/1cUkqsDjjSb4APxygfq6MsL43MItWodcV7gno52Pf5Z8th568NdvJlk=,iv:lffK5Xbtjw/nLeWuTdlNsNA2DokVD8bGlX4jBaWTq9U=,tag:lY//EZmlYdoP9tPm1/zx+Q==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcXBwUmxOL0UwOS9mZjZ6
            S1dMUjRPQ2xNR1NIMittbnlsenBZbW9YSHdvClNlYVZVUU82d21MTjhpZTZGejM3
            L2RuLy9KSFJuUEIzN01XbktwSWdCb3cKLS0tIG5DQjRJSFczbFlDS3kvY3J5WjVL
            OThUM2NyaVBmZ2tTZlA3dDZ3R1A3UVUKCnVhNEzc1X1mH4hyBk8uyxjHkEJN9o0r
            RwNuXJbtjSdd7p7+XXyGDqNCDWf3nAvdyyZJNBEepqk+Ekpbq0Y25Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ1MyS3RqL0xmMkRhNllu
            QnNLNGxnWHVuTW5mSlZ3dVFmbGVQSzhja1VVCndhZ1FDZDVTNzNydHRVMisxYkVL
            MndNcVRNcjBDT09WbytvKzIrcm1nS0EKLS0tIFluUUN4UzlQNTc4ZVN5cy9lRUxY
            NGtnWUpRUzNDWENzZmVsWTIvaWp1N3cKZcsIiJWIgbjIeyzwMeqKOaXmBVZ0fCDe
            T2sHiovkKwSkkXjoPak00YYkcnQ5/uY6Jq0Limil4WYTVs1SHyiZXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T00:59:27Z"
    mac: ENC[AES256_GCM,data:0QVEYYmxh7BbMW/2LcoMrcNSKrOe/+7jnZN2WE71w1d2F1jyFOI6DfKyUKIcYMe+PbgSvz3i4txTeRfApJRVzl0rGx8AzVN2U9ICnoPO2sgP+mnsCRghGbDFbPxgYsvWy78fphbRa9mrQoVIokBWWoVzW4ypzVOpMDl6AlphfQk=,iv:jAo5yv/8DqZbO1vonpX9fEoZPY2TZbT1BmwKkWBeDVk=,tag:04oU/jwcsWCjw3SUxD7Fng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
