apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: redis
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:55+nQeOv7ZFhyjjoVrWiwlXd7NaeFf6W8vkHF4vv5cV9DPM3K6HcpIUgT/Cv6/xRd4aHvl7i8DfE/cvDXCme14QDaD4jBKRAMVO/hgCF2rll2Cr6Hmwq+C+eVlo8thltGp54hGpjonFIbxvJ3hHHWfd+Vz/Xr+VYTOi9eUZv9VtdfEh+AQogLnzmYEUZIl+qfrqqAgtUtZP/Oj4Z7AFsKdyTFsYO+kPvFPIWM2qsU4+q3DXfVP6DOvV9CuvGA4KlGvozNSGiTYxNW+CeB1e2DTjCuw76c0ikkRS4BWvdMfO2iIoP5szasb5QDa1Yg0gxX0nzEAa5yrZA6yUID/mnxz0LpJCWKo99hLaGUs3RyRezZZx7g+9tILdURkaqzyfFksyh0bcORMLhQZ/AdP0O4P4WRsFPyD4znmUEhFhNBJUW1rS2kxiiOp3cqmDGf4540mh/iSAsvZHO5SD2IDdVnrl5TIy95p7hZzKdkjiRaEcs3k4jwhKj8ne9uO+AxPj6zadF4bTVW9TH6NFY6Hnwv0yztYp7WMx9UuxHiT+bySvw9OWDqngFraYUTSNUKtVswawsXBB8Gfl4xl79UcDJXtoPN3b2CVGFvkMACdc1IEGwPQp3ENzkYGHAtAlWitOQVxCjNEtTT1IR5d8Qu50rz3y3F2V3hcS5Xrjb6vySVTL6HPgDKdw484eo1Wl5JB4HFN7VlCIMo3eMBy2EUP/FS9Q3mC8g+Mzd92O7eWIg5LhuuD+VGVEeljj7E/1hNMg5yLNeFjovVPn/KDs1ia0U6Qk1kszsIbsGNuEb6W/EFc7KccWkQDVyOQZ30nOF+/zYc2k7bHg/dJg+Sh8=,iv:53OXGF2WPsqfYVZ7sILvOM8VREqIYsPyoB6c2Y1NRnM=,tag:rmYaGCh6kAJvmnvmOfiH+g==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K25DcmNqUFNZN2RZdlVl
            NUtsRmo3YTVCVXgvN01tZ2lJMWR5aDZSU1JZCkFSL2ZsZlNNaFFvQ3Z4cjN4bmIr
            bE1LN3RKVERxU3QxaXpkOGF1R0xQaUUKLS0tIExZbVozYVMzelRrSlJUdTU4MllX
            TlVtN1U1NEZVVFZJM0tEZnZlZEQ5MzAKGiVuwkwUgzsLHGd2lGmJRnFcJWJ3ifXd
            3j82IisL/4nclxiDtKDhbrPL8pawFtuYA3PIBnmfiTrnFGu38AtCtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdEo0bHZZSEt5QitqTW1z
            QTQrNkRJNlZuamZSUkQwMHVnWER2dmV6RkZnClpsbWU2R2VCSHFyNkZkcElWS2JO
            b3dCNXhOK1N0T29URTl6UzRUczQyK0EKLS0tIHhqaUhZR2xRR2lzaVgzYUFTb3l6
            Q21mMUo1V3NKM0t6RDVrazlIR0ZBbEEKDpv9ovIgxqoYX6KNTMQoc11geLZzle7U
            8Km8grFHAGaHY5Yy6JpZW0eNQeWWBs95xMg8RPbDpdoid+OvnTfp1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T01:57:00Z"
    mac: ENC[AES256_GCM,data:hSgkEHCqMsKI6dNacGp6L+n6XwszeSZU0IfU5ihgXAmzOdEDqYK+UQHcgXXI+PmnAmE+AH4ohp/9Q5EKibvieAFHoMF6z0wD18Q3h4lb4Gsh3xeXQWbQKxtzeuqjtSzINQ5tDQcByerbk9LYTxQGy8pfv9LYCUty0Hgf+SCSK0A=,iv:3NExyBhhXYFif578QPDe7NXszznxT3Fsn5QsziUyJ5c=,tag:8NCaYBqP4nY0rJQx5qTfFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
