apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - ../../../platform/ingress-nginx/overlays/dev
  - ../../../platform/cert-manager/core
  - ../../../platform/storage/base
  - ../../../platform/step-ca/base
  - ../../../platform/external-dns
  - ../../../platform/argocd/overlays/dev

