apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - backupstoragelocation.yaml
  - volumesnapshotlocation.yaml
  - ../secrets/dev

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 11.1.1
    releaseName: velero
    namespace: velero

    includeCRDs: true

    valuesInline:
      credentials:
        useSecret: true
        existingSecret: cloud-credentials

      configuration:
        backupStorageLocation: []

      schedules: {}

      snapshotsEnabled: false
