apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: seaweedfs-secrets-generator
  annotations:
    config.kubernetes.io/function:
      exec:
        path: ksops
files:
  - seaweedfs-s3-config.enc.yaml
  - seaweedfs-console-oauth.enc.yaml
