apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-console-oauth
    namespace: seaweedfs
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:rSfkEn2yl9Q71iiNIo9u7uGdzLgbyBrki8q2Ge6tpzw=,iv:50Mf74qlA4EGv00pokN/wPUKAqrAFf/P3Lmg+LPMAng=,tag:INLzNc8Jf9wyR3bVh5T+VA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:7lzU4Bfb3Jr3UTPiBzRwvfQxTOImngHLsBgsYbyrdL4=,iv:7yLyguEaSpSm8X0ymcSI1WErwgT37Qr+ZFI8qHfeuFA=,tag:kOu8GdmLHgwMzZvYvzMsyQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndHM0QytaOVN4M1IvY0hB
            dTFIQWtvcHpwdUdRbS83U2V4WWJSdjNldW1jCnpCdXdrdUw0bTNraWtnOWdCT3dm
            bU1GZ3A1ZitLZVd3UmI4NUorMjlqY1EKLS0tIDBHYXk0RHlNWTJvcWtsN090aUoz
            NVRRbXBkYndaVFk1R2NBL0dRWXZPOGMKkIUgycJfHjBuzpBeNTMZVzJSOkQuH0xd
            N6Lz0GvHf8bLOAOs5lk3dP3N5PyVmQsFjJlMBe0spXHpEBH1TYWH/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVF2ODN5cFhiQXJ0blB5
            eXpTYXNZZUY2VURyYUdsemRFcVkxczdCMFEwCjNPL2hmRXJ1OVJXYnJsQTN1QkNm
            UnlrWGFNZUlQei8wVU9MTUc1NHo3aTgKLS0tIHVxSC83ZEtxT0FQSW00eGNjNU12
            YXhsc2dsdTlVaFE3NkJrT3p5RUZwMkkKH7LXKcXTdQQvCvU7A56s6oabyxLeM5v9
            4Go//0+uNqaNYO4veQgK65v4xIPQwhnWo4F3MSwkPpo4bc4Tj1YOIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T16:58:14Z"
    mac: ENC[AES256_GCM,data:aM2hZ8Hs8Qroaa6URuP96pwItdIaf81ElgXuAiij3OeK5aseJmt793PIiDcxnTE0tydj+nHWZEtQW8oawWslsBYulqyQm+phJRhQbTpiK3quZ5aR75WGnYR6gnwCa8tm8e6RdKTTg2uyAyLzV3RHpcqyytX0f8CoOq7Xl0K5ITA=,iv:ernNSFdCWUSb3VEl79FsffM97ThSeE+UlTJMiZVPpoU=,tag:yuMcg0nS1G/Um1SEDUpwNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
