apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:cpFzUe1Mv1EMihTolqItY/ncHYJ6jjY/7QuBfRyN4HEDULyU3I1QIHoJwuNfUv05UbJe3xkbkyMTQj3n8X9Gbh65RXExLJVBwEd122F6SyN42ewzxlnKhFRMJz5h97JWGpGsrhqlfcFJj4lvGHNZZuf8EaBeBHodqlcgi+XhWuTrwLmV+V8gs9hECBjfdZR8WuJIX52RxKcDSjnEi0w/JCMSCNXM4+iVPP3aISV3hicoFojriehAkNSoiIkSBwcqZGfic4cKgoNir7B2+CuhEvADoKh/YOrWUQx+tEKvfvhxUAMSXM7ZwOxjODfNKKHli1aDdUhxS4Qj+FIc4PGI5c1TUHLamUU6WST+Jjo3XW/CGxp361ojYpKLoLi6ChSvZ+OFytIwsd9G0KrcY6volMQdpuxCfcmQO/RUA6aBU4hLigFV/DM2z1d6aTyGEc5AQxkmPL3BvxLgIg57yIfZV/6Y+/k+z3FzJfj0+PB/Li1CdXoy/bkGdsvxqZ1fF0Yt6ubSneG2TbTunUgoLRNZkRe5mtMFH7/buCfc0iHLxxko3vGjfqL1z+oqqzI2hUWwEo2tagMyxXxcrttxZPYWreScZD+skL8ImCrU3lze1scEzFbPR9I2XNTkLXgpZHPhkFu0wot8zMW1ynlqbpT60eArTvAWClMKyoLqySefiqqX7YUqc3W4mLPVVCpJGX0UaBhxjiK2LzfliFpLzXZaiRbKBoA2zjzIeS/e6oObZs5oMOLtZBsizg/UDeKsrr3pIS6dMdcQ9CiqFdCazH90HueF7CG3lfen99LqOoigVXiWDO5YogHnT8tGRmwsXB3scMJZijcr11OpXHVEj4tS6TDydy8q+A5xmryX/a0Qzgjsng50PSgB6c9u3CfcrsdxQcx+ZWjA3uQrOidDoCqhmtJjFQNO23UOmpCsesA5Unaj/dsZflmL+FjMy6wpcFF5XETZn35/n5mKSlVhxZOocL4hvZN5sJeuoxVkpdBDoS5AxKp9DvRQNQB69Du+lxPPhI0l5DDpizlZg6pZ8gphb5WnuFuOImgsEOijfCBSD2s5BDwWa3gYQ1Rq8cmAAndBXnf38fywbTf0017eeP2FgK87cUloXVBbyo8O3t+6EMs4QvyKcjXIbBYnG7F7jgCNuvN48XVen+I8iYKg/NI71U6mHsg8164alLTuvBz4ybILtEcAECeSK+wof2GtsEI1f8jek63IEFTbpx34RdDRcjIsMsGt6XuIb3kg3iB/Kga4PKX0mob1Kx3vVFdoU3g=,iv:n2Smw2fehZmLW+WPTcNhMzu+t1qFuBCcUC45UWinR90=,tag:PcIPQ8xqTeSYzGy2wQ9ZGQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTDBmSk5ESnhBK3Z5cEx6
            WjQ0N0lHdnB2N1NoVm50azF0S0RaNzBadDBnCnhZRVh0YklVV1FFaXFmRDR4RjZF
            Szc3ejhMY2d3blZtbkZxcHRaR0lEcVUKLS0tIDdhYXhQbXd5YkJLT1hxV0l5dC9v
            ZEFXNFVyR2pvVDk1MWV0bTl2T2RUaUkKx3ziXnxQR+YKFoj5jot0t0jlrjAxkd/7
            i1OGMc516FAUncQY/jTYsqR3L68xtzXGPn63h/NPMLZ5Zr57kG9Pew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZDFJRFhWbnI4dHpOaVJo
            OWhMYm9GOTROMGN1QmU3N0hlU2wwTE1zRUNNCklKaEJVTWtkNGlHZEEvQ1ljaHFQ
            cDdRODFHZ2FBeDBQT2orOUV2K1NvMVkKLS0tIEpXWm5XTVpjNWV6OHNja1AyYlpT
            K2dETE9semNNQmI5NVJLR3Y5dmk3QWsKMAkBoCAfxNrgw48ZcyG4K8wNOJcIq039
            sdRXs7oJ3G7HFwVwvDyxRvpsuI30xXwlOOm+/YvfI3Qz7YzHA9P8fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T16:37:39Z"
    mac: ENC[AES256_GCM,data:va7DcXE+Z4TyAJZ5g/DbgFO50Fx+6dOWEYKaJ9dbKgEfSfKUP1GQUW2ljx5pa8QLESZIHT3t/vE98ZjQYhj9KGAA/P315Kx2gayeu/69No04VlsEJtpQQ9VgotjlhzvEvGSb54Va/HSQtNEEZHkuJ92m2fyaYLd/PQZa3xuI01g=,iv:PgGE6AyLY9kBcg4bTdbLrtqpu3yM35ggVghPvT5FGb0=,tag:uYpA1j+mXgLSilNLhZZ4uQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
