apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: Aetheric Forge Applications

  sourceRepos:
    - 'https://github.com/aetheric-forge/aetheric-web.git'
    - 'git@github.com:aetheric-forge/infrastructure.git'

  sourceNamespaces:
    - 'aetheric-forge'
    - 'hello-world'

  destinations:
    - namespace: aetheric-forge
      server: https://kubernetes.default.svc
    - namespace: hello-world
      server: https://kubernetes.default.svc
    - namespace: velero
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
