apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: services
  source:
    repoURL: git@github.com:aetheric-forge/infrastructure.git
    targetRevision: v0.9
    path: platform/services/argocd/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
