apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forge-db-dev
  namespace: argocd
spec:
  project: services
  source:
    repoURL: git@github.com:aetheric-forge/infrastructure.git
    targetRevision: v0.8
    path: platform/services/percona-mysql/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
