apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services-project.yaml
  - operators-project.yaml
  - apps-project.yaml
  - root.yaml
  - argocd.yaml
#  - hello-world.yaml
