apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: Aetheric Forge Platform Services

  sourceRepos:
    - 'git@github.com:aetheric-forge/infrastructure.git'

  sourceNamespaces:
    - ''
    - 'argocd'
    - 'minio'
    - 'rabbitmq'
    - 'cnpg'
    - 'redis'
    - 'mongodb'
    - 'aetheric-forge'

  destinations:
    - namespace: ''
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: minio
      server: https://kubernetes.default.svc
    - namespace: rabbitmq
      server: https://kubernetes.default.svc
    - namespace: cnpg
      server: https://kubernetes.default.svc
    - namespace: redis
      server: https://kubernetes.default.svc
    - namespace: mongodb
      server: https://kubernetes.default.svc
    - namespace: aetheric-forge
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
