apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: rabbitmq
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:dPDnBMzFada60TBRkAjCG3kayh86bHYAVw7u+1ZJhkikI97kh/goYj2OJlXaGX6kOxvS2iWpVHxOUOAtWHVqj73YHGkgx4f1TG+k6f4Z0956vA6sKcIWZIYbeYapOBRC67nt+ajeYH89WDA+8VmsDrQlKFHKECCpMkR07/cReejNWVxpp1O/UQrkLe1PFO4SRPQFCakqdBBp7zfTu2AYxQpz2fTG36Xwttdj1sLfrwBQVGuJ2Kiu7lrU5WS7gcNy+piIxBEh/CzC05xYJpQEEu1R0gCIvZCWqXo1NCruFGfsuoujH12+U77XcCUrXXYsWrdPnW0CCCo/WOOkO+MHXRFQVn+0SZt86/LKckQkA1LTo0h+Hi0qOHBQF5XamTJJgb/TyH482Q3IaIVXlf3UuyrRnh0/v89KTV8bQaFq2SypfwGdkd4fhXiVGh3Mdb8pMGKEdw1GgV0vNDBv6ulzXILa13HuJOCKSZHsfkgySedYbhkbLIwMPR31W4xgC6FbEB1uG631Tjb5HosHqlDZLtM/4u4B7LUtWhnOpq71sKz2vcPXACJcTTMevedN3jJ3KCOTxzsQncancqlx86NHhs1aT4Gkj799NivUm7tWuZNIroo9A1IUvOV5nKuiNXuOwOr7EIf8xVlb0W5TOKCs7fYcfOVJ3dTPvLF7eGUZUjXjPmqRtaLmJv/XCsDR6SZpY6O0VMgHNvD8pFys8mZBfk0hHtgPhcpxNcyfiKlKxPDj8e/UVQx9HSXXmD4hrDwid3lDAaAvIcSfhPqr1alSI0b076UelLmfHjUT2YOTQbKa/BSK/ucRVxKBuybtNEVC+SYaY9xc5kBoD1Y=,iv:EMRFFQtrV2lWPnfxiCbU2Z40VB7bjicw+mncays36Hc=,tag:z/Ii+tZQx1j+Z2iqrEr8zw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOGdSM1YvRjhKVEh2Smdk
            L0p6MzlpOG12NHF5ejZqc2RpN1JmTDNwRGowClhpeGhnZkk4OC8zVGxZWWxRN08y
            Z1dJVS9JOVoxWnJFemxMRk9UbzA4T0EKLS0tIE5FTnhJSHdyWTdZczRoZHZaTmZn
            WE5kanF2MGhjbGZkSjExc2Z1T1RiQTQK+vHUuE/rg039dvJxploctAuH+GxtDS1p
            QaqYffg5ZyA8Gq8ZDRrzSjjEBGHTOBfjP602HwndfSc053+UFk4rBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cmVyNTk3aEU1dnNXY0lj
            UFhWL0RoTWlDaGtXYnAzOFhFVDFXUWlZYkgwCmVHZFE0NTFpOThyUkNzeWludFJH
            N3dwWXcwUm05d2J6V05ka3p0enptcWcKLS0tIEI5bDFUc1F2ZkxUajJWcGNSUXlV
            SjF5Wjl6MGhwU0syTUxsejdvQTlzWTgKOO4yzGza1yAdpffJuoVBBcCYHatXdeoI
            kClR1iXjpbF1TFvJMuF2tIl/uY5EiFqO1cae4CiuD1jMRPDEtOexQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T03:48:02Z"
    mac: ENC[AES256_GCM,data:gTLyQsFKS2SsZ2rSIZVIwcukXP/+hX7NhmmxNP7YI+D2WRxPKm3VKR7e3g90qGlhabswEHmlyfgz9PKu/he2dqjNU5Wti5QJ6yxX+9RsCQLXv15AHjvuTEUkpSYzehAXwjKQZC5Ot7p7Y0Vd/k/unRFhEC12a/jJdwbAcPgy6sw=,iv:9P/fz/sPJ3QIDMp62aw2C6GKueLdHMjX/F9qbvBlTO8=,tag:iuvNa4fvv6G7C+n2X6GrTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
