apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: hello-world
  annotations:
    cert-manager.io/cluster-issuer: le-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hello.aethericforge.ca
      secretName: hello-tls
  rules:
    - host: hello.aethericforge.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 80