apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hellow-aethericforge-ca
  namespace: hello-world
spec:
  secretName: hello-aethericforge-ca-tls

  issuerRef:
    name: le-staging
    kind: ClusterIssuer

  dnsNames:
    - hello.aethericforge.ca