apiVersion: v1
kind: Secret
metadata:
    name: step-ca-secrets
    namespace: step-ca
type: Opaque
stringData:
    provisioner_password: ENC[AES256_GCM,data:yJr+OnrhZqS1wZMN9PVc1C/gCfh/zj8oyYVo3iDhKw2yuDI1Jc8taoA3NsvmwbbY,iv:/l+7iW7AWYFOA0ogN6oz5f5NWSragC/PwRsUibJavCM=,tag:tIPzoPQqxZOf8v7A53B5lA==,type:str]
    password: ENC[AES256_GCM,data:Bp3gmuAQbhyARmk0QNIyqosMSWLnIW69H3NkfgGHbLY=,iv:k1pUyx9Wu7I2rbnyAh/LefhlhYS24RYpLsGwwEke9ss=,tag:jWIovnMaBwxU5ALYKPEESQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZHRyZDloUWJ1Zk1Fbnds
            REcrZG5jR3VrVVpvdG0wVURzazNwVCtpRTJJCk42OXdxc3pBc0FhVDlPM2xUN2dm
            SDMzRXQ3M0NWVUFoZTFyeWNVQkFCOGsKLS0tIEwyRytQMTYvM2RYQXI0eWpKMGRD
            TjRJaTNya1dDYzZiUlVPc2JSMlF3eEUKb/NV6eOSYUuum557BG9s+j37V5SE6Ud2
            vqpEcAlZSP3wukuqX+SnLZQWfo7JgquyRNg/vkhmMLhoX4mTe/eYag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZEVGMlVOeEZ3aTBnTFNi
            RS93SDkvVVVtQmdGL2Nja3RUb0ZxQjZuNEJJCnphdVZ3NlA1RmFCTytxKzNJWjNv
            RVpHZnhZbTkzSkFTalpKMjQ0QmdseHMKLS0tIGNveERXakJvUUtJTnorbW0zN0tM
            eWp2WXQ2UjZiblRwQmV0bWx5ZWZiSzgKQrmsqBtw5DiCQ/Q/tPoILRhPWlbms2wS
            Ok2qqtpmCVSKYIzghK742PrsXj9Ugp4QtPEE2nZZLv/6vUecdVeKGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:01:00Z"
    mac: ENC[AES256_GCM,data:Y7N7YfRXQHp021rBPXBN7pb5tbGhqRMZ99S8GtyVaJnam5tMTiPO8u9Lzk4lFiwly8Dn2kb74mH4INVaIVJhBYpN0op6G3L5xXfke7rbgy2vnHp5oGthRC3u0GXuHc2yS95j2UHoYTDZeOiBFxVSlZj7qJ29C0RG4lxjHWAa7L0=,iv:RXXqm4rBr/3WYEo1lUI8y0svTae+8EINygee6oxmNoc=,tag:2v5a3CE7sLF1QZAbiOvQ/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
