apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example
  namespace: argocd
spec:
  description: Example applications

  sourceRepos:
    - 'git@github.com:aetheric-forge/infrastructure.git'

  sourceNamespaces:
    - 'hello-world'

  destinations:
    - namespace: hello-world
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'