apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forge-cluster
  namespace: aetheric-forge
spec:
  instances: 1

  storage:
    size: 20Gi

  enableSuperuserAccess: true

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: forge-cluster-rw-lb
              annotations:
                metallb.io/address-pool: private-pool
                external-dns.alpha.kubernetes.io/hostname: cnpg.int.aethericforge.ca
            spec:
              type: LoadBalancer

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: forge-cnpg-store

  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
