apiVersion: v1
kind: Secret
metadata:
    name: minio-env-configuration
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:7zAMGB7hOevIC92Iu3Fixg+2SKb5CueLRTGxDCutoubk3UdvUEUmzWO0Cxs3koa1Hhzw/pDuF1aBOBSD7F0s5bL0wTHy7q3wPPplQbEgDFd/rL98M4ziImkWkAx2b7YN0W0N7l1iYLsA4zjuvFYJDgurVjA34la1m2/RjcbUFlaWJhcgNMgnZ0mzeIrReMg1,iv:5LxWfxKz54V/3J+tZAI/egOuBdbw9kQEYIQOKynBpDI=,tag:puJkGB0x48+baVoZZd4yyw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dHB2WjF2Yk0wc0QxczJF
            eUFvYU54eloycEE3STlxUk1OMi8rcGh6bzJ3ClVMRHVKL0dDRUZEaTQ5TlNoS2R0
            WFBRajYwZEtERHNuY0x1WUtOWE9POHMKLS0tIDRGYUtmZkhtVmxPU0dwNHZLVEs5
            UmZiZk5DVUpmV3JtbjJYWkQvb2U0YjAK3iI3CyFHAxiieIfMlw55oV0Equnbdg2p
            ZETdklt0ZjS58mU7BB+XU1TwfRFfuAcfNwsTyF63YPimzjGPsrGPGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbjduK1dvRDBncU53Q0Z6
            NVhmZm5xMFZ1QzR6eEtTdlhpZm02WVV0S1djCnBHQndnRTRjWWt2RGx1WHd0QmJr
            TmJhSFBZSklHVzNqczYrQkhvaUlVOVkKLS0tIDlTMjk2NUp5c3drZjhveUZRL1Z3
            ZGcyU2lkbkN0YlV3TUFEcTE5c2lYUE0KJNGxCDKY3S81GnioLU6SUTDj53B6qhEC
            V+pRBLP9VaSGTwQPM5d0R0NcykqweinNTyWSKhyfO3bBiKQPut9Zsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T13:29:27Z"
    mac: ENC[AES256_GCM,data:vEEAtQa2E/rD7JZZFHo4K2tO8dBkerdtRq09zcugte6kGEptbYJn8aDrhloaJO6Bhs4kJvqUD8LtZsuNda2PwWQ6rm83gal6uRQE6wsgpvfZaVRE8ye4ryMYytUDcpc9hCIVqKhUZr+8FhXbOsAdTAU/8QsEUyfeuYjbbc17zRI=,iv:V63Yh8qXUIMUEN+sopJ5dkfsa6e10NCo5ZifmKQ8WuQ=,tag:TDudzJxL4WwMoir0aTdahg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
