apiVersion: v1
kind: Secret
metadata:
    name: minio-env-configuration
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:7sU95DM6XtRWBYZSUvPCnyrSORAQ7Y8X8eq6GSYb58eHQfCZnYtuz9okuYOgObWdkuZIsNv/4PavDNL8ojhX7oxWiTeIfQ8f+wOnPwxxfBAItGICDLsoWJvCtexAuezvOsb6hsAjeKtwA2dBZoJBKOfeIBeosoLahpwgBXtxHbNjj9/t8KTWGrJZv9/D8Vwa6A==,iv:wkvFkjENOimxswWEwE//2N5DINBJguDlfT0TSMc2AWE=,tag:5daKZJTkenInQ1GZm+KsIQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QnI5eEFXZ1F2dVk2cjdt
            K0NMQXNRdDg4bE5Db1NhYW4xaXZ3ZEtnRVVZCmdWL0FFdjd0WXllYm1ST2k0SHBK
            WGd3dS9XMkx0TThMQkVLRFNkSzZEOW8KLS0tIHg2YVJGenVVT2xaYWxNUjRpZEZK
            M1JCS09YUWJpUzRLR1FiOHdjaHBJZTQK3vq/ijJoippwCsfVd9yU1YQEKuYbyfGg
            JjywT4VXPlXcLgnQNs0d4ueDPC6QoGQpURZp2zA/u7iyXz15vy0hNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaExyWGhNT0wzQU5Ma25h
            QVpEeEEwZVN3TmJRdzhyUFZqdlVOd295elQwClVmYVp2UXZmNUxpcE4xcjEva1hF
            amNNdE1NZ2FjeEEwRlY4UXBMamtJZU0KLS0tIGVIMXA3bXBtMFBWSWEvbUxzdCta
            WGdKdDB1N3Z3K3FVaHZ3UzRONzJyRkUKERKcGzcfxZmx66YDfaeKjk1FxusOKJrx
            mfnlzf1dXiZjffK819Sd21fk2jeIvw27u2tubpKEvM8Oe+oRwee31g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T19:35:39Z"
    mac: ENC[AES256_GCM,data:XMh5pH2MgBSCtE8JMjFAqURi5Wpuz7wLTFfPLBo+X1pWxIBuhZ8iNe8qiXNXkEBS94ub3BVo7xMDVigGwwuTz1kN20Go/tSQTcJiHWLRaERbIdqZoLMhP5ZSJMzVvEmG3MpOvBaXk50WTocgoeUW75dMWDZhRz3M0eqP5FxNQ1c=,iv:cnnZAcCouqwVVVLihylmgTL/azgsSsu45soClItqWYk=,tag:xif77yvKXP628xKZ3PAnkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
