apiVersion: v1
kind: Secret
metadata:
    name: minio-env-configuration
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:rEb0tV7YRGFNbqRx7L+DLDro9UW0xVKSsGHzAnpwE59t/E0EDtg341URfZV4mhDjbwahqJfWCm/CuSCQNqAvyL/gME7diqywmEoqm/QJBBdQInAkaBgf4DjQ5BSdKzKBBxxK58Qbz6D+K2zwTgTMafyccPiUYqPvRGDEpmuDfc2CnD3mGXqQMD3cGOwaazafCQ==,iv:hob58Z1423KbxaEM7yce/77lwd+PtodfHY8cjdxM7aM=,tag:8MAZy4kn58vd92qegDjOsg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSDBadmluR2ZmSkxUdWxW
            dm5qMUQzT0NMeTdSeHZqOVhhdGREWTE5WERJCmM0M050T1dHN3g0UDNuTXdvY0tk
            SGNMZ2VKTlFvME1oZnhacFY0a0J5NDAKLS0tIGNHVUJvTHVHRHdsaFVpU2RJVzhq
            S0FPMDQrcTRUMTFibGFwV3NHSTB5TXMK7Ci+yM9/Vbr4v/niVN17aq6DSt1cZLiP
            QWBVpjCX5bobIX0j9i+XOmXVaZGGP0sur3d6F8o6ylKzmGYXRwhkqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLb3kzMWE3dGpBY3NwVUpJ
            T2J1YlhHUTBlWmtkSlRXL3BQYzBOVE54clVRClBML1p0cHJNTmpLbGRUT1hxT0FF
            YndwUlEzL092dnBtNVh5L1JXUUg5TGsKLS0tIGs2V1V2YlRlb3BaWWlWMUgySmlY
            aVVRMjhKUDdUbW1iSDJibGpMSTdhdlkKBZwwTnSQJVe7UVLOefDxRYB2RGhOClDH
            amlhug0SnJHwcMttIN6Qpo3e97g77H57TmY86nvHcVqa9usLxGvqHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T22:42:47Z"
    mac: ENC[AES256_GCM,data:g3cZi9Gg8sTSdSsOLNXEYLc7mikJTf1tujllCcgSO6U7y6KXqD058wliU9VNmXziQjIGx3yRGHLgwVq1c4qURDL5CAePJk0kZvfzS4t9ovzx9+GgAmIMzOcKvRSQHt7b6rjYbKxKCqobVimiV8urCZ9PO1nH8X27k2t4lTkj1MA=,iv:e41lkKTW0So/RjjqAUXLzPxPPsCJOjCzyWZPJCpdCmU=,tag:dhTtrvY6dhEQYYFK03PBXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
