apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: minio
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:yP61QYjevqtQ6tUXH4rrA6z80OBR5zdn7vH+RmenTd3ViJ8e46HRmIaNuLJbvVpgAuQIGlmnG38OkvtfFLjGxs7MhJr4NIvRk8UIzTOoM1rNTi1BgCUuP1TEk2g6EHse/J7KCGGZhnGwyGNRLW0ujQGd5r1W46uii2XdQFOxeVQakM5tTuZkM0uUcpynAeQWDfK0uPpt5BnhK+73cToQo5+vuK6DY2yNS3kaf/I+ATxqvr4FxNi9kOnBKPGVzQZ6CzABiTcXcwMlt8L3nDTAEerGPghUaPN0aD2PJGfwTbClOZIjT/u1cp39n1eHOawK7RuZtwWgfRqwBkEgO1f0/hKQU398W/kgYPKIbRhjQn0P47cnsl2q8jROhTYb1pgKrpZWHJWwHyc/cRbic2EB5pZdwHt6jNy3THUeodPNdijU3+eSLZ+jMB1srC3zOgWEWuypbGYkz/iYAJvYjdb3ibTlspf5up8AQhYZCGhBwDWc2Fu8dRbjJJ07eDPqsvl2jZDB063pQmTgaoHwCSYDEFhYNlK6rFcVqMowKrIVHJV4o9po7Lk+pdJ33loRcKooVo9h/GkCqlHYThbvYCBE1Reg3yEGB0ar7bY/EA4+T85I+lde/hVDuUY9eyiqcd5d3zb5+8W/7sXDZQBHwUt+Gp0pM+r/zG0XeZ3zXuSXVcEHKtYC1ILhM6g8VmEBu+GsA98HNjo0n+OSkqj/7oXXxYpqIWtAjRaFqYR+68H+oTYxKMNhAZXD32Um0pVgTwoV0eOEUyqu1WSv1WY9sVFv41wdfrNWgJbmmOd4dtcsZtPFJgWhzvI1GKsAC466ZQd75igLHUW/qt+diBk=,iv:X/RSdVGJwHa3k3RX+snomuiav57KO6+fJiRj1yUy+28=,tag:oB8tLUrlLt9cGkLYKL21jA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxKzhYUXZ4K0NDUHBRZHRX
            eVY2UGkwZXNOYnlWZXdoM1Y3YTk2TW13QkY0CkV2NTB3QW1oazRneHplcXd4Wi8z
            emN2NUxMQWltTUU1dG54cFN0QWQ4TTQKLS0tIEZvV280bnBpbHNNeHRacDBKTTlj
            azFOUUxMc1ZQcFYyczJIR2g2bWZwQ2sKLkl1FZUU+wsQmXCM5d26G2dg2tfXxwvg
            7IWjtCY1o5XRy/iApuDjfnlLOrlGTuAxPDg9w8Lkn3M867mj1ZkS/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOWU2TVRLcmJuaU5DejVF
            UW1ORVNJajhpcEE5cWFSTGIyc2phTlBBN3dzClk2Q3gvRlNMTXFybHRtR3JVSTJX
            MzhGSzk2Wm5PQW1FckQzMGUrUjdmUWsKLS0tIEd2ZEtuanBMaVF6RWZMOVQ5RUYz
            dklwaWVpVTEvMlFibkFDdCtmWFBKaDQKrq38K+5o0QThH3xKGcbPgt6KdofQo5eJ
            yWr9sxJOrGk4ykbhGgALoh47+1X3YoMFXcnvl5/KOxmKZ41i3gZjcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T19:41:53Z"
    mac: ENC[AES256_GCM,data:4Zpru0Nnnml7bRMhXF3OaTKIkNRulC3DspKx6aRE46KAD5Ld8FjrZx/zy7JqvCaDJz/t/RO5cb3HOLzeRqGak92lQ5G0G+nrC6Pc3Vvf5wScw0oXw6TQG3x86QzrqNdFOFa7yTttkLG5xqCJx2XpP4+g9Zi2NVnBYcIFRw899U0=,iv:qkzPWNC6T0W296aWNFJJL0Nz95Q3o/kSgitwQmVB7JQ=,tag:AybgGa0KvyWLNWOSi9K10g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
