apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: minio
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:hGOuJeIPVlxkDdU5uLoZS0YgQltvnflCg0BhJBvkugrfi4YOVETieTG/IaSsC0EAJJsnVWSMASUiAyfT5enT7Nzh86Whn+/RlPa615kenK5CT8UEdHISaHLWHWYv9MrZB9TzMAV6nsbUT95BzzdgjKYz3nwCHY5UepnG29np3tbzXcuiEtAuBFWjBQkXLYS/lMATxrDdNG+j15NhYlZYs3Gl3gEwu42nBrv8aH8ZYiJZpzr35fNb4s8wg0wDzsHcIocv5RvG41Xu1YBqgPvTt+N3IV++gLa+dV+UNingiN0XnRuFbGIB2XZbx5o66oMVcTi8lKpxuw2jAkAlLQqXmXGtVc/i1ovQhOHI8TME8OKuyQNTkV26mlvrHufa0tchrNilBtIjDDHz6yuKh7CvknGsIKqN0Ez4t13Xkt8nn2B7Esg76XeIJti3aJGymuEwcu2d5TFrNspGP56l9aLvhmqaQd1m80U841Im0taZBVLqDZQso+T1wtiCVPeSLVbstB3F4YMzTeQZzsbm0uUY1sza/DcnFJrcKo89fCy3WfGFVibKECfw6D6rN41sH5Pr4mY1UfiTV2hfOoFHJNIQ8rUrY4mzXlsvmFUzKlEF4UrBikr5p4yS40Pe2sOHwqCAZ2cg49QpK1557KZIQvioeF+y2IpScpHMUtATxFRaMEsIoxSSuyezmCHLxbJ63MiIuPlO20bCXgLi9D10gw06pMrkw+P+K7q/MZw8vzH8SoQVsJpJ6c2Z5pFVg9SKdx777IDPXeZ/+flbpBDjS8s5rFpZMh1J9Z3IRilvvqIifaJD68H3EtMGq/tKLtJzWikUQng+5Yla2N/sijY=,iv:kY2tRDhewOyQcfguUTYBGk1BJTJzRXR/5OjKRUqmpZw=,tag:yL6KwOwOD4yGWYQJQP5OAQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZFFrdlZod2VmcUNRNVdo
            WjRhY0FBb2xReWhIK2kxWFc4L3BWNUQzMUJRCndYNW5OTjdwVFlsTWdZc3FoWjNY
            cjFpOTV5ZVhnRkVMdnQyNkRpZVI4QnMKLS0tIGVPTGcxakZ3VFN1ZDJBR3h2dnUv
            d0VUMnE5VjRmYVJPVXhQVGZQZW4vODgKc647lPCo/yPxDJndb81euHO3H3uWsRK7
            LduA9zVTa7zow9t9Zh49aSs8m9qxiBJd7dQy2e5QofnNUbi/Fu0EKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOG1uOWpiTWh3NWlCTlRP
            bzl4Sm0zV05KdlFWbnVSYVBUaWhzTEpldEZZCitvdEJ5N3RlNjVBdnFlME5YZFNY
            Z3lSWFUrbE9hODkzZFduSkgrcWtmdW8KLS0tIE11ZTQ1bDNLcllvUERta3RsZk9F
            ck0vamxQQzRvdTN1K1NGK2hZZEdnSDgKXx/0GeUtwfVOQrWaaRGROYdjDvYnKKUF
            KglVmt8fGAsmYA5bPEReqJlTHhjiJuOGmS6n3MjiPDlICBH5hGnPoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T19:46:04Z"
    mac: ENC[AES256_GCM,data:NC0emdGvuDjFTkb1Ax0raec2snxlhl3e/wkG0dAh5cfKiAbj2bCvCQcD1rE5KIbFdL3hx8MbIWMysDZVVoZGupr7YsNpi9txHnFIyQ6BZNMEcQLD6JUZgoez2KNGarFPfrfB43UQzeSm02rvSSZCAdLylm6R3OT7HS343N1Mafk=,iv:7gCla7t1zADwGRfh+eFulYdj9A4sPZK4bTd47h0Li88=,tag:48MoRPvpA/Xj/eBXOiRPPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
