apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: minio
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:53o52YLUfNP3PGyp5S0PlZK7d7NuIafcHpfFQnKnSE81Y6B5pYBY6coRIG3yQqIRonhHD6A/2VE+VPCPcVeB9YBatBvfafd++4MjlmQBK9+fH/STjGVQ7V8jQwrwdOrew7Rbx75MIZ1lbMC73YDej0OieGDhBxDL8j0nYicxWLyscN/9ShibR1Pyp1qWjpb9ARNpgsI+CkhMqvExmR98Qmh9LN31Z6UQVSoReN3X5t42yVkExjQssYqAQosIjnpZQ9xUfEUrA+V758uMf+v91yAxO0napLhETjULgM40AYvb4/aRUI2MNmyh4xvdnA3uJ13MQptNTNp5xojS2+AKM7k2eAJFHCDevUhBfnbCBtwlrHc7eerbR1tEssMPBBerT/Nrr9b1Zz/LWAUY4qD1569dDLoQQZZdjlEauEVw1+zMqycMDY8NScOGJ12scm6C+htudYtQlTnfl0Ou8g0LQzmLNhAZ2zOvfPLRSv4BlY04vuMls1XgOuK1n3nve3v+69TdB6QKQQg2/ww9sJ/5tGdotfD7Le6JTwN0s0CKcCtlOmkpH0d7HLDT02G6b9QgLp9SAcZHau33fuUhmsGKlZqZAwPw7e7MwxshGCfJHPeFyJdFotAsf23zm633TGHQUinIktIMzSUcVu8RDfJfrmwYXmHU0+XTpFtOMCii3YUw1i2YZXb3gqioOrttBm33TadJ0sjrXs6H27Sh6WR9UrM1GzpeupTlYu0TbQW17Vp1UQaW5zbNrww5nIB2iMOXSXDkefKgwjru6mRW0gqZ6zGxCW18gHUQGr+F4350UYnyOM9qHC3wIqVF49DAcorrtoJxNbMLdUGwRYY=,iv:RjLNpe9ANn6VGGqLI30sX0C9FlIlRKpPrcsOrIqSnmk=,tag:useiXkE0OnhzHpnrkSaeOQ==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc2ZHdEhja0Y1dzh5cnpY
            Qkp0amY5L3JNWGQrZHZYYjUxTjcvWWx3L1NnCms5ZXYxR3FhdFFSa1ZIUk15WURN
            ZG1uYlRCRlJmUFozM2R3R3BkaW5PcFkKLS0tIE1rSTJoTVZRRjNuTzJUR2JNQXk1
            ajdsT2dENXh1K1lwZXdkQUFNajBWNjAKNCvsIxTrUGuTqRGDbxmk+TRjSr6dWg82
            Za/rFICA+cWxZebHptbnE9dIKVDIM9frg3w6nltGXMhYbRH1ynvJHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU2VjU20zRXY2OUlYVW9C
            ai9mbzMrNEsrNFgvLzJZRW5UeVF6V1NqUFM0ClZCZXZ2eWRJeDZ5WUlENEhGVmxJ
            R0kyMUpqRTNTNGFpOXF4ZzFBTTVWc3MKLS0tIGtSUXFuOXh2Mi9lVHp6bXluOGRy
            d3UyTFhZc2U3SU9US3J6VmJ4czY4YWsKdrPZb81NiF+KRHUPANUYrsNFGWUuzOTA
            vcyGO+vLz6COnnQZsUSstqOxXBSkAuQjFIuszz05gxVcSFqsycyT1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T19:35:38Z"
    mac: ENC[AES256_GCM,data:kJvs+ASs5VuaGrKE6+ojIpgnF4zEimX4qveZFH0aTYM2paiEutAXTqPgF08uFtHLR0g5Ef+SZkmBoZsN2CBA3GbR8SprJhHJUxBr2rS7nkEy5AOQRfJTi8n4dauUhJ39ypKdmCLRvo/SoFKLE/O0jnFrz9+wGxcHyPIUNM/BFiw=,iv:vuLeM5EY4HClo2YED2KHzOjgT0iwRuRhwwsI7FTC2gM=,tag:EbKph96NSQpOW9tPZu3iVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
