apiVersion: v1
kind: Secret
metadata:
    name: step-ca-root-ca
    namespace: rabbitmq
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:0Y7k+gYmde1jB5U8wM+tsOXikBj6D3PL6gaOU7swMXpg3cHUVG2aQfRZpGs+W5YwRdNLStJB1q+53ROiozDkmt2c4LvOO0Fx/unz6Pq+28BQKRo1trt1utfG4R9/0sG6JJzogzj6oo4z/A6R8hINgWHjFT2xPYGnGOfuNSKQJA/ePh5DYqyGbMO5LE0hZxyYqshn7xQxLyVqUGV4Vu97c2bZfS4D5uBfvdZ1KljBhjhiSNBzDBl860s0tSMWmNjUlXya/TSSvSUAWnDTXtrq5v+d8RZIY9ODbxX9kYfLmrsIolFWQ1HV9OQt2HHp1zDXMaGSfwrQOBOBuD/YONna47f95SlmBXuXG4UWuonYjChH4EjIanq0x8zVZCZBnL6wB5toJHJagybXHWfMgrTauLX+21pM6L7KiTdfOeLefyp+hLWX5SfRFy20MolHDw8yx6mtfmGaBJir169ORCanCPwomN646pU6TQ+X0NUEFjC/bTiUoTQ5qwCZi+nIU1LOJrHs5scCITvOdiNHEN6NPEVCDzHRhb5+pmvnwYCTsl7/dptmUxVxZWOnkniMJmZvAQUZpQMxI0nKZeQ5d01UNanjdUBFYEao2/uVo8TFYJ71rySTgVo65BQZiEj2TTvfT6HKdX3pff2mQ2DewTGn++5UpzHNyy1yypnZLIE2rMYzpmqIlgGcTgt0iVrVAoRZBxcQ5u1wjkryPtHEPscefmSAa6IVYGy9LXbZfrA/eqecYJ3JawvwfwttJ9bdduBnZiWdii9T30cww4XPMqbUsKsbiNKBxi210mnlrp4toQifTQTpF/p+UMrtbSQwSHV/gioH68QEJKQbdXg=,iv:k4oVjXe4zdGnOxPe81ZAgx8/2y8zSdF+thoPGkSZ+gU=,tag:0YHtyrEpxu1GpG052ZhduA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwakdNbU1idnRQVWRyTEJL
            N1ZVeWtiR2tvK2EvQVpWNUxSN3dmb3FvVlVBCjUyTzlhL0ZjOEkyamRYOXpLTVVo
            TEFabmMrSDZoZkdNWnNtZkY3a3hXaUEKLS0tIGVUcjFjYlBueHZ5MGtLS2JDdVZr
            QzVpS0VPUUp2U2JOSzd0ekxsVmtCZmMKPr+TETjFZCm9QPEqs+W53trY5NEOxOi4
            H8aHSRPR+5wyJAqKDpuUF5vtZQcbq6ch1w/fLtLskny/CHz0P9c62w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmL1Fub0JUcDZ6dUx5OGlT
            S2ZEU1l0Wm1PYUpTb3lERDg1a1RXeHVUWUE0Ck1Md21KTURXdXBCNGNOQXNLMkhl
            SG96VGpKWFlrM2t1VFkvUDhrY2tlNVUKLS0tIEpSNWpHT2VKMGI0ZjdPME1OY2hS
            eW5qWklJU3JZYm9Bbit3d2VXZWpnWjgK939/YujsEyeJHNGXOzCya6/hcAyDvmlC
            eTqC0IrwDlYZsB4pec5+p85E6ADImTj6ck15Oki6zD0nGRKTjRkdOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T03:51:26Z"
    mac: ENC[AES256_GCM,data:mpy5/xzPDF9D+eD00f3NSuhJo51HG4HjK2s6ZyozLFWx+MoQDVmaa/wrzG8L1PAuG7DTQa2WL3JYZRcEgQap60KmpJUOxfmbNnRcGn8TpR68QUn5FuBS5RyjzHLbIrpPCnCw/EGXYoN3CXN3JXihrrv3/Fmz8IT7Ym9np+PLk4k=,iv:U8rTIcgc++LugQEiOv1U0Y27SvYP50y0eEnUf05VOLs=,tag:uCE5gf5kK46Q0fThk3euaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
