apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: hello-world
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: example
  source:
    repoURL: git@github.com:aetheric-forge/infrastructure.git
    targetRevision: v0.8
    path: apps/hello-world/workloads/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
