apiVersion: v1
kind: Secret
metadata:
    name: minio-env-configuration
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:xalvDnbRcVdJkQbST0rs1792H0wfa0JU0WpH7hAYtDyhMBXAB1qSDTcwJXXwM7FxY/PK70BY0FJUnpcfom0VvSe1zlLHmtrS6zYvoDKTsDgGvd03A2WQbY/wT5rfsPCAgoKCifkbqNUNLS1r6pBBXANDWt4PO/gjFvZKVWWfb8C3GVaC0yR2h8gdWr+OwjrhZJg=,iv:Fp6UF5CeoaJq0zhEopq0MS857uJoPqe3zRN+3B/y5m0=,tag:0YzFEs4TV5MCQ4nelYMyOA==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByV0RQVjFPN3JISUdrOGFK
            ZmVXQU9ncEJEYXdiR3E2NHgweCtJVS9rMm1vCm94Q2kvK0hsU29OYTJsaDhjYjEz
            bzd4THlSeFVFRUpWQUQ1ZllwYWxUbncKLS0tIGVmV0hjYlpWOEpGL2pveUdTYjNK
            c3ZtYTYySXFaaU81VXIyUUpjZ0NDS0UKGEwczZE3aFRa7unjUGuR+EfzxNYQ7PCw
            ANwL/RMwR/AhZSaih7l4LKwWJ47F/MbaSqPqy3GVCa0rdYHfeLk9GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ckme6fk2aldhcevlxhdur5npqt89ssvk29u9fescwdtklc2d8axqh06rhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaGZGc0JPd1ZFelFPYm44
            d1h4SS9jVW5paUtHOXJtMDBxZ3liMHJvV21RCjJadHF2azV4bXUrL2JXT0hsbGlk
            TUVTNUVFL3c3aHI2WWQwVm8vZmNMRDgKLS0tIDFURytmSnhybzQwdCttaEY5UkZE
            aXMzaGNGSWpFVGg5OGc2bi9ETysxem8K4oTEiW57L9ZeQhQX+PwrGc2CfAkMWI/d
            ZXdVpyOC7ULVp7yoduNEBaMFE0G9+YAIwihrvNp3n2Exh6QNaRHnwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T08:30:08Z"
    mac: ENC[AES256_GCM,data:DuxW++AWXyIENCqlgFLv7jlrJg0rBIrWtOz1wj6u2E2/T2MqaovQpfYqDb39Fj99VFCxdDnLWQ25UAvSJQshIENgBKeTsv0qwHXz7CTacIpGdb8neBZpIS4hU6/1Kr0kyb0jCI4ufP3Cw7W0+EY1QCRQL+EDZSBMjVAH/AaUgWI=,iv:L0/XFrRLa4J5SRhrnKAIBx5gOCSrhIIugyeYaVdoWos=,tag:e2Mq4Vmk8yjhYYRUQ9YwZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
