apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
- name: ingress-nginx
  namespace: ingress-nginx
  releaseName: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  valuesInline:
    controller:
      admissionWebhooks:
        enabled: true
        patch:
          enabled: true
      dnsPolicy: ClusterFirstWithHostNet
      electionID: ingress-nginx-leader
      hostNetwork: true
      ingressClass: nginx
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx
        default: true
        enabled: true
        name: nginx
      replicaCount: 1
      service:
        type: ClusterIP
      watchIngressWithoutClass: false
  version: 4.13.3
kind: Kustomization
resources:
- namespace.yaml
